### ISSUE TITLE
chord.Chord("C4") does not work

### ISSUE THREAD

**Issue by crsegerie** [cuthbertLab/music21#1009]
**music21 version**

`5.5.0`  

**Problem summary**

 chord.Chord("C") and chord.Chord("C4 E4") both work but chord.Chord("C4") does not work and returns
`PitchException: Cannot make a name out of ''`

**Steps to reproduce**

```
from music21 import *

chord.Chord("C4")
```

**Expected vs. actual behavior**
if "C" and "C4 E4" both work, it is very counterintuitive that "C4" does not work.

**Comment by jacobtylerwalls** [comment]
Thanks, I agree. PR shortly. 

(It's a shame Google Colab is using 5.5.0 instead of 6.7.1, but I reproduced on dev.)

Workaround is to use a list:
```
chord.Chord(['C4'])
```

**Comment by crsegerie** [comment]
Thank you for the workaround, I've not thought of this possibility and makes my code much cleaner
