### ISSUE TITLE
tuplets not appearing on lilipond.

### ISSUE THREAD

**Issue by crsegerie** [cuthbertLab/music21#1015]
**music21 version**
"6.7.1"

**Problem summary**
tuplets not appearing on lilipond.

**Steps to reproduce**
see the colab [here](https://colab.research.google.com/drive/1JhBYXov4d6RpXsPDNZmhnJX6rrZ8_p2v?usp=sharing)

**Expected vs. actual behavior**
The example showing how to use tuplets in music21 does not work.

**Comment by jacobtylerwalls** [comment]
Not every export format runs `makeNotation()`, one function of which is to call `makeTupletBrackets()`. The example from the tutorial assumes you are using musicxml export, which the vast majority of our users use.

The subset of users using lilypond output usually demand greater precision over their exports, so makeNotation isn't run automatically. I understand that musicxml output is difficult to configure in Google Colab, but I would really recommend it over LilyPond. See #260 for a model of how to configure musescore in Google Colab.

Workaround if you desire to use LilyPond to generate images is to call `makeNotation(inPlace=True)` and show that:

![tmpzpm216qk ly](https://user-images.githubusercontent.com/38668450/117898151-4bb42a80-b292-11eb-911c-2b5ff9ab187e.png)

**Comment by crsegerie** [comment]
Thank you for  "#260 for a model of how to configure musescore in Google Colab.", this helped a lot. I just place here an example of Setup on colab with [a proper setup of musescore](https://colab.research.google.com/drive/1Gq4qSAbgyhw-YZDYnUu_61vmeQCp0fzy?usp=sharing) and working audio. Maybe you could also put an example of colab already setup in your installation instruction ? Maybe this could help people to begin with the library more easily.

I do not know where to put the tip, but maybe this piece of info could be repeated in the installation page ? Because even I who has taken the time to read a good half of all the documentation didn't see the tip ?

**Comment by jacobtylerwalls** [comment]
>maybe this piece of info could be repeated in the installation page ?

Referring to [first part](http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html) of user's guide?

**Comment by mscuthbert** [comment]
It's too advanced for the first 8 chapters of the User's Guide.  It should probably go in, but later -- we need to deal with people who have never programmed before first.
