### ISSUE TITLE
Cant find method to find circle of fifths for a given pitch

### ISSUE THREAD

**Issue by pyweeker** [cuthbertLab/music21#1017]
Hello, i read documentation but cant find how to get circle of fifth from a given pitch.
Something like this:
```
>>> my_circle = circle5('C')
>>> my_circle
...    ['C','G','D','A','E','B','F#','D-','A-','E-','B-','F']
```

does it exist ? with midi number option ?

**Comment by jacobtylerwalls** [comment]
Hi 👋🏻 . This forum is for bug reports. This question is better suited for the mailing list. But yes, you could construct one from midi numbers.

```
n = 60
for unused in range(12):
    note.Note(n + 7)
```
etc.

**Comment by pyweeker** [comment]
thank you for your help !
