### ISSUE TITLE
`getContextByClass()` doesn't find elements positioned in self at 0.0 by default

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1028]
**Motivation**
I started the rest of the v7 deprecations. Figured my other contributions were distracting us from what we've already promised for v7.

While doing them, I noticed that if we are going to deprecate `getKeySignatures()` and `getClefs()` there will be a problem -- recursing is not really what they did; they searched context. These methods searched themselves first with gEBC(), and then, finding nothing, searched the context with gCBC().

This made replacing the calls in the test suite difficult: I had to let them fail, and then see whether the correct result could be had by calling either gEBC or gCBC. This is a sign that we are taking away some functionality.

**Feature summary**
`includeSelf=False` parameter to getContextByClass. Default False for BC. But in the deprecation notice tell users to replace `getClefs()` with `getContextByClass(clef.Clef, includeSelf=True)`.

Notice:

```
>>> s = stream.Stream()
>>> s.insert(0, clef.BassClef())
>>> s.getContextByClass(clef.Clef) is None
True
```

**Intent**

[x] I plan on implementing this myself.

**Comment by mscuthbert** [comment]
ah -- if I had misunderstood how getKeySignatures and getClefs works, my mistake.  But maybe we need a generalized system for streams finding things that are either at offset-0 or in the context.   In music21j we call it "specialContext" and perhaps that's what's we need here (with a better name than `specialContext`)

**Comment by jacobtylerwalls** [comment]
Now I think this is just a bug with gCBC. gCBC docs imply this should work ("searches backwards within the measure"):

https://github.com/cuthbertLab/music21/blob/49cc89bb7483ed04cff0bf4959ad3a5a594a046c/music21/base.py#L1215-L1219

So I think gCBC just needs a fix; in other words, it should already be including self.

Funny, it works with "getElementAfter":

```
>>> s = stream.Stream(clef.BassClef())
>>> s.getContextByClass(clef.Clef) is None
True
>>> s.getContextByClass(clef.Clef, getElementMethod='getElementAtOrAfter')
<music21.clef.BassClef>
>>> s.getContextByClass(clef.Clef, getElementMethod='getElementAfter')
<music21.clef.BassClef>
>>> s.getContextByClass(clef.Clef, getElementMethod='getElementBefore') is None
True
>>> s.getContextByClass(clef.Clef, getElementMethod='getElementAtOrBefore') is None
True
>>> 
```

**Comment by jacobtylerwalls** [comment]
And no problem here!

```
>>> s.getElementAtOrBefore(0)
<music21.clef.BassClef>
```

**Comment by jacobtylerwalls** [comment]
Works with passing more permissive getElement methods such as atOrBeforeOffset, or even garbage values that perform no operation.
