### ISSUE TITLE
Superfluous `<part-group>` tags on joinable groups are written

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1037]
**music21 version**

dev

**Problem summary**
[Spec says](https://w3c.github.io/musicxml/musicxml-reference/elements/part-group/) not to use `<part-group>` tags to represent multi-staff parts. This was reworked as part of the part staff exporter feature in v6.5, but apparently I should have jettisoned it completely:

> A `<part-group>` element is not needed for a single multi-staff part. By default, multi-staff parts include a brace symbol and (if appropriate given the `<bar-style>`) common barlines. The symbol formatting for a multi-staff part can be more fully specified using the `<part-symbol>` element.

**Steps to reproduce**

- load score containing piano into music21
- observe one `layout.StaffGroup` created to join the piano staves in music21
- export musicxml
- observe `<part-group>` tag written: usually harmless but noncompliant
- do stuff with another package that might be altering the staff-group tags
- load that exported musicxml file back into music21
- observe there are two `StaffGroup` objects now
- export THAT

![Screen Shot 2021-06-15 at 3 48 33 PM](https://user-images.githubusercontent.com/38668450/122114369-31212400-cdf1-11eb-8336-fdf8119f9809.png)

**More info**
Haven't debugged what the "other package" is doing with the staff-group tags, because I can (theoretically) moot that by not writing out the superfluous tags.

**Comment by mscuthbert** [comment]
Super clear explanation.
