### ISSUE TITLE
Make doctests compatible with expected enum changes in Python 3.11

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1048]
fixDoctests() will need to account for the new repr() of enums in Python >=3.10, see https://github.com/python/cpython/pull/22392.

Otherwise the test suite looks fine on Python 3.10b2.

**Comment by mscuthbert** [comment]
Possibly the best thing to do in fixDocTests() for now is to temporarily change Enum.__repr__ and Enum.__str__ to the older versions, and then once 3.11 is out and most users are on 3.10+ to change Enum.__repr__ and Enum.__str__ on older versions to match 3.10+?  This is hard to find.

**Comment by jacobtylerwalls** [comment]
Looks like this will be reverted from the 3.10 beta and will need to wait for a PEP: https://bugs.python.org/issue44559

**Comment by mscuthbert** [comment]
We can leave this open as an issue for "Make doctests compatible with Python 3.11"?

**Comment by jacobtylerwalls** [comment]
The changes will be backed out of 3.11, also, since the PEP was rejected: https://mail.python.org/archives/list/python-dev@python.org/message/RN3WCRZSTQR55DOHJTZ2KIO6CZPJPCU7/

**Comment by mscuthbert** [comment]
Thanks.  It's too bad, since the new Enum reprs were such an improvement.  But the path to compatibility was really difficult.  It'll have to happen another way.
