### ISSUE TITLE
Tuplets Sometimes Missing in LilyPond Output

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#105]
The following code produces a LilyPond file without the expected ``\tuplet`` command.

    from music21 import *
    settings = environment.UserSettings()
    settings['debug'] = 1
    score = stream.Score()
    measure = stream.Measure()
    phrase = []
    dur = 1.0/3
    for _ in range(3):
        phrase.append(note.Note('c', quarterLength = dur))

    measure.append(phrase)
    score.append(measure)
    score.show('lily.pdf')

I understand that LilyPond support is not a high priority for the core music21 developers, so this issue may not be fixed unless an external contributor can do it. All the same, better to have the issue documented somewhere!

**Comment by mscuthbert** [comment]
Add before show:

    score.makeTupletBrackets(inPlace=True)

Apparently these are absolutely required to get correct layout.  

I am not sure why makeNotation=False in all the output in `loadFromMusic21Object()`

Wish I had time to fix now, but lily, as you mentioned is a lower priority.
