### ISSUE TITLE
corpus.search() doctest fails on local systems with additional Bach pieces

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1070]
https://github.com/cuthbertLab/music21/blob/902ea05d559a3443e5857dc973dd9580fe47ce85/music21/corpus/manager.py#L230-L231

This test fails on my system because I have a local corpus with additional files matching this search, and the doc example is not limiting to the core corpus. I understand why -- it's not until a few lines down that limiting by corpus is introduced.

Should we limit the corpus here, anyway? Or do a `#_DOCS_HIDE` shuffle (less appealing, but open to it).

Same goes for the two doctests directly above.

**Comment by mscuthbert** [comment]
yeah, we should docs_hide and just do a core-corpus search.  I've been bitten by this myself, and part of the reason I don't use local corpora as much as I should.
