### ISSUE TITLE
Give better common names for Augmented-Sixth chords

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#1071]
**music21 version**

`7.0beta`   

**Problem summary**

Augmented sixth chords not in first inversion are lacking proper `commonName` functions

**Steps to reproduce**

```
>>> roman.RomanNumeral('Ger7').commonName
```

**Expected vs. actual behavior**

Expected: `'German augmented sixth chord in root position'`
Actual: `'enharmonic to dominant seventh chord'`

**More information**

Same problems for French, Italian, and Swiss augmented sixth chords.

Note that there's disagreement on whether there should be hyphen there.  Wikipedia + Aldwell/Schachter + Kostka Payne + Burstein/Straus don't put a hyphen in "augmented sixth chord".  MGTA is the only one that does (as my instinct would be to do).  That's 4 to 1, so we keep it out, possibly to keep with "dominant seventh chord"

**Comment by jacobtylerwalls** [comment]
Fixed in #1074
