### ISSUE TITLE
MIDI note velocity no longer saving

### ISSUE THREAD

**Issue by Meekohi** [cuthbertLab/music21#1084]
**music21 version**

`7.0.8+ (44665f049fad7b20d7b4bd7f4765fc7b20ac7672)`   

**Problem summary**

The velocity of MIDI notes not longer seems to save back to the MIDI file.

**Steps to reproduce**
Here is a quick example script that works on v6.7.1 but doesn't seem to work on the newest commit:
```
import copy
from music21 import *

orig = converter.parse('test/4part.mid')

for idx, p in enumerate(orig.parts):
    s = copy.deepcopy(orig)
    for part in s.parts:
        for note in part.notes:
            note.volume.velocity = 0
    for note in s.parts[idx].notes:
        note.volume.velocity = 127
    s.write('midi', fp='{idx}.mid'.format(idx=idx))
```
https://www.dropbox.com/s/oln4y19yn81kqhc/4part.mid?dl=0

**Expected vs. actual behavior**
Expected: one MIDI file with each part at max volume (and others silent)
Result: all the files are essentially identical to the original.

**More information**
Windows

**Comment by jacobtylerwalls** [comment]
Hi @Meekohi . First of all, thank you for testing the v7 beta!

There will be a backwards incompatible change in MIDI parsing documented when v7 is officially released. See #856--we're now making measures from MIDI files. So anything after `for note in part.notes` will not execute. You should use `.recurse()` or `.flat` to access notes in measures.

The motivation is to bring MIDI parsing in line with the other music21 parsers that make measures. We get quite a lot of inquiries about why music21 doesn't create measures from MIDI files. I've also seen a lot of people with ML projects adapting code published on Medium that uses `partitionByInstrument()` to make measures from MIDI files, which although not being the way I would suggest people do it, shows that people are looking for workarounds to get measures made.

Regrettably, it will break some code relying on the old behavior.

If something else changed in the v7 beta for the worse, please do report back! Cheers.

**Comment by Meekohi** [comment]
Ah thank you for the info. Sounds like an excellent improvement.

**Comment by jacobtylerwalls** [comment]
No problem. If you don't mind I'm going to retitle this so that folks searching on GitHub can find this answer.
