### ISSUE TITLE
Suppress messages from MuseScore CLI

### ISSUE THREAD

**Issue by adammichaelwood** [cuthbertLab/music21#1089]
**music21 version**

`music21==6.7.1`   

**Problem summary**
Tiny notation + show() produces an error, which nonetheless does not affect the output, but is very annoying in Notebooks.

(The actual problem is that the tinynotation parser produces something that the XML parser does not like, and this is not a notebook specific problem.)

**Steps to reproduce**

Using the exact example from the beginning of the documentation:

```
music21.converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#").show()
```

**Expected vs. actual behavior**
Expected: see the music example in cell output

Actual: see the music example, preceded by an error message:

```
convert </var/folders/n2/3fzlvz9j4xl3mthwygc5n67m0000gn/T/music21/tmp14amnsf_.xml>...
Error at line 24 col 47: no instrument found for part 'Pbb8d9a620e009425ce86d3f720af6859'
	to </var/folders/n2/3fzlvz9j4xl3mthwygc5n67m0000gn/T/music21/tmp14amnsf_.png>
... success!
```

<img width="1118" alt="Screen Shot 2021-08-12 at 4 01 54 PM" src="https://user-images.githubusercontent.com/1776241/129280921-2d512fd3-cc68-457e-97ed-6cbeb1c0c21d.png">

**More information**

Fixing the XML created by tinynotation.  
or.  
Fixing the XML parser so that it doesn't expect something that it apparently doesn't need.  
are both good options, and one of them is probably the right one, but...

Suppressing a non-blocking error from output when calling `.show()` would also be equally useful (at least for me), and might be easier.

**Comment by jacobtylerwalls** [comment]
Hi, thanks for writing. That error is emitted by MuseScore, which converts the musicxml document written by music21 to a PNG for display in the notebook. I can't reproduce the error with MuseScore 3.6.2. What version of MuseScore are you running in the notebook?

**Comment by adammichaelwood** [comment]
Thank you for such a prompt response!

I was on 3.2.x, but I have upgraded to 3.6.2, and am getting an even more annoying error message.
<img width="1121" alt="Screen Shot 2021-08-13 at 12 06 25 AM" src="https://user-images.githubusercontent.com/1776241/129318388-1fcad4bb-ccff-410a-a986-931e0f0c9e1f.png">

```
dlopen error : dlopen(libjack.0.dylib, 1): image not found 
dlopen error : dlopen(/usr/local/lib/libjack.0.dylib, 1): image not found 
Creating main window…
ZoomBox::setLogicalZoom(): Formatting logical zoom level as 100% (rounded from 1.000000)
Reading translations…
convert </var/folders/n2/3fzlvz9j4xl3mthwygc5n67m0000gn/T/music21/tmpzqihkh5r.xml>...
JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
	to </var/folders/n2/3fzlvz9j4xl3mthwygc5n67m0000gn/T/music21/tmpzqihkh5r.png>
... success!
```

I suspect MuseScore is not playing nice with Big Sur (MacOS 11.5.1), but I'm not sure what to do about it.

**Comment by adammichaelwood** [comment]
This might be bubbling up from under MuseScore, all the way in QT.

https://musescore.org/en/node/318554

**Comment by jacobtylerwalls** [comment]
Just opened a PR to silence the messages from MuseScore. I suppose this approach might be silencing a useful error message, but you are right--as it stands today, this is somewhat ugly.

**Comment by mscuthbert** [comment]
What operating system are you on?  As the original message notes, this support channel is only for Windows or MacOS.

**Comment by jacobtylerwalls** [comment]
I reproduced on macOS.

**Comment by adammichaelwood** [comment]
I was also on MacOS
