### ISSUE TITLE
Haydn Quartets have disappeared

### ISSUE THREAD

**Issue by jsundram** [cuthbertLab/music21#110]
It looks like in the great musedata culling, all the haydn quartets except Opus 74 numbers 1 and 2 have been removed. 

Is there any plan to re-add them as musicxml, or are they gone forever? I'd be happy to do the conversion and submit a PR with the musicxml if you're open to it.

**Comment by mscuthbert** [comment]
Yes, unfortunately they needed to go.  If you have a source for the other quartets besides the Musedata versions that are good quality and freely distributable I would love to include them back in music21 (along with anything else out of copyright).  Unfortunately, converting the Musedata information to another format and back would not be sufficient to remove their licensing restrictions -- there are telltale errors in the sources that would be obvious as to their origins.

**Comment by maxalbert** [comment]
The Mutopia Project has at least Op. 76 available (public domain): http://www.mutopiaproject.org/cgibin/make-table.cgi?searchingfor=haydn+quartet  However, I have no idea about the typesetting quality or whether these would be easy to import into music21.

**Comment by mscuthbert** [comment]
It'd be hard -- they have MIDI which is too lightweight and .ly which is unparseable except by lilypond.  There's a project working on a solution in general to this, but it's at least six months away.

**Comment by mscuthbert** [comment]
I'm going to close this for now since it's a known issue without an easy solution; happy to reopen if someone is actively working on the project. Thanks - M

**Comment by jsundram** [comment]
If I understand this correctly, the CCARH license is the problem? http://www.musedata.org/legal/lcr.html

**Comment by mscuthbert** [comment]
Yes. Lots of discussions have been had that have not come to anything positive.  There's absolutely nothing more to do with that unfortunately.
