### ISSUE TITLE
Unpitched musicXML export was reverted

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1106]
**music21 version**

36a7b6f

**Problem summary**
Unpitched export to musicXML (new in v7) was reverted in latest commit. Intentional? Was there a desire to postpone this to the next version?

**Steps to reproduce**

```python
>>> from music21 import *
>>> s = converter.parse('music21/musicxml/lilypondTestSuite/73a-Percussion.xml')
>>> s.show()
```

**Expected vs. actual behavior**
36a7b6f -- actual
<img width="601" alt="Screen Shot 2021-08-25 at 8 56 13 AM" src="https://user-images.githubusercontent.com/38668450/130794352-4b848138-35c8-4e77-b533-2ab8146ec3c2.png">

b0af88fbafc3fd253c8979239cb61cd333e7c5d1 -- expected, two commits ago

<img width="591" alt="Screen Shot 2021-08-25 at 8 56 03 AM" src="https://user-images.githubusercontent.com/38668450/130794316-f3db2453-3a52-4bf9-9c79-ecfd95d9fd1a.png">

**Comment by mscuthbert** [comment]
definitely unintentional.  Glad to get it back in and even do a release for it since it was a major part of the code (and this is worse than v6.7 output)

**Comment by mscuthbert** [comment]
Oops -- old, old thread.  I thought this had come up again!
