### ISSUE TITLE
ChordWithFretBoard display issue with exported stream.

### ISSUE THREAD

**Issue by carrus2049** [cuthbertLab/music21#1118]
**music21 version**
`6.7.1`

**Problem summary**
When trying to build a chord notation with fretboard, the displayed notation got unwanted 'x' on fret zero of the fingered string. Am I missing some parameters to set? Thanks!

**Steps to reproduce**

```
    import music21 as m21
    st = m21.stream.Stream()
    fn4 = m21.tablature.FretNote(string=4, fret=0)
    fn3 = m21.tablature.FretNote(string=3, fret=2, fingering=2)
    fn2 = m21.tablature.FretNote(string=2, fret=3, fingering=3)
    fn1 = m21.tablature.FretNote(string=1, fret=2, fingering=4)
    cwf = m21.tablature.ChordWithFretBoard('D', fretNotes=[fn1, fn2, fn3, fn4])
    st.append(cwf)
    st.show()
    # st.write("musicxml.pdf", fp="./testscore.pdf")
```

**Expected vs. actual behavior**
expected
<img width="366" alt="Screen Shot 2021-09-08 at 3 30 57 PM" src="https://user-images.githubusercontent.com/70931300/132465873-a51ec9ef-ecc3-46eb-bd60-b0909956ed90.png">

but got
<img width="371" alt="Screen Shot 2021-09-08 at 3 30 41 PM" src="https://user-images.githubusercontent.com/70931300/132465917-0ecd029d-1690-4381-9f4a-9ef557aa2b26.png">

**More information**
MacOS 10.15.7 (19H15)
Musescore version 
OS: macOS 10.15, Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548020600, revision: github-musescore-musescore-3224f34

**Comment by jacobtylerwalls** [comment]
Thanks for writing. The musicxml emitted by music21 looks correct. (Have a look after calling st.write().) Finale can display this as you desire:

<img width="202" alt="finale" src="https://user-images.githubusercontent.com/38668450/132694857-d754f890-c4cd-4aec-af39-c7a32cbf40f6.png">

You could see if this has been reported to MuseScore. Feel free to reopen if you can identify musicxml being written by music21 in an unexpected way. Thanks.

**Comment by carrus2049** [comment]
I double checked and guess it's and issur from Musescore. Thanks for checking that out!

**Comment by mscuthbert** [comment]
Thanks all!
