### ISSUE TITLE
Improving Noteworthy converter support

### ISSUE THREAD

**Issue by nvuaille** [cuthbertLab/music21#1123]
**Motivation**
Improving the Noteworthy Converter, for more interoperability

**Feature summary**
Centered on version 1.75,  binary  and text format.

**Proposed implementation**
Improve supported NWC objects parsing  in https://github.com/cuthbertLab/music21/blob/master/music21/noteworthy/binaryTranslate.py
By design, this also require some improvements in https://github.com/cuthbertLab/music21/blob/master/music21/noteworthy/translate.py  (`binary translate` pass a text stream to 
the `translate` module) 

See my current branch [here](https://github.com/nvuaille/music21/tree/Noteworthy). I think I have most of the features I want, I still need update/fix current tests and add more =)

**Intent**

 * I plan on implementing this myself.

Is it something music21 would like to have ? Is there some recommendation about this kind of feature ?

In any case, thanks for all the work you did on this great tool !

**Comment by mscuthbert** [comment]
most welcome contribution if you have it!  I'll need to fire up my PC to get some more files.
