### ISSUE TITLE
MusicXML importer: PartStaffs end up with too many (2) TimeSignatures in a non-first Measure

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1129]
**music21 version**

`7.1`   

**Problem summary**

Attached is a MusicXML file that music21 wrote from a stream containing two PartStaffs (and a StaffGroup relating them).  It's an Organ score, with 5 measures, each of which has a new time signature: 7/8, 8/8, 7/8, 8/8, and 11/16, respectively.  I believe the MusicXML is correct, but I might be wrong.  It displays correctly in any case.  When I import this MusicXML file back into music21, however, while the first measure's time signature looks right, the second measure's time signature (and I'm guessing the others as well) shows up in the measure twice (in each PartStaff)

If I export a different MusicXML file from an otherwise identical Score containing Parts instead of PartStaffs, and then import _that_, all is well (I get one time signature at the beginning of each Measure in each Part).

I would note that neither MusicXML file appears to have the extra time signatures in it, so I'm guessing this is a bug in MusicXML import, that only happens when a part has more than one staff.

I have attached both MusicXML files for your enjoyment (zipped).

[LesCorps_Parts.musicxml.zip](https://github.com/cuthbertLab/music21/files/7173870/LesCorps_Parts.musicxml.zip)
[LesCorps_PartStaffs.musicxml.zip](https://github.com/cuthbertLab/music21/files/7173871/LesCorps_PartStaffs.musicxml.zip)

**Comment by jacobtylerwalls** [comment]
Thanks for the report. Reproducer:
```python
from music21 import converter, layout, meter, note, stream
ps1 = stream.PartStaff()
ps2 = stream.PartStaff()
sg = layout.StaffGroup([ps1, ps2])
s = stream.Score([ps1, ps2, sg])
for ps in ps1, ps2:
    ps.insert(0, meter.TimeSignature('3/1'))
    ps.repeatAppend(note.Note(type='whole'), 6)
    ps.makeNotation(inPlace=True)  # makes measures
    ps[stream.Measure][1].insert(meter.TimeSignature('4/1'))  # another time signature

fp = s.write()  # writes 4/1 time signatures in both hands
inn = converter.parse(fp, forceSource=True)
m2 = inn.parts.last()[stream.Measure][1]
assert len(m2[meter.TimeSignature]) == 1, m2.elements
```
```python
Traceback (most recent call last):
  File "/Users/jwalls/Desktop/repro.py", line 15, in <module>
    assert len(m2[meter.TimeSignature]) == 1, m2.elements
AssertionError: (<music21.meter.TimeSignature 4/1>, <music21.meter.TimeSignature 4/1>, <music21.note.Note C>, <music21.note.Note C>, <music21.note.Note C>, <music21.note.Rest whole>, <music21.bar.Barline type=final>)
```

**Comment by jacobtylerwalls** [comment]
I think this is an issue in the exporter, which writes an `<attributes>` tag with the time signature in the left hand after a `<backup>`. There shouldn't be a need to reiterate the time signature (or key sig) on the second staff unless it's polymetric. We do have logic to detect polymetric situations and deal with them, but the partStaffExporter is still liberal about merging all the `<attributes>` tags together, which is a consequence of the current design of exporting each part separately and then merging the musicxml tags back together under a single `<part>`.

Fix needed in `moveMeasureContents()` to do something smarter in the branch handling `<attributes>`.

**Comment by jacobtylerwalls** [comment]
Heya @gregchapman-dev last comment before I sign off for the week.

I looked just a bit more into musicxml representation of multi-staff multi-clef/key situations -- I'm back to my original diagnosis: we shouldn't be writing these extra `<attributes>` tags after a `<backup>`. If we wanted to represent multipart multimeter or multikey (we can), we can use the "number" attribute on the initial `<attributes>`, not after a `<backup>`. So in a multipart _uniform_ meter situation like this, we just shouldn't be writing these extra tags. What the superfluous tags might mean seems like undefined musicxml behavior, similar to #1067. The extra tags may be harmless in Finale and MuseScore right now, but they're harmful to music21 import and possibly elsewhere! :-D

Nothing is superfluous or duplicative in the Python streams, just a single meter or key in both PartStaffs.

I would think we need some sort of linear scan through all staffs in a joinable group to determine whether there are certain measures with multiple meters or keys, and in all other measures, we need to suppress the output of clefs and keys on subsequent staffs in `setMxAttributesObjectForStartOfMeasure()`.

I'm going to close this PR as I don't currently have capacity currently to keep working on this, but if you want to have a go I'd be happy to offer any input as I'm able. Thanks again for the report.

**Comment by jacobtylerwalls** [comment]
> What the superfluous tags might mean seems like undefined musicxml behavior, similar to #1067. 

There is an explicit case for attribute tags after a backup in Reinhold's musicxml test suite:

https://github.com/cuthbertLab/musicxmlTestSuite/blob/main/xmlFiles/43c-MultiStaff-DifferentKeysAfterBackup.xml

But this was written c. 2005-2008, and I don't know what the modern practice is. Finale can't read this sample file. MuseScore can. Neither software emits musicxml like this, though.

Still inclined to say in a _uniform_ meter situation we should not be writing these additional tags after backups.
