### ISSUE TITLE
'musicxml.png' export problems

### ISSUE THREAD

**Issue by akdor1154** [cuthbertLab/music21#113]
Hey, just getting started with music21 so apologies if any part of the following is in fact user error. Note also this is with 2.1.2 from PyPI, so line numbers don't match with master.

Instantiating a simple tune from the corpus and running
```py
tune.show('musicxml.png')
```

I get the following error:
```py
File "/home/jarrad/src/Zouk/venv/lib/python3.4/site-packages/music21/converter/subConverters.py", line 662, in runThroughMusescore
    elif not os.path.exists(musescorePath):
File "/home/jarrad/src/Zouk/venv/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
```

This is because in coverter/subConverters.py, the line (in current master) https://github.com/cuthbertLab/music21/blob/master/music21/converter/subConverters.py#L694
```py
if musescorePath == "":
```
should be 
```py
if not musescorePath:
```

because (for me, after a vanilla pip install) musescorePath is None, not "".

Further issues: after this is fixed, a user in this position will still be confused, because the given error will say that Musescore is not installed, when in actual fact the problem (again, for me) is that ```environLocal['musescoreDirectPNGPath']``` is not set to Musescore's path. Maybe the error could state that the user should set this path as well as check that Musescore is installed?

Finally, from the looks if it, it seems that the expectation is that the user should never have to set this path at all. I have musescore in /usr/bin/musescore from the default Ubuntu 15.10 package, yet music21 is not finding it (I had to set 'musicxmlPath' as well). I'm not too sure how to go about fixing this as as I said I'm only starting out with music21 as a user, let along being familiar with its source code. As a hunch though, Musescore changed their default binary name from ```mscore``` to ```musescore``` with version 2; perhaps this is related?

Cheers
Jarrad

**Comment by mscuthbert** [comment]
I've fixed the line you suggest and improved the message as you suggest.

We're not able to automatically find paths on Unix/Linux systems, sorry.  It's just too much overhead for the small support team to test.  Mac + Windows are the only systems we try to guide installation through.

Best, Myke

**Comment by akdor1154** [comment]
Thanks for the quick fix! On Linux paths, it would be enough to just just call 'musescore' (or indeed any binary) from a shell exec function (i.e. one that respects $PATH) and it will magically work on 99.9% of systems. :)

**Comment by mscuthbert** [comment]
If you could submit a pull request it could be something I could try, but with no way of testing it here, I'm not sure I can commit to adding it on my own. Thanks!
