### ISSUE TITLE
Deprecate `StreamIterator.__getattr__()`

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1137]
The following code silently fails (unless running in `-Wall`, which will merely say it's inefficient):

```python
p = stream.Part()
p[stream.Measure].insert(0, stuff)
```

The user forgot to access the iterator and isn't told this didn't work.

The existing code has warnings for attributes, but silently dropping arguments to bound methods seems bad.

I suggest in v.8 it's time to finally deprecate `StreamIterator.__getattr__()` and remove in v.9 (with flat and the rest).

**Comment by mscuthbert** [comment]
Sounds good.  Approved.

**Comment by mscuthbert** [comment]
Btw -- part of me wants to already make a v8 branch for things like this, but I know how much of a pain the merging from master can be unless it's auto setup to do so.
