### ISSUE TITLE
origin of tuning system/scale data in music21/music21/scale/scala/scl/

### ISSUE THREAD

**Issue by musicus** [cuthbertLab/music21#1143]
Where did the data in the .scl files located in the https://github.com/cuthbertLab/music21/tree/master/music21/scale/scala/scl directory come from? I have seen ones in the _same format_ in @flexatone's _athenaCL_, and strangely enough in the library for the Garrison ARIA player and was wondering if they are from the same origin, and what that origin might be.

**Comment by musicus** [comment]
The data comes from the [_Huygens-Fokker Foundation_](http://www.huygens-fokker.org) and was designed for use in its [_Scala_](http://www.huygens-fokker.org/scala/) software package. _Scala_ can also be used to design new microtonal systems. Its file format is **.scl**. I'll close the question, but credit should be given.

**Comment by mscuthbert** [comment]
yes.  It is used with permission (though I'm not 100% sure it is copyrightable)
