### ISSUE TITLE
Problem with score.expandRepeats() expanding repetition brackets

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#1160]
**music21 version**
6.7.1

**Problem summary**
Expanding repetitions fails when attempting to process repeat brackets that don't have two dots after the first bracket, found in eighteen-century arias scores.

**Steps to reproduce**
Try to expand repeat brackets without repetition dots after the first bracket.

**Expected vs. actual behavior**
Expanded score VS Error: 'repeat brackets are not terminated with a repeat barline'

In our specific corpus (18th-century arias) we have some passages that require some special repetition elements that are not considered by music21. We get an error at line 1192 of music21/repeat.py as it expects two dots mandatorily after the first bracket. Our case(s) looks like the following:
![imagen](https://user-images.githubusercontent.com/52449822/140038235-70a08d6e-d5b0-46dc-b0bb-51fa20a432d5.png)

We are aware that this is a nonconventional way of noting down repeat brackets, but we actually need it that way to be able to express what occurs in the score being faithful to the original composition. 

Just to notice, when we ask Finale or Musescore to play the score, they both understand perfectly this kind of notation and play it with the proper repetition segments. 

We'd be really grateful if you could consider implementing this type of cases to music21 expander, which would be really useful for our 18th-century corpus and other historical scores that need this notation.

Thanks for your time! We are absolutely available to discuss any future details regarding this issue. 
Regards from DIDONE project ;)

**More information**
Tried to run this problem with 7.1 version, same error.
Attaching the .xml file in case you want to run some tests
[Test.zip](https://github.com/cuthbertLab/music21/files/7466645/Test.zip)

**Comment by mscuthbert** [comment]
I think you should implement this with a repeat barline with .style.hideObjectOnPrint = True
