### ISSUE TITLE
Cannot convert .mid midi file to musicxml.png image file

### ISSUE THREAD

**Issue by GodusOV** [cuthbertLab/music21#1168]
**music21 version**

`7.1.0`   

**Problem summary**

I am getting this error below when I am trying to convert a MIDI file to Image file
```
Ignoring exception in command file:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 96, in file
    stream.write("musicxml.png", fp="song.xml")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/music21/stream/base.py", line 328, in write
    return super().write(fmt=fmt, fp=fp, **keywords)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/music21/base.py", line 2665, in write
    return formatWriter.write(self,
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/music21/converter/subConverters.py", line 1074, in write
    outFp = self.runThroughMusescore(xmlFp, subformats, **keywords)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/music21/converter/subConverters.py", line 957, in runThroughMusescore
    raise SubConverterFileIOException(stderr_str)
music21.converter.subConverters.SubConverterFileIOException: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
initScoreFonts 0x55e196e3c140
convert </home/runner/music/song.musicxml> to </home/runner/music/song.png>
unknown file suffix <musicxml>, name </home/runner/music/song.musicxml>
Cannot read file /home/runner/music/song.musicxml:
unknown type
```
The MIDI file is valid and works perfectly fine when I convert it to `.wav` online manually

Note I am using an online IDE called Replit
I installed MuseScore2 `2.1.0`

**Steps to reproduce**

```
import music21

...

stream = music21.converter.parse("song.mid")
stream.write("musicxml.png", fp="song.png")
```
I found this from https://stackoverflow.com/a/65366499
I tried using stream.show() and it shows the same error

**Expected vs. actual behavior**

Expected to create a png music sheet from the MIDI file. But instead it created a song.musicxml file and gave me an error.

**More information**

**Comment by jacobtylerwalls** [comment]
The error is coming from MuseScore ("unknown file suffix <musicxml>") This was [fixed](https://musescore.org/en/node/235516) in MuseScore 2.2, and I see you report using 2.1, so upgrading should do the trick.

>But instead it created a song.musicxml file and gave me an error.

This is how the feature works: music21 creates a musicxml file and passes it to MuseScore's CLI interface to convert to PNG.
