### ISSUE TITLE
From MusicXML to pianoroll ?

### ISSUE THREAD

**Issue by qsdfo** [cuthbertLab/music21#117]
Hi all,

First of all, thanks for this awesome lib :)

I would like to get a pianoroll representation of a musicXML file, as a time/pitch matrix for each part (i.e. each instrument). So input would be an XML file and output a (several if more than 1 instruments) 2-D matrices with time along first axis and pitch along second axis.
I am pretty sure this is easy to get, since the plotStream function displays a pianoroll, but I don't manage to.

Best,
Leo

**Comment by mscuthbert** [comment]
Hi -- thanks for the compliment.  Could you post this to the music21list (google group).  I believe someone asked about this about a year ago and might have the solution.  It shouldn't be too hard to get (.offset, .pitch.ps) information for each pitch in a piece.  Thanks! Myke

**Comment by qsdfo** [comment]
Ok thanks. Indeed, found it here : 
https://groups.google.com/forum/#!searchin/music21list/pianoroll/music21list/1mMMrzHUUTk/Bi35WyZUEZ0J
