### ISSUE TITLE
MIDI: reading performance can be improved

### ISSUE THREAD

**Issue by kwikwag** [cuthbertLab/music21#1174]
**Motivation**
The code that reads in MIDIs uses a lot of inefficient code, causing in rather slow reads.

**Feature summary**

I tried some straightforward approaches to make it more efficient. See https://github.com/kwikwag/music21/tree/feature/midi-read-performance

**Proposed implementation**

* Replace `bytes` with `memoryview` for the reading process.
* Use a pre-calculated `frozenset()` for the `_ContainsEnum` base class

**Intent**

[x] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[x] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by kwikwag** [comment]
Note: with this change, `event.data` will return a `memoryview` where it used to have `bytes`. I can change that, but not sure what would be best.

**Comment by jacobtylerwalls** [comment]
Hi, thanks for using the package and thinking of giving back.

Regarding the two proposed changes, do you have a benchmark? You mention the frozenset change saves 5%. What about the other? (The other diff is much bigger, so it would help to evaluate processing time vs. patch review time / documentation time.)

> Note: with this change, event.data will return a memoryview where it used to have bytes.

This sounds like something that might need to wait for v. 8. The frozenset change could go in now.

**Comment by kwikwag** [comment]
They both are at aboud 5% is my measurements. I will try to come up with a benchmark set. I'll fix the pylint problems first.
