### ISSUE TITLE
Re-raise FileNotFoundError with hint to call configure.run()

### ISSUE THREAD

**Issue by NuclearTruffles** [cuthbertLab/music21#1179]
**music21 version**

`7.10`   

**Problem summary**

Sorry if this is trivial, as I'm a beginner, but I just started using Music21 in a new python virtual environment on Visual Studio Code, no other libraries installed, and just this code running - and I received an error that seems to be with a bug in some obscure file in music21 called subConverters.py

**Steps to reproduce**

```
from music21 import *

n = note.Note("D#3")
n.duration.type = 'half'
n.show()

```

**Expected vs. actual behavior**

Here is the error:

  File "C:\Users\pawel\Documents\Dev\PythonProjects\Music21\main.py", line 5, in <module>
    n.show()
  File "C:\Users\pawel\Documents\Dev\PythonProjects\Music21\.venv\lib\site-packages\music21\base.py", line 2738, in show
    return formatWriter.show(self,
  File "C:\Users\pawel\Documents\Dev\PythonProjects\Music21\.venv\lib\site-packages\music21\converter\subConverters.py", line 1098, in show
    self.launch(returnedFilePath, fmt=fmt, app=app)
  File "C:\Users\pawel\Documents\Dev\PythonProjects\Music21\.venv\lib\site-packages\music21\converter\subConverters.py", line 197, in launch        
    subprocess.run(cmd, check=False, shell=shell)
  File "C:\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**More information**

This is on Windows 10

**Comment by jacobtylerwalls** [comment]
Hi, thanks for the report, and sorry your first day with music21 was a little bumpy.

On Windows, it looks like we don't set a default MIDI player and just rely on the OS to open an appropriate player. Maybe this no longer works on Windows 10. If you're game, could you try the following?

```python
n = note.Note()
n.write('midi', fp='test.midi')
```
And then at the command line:
```
start test.midi
```

If that works, we're getting somewhere. If that doesn't work, then that's useful for us to know we can no longer depend on it. (We want to maintain music21 for Windows users, but we don't have any maintainers actively developing on Windows right now.)

The other alternative: if you know of a MIDI player on your system that will work (Windows Media Player?) then you can pass that app's path to the show function like this:
```python
n.show('midi', app='...')
```
Where `...` is replaced with something like `r'PROGRAMFILES...` or whatever.

If you get the path working:
- you can store it in your environment like this:
```python
user_settings = environment.UserSettings()
user_settings['midiPath'] = 'the path to the application that worked!'
```
- and please let us know what it was; we could add it as a default for Windows users.

**Comment by NuclearTruffles** [comment]
Excuse me for the delay - I'm working in GMT. Also I believe I posted the wrong code snippet - the midi player was indeed functioning normally, but it was instead diplaying the note in a score that caused the error - the error message is the same.

**Comment by jacobtylerwalls** [comment]
Ah, then you may need to run the configuration tool to select a MusicXML reader on your system.

Try:
```python
from music21 import *
configure.run()
```

And one of the prompts will help you select a musicxml reader. In #1178 I'm trying to add a hint for this at runtime instead of a bare `FileNotFoundError`. Let us know if it works.

**Comment by NuclearTruffles** [comment]
Yep that worked great - Selected Sibelius and the sheet music was imported in fine, though Sibelius did mention that the MusicXML was of an older version and I may encounter problems importing it in. I didn't, but I thought it was worth mentioning.

Thank you for the help.

**Comment by jacobtylerwalls** [comment]
Super. I'm going to let this thread track the improvement I mentioned so that the next user has a smoother ride. Cheers.
