### ISSUE TITLE
Parsing Chord Strings

### ISSUE THREAD

**Issue by el3ment** [cuthbertLab/music21#118]
Is there a parser that reads chord strings like "Amaj7" or "B6/9" into music21 chord objects?

As far as I could tell, the answer was no, but I wanted to check. There are lots of reading formats, but not too many of them have examples and I'm not familiar enough with the formats to know if "Amaj7" is part of this-or-that format.

**Comment by mscuthbert** [comment]
If you want to create one object, look at the harmony.ChordSymbol() object.  If you want to have a format that can parse them, look at the tinyNotation.HarmonyNotation() tinyNotation subtype.  You may need to set up aliases in the chord symbol dataset.
