### ISSUE TITLE
Far too slow makeMeasures

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#119]
https://www.dropbox.com/s/9iwttc9nkdyi8ja/Anh06%20Rondo.mid?dl=0

``` python
In [5]: for p in c.parts:
   ...:     p.insert(0, meter.TimeSignature('6/8'))
   ...:  
In [6]: d = c.makeMeasures()
```

hangs.  Profile and figure out what is taking so long.

**Comment by garncarz** [comment]
It's too slow for me too. `s.show('midi')` is almost instant, whereas `s.show()` takes few minutes.

I've uploaded [a zipped cProfile's output](https://github.com/cuthbertLab/music21/files/210749/profiler.zip).

I'm not sure if I'm able to debug this, but I'd appreciate if you'd give few hints where to start.

**Comment by mscuthbert** [comment]
Yes, running into this myself in other places still.  I tried a MakeTies fix but that didn't work.  Still looking.  This midi file is magic -- it's in the sweet spot where it's unacceptably long, but "short" enough that one can generate a profile.

**Comment by garncarz** [comment]
And it's very nice. :notes: At first it sounded like Mozart to me, but I googled it to find out it's Beethoven.

**Comment by mscuthbert** [comment]
first commit just in.  Turned on a Cache that was accidentally turned off years ago when caching was unreliable.  Now we rely on caching almost everywhere.  Result: 20% faster.  Looking for about 90% faster, but small progress...

**Comment by mscuthbert** [comment]
gotta run to an appointment, but I've figured out one big issue:  Stream.sort() is being called 4000x for each part.  It's a rather slow operation, but more importantly, I can't imagine anything that would be happening in makeNotation() that wouldn't leave the Stream sorted afterwards.

I'm going to see if there's an easy solution to solving the sort problem.  If not, then we'll need to wait until the real solution, the always-sorted binaryTree representation that I've been working on for the last year, is ready.

**Comment by mscuthbert** [comment]
Latest commit reduces time for this file from 50 seconds down to 7 by finding a slow O(n^2) operation and reducing it to O(n).  However some even larger MIDI files, such as omr/k525MIDIMvt1.mid are still taking far too long, so not closing yet.

**Comment by mscuthbert** [comment]
Apparently the slowness for that piece comes from the fact that all the eighth notes are imported as triplets and there are still .fractions optimizations to do.  So that's a different problem.  Hence, closing this.  Hopefully it's a good ending.  Re open if it's still too slow.

**Comment by giamic** [comment]
Found this old issue while filing another one. It seems like makeMeasures has become much faster, but it is still not blazing fast. I have profiled it and I noticed that almost all the time is taken by deepcopy, even if I'm running with the inPlace option. Can one get rid of that somehow?

**Comment by mscuthbert** [comment]
If you can find any place where we can skip a deepcopy because we've already done one, please let me know -- those are easy fixes so long as we have a test to make sure that inPlace=False still deepcopies.

**Comment by jacobtylerwalls** [comment]
You're right, @giamic, makeMeasures(inPlace=True) makes avoidable deepcopies.
