### ISSUE TITLE
Dissonance score treats compound intervals incorrectly

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1191]
**music21 version**
dev

**Problem summary**
The dissonance score used by `pitch.simplifyMultipleEnharmonics()` et al. might give a "triad award" to a compound diminished seventh, or other compound intervals enharmonically equivalent to triadic intervals (thirds, sixths).

**Steps to reproduce**

```python
In [1]: from music21 import key, pitch

In [2]: pitch.simplifyMultipleEnharmonics([pitch.Pitch('B5')], keyContext=key.KeySignature(2))
Out[2]: [<music21.pitch.Pitch C-6>]

```

**Expected vs. actual behavior**
Should have returned B5 (original pitch).

**More information**
The dissonance score algorithm is doing a mod 8 operation that breaks for compound intervals. The default "D" in the two-sharps key signature is D4, so we have a compound diminished seventh (diminished fourteenth) from D4 -> Cb6 getting a "triad award" incorrectly.

Thanks to Brian Lee for reporting on Google Groups.

**Comment by mscuthbert** [comment]
Thanks Jacob!
