### ISSUE TITLE
Export of cross-Voice DynamicWedges to MusicXML sometimes get confused about which wedge is ending where

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1204]
**music21 version**

`7.2.0`   

**Problem summary**

Two DynamicWedges are added to a Measure with two voices.  Each of them start and stop on notes in different voices.  If the two DynamicWedges are both Crescendos or both Diminuendos, all is fine.  But if they are one of each, the starts and stops (in the MusicXML) are wrongly ordered, and are confused between the two wedges (it looks rather like the wedges have exchanged end notes with each other).

**Steps to reproduce**
```
# This example fails. The resulting MusicXML <wedge> elements are swapped around, and the MuseScore-
# generated PDF has one wedge that starts correctly but covers the whole measure (should have stopped 
# half-way through the measure), and one that starts correctly but is only one eighth note long (should 
# have stopped at end of measure).
s = m21.stream.Score()
p = m21.stream.Part()
m = m21.stream.Measure(1)
v1 = m21.stream.Voice()
v2 = m21.stream.Voice()

s.append(p)
p.append(m)

m.insert(0, m21.clef.TrebleClef())
m.insert(0, m21.key.Key('G'))
m.insert(0, m21.meter.TimeSignature('3/4'))
m.insert(0, v1)
m.insert(0, v2)

# three quarter notes in one Voice
v1n0 = m21.note.Note('G4')
v1n1 = m21.note.Note('A4')
v1n2 = m21.note.Note('B4')

# 6 eighth notes in the other Voice
v2n0 = m21.note.Note('B4')
v2n0.duration.quarterLength = 0.5
v2n1 = m21.note.Note('B4')
v2n1.duration.quarterLength = 0.5
v2n2 = m21.note.Note('C5')
v2n2.duration.quarterLength = 0.5
v2n3 = m21.note.Note('C5')
v2n3.duration.quarterLength = 0.5
v2n4 = m21.note.Note('D5')
v2n4.duration.quarterLength = 0.5
v2n5 = m21.note.Note('D5')
v2n5.duration.quarterLength = 0.5

v1.append((v1n0, v1n1, v1n2))
v2.append((v2n0, v2n1, v2n2, v2n3, v2n4, v2n5))
cresc = m21.dynamics.Crescendo()
cresc.addSpannedElements(v1n0, v2n2) # Crescendo should be 3 8th notes long (start of measure to end of v2n2)
dim = m21.dynamics.Diminuendo()
dim.addSpannedElements(v2n3,v1n2) # Diminuendo should start with v2n3 (offset=3 8th notes), end with v1n2 (end of measure)
s.insert(0, cresc)
s.insert(0, dim)

s.show('musicxml.pdf', makeNotation=False)
outputFile = s.write(fmt='musicxml', fp=None, makeNotation=False)
print('output musicxml is in', outputFile)

# If you change 'Diminuendo()' to 'Crescendo()' above (or change Crescendo to Diminuendo), the 
# MusicXML (and the Musescore-generated PDF) looks right (the first wedge starts at beginning 
# of measure, ends in the middle, the second wedge starts in the middle, and ends at end of measure).
```

**More information**

I'm running on macOS.  Workaround: If I only use notes from one Voice in the DynamicWedges, everything works fine.  But while this workaround is possible in this simple example, it's not possible in many cases.

**Comment by jacobtylerwalls** [comment]
Hey Greg, thanks for the report. Working through your example taught me about `setIdLocals()`, which luckily enough _is_ still run even with `makeNotation=False`, although I'm not sure whether it should, since it leaves side effects. But that's another question.

If you read the docstring for `setIdLocals()` I think you'll see what the issue is: some music21 classes translate to the same musicxml tag. We need to take that into account. We already have a shared parent class `dynamics.DynamicWedge`, so we should probably be numbering those instead. I might see about putting together a patch this morning.
