### ISSUE TITLE
Doubly-sharped roots in Aug6 chords when assigning same "figure" attribute

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#1205]
**music21 version**

`7.1.0`   

**Problem summary**

I noticed a weird behavior when standardizing the `figure` attributes of my `RomanNumeral` objects.

This (hopefully) self-explanatory code shows the issue.

**Steps to reproduce**

```python
>>> import music21
>>> rn = music21.roman.RomanNumeral("Ger7")
>>> rn2 = music21.roman.RomanNumeral("Ger7")
>>> rn.pitchNames
['F#', 'A-', 'C', 'E-']
>>> rn2.pitchNames
['F#', 'A-', 'C', 'E-']
>>> rn2.figure = "Ger7"
>>> rn2.pitchNames
['F##', 'A-', 'C', 'E-']
>>> music21.__version__
'7.1.0'
>>>
```

Maybe it is my own fault for tampering with the `figure` attributes, but this only seems to happen with Aug6 chords. It might be that there's an operation raising the root somehow. I haven't seen the relevant code yet.

**Comment by jacobtylerwalls** [comment]
Hey Néstor, thanks for the report. I had a quick look and think the issue is probably not clearing some attributes when resetting a figure.

```python
>>> rn2 = music21.roman.RomanNumeral('Ger7')
>>> rn2.bracketedAlterations
[('#', 1)]
>>> rn2.figure = 'Ger7'  # clearing the figure should clear the attributes that got set when parsing the first time
>>> rn2.bracketedAlterations
[('#', 1), ('#', 1)]
>>> rn2.pitches
(<music21.pitch.Pitch F##4>, <music21.pitch.Pitch A-4>, <music21.pitch.Pitch C5>, <music21.pitch.Pitch E-5>)
```

I'd review a patch if you had the time to add a unit test and get this in. No worries if not!

**Comment by mscuthbert** [comment]
Definite bug. Probably just need to clear all lists.

**Comment by napulen** [comment]
Opened #1209 for this

The code is more complicated than I thought, but here is what I know...

The extra bracketed accidental is introduced here:
https://github.com/cuthbertLab/music21/blob/26ac5f690671d33f3003691ad54e6f682f64c86d/music21/roman.py#L2696

I think the solution is definitely clearing lists (at least `bracketedAccidentals`)

The `if` condition in `figure.setter` seems to be the best place for that, because the call to 
https://github.com/cuthbertLab/music21/blob/26ac5f690671d33f3003691ad54e6f682f64c86d/music21/roman.py#L2605
happens in 
https://github.com/cuthbertLab/music21/blob/26ac5f690671d33f3003691ad54e6f682f64c86d/music21/roman.py#L2980
