### ISSUE TITLE
Support "root position" Neapolitan chords using the "N" notation

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#1210]
**Motivation**

Currently, it seems that using the `N` figure for a Neapolitan chord forces the chord to be in its (usual) first inversion

```
>>> import music21
>>> rn = music21.roman.RomanNumeral("N")
>>> rn.pitchNames
['F', 'A-', 'D-']
>>> music21.__version__
'7.2.1'
```

It is clear to me that this is intended, as per this code

https://github.com/cuthbertLab/music21/blob/26ac5f690671d33f3003691ad54e6f682f64c86d/music21/roman.py#L2193-L2195

Unfortunately, this means that a "root-position" Neapolitan cannot be indicated (maybe except as `bII`). 

There are examples in the music literature (e.g., Chopin's Op.28 No.20) of root-position Neapolitans, and some annotators (e.g., me) often differentiate between `N` and `N6`. The current implementation does not support that distinction.

If I understand correctly, to change this behavior, all we need is:

```python
        # Replace Neapolitan indication.
        workingFigure = re.sub('^N6', 'bII6', workingFigure)
        workingFigure = re.sub('^N', 'bII', workingFigure)
```

Thanks!

**Intent**

[x ] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by MarkGotham** [comment]
Thanks for the suggestion @napulen . 

Slightly tangential, but worth noting as part of this discussion that there's an `isNeapolitan` function which does make this distinction (`require1stInversion: bool = True`)

**Comment by mscuthbert** [comment]
I think that like we've done w/ aug-6 chords (Italian, etc.) which also have a default behavior of being in inversion, N should probably mean N6 while getting a root position should take N53 with 53 being explicit (or just bII).  See It53 for precedent.  So the line would be to insert before the "^N" regex a "^N53", "bII" substitution.
