### ISSUE TITLE
Incorrect Transposition for C Trumpet from MusicXML file

### ISSUE THREAD

**Issue by werneta** [cuthbertLab/music21#1235]
**music21 version**

`7.1.0`   

**Problem summary**

In a MusicXML score that uses a C Trumpet with no transposition, the associated music21 instrument has a -2 semitone transposition.

**Steps to reproduce**
Rename attached file to "C Trumpet.musicxml"

```
fname = 'C Trumpet.musicxml'
stream = music21.converter.parseFile(fname)
print(stream[2][0]) 
print(stream[2][0].transposition)
```

**Expected vs. actual behavior**
Expect:
```
P1: C Trumpet: C Trumpet
None
```

Actual:
```
P1: C Trumpet: C Trumpet
<music21.interval.Interval M-2>
```

**More information**
None
[C Trumpet.txt](https://github.com/cuthbertLab/music21/files/8148300/C.Trumpet.txt)

**Comment by jacobtylerwalls** [comment]
Thanks for the well-written report.
