### ISSUE TITLE
Notes offsets in 2/2 counts as 4 beats, instead of 2.

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#1238]
**music21 version**
6.7.1

**Problem summary**
Note offsets of parts in scores with 2/2 Time signature get counted on a 4 basis, like it was 4/4, instead of counting on a 2 basis.

**Steps to reproduce**
myStream1 = converter.parse('tinynotation: 2/2 c4 e4 g2')
myStream1.elements[0].elements[5].offset

I'm not sure if this is the right code to explain it as it doesn't include measures, but the result is as expected. Getting the offset of the last element results in 4.0 in a 2/2 Stream, which I believe it's not what according to music theory should (2.0).

Just let me know if you have previously considered this and it is intended or there are some changes there should be made.

Thank you very much in advance! Let's keep in touch in case you need any further info

PD: note.offset is an immutable attribute so there is no easy fix I can make by just dividend all note offset elements by 2 or sth like that.

**Comment by mscuthbert** [comment]
offsets are by default measured in quarterLengths.  This behavior is correct.  You can get the beat position with .beat

Note that if beats were used as a fundamental basis then meters like 5/8 could have quarter notes and dotted quarter notes with same offset and duration in the same measure, which would be computationally confusing.

**Comment by mscuthbert** [comment]
Also note that note.offset is not immutable.  "n.offset = 503.25" works great.  But offset is relative to a stream, so you'll need to do  `s.elementOffset(n, 503.25)` where s is the immediate container of n.  You can find that from `myStream1` with containerInHierarchy()

(music21 v7 code here; please upgrade).

```

In [9]: bach = corpus.parse('bwv66.6')
b
In [10]: bach[note.Note][54]
Out[10]: <music21.note.Note D#>

In [11]: d = bach[note.Note][54]

In [12]: bach.containerInHierarchy(d)
Out[12]: <music21.stream.Measure 4 offset=13.0>

In [13]: bach.containerInHierarchy(d).activeSite
Out[13]: <music21.stream.Part Alto>
```

**Comment by DIDONEproject** [comment]
Hey Michael, thanks for your advice. You are right about the offsets measuring. I needed kind of a 'global beat' measure, like a coordinate to place notes along the score to compare this info to other information at the beat level. I thought offset could work but now that I see it, I ended up creating this global beat with measurenumber + beat. So I don't need offsets any more.
Thanks again for your availability and sorry for bothering you! :)

**Comment by mscuthbert** [comment]
No problem at all.  Glad to help!
