### ISSUE TITLE
UserGuide / Colab / Link / Accessibility

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1243]
**Motivation**
Direct readers of the user guide to colab so that they can experiment right away.
This could be very helpful given that installation is the hardest part for new users and (otherwise) has to come first.

**Feature summary**
A simple colab link at the top of each userGuide notebook.

**Proposed implementation**
Either just:
```
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/cuthbertLab/music21/blob/master/documentation/source/usersGuide/usersGuide_01_installing.ipynb)
```
Or perhaps, slightly wordier:
```
To experiment with this chapters' content online (no installation required), [click here](https://colab.research.google.com/github/cuthbertLab/music21/blob/master/documentation/source/usersGuide/usersGuide_01_installing.ipynb)
```
Or perhaps with another short page with explanation.

**Intent**
I'm happy to implementing this myself, or for anyone else to.
And there should be not maintenance issue, except a small update if the chapter numbering ever changes.

**Comment by jacobtylerwalls** [comment]
Closing per mailing list discussion: won't be expanding the supported platforms footprint at this time. If you do wire up your own table of contents and share on the list, I'd enjoy playing with it.

**Comment by MarkGotham** [comment]
Thanks @jacobtylerwalls and sorry I missed this suggestion the first time around. I have now put URLs for the 'Users Guide' via Colab up on the list (https://groups.google.com/g/music21list/c/UTliPUChTGM/m/WYrQyC7RAwAJ?pli=1).

FAO anyone coming across this chat, Myke has since produced a great landing page here: https://tinyurl.com/m21colab
