### ISSUE TITLE
Problem with 'start' and 'stop' in nested tuplet with Dolet 8 

### ISSUE THREAD

**Issue by charlesneimog** [cuthbertLab/music21#1263]
**music21 version**

`7.3.1`  

**Problem summary**

Hi, I am having a problem with nested tuplets exported by `Dolet 8` in `Sibelius`. The nested tuplet level 1 has the type `stop` when just the level 2 should be `stop`. See this example: 

![image](https://user-images.githubusercontent.com/31707161/162203193-04257817-8699-4930-a493-5b7fd2385cb4.png)

Some observations:

* This seems to happen just with nested tuplets that start with two levels! _All tuplets in the score below have this problem!_

![sem título 3](https://user-images.githubusercontent.com/31707161/162213022-7e56bbd3-6647-43d3-afa3-4da42de62913.png)

**Steps to reproduce**

``` python
### VARIABLES ###

musicxml_file = "MY-FILE.musicxml"

### CODE 

import music21 

xml_data = music21.converter.parse(musicxml_file)
for part_index in xml_data.parts:
    all_measures = part_index.getElementsByClass(music21.stream.Measure)
    for measure in all_measures:
        ## Loop for Measures
        numero_do_compasso = measure.number
        print(f'=========================== | Compasso {numero_do_compasso} ======================')
        for notes_and_rests in measure.notesAndRests: 
            tuplets = notes_and_rests.duration.tuplets
            if len(tuplets) != 0:
                print(tuplets[0].type)
```
-----------------------------
#### Actual behavior

```
=========================== | Compasso 1 ======================
start
None
stop                ### HERE THE ERROR
None
stop
=========================== | Compasso 2 ======================
start
None
None
None
None
stop
=========================== | Compasso 3 ======================
start
None
None
None
None
None
None
None
stop

```
---------------

#### Expected behavior
```
=========================== | Compasso 1 ======================
start
None
None                ### ERROR FIXED
None
stop
=========================== | Compasso 2 ======================
start
None
None
None
None
stop
=========================== | Compasso 3 ======================
start
None
None
None
None
None
None
None
stop

```

-------------------

`Musicxml` and `Sibelius` file: [music21.zip](https://github.com/cuthbertLab/music21/files/8443132/music21.zip)

**Would be possible to fix it in another way, maybe someone has some idea, I thought a lot and I couldn't.**

**Comment by charlesneimog** [comment]
Yes, I noted that would be a problem for `Dolet`. 

Thank you very much for the answer and the fast Pull Request. It will be very helpful to my research.

Charles,

**Comment by mscuthbert** [comment]
Note btw that Musescore also has very limited nested tuplet import support (or did last time I checked) so Finale's output is the only one I know that can be trusted (have not checked Dorico)
