### ISSUE TITLE
"No available MusicXML readers are found on your system" with multiple readers installed

### ISSUE THREAD

**Issue by mirandamon** [cuthbertLab/music21#127]
Hi, 

I have both Finale Notepad 2012 and Sibelius installed, but whenever I run the configure.py script, it never is able to find a reader. I am running OS X El Capitan. Any help would be greatly appreciated!

**Comment by mscuthbert** [comment]
What are the pathnames to your readers? Should be something like /Applications/Sibelius.app or something of that sort. Finale Notepad 2012 should definitely be found.  I'm not sure if we have automatic opening of Sibelius working though.  Thanks!

**Comment by mirandamon** [comment]
Both of them are in the Applications directory (/Applications/Sibelius.app and /Applications/Finale Notepad 2012.app). I did notice that for some reason, Sibelius is set to be the default application to open MusicXML files, but Finale was not even on the list of default applications.

**Comment by mscuthbert** [comment]
Okay -- I figured out the Finale Notepad problem and I've pushed it into the latest version which will be in the next release.  I don't have Sibelius, so I can't test it well.  Could you try doing this on the terminal.  Find a directory with a musicxml file (example: score.xml) and try typing this:  

``open -a"/Applications/Sibelius.app" score.xml``

If that works, then I'll make a patch for Sibelius.

This doesn't solve your particular problem until I do another release.  So I'd say do this.  Open terminal and try to edit the file ``.music21rc`` and find the preference ``musicxmlPath`` and change it to:

``<preference name="musicxmlPath" value="/Applications/Finale NotePad 2012.app" />``

That should do it.

**Comment by mirandamon** [comment]
Okay, I just tested ``open -a"/Applications/Sibelius.app" score.xml`` and it did open Sibelius.

It looks like the default value for ``musicxmlPath`` was ``"/Applications/Finale NotePad 2014.app"``. When I changed it to 2012, it worked. Thank you so much!

**Comment by mscuthbert** [comment]
Glad this was helpful!

Btw -- running `python -m music21.configure` should now fix this automatically.
