### ISSUE TITLE
Raise an exception when `RomanNumeral` gets non-numeric non-accidental figures

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1280]
**Motivation**
In v8, I suggest raising an exception when something non-numeric or non-accidental-ish is passed to the RomanNumeral constructor:

```python
>>> roman.RomanNumeral('V¯\_ (ツ)_/¯')
<music21.roman.RomanNumeral V¯\_ (ツ)_/¯>
```

The more realistic case:
```
>>> roman.RomanNumeral('viiº').commonName  # because that symbol is subtly different from °
'minor triad'
```

**Feature summary**
see above. Need a way to delimit allowed figures (numeric, b, #, n? hyphen?)

**Intent**

[x] I plan on implementing this myself.

**Comment by MarkGotham** [comment]
+1 ... with the caveat that similar symbols should be mapped to the obviously intended form, or nudged that way. We map `/o` to `ø` now; isn't `º` to `°` comparable? I don't know where the line exactly, but yes `¯\_ (ツ)_/¯` sure wants an exception!
