### ISSUE TITLE
Single convenience function for simplifying a Roman numeral (or perhaps any harmony)

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1319]
**Motivation**
Music21 currently has several ways of simplifying returning a simplified form of a Roman numeral.
For instance:
```
>>> rn = roman.RomanNumeral('#ivo65[add4]')
>>> rn.romanNumeral
'#iv'

>>> r.romanNumeralAlone
'iv'
```
I can never remember which one does what.

**Feature summary**
A single `.simplify()` convenience method on the `roman.RomanNumeral` object, bringing these (and other) options together.

**Proposed implementation**
Given a chord (expressed as a `roman.RomanNumeral`, or perhaps also accepting a figure str),
simplify that chord in one or more ways with settable arguments like:
- `hauptHarmonicFunction` returns the basic function like T; e.g., 'I' becomes 'T'. See notes at music21.analysis.harmonicFunction
- `fullHarmonicFunction`: likewise, but supports Nebenfunktionen, e.g., 'vi' in a major key becomes 'Tp'. Again, see notes at music21.analysis.harmonicFunction
- `ignoreInversion` e.g., '#ivo65' becomes '#ivo'.
- `ignoreRootAlt` e.g., '#ivo' becomes 'ivo' (NB: Not usually desirable!)
- `ignoreOtherAlt` ignore all added, removed, or chromatically altered tones. So '#ivo[add#6]' becomes '#ivo'.
- More!

These are all settable separately, and so potentially combinable, but note that there is overlap and hierarchy here (i.e., some imply others).

**Intent**
[X] I plan on implementing this myself ... if it's of mutual interest ;)

**Comment by mscuthbert** [comment]
I'm much less interested in this than in improving the docs so it's clear what to use when.  I'm not sure what "Simplify" means in this context.

**Comment by jacobtylerwalls** [comment]
Hey Mark, I agree with Myke here so I hope you don't mind if I close this. I think better docs for the properties would be great!
