### ISSUE TITLE
'notesAndRests' breaks the 'secondsMap' Attribute

### ISSUE THREAD

**Issue by sonovice** [cuthbertLab/music21#133]
Trying to get the `secondsMap` of a `notesAndRests` Stream like this
```python
parsed = converter.parseFile('Krebs_Trio_Eb_2.mei', None, "mei", True)
secondsMap = parsed.flat.notesAndRests.secondsMap
```

results in an error: `AttributeError: 'StreamIterator' object has no attribute 'secondsMap'`

I am pretty sure that this was working 2 months ago...

**Comment by mscuthbert** [comment]
Not a bug. StreamIterators are now produced and not Streams from calls such as .notesAndRests. It's the big change for v3. See the music21list for details. Call .stream() to get a stream.

On Jan 11, 2016, at 04:39, Simon Waloschek <notifications@github.com<mailto:notifications@github.com>> wrote:


Trying to get the secondsMap of a notesAndRests Stream like this

parsed = converterparseFile('Krebs_Trio_Eb_2mei', None, "mei", True)
secondsMap = parsedflatnotesAndRestssecondsMap

results in an error: AttributeError: 'StreamIterator' object has no attribute 'secondsMap'

I am pretty sure that this was working 2 months ago

**Comment by sonovice** [comment]
Ah, thanks a lot.
Maybe interesting: `secondsMap = parsed.flat.secondsMap` works, so .flat returns a Stream, not a StreamIterator. Not sure if this is intended. I will subscribe to the list...

**Comment by mscuthbert** [comment]
Yes, .flat changes the offsets of elements so it needs to produce a new Stream.  My plan is to make things like `.secondsMap` still work on StreamIterators, if I can, but it's worth being on the list to see the major changes to v.3. anyhow.

**Comment by mscuthbert** [comment]
Btw -- I put the fix in (see latest post to the list) so this would work now.  Think of this thread as a rejected bug report but accepted feature enhancement. :-)

**Comment by sonovice** [comment]
Thank you very much ;-)
