### ISSUE TITLE
Possible bug/slowness in Harmony constructor

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#1350]
**music21 version**

`8.0.9a`   

**Problem summary**

In harmony.py, l. 246 currently reads:

    if (updatePitches
            and self._figure  # == '' or is not None
            or 'root' in self._overrides
            or 'bass' in self._overrides):
        self._updatePitches()

before a formatting change in 2020 it was:

    if (updatePitches and self._figure is not None
            or 'root' in self._overrides or 'bass' in self._overrides):

before that it was:

    if self._figure is not None or self._root or self._bass:            
        self._updatePitches()

The way `W and X or Y or Z` is parsed is `(W and X) or Y or Z`.  
I think we mean `W and (X or Y or Z)`

I'm wondering if it is supposed to be something like this:

    if (updatePitches 
        and (self._figure
                or 'root' in self._overrides 
                or 'bass' in self._overrides)):

Does that seem right to you, @jacobtylerwalls ?

**Comment by jacobtylerwalls** [comment]
Yeah, worth a try. I just don't know if we have enough tests with ChordSymbols calling updatePitches=False with bass overrides. I see a few places in the internals that call updatePitches=False.
