### ISSUE TITLE
Stream.__getitem__ is stricter about subclassing `Music21Object` than `ClassFilter`

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1360]
**music21 version**
de1be4b76af0ce2bae9bdfb2a7f02eaa787370ec

**Problem summary**
Filtering streams with the square-bracket syntax enforces stricter conditions on types (must subclass `Music21Object`) than long-hand searches with `.getElementsByClass()`.

**Steps to reproduce**

```python
>>> from music21 import *
>>> s = stream.Stream()
>>> s.append(bar.Repeat())
>>> [x for x in s.getElementsByClass(repeat.RepeatMark)]
[<music21.bar.Repeat direction=start>]
>>> [x for x in s[repeat.RepeatMark]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacobwalls/music21/music21/stream/base.py", line 619, in __getitem__
    raise TypeError(
TypeError: Streams can get items by int, slice, class, or string query; got <class 'type'>
```

**Expected vs. actual behavior**
The two forms should behave the same: we should either enforce Music21Object inheritance for class queries in both forms, or we should loosen it to ProtoM21Object to ease the problem of searching for mixins like RepeatMark.

There are some documented places that say to search on the string "RepeatMark" instead of `repeat.RepeatMark` for this very reason, despite that it works with the longhand form.

**More information**
Found while doing #1359, and could potentially be fixed in the same PR.

**Comment by mscuthbert** [comment]
Definitely should both be the same.  Better to do the looser way to allow Mixins, but maybe should be loosened to just `isinstance(k, type)`?   Would be faster also.

**Comment by jacobtylerwalls** [comment]
> maybe should be loosened to just isinstance(k, type)? Would be faster also.

Took that approach in #1359
