### ISSUE TITLE
The editorial is not linked to a note when read musescore file

### ISSUE THREAD

**Issue by xav12358** [cuthbertLab/music21#1386]
Hello,

I notice that when I read a mxl file containing indication at the top of each note there editorial data in the note.

**Comment by mscuthbert** [comment]
Closing.  Please use the "bug report" form to explain what you've done, your version, etc. and what happens.  Note that .mxl (compressed) files are much harder to diagnose bugs in, so please make an uncompressed .musicxml file to demonstrate.
