### ISSUE TITLE
RomanText: m15-18 = m1-4 syntax copies repeats

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1387]
**music21 version**

`8.0.0a9'`   

**Problem summary**

I've just noticed that the m15-18 = m1-4 syntax copies repeat signs. I don't think this is expected or ideal behavior.

**Steps to reproduce**

Consider a score like [this song](https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/OpenScore-LiederCorpus/Hensel%2C_Fanny_(Mendelssohn)/6_Lieder%2C_Op.9/3_Der_Rosenkranz/score.mxl) by Fanny Hensel.

- The song begins with a 14-bar strophe that is repeated once (with repeat signs).
- The next 14-bar strophe is a variation written out in full.
- The fourth and final strophe is another variation written out in full.

The annotator of the [analysis here](https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/OpenScore-LiederCorpus/Hensel%2C_Fanny_(Mendelssohn)/6_Lieder%2C_Op.9/3_Der_Rosenkranz/analysis.txt) used romantext's "=" syntax to indicate direct repetitions. In particular, we have

```
m1 E: I b2 V7
m2 I b2 V42/IV b2.33 IV6 b2.67 I64
m3 IV b2 IV6 b2.33 I64 b2.67 IV
m4 I6 b1.67 ii6 b2 V
```
and later
```
m15-18 = m1-4
```
and 
```
m29-32 = m1-4
```

However, I'm just now going through and adding repeats to these files. This causes a problem here because the repeats are copied along with the harmonies. There is a forward repeat bar at the start of measure 1; it is thus copied to mm. 15 and 29, where it does not belong.

I don't believe this is expected behavior according to the romantext standard, which says the following about the "=" syntax.

![Screen Shot 2022-08-15 at 11 51 17 AM](https://user-images.githubusercontent.com/28103673/184688624-d413dc11-916f-476f-bc40-409f07156163.png)

I can imagine many more scenarios in which one would not wish to copy the repeat signs (such as the present song) than those in which one would. Assuming no one has any objections (@MarkGotham?) I will go ahead and implement a PR to avoid copying repeats.

**Comment by mscuthbert** [comment]
Disagree -- if there are any differences in the measures, then they should be written as:

```
...
m4 I6 b1.67 ii6 b2 V :||
...
m15-17 = m1-3
m18 I6 b1.67 ii6 b2 V
```

the parser shouldn't be going through and deciding exactly what you want to and don't want to copy when you say "make a copy".

**Comment by malcolmsailor** [comment]
OK, that's fine. 

My thinking was that
1. the standard specifically says that the equals syntax copies harmonies (i.e., not repeat signs)
2. revealed expectations by annotators in demonstrate that they expect the repeats not to be copied. (I.e., there are many cases in the When-in-Rome corpus where repeats are inadvertently copied because of the = syntax.)

But in any case I already went through the corpus and made a version of When in Rome where inadvertently copied repeats are repaired by avoiding the = syntax. So I guess I will just go ahead and make a PR of that there.

**Comment by MarkGotham** [comment]
Thanks both. I understand both sides and defer to Myke's final judgment.

Related to this, there's explicit repeat of the time signature when m1 is involved in that repeat.

@mscuthbert could you countenance removing the duplicate time signature, either at the point of repeat, or in a post hoc 'remove all time signature duplicates'.

You could view this as different because the initial time signature is not specified in measure, but on a separate line of rntxt. Indeed, perhaps that first line should write to the part, rather than m1.

Happy to implement this if approved.

**Comment by mscuthbert** [comment]
yeah, we'll go with #1387 in some form.

I think the standard is ambiguous at this point.  It's sort of like if you copy from another key, all the chords get parsed in the new key, but if the first measure of the copy region has a key indicated then you need to edit the measure to make remove the key specification.
