### ISSUE TITLE
Parsing double-flat keys in RomanText

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1390]
**music21 version**

`8.0.0a9`   

**Problem summary**

The RomanText parser can't handle keys with double-flats, which occasionally occur in highly chromatic music (e.g., in [this Reger example](https://github.com/MarkGotham/When-in-Rome/blob/master/Corpus/Textbooks/Reger%2C_Max/Modulation/21/analysis.rntxt)).

**Steps to reproduce**

```
>>> music21.converter.parse("m1 Bbb: I", format="romanText")[music21.roman.RomanNumeral].first()
<music21.roman.RomanNumeral I in B- major> # should be B-flat-flat, not B-flat
```

Double-sharps are ok:
```
>>> music21.converter.parse("m1 F##: I", format="romanText")[music21.roman.RomanNumeral].first()
<music21.roman.RomanNumeral I in F## major>
```

And music21 can handle double-flat keys in general:
```
>>> music21.key.Key("B--")
<music21.key.Key of B-- major>
```

I can have a look into this.

**Comment by MarkGotham** [comment]
Thanks!
