### ISSUE TITLE
Reading and writing xml file remove forward repeats

### ISSUE THREAD

**Issue by RoyShmuli** [cuthbertLab/music21#1400]
**music21 version**

`7.3.3`   

**Problem summary**

Source sheet:
![image](https://user-images.githubusercontent.com/16102210/186158116-9b24bd26-bc82-469f-9386-4755118b02ac.png)

Sheet after read and write:
![image](https://user-images.githubusercontent.com/16102210/186158200-09cd93d7-b790-4002-95ae-cfb5040c594a.png)

**Steps to reproduce**
Running the following code on the sheet music: 
[Stream remove repeats Test.zip](https://github.com/cuthbertLab/music21/files/9402525/Stream.remove.repeats.Test.zip)

```
fileNameWithoutSuffix = "Stream remove repeats Test"
filePath = "PathToTheFile"
s = music21.converter.parse(f"{filePath}\{fileNameWithoutSuffix}.xml")
fpXML = s.write(xml, fp=f"{filePath}\{fileNameWithoutSuffix}-result.xml") # I also tried with mxl format
```

**Expected vs. actual behavior**

Expected to have the forward repeat (at least in the middle one)
Actual see the image under "Sheet after read and write"

**More information**
Using Windows 11

Am I missing something or is there workaround?

**Comment by mscuthbert** [comment]
Hi @RoyShmuli there are four potential problems:  (1) the .xml file generated by your notation software does not have proper musicxml repeats (not a music21 problem),  (2) the xml file is perfect but music21 is not reading the repeats in properly (they are not found in the stream) -- this would be a music21 problem.  (3) on s.write() the repeats are not appearing properly in the musicxml file, this would be a music21 problem.  (4) the properly created -result.xml file is not being parsed properly by your musicxml reader.  That would not be a music21 problem.

It would be good if you could isolate which of these four problems (or more) is happening -- what is your musicxml writer and reader?  Does writing the file out to .xml and then reading it back in to your software drop the repeats?  Does writing the file from another software system work or reading it from another system (such as musescore) work?  

If your version number of 3.7.7 is correct, please upgrade.  We're only taking 7.3 or master bug reports at this time.  If you're on 7.3 or master and it's still a bug, please paste the MusicXML file in a reply to see if it's something we can fix (problems 2 or 3).  Thanks!

**Comment by RoyShmuli** [comment]
I had typo issue with the version, it is the latest - 7.3.3
I will check where is the exact issue between the 4 options you raised

**Comment by gregchapman-dev** [comment]
I also am seeing repeats removed in piano scores. See issue #1380.

**Comment by RoyShmuli** [comment]
@mscuthbert I know that the bug in music21 lib, the issue related to write stream scope.

1. The input xml contain repeat (you can find 2 forwards and backwards repeats within the xml text)
2. Music21 does read those repeats well by testing the following code:

```
fileNameWithoutSuffix = "Stream remove repeats Test"
filePath = "PathToTheFile"
s = music21.converter.parse(f"{filePath}\{fileNameWithoutSuffix}.xml")
sExpand = s.expandRepeats()

len(sExpand.parts[0].flat.notes) # It's print 4 as expected
len(s.parts[0].flat.notes) # It's print 2 as expected
```

3. Exported xml file contain 2 backwards, but not contain forward direction at all
