### ISSUE TITLE
Stream-stream alignment

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1406]
**Motivation**

There are many contexts in which the basic information of two streams should match. E.g., we typically expect two parts within a single score to have the same number of measures and position of time/key signature changes.

There are also many ways in which those two streams can diverse in practice and end up being displayed and/or encoded differently. E.g., often different editions of the same piece end up with different measure numbering.

In cases where we definitely want to recognise two sources as "the same" (or at least "connected in this way"), we need to somehow get past those differences. It would be useful to have some kind of alignment tool to assist.

**Feature summary**

The new functionality would be similar to the wonderful `.template()` function (for creating a new stream with important information from an existing one) but here serving to adjust an existing stream to (better) match another one.

No attempt to deal with:
- note-level comparisons (that is one possible use case of this functionality)
- all possible differences on the stream (only number of measures; length of those measures; position of changes to time and key signatures).
- choice of which stream to use as the model (user defined)

**Proposed implementation**

Here is a **very** basic example of how to deal with at least anacruses and empty trailing measures:
https://github.com/MarkGotham/When-in-Rome/blob/master/Code/alignStreams.py

For more a fully functional version, perhaps:
- total number of measures match or not?
- in/complete first measure in one / both? Numbered differently?
- pairs of incomplete measures mid-stream that add to a complete one = join them?
- all time and key signatures align (check is optional, default True)
- all repeat marks align (check is optional, default True)

**Intent**

I'm happy to implement this alone or with others.

**Comment by mscuthbert** [comment]
Is this a "check if they match" tool or a "fix if they don't match" tool?  I haven't had this problem arise in my own work, so I'm unclear how much of a general purpose tool this would be and whether it belongs in the main music21 functionality.  If there is a conflict, how does the script know which stream is the correct one, and what sorts of fixes would happen?  If there are two parts with measures of different lengths, does one get rests added to pad or does the other get notes dropped?

5-10 years ago, I would definitely add this to the general toolkit, but since I'm getting more weary about expanding the scope of the main library (as opposed to encouraging add on libraries which are very simple), I'm somewhat against this proposal.

**Comment by MarkGotham** [comment]
Thanks @mscuthbert .

First, and as always ...
- This is functionality that I intend to develop and use.
- I'm offering music21 first refusal on all/any of it that you think appropriate for inclusion, without any pressure. No problem either way!

To the detail in your questions then ...

"check if they match" tool or a "fix if they don't match" tool? I 
- I intend to attempt a fix, but again, the "check" could be on m21 and the "fix" elsewhere.

Use cases
- I mention comparing of parts and scores above. Both have been relevant to me (e.g., in number of first/second time measures), however ...
- the main use case for me at present is as part of a solution to aligning analysis streams with scores. We have talked elsewhere about improvements to our RNTXT, and we'll continue with that, but in my view there is and will probably always be a need for the kind of a separate stream alignment functionality set out here.
- It seems to me like this is of much wider utility for anyone trying to sync up different datasets etc. It won't fix everything but might go a long way.

Which is the "correct" one:
- as above "choice of which stream to use as the model (user defined)"
- also falls to user to assert that comparison is possible and sensible
- also falls to user to select "fix" (if appropriate), default = False.

Further notes in discussion with @magiraud:
https://gitlab.com/algomus.fr/dezrann/dezrann/-/issues/1030#note_1122509147

**Comment by mscuthbert** [comment]
It looks like it'll be a powerful tool, but I want to move music21 function more like Python and the Python standard library -- for anything significant that will require significant upkeep in the future, and that is not a proposal to change the core internals of music21, I'd like to see a third-party implementation first and then if it seems so generally useful that it should be part of the toolkit and the authors want it to be, then it can become part of it.

There are a lot of things I'm developing now that I would've put into music21 in the past, but the amount of time spent per line of code in music21 in upkeep continues to increase, as music21 becomes more performance-tuned, and I need to cut back the time I spend on sysadmining it.  (Hence the dropping of support for pre-Py3.10 m21 lately).

I'm going to close this until the tool is further along.  Feel free to reopen at that point.
