### ISSUE TITLE
voice numbers are (sometimes? always?) ever increasing in each Measure

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1408]
**music21 version**

`8.0.0a12`

**Problem summary**
I think I busted voice numbers badly a few PRs ago.  I'm seeing voice numbers keep incrementing across Measures.  This causes voice numbers to get really large, and Musescore stops rendering notes altogether.

I broke it, I'll fix it.  I will also fix the tests I wrote that let this really bad bug get through.

**Comment by gregchapman-dev** [comment]
Please assign this to me.

**Comment by mscuthbert** [comment]
thanks!  Is it bad enough that I should revert in Master now?

**Comment by gregchapman-dev** [comment]
I take it back. It’s a bug in my own humdrum converter. (Sigh) Never mind. 

Greg

**Comment by gregchapman-dev** [comment]
Ah, this is indeed a regression in music21 due to my voice number PR.  It only happens when there is more than one voice in a staff in a multi-staff part.  I have a fix (PR coming in the next few minutes).
