### ISSUE TITLE
Expected behavior for "bVII7", "bIII7", etc. Roman Numerals?

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1410]
**music21 version**

`8.0.0a12`   

**Problem summary**

Roman numerals with figure "7" preceded by a flat always seem to be dominant 7ths. Based on my reading of the docs this appears unexpected to me.

**Steps to reproduce**
The [docs](https://web.mit.edu/music21/doc/moduleReference/moduleRoman.html) contain this snippet:

> Dominant 7ths can be specified by putting d7 at end:
```
>>> r = roman.RomanNumeral('bVIId7', key.Key('B-'))
>>> r.figure
'bVIId7'
```

The implication seems to be that if we *don't* put a d7 at the end, we'll get the diatonic 7th. This is indeed the behavior for other diatonic degrees, e.g., 

```
In [17]: RN("IV7").pitches
Out[17]: 
(<music21.pitch.Pitch F4>,
 <music21.pitch.Pitch A4>,
 <music21.pitch.Pitch C5>,
 <music21.pitch.Pitch E5>)

In [18]: RN("IVd7").pitches
Out[18]: 
(<music21.pitch.Pitch F4>,
 <music21.pitch.Pitch A4>,
 <music21.pitch.Pitch C5>,
 <music21.pitch.Pitch E-5>)

In [20]: RN("iii7").pitches
Out[20]: 
(<music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G4>,
 <music21.pitch.Pitch B4>,
 <music21.pitch.Pitch D5>)

In [21]: RN("iiid7").pitches
Out[21]: 
(<music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B4>,
 <music21.pitch.Pitch D5>)
```

However, for Roman Numerals preceded by 'b', we get dominant 7ths:

```
In [22]: RN("bVII7").pitches
Out[22]: 
(<music21.pitch.Pitch B-4>,
 <music21.pitch.Pitch D5>,
 <music21.pitch.Pitch F5>,
 <music21.pitch.Pitch A-5>)

In [24]: RN("bII7").pitches
Out[24]: 
(<music21.pitch.Pitch D-4>,
 <music21.pitch.Pitch F4>,
 <music21.pitch.Pitch A-4>,
 <music21.pitch.Pitch C-5>)
```

It seems that to get a major 7th we must use "#7":

```
In [23]: RN("bVII#7").pitches
Out[23]: 
(<music21.pitch.Pitch B-4>,
 <music21.pitch.Pitch D5>,
 <music21.pitch.Pitch F5>,
 <music21.pitch.Pitch A5>)
```

Perhaps this is expected behavior. In that case I would suggest that the example in the docs should be updated to clarify that "bVII' will give a dominant 7th even without the "d" annotation.

But personally, I would prefer if "bVII7" or especially "bII7" used the diatonic 7th of the chord unless the "d" dominant 7th annotation is provided. FWIW, this seems to be what analysts expect, e.g., the bVI7 chord [here](https://github.com/MarkGotham/When-in-Rome/blob/81c00db8d03830846469de70c07185fb2481e458/Corpus/Etudes_and_Preludes/Bach%2C_Johann_Sebastian/The_Well-Tempered_Clavier_I/12/analysis.txt#L24) or the bII7 chord [here](https://github.com/MarkGotham/When-in-Rome/blob/81c00db8d03830846469de70c07185fb2481e458/Corpus/OpenScore-LiederCorpus/Mahler%2C_Gustav/Kindertotenlieder/2_Nun_seh%E2%80%99_ich_wohl%2C_warum_so_dunkle_Flammen/analysis.txt#L20). I am willing to implement this if that suits you.

**Comment by mscuthbert** [comment]
please define `RN(...)` first -- what key is being fed into this function?

d7 is supposed to wipe out all other considerations and leave a dominant chord based on the tonic.  Is that happening or not?  Bb D F Ab in your first example seems to be working.

**Comment by malcolmsailor** [comment]
`RN` is just an alias for `music21.roman.RomanNumeral` to save myself so much typing. Sorry for omitting that. I was not providing any key and just relying on the implicit C major realization of the pitches.

However, the result is the same if I explicitly provide "C", e.g.:
```
In [7]: RN("bII7", "C").pitches
Out[7]:
(<music21.pitch.Pitch D-4>,
 <music21.pitch.Pitch F4>,
 <music21.pitch.Pitch A-4>,
 <music21.pitch.Pitch C-5>)
```

Or C minor:
```
In [8]: RN("bII7", "c").pitches
Out[8]:
(<music21.pitch.Pitch D-4>,
 <music21.pitch.Pitch F4>,
 <music21.pitch.Pitch A-4>,
 <music21.pitch.Pitch C-5>)
```

Note that both chords contain Cb, rather than the "diatonic" (and more likely to be expected, I believe) C-natural.

> d7 is supposed to wipe out all other considerations and leave a dominant chord based on the tonic. Is that happening or not? Bb D F Ab in your first example seems to be working.

Yes, that is happening. The issue I'm raising does not relate to the `d7` annotation, which is working as expected. It relates to chords like bII7 and bVI7. Music21 realizes such chords as dominant 7th chords, regardless of whether they are provided with `d` annotations. I would suggest that it would be better to realize the seventh "diatonically" (i.e., take the note a 7th from the chord root within the original scale---C and C minor respectively in the bII examples above) and only provide a dominant 7th when the `d` annotation is provided. Moreover, this is what the example from the documentation I quoted above implicitly suggests will happen:

> Dominant 7ths can be specified by putting d7 at end:
> ```
> >>> r = roman.RomanNumeral('bVIId7', key.Key('B-'))
> r.figure
> 'bVIId7'
> ```

Note that if we omit the "d" we also get a dominant 7th, in spite of the fact that G-natural, not G-flat, is diatonic to the key of B-flat:

```
In [9]: RN("bVII7", "B-").pitches
Out[9]:
(<music21.pitch.Pitch A-5>,
 <music21.pitch.Pitch C6>,
 <music21.pitch.Pitch E-6>,
 <music21.pitch.Pitch G-6>)
```

**Comment by mscuthbert** [comment]
got it now.  My preliminary notion is that you're right, that in the absence of any other clues (like o or ø or d), 7 should refer to the diatonic seventh.  I was asking about the key in RN, because what the diatonic 7th is for, say, bVII7 in minor is up for debate -- for that one, I definitely think Ab is the correct note to return, not A-natural.

Before implementing this, it'd be good to have at least one citation from a published analysis showing that the expectation of bII7 is to include the tonic note and not the lowered tonic.  I think that the fix will be more than one line of code, and I want to make sure that other experts agree with us on this before implementing.  Thanks!

**Comment by malcolmsailor** [comment]
OK, I'll have a look for published analyses.

I did grep the when-in-rome analysis corpus before posting this issue, which is where I found the examples linked in my first post. In general, these chords are rare (there were only a few) and I didn't find any cases where anyone seemed to have expected a dominant 7th by default.

**Comment by malcolmsailor** [comment]
OK here's a published analysis. Aldwell & Schachter, 4th edition, p 552.
![Screen Shot 2022-09-09 at 7 25 31 AM](https://user-images.githubusercontent.com/28103673/189339637-45a030ab-f724-4463-915c-75e104967b79.png)

Note the Neapolitan 65 with D-natural, whereas music21 gives D-flat:

>>>
In [18]: RN("bII65", "d").pitches
Out[18]:
(<music21.pitch.Pitch G4>,
 <music21.pitch.Pitch B-4>,
 <music21.pitch.Pitch D-5>,
 <music21.pitch.Pitch E-5>)
>>>

**Comment by malcolmsailor** [comment]
@mscuthbert, just bumping this again. I found a published analysis (see my previous comment). Can I look into implementing it? (Or would you rather do so?)

**Comment by mscuthbert** [comment]
That's a good enough example for me (A-S is almost a reference work for how people expect roman numerals to be interpreted).  So that's what M21 should do.  Let me refamiliarize myself with the part of the code base that's making this decision (since I'll need to do that to review any potential PR anyhow) and then I can say whether I can just plop that in or whether I'll lean on your expertise.

**Comment by mscuthbert** [comment]
Fix is being tested now.
