### ISSUE TITLE
Allow writing to file-like objects with romanText writer

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1415]
**Motivation**

I would like to be able to pass a file-like object to the RomanText writer. Judging from [subConverters.write](https://github.com/cuthbertLab/music21/blob/00971f4a8e8d44e326e35bd922fd02311bb8f467/music21/converter/subConverters.py#L262), which delegates to [subConverters.writeDataStream](https://github.com/cuthbertLab/music21/blob/00971f4a8e8d44e326e35bd922fd02311bb8f467/music21/converter/subConverters.py#L275), this capability is expected to be supported, but in `ConverterRomanText` it [is not](https://github.com/cuthbertLab/music21/blob/00971f4a8e8d44e326e35bd922fd02311bb8f467/music21/converter/subConverters.py#L1317). I can implement this modeling the new code on writeDataStream in the parent class `subConverter`.

**Intent**

[x] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by mscuthbert** [comment]
Thanks -- that'd be nice to have.
