### ISSUE TITLE
Save arpeggiate notation when use `Music21Object.write()` outputting sheet music 

### ISSUE THREAD

**Issue by NeroBlackstone** [cuthbertLab/music21#1422]
**Motivation**

At this version (7.3.3), `.musicxml` sheet music outputting will remove all the arpeggiate notation.
But I want save these notation, it's useful.

For example:
sample file: [2.zip](https://github.com/cuthbertLab/music21/files/9546626/2.zip)
Original `.musicxml`:
![before](https://user-images.githubusercontent.com/17470335/189616343-5a2cc743-879f-4ee7-a640-a90c57a453c6.png)

At measure 15:
``` xml
<measure number="15" width="256.95">
...
<note default-x="24.60" default-y="-10.00">
        <pitch>
          <step>D</step>
          <octave>5</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <beam number="1">begin</beam>
        <notations>
          <!-- Here is arpeggiate notation -->
          <arpeggiate default-x="-11.60" default-y="30.30"/>
          </notations>
        </note>
...
</measure>
```

After calling `Music21Object.write()`:

``` python
from music21 import *

s = converter.parse('2.musicxml')
s.show()
s.write(fp=r'out.musicxml')
```
![after](https://user-images.githubusercontent.com/17470335/189617070-17998b0f-2bd9-4a5d-bc15-308bf7562e89.png)

``` xml
<measure number="15" width="256.95">
...
 <note default-x="24.6" default-y="-10">
        <pitch>
          <step>D</step>
          <octave>5</octave>
        </pitch>
        <duration>5040</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <beam number="1">begin</beam>
        <!-- arpeggiate notation removed -->
      </note>
...
</measure>
```

**Feature summary**
Save arpeggiate notation after calling `Music21Object.write()`

**Proposed implementation**
I have no idea.

**Intent**

[ ] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ x ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by gregchapman-dev** [comment]
Support for arpeggios has already been added in music21 v8 (alpha).

Greg
