### ISSUE TITLE
TempoText is ignored when writing MusicXML

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1436]
I have a simple implementation that pulls out the underlying TextExpression and exports _that_.  PR coming soon.

**Intent**

[ x] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by gregchapman-dev** [comment]
PR #1437 fixes this.

**Comment by mscuthbert** [comment]
Ah, needed a "Fixed in #...." to auto close.  Closing.
