### ISSUE TITLE
Discussion Point: Change m21 Release Support

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#1444]
From the mailing list, in case anyone didn't see it.  #1443 will go in this direction unless there are good reasons not to:

-----------
Today also started the path towards v9 — there are still backwards incompatible parts of the system that I want the freedom to break; they would have all gone into v8, but it’s been over 6 months since I last did a release, so I wanted to get that out now.  But I’m going to move right ahead and start the next major version; there is unlikely to be a v8.3, but who knows, because…

The policy of music21 (er…of me) since music21 v2 has been to support the latest three versions of Python (+Py2.7 until v5) available at the time of release.  This means that music21 v9 would support Python 3.9, 3.10, and (starting in late October) 3.11.  The primary branch of music21 is already on Py3.9-only status, and I like it a lot.

I have found though that needing to use only older Python syntax, modules, etc. has made me enjoy working on music21 far less than I should (maybe other devs feel this way too?) and sometimes the little bit of free time that I could use to implement something we all want instead goes to other projects.   Music21’s a pretty mature project (witness the chirps on this list announcing a new release) and many people are happy using v6 or v7 and don’t need to upgrade all the time.  At the same time, upgrading to a new Python version keeps getting easier and easier, so (except for Google Colab users, who are already lost in v8) the number of people who would want the latest m21 version but need an old Python version keeps getting fewer and fewer.

I propose that music21’s latest version now be developed only for the latest version of Python available when development of that version started (so Python 3.10 right now) and any versions released during development (Py3.11 I imagine).  Patches will be accepted that also target earlier versions of music21, so if someone really wants/needs their code to work on Python 3.8/9/10 they are welcome to submit a PR against the main branch as well as m21_8, m21_7, etc.  Very Major bugs uncovered (or things that break due to changes in Python packaging etc.) will be fixed in the last version also, but minor bugs (or bugs that affect only a small number of users) will only be fixed in the new version.

This isn’t the best way of doing things if there were a major dev team with major financial support, but given the small group of people developing music21, I think that this is the right way forward for the energy and enthusiasm of the project.

Comments and discussion welcome.

**Comment by gregchapman-dev** [comment]
I think I like this. Approximately when do you think v9 will be released?

**Comment by mscuthbert** [comment]
It's been four days since announced on music21 list and here and no objections and one support message.  This is going to happen!
