### ISSUE TITLE
RomanNumeral: "d7" doesn't work with "+"

### ISSUE THREAD

**Issue by malcolmsailor** [cuthbertLab/music21#1448]
**music21 version**

`9.0.0a1` 

**Problem summary**

The "d7" syntax for dominant-7th quality chords doesn't seem to work when preceded by "+" (for augmented).

**Steps to reproduce**

```
In [1]: from music21.roman import RomanNumeral as RN

In [2]: RN("I+", "C").pitches
Out[2]: (<music21.pitch.Pitch C4>, <music21.pitch.Pitch E4>, <music21.pitch.Pitch G#4>)

In [3]: RN("Id7", "C").pitches
Out[3]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G4>,
 <music21.pitch.Pitch B-4>)

In [4]: RN("I+7", "C").pitches
Out[4]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B4>)

In [5]: RN("I+d7", "C").pitches # I expect G# and Bb, but get G# and B-natural
Out[5]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B4>)
```

Assuming there are no objections to implementing this so we get G# and B-flat, I can look into implementing a fix.

On the other hand if there *are* objections, then I think such figures should raise an exception.

**Comment by mscuthbert** [comment]
I don't see it as a mistake -- I've never heard of an augmented dominant 7th.  Specify as "Id7[#5]" or "I+[addb7]" -- d7 specifies a dominant 7th chord, and that's not what this is.

```
In [3]: roman.RomanNumeral('Id7[#5]').pitches
Out[3]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B-4>)

In [4]: roman.RomanNumeral('I+[addb7]').pitches
Out[4]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B-4>)
```

**Comment by mscuthbert** [comment]
also works:

```
In [7]: roman.RomanNumeral('Ib7#53').pitches
Out[7]: 
(<music21.pitch.Pitch C4>,
 <music21.pitch.Pitch E4>,
 <music21.pitch.Pitch G#4>,
 <music21.pitch.Pitch B-4>)
```

**Comment by mscuthbert** [comment]
The only thing I think to possibly do is in a strict mode to throw an exception for "+d"

**Comment by mscuthbert** [comment]
Yes, I am aware of it as a jazz/pop standard, and if "+7" is not working in ChordSymbol then I'd be immediately inclined to fix it.  But it is not a standard in Roman numerals which is what this module concerns.  I very much want to push back on having a "dominant-seventh" chord that doesn't sound like a dominant seventh chord, and that's what the d7 symbol in m21 is about.

**Comment by mscuthbert** [comment]
Closing as not planned -- this sounds like something that preprocessing of TSV format should take care of before passing to RomanNumeral rather than a change in the very delicate RomanNumeral._parseFigure core.
