### ISSUE TITLE
Major/minor distinction in `roman.RomanNumeral` from degree

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1450]
**music21 version**

Github, dev.

**Problem summary**

RomanNumeral from degree always return major triads.

**Steps to reproduce**

```
>>> majorKeyObj = key.Key("C")
>>> roman.RomanNumeral(1, majorKeyObj)
<music21.roman.RomanNumeral I in C major>

>>> minorKeyObj = key.Key("c")
>>> roman.RomanNumeral(1, minorKeyObj)
<music21.roman.RomanNumeral I in c minor>
```

**Expected vs. actual behavior**

The above should return
- `I` in major (upper case)
- `i` in minor (lower case)

Instead, they both return `I` (upper case).

**Comment by MarkGotham** [comment]
p.s.
This extends to `ConcreteScale.romanNumeral` which is a convenience function for the same thing.

**Comment by mscuthbert** [comment]
Sorry, your code does not work, can you edit to give working code.

**Comment by MarkGotham** [comment]
Apologies for the unmatched bracket (prob. a copy'n'paste fail).
Done now.

**Comment by MarkGotham** [comment]
Also clarified further in case the case is not very visible -- pun intended ;)

**Comment by MarkGotham** [comment]
Ok, sorry to be the bearer of bad news but there's a related bug:

Given a single pitch, the equivalent function within `roman.romanNumeralFromChord` always returns minor.

```
>>> rn = roman.romanNumeralFromChord(chord.Chord("C"), key.Key("C"))
>>> rn
<music21.roman.RomanNumeral i in C major>
```

So in summary we have:
- always major from `<key>.romanNumeral(<degree>)` on a degree (as previously reported) and now ... 
- always minor from `roman.romanNumeralFromChord(<chord>)`

Came across this thinking it would be helpful for refactoring #796 but clearly no luck that. That PR now has a rather verbose workaround for all of this.

Ok that's all!

**Comment by jacobtylerwalls** [comment]
@MarkGotham would you like to test if a patch like this functions as expected?

```diff
diff --git a/music21/roman.py b/music21/roman.py
index 15414fe72..de87e1cac 100644
--- a/music21/roman.py
+++ b/music21/roman.py
@@ -2373,8 +2373,18 @@ class RomanNumeral(harmony.Harmony):
         self.scaleCardinality: int = 7
 
         if isinstance(figure, int):
-            self.caseMatters = False
             figure = common.toRoman(figure)
+            if self.caseMatters:
+                mode = ''
+                if isinstance(keyOrScale, key.Key):
+                    mode = keyOrScale.mode
+                if isinstance(keyOrScale, scale.DiatonicScale):
+                    mode = keyOrScale.type
+                if (
+                    (mode == 'major' and figure in ('II', 'III', 'VI', 'VII'))
+                    or (mode == 'minor' and figure in ('I', 'IV', 'V'))
+                ):
+                    figure = figure.lower()
 
         # immediately fix low-preference figures
         if isinstance(figure, str):
```

There is some overlap with `figureAndKey`, so maybe the common functionality could be factored out into `modeFromKeyOrScale` or something like that.

**Comment by MarkGotham** [comment]
Hi @jacobtylerwalls.

The answer is ... 

1a.
... "yes " to fixing this first part within ` roman.RomanNumeral`:
```
>>> minorKeyObj = key.Key("c")
>>> roman.RomanNumeral(1, minorKeyObj)  # key obj argument works
<music21.roman.RomanNumeral i in c minor>
```
Do you want a PR for ^ that working part (with a couple of doc tests and `II` in the minor list), or will you do it?

1b.
... no to fixing this variant on the same:
```
>>> roman.RomanNumeral(1, 'c')  # string argument fails
<music21.roman.RomanNumeral I in c minor>
```

2.
... and no change to (not called by) the `roman.romanNumeralFromChord` (still always minor).
I'm pretty sure that latter part is due to this current routine:
```
    root = chordObj.root()
    thirdType = chordObj.semitonesFromChordStep(3)
    if thirdType == 4:
        isMajorThird = True
    else:
        isMajorThird = False
```
I.e., this appears to assume minor third, including (perhaps inadvertently?) where there's no third. We probably want either a new `thirdType = None` option, or else to assume third from missing degree, so a figure like `I[no3]` still has a `thirdType = 4` and `isMajorThird = True`?

Happy to help further or leave this to you as you prefer.

**Comment by jacobtylerwalls** [comment]
Thanks, that's helpful. I'll put up a PR for bug 1a/1b, and ask you to review.

For bug 2, can you open a new issue?
