### ISSUE TITLE
Regression issue - unable get fingering of cords after parsing xml file

### ISSUE THREAD

**Issue by RoyShmuli** [cuthbertLab/music21#1473]
**music21 version**

Issue on version `8.1.0`   
Working well on version `7.3.3`

**Problem summary**

**Regression issue unless there is a new way, I didn't find out.**
Unable get all fingering of chord, I'm receiving only the first finger

![image](https://user-images.githubusercontent.com/16102210/198280635-565c74ca-770f-49ca-be76-204dde5574f6.png)

**Steps to reproduce**

Use the following code and the attached file (simple cord)

```
for generalNote in music21.converter.parse(f"myFile.xml").parts[0].flat.notes:
  fingers = []

  # On version 8.1.0 print "generalNote.articulations.size: 1"
  # On version 7.3.3 print "generalNote.articulations.size: 3"
  print(f"generalNote.articulations.size: {len(generalNote.articulations)}")

  for articulation in (generalNote.articulations):
    if isinstance(articulation, music21.articulations.Fingering):
      fingers.append(articulation.fingerNumber)

  # fingers contain 1 finger on verion 8.1.1 and 3 fingers on version 7.3.3

```

**Expected vs. actual behavior**

Actual getting 1 finger
Expected getting 3 fingers

**More information**

**Comment by mscuthbert** [comment]
I believe that this is a known change and improvement.  If a note is a Chord, then you should iterate over it:

```
for chordNote in foundChord.notes:
     print(chordNote.articulations)
```

The reason for the change is that it is possible to associate a particular fingering with a particular note in a chord, not just three fingerings to the chord as a whole.

**Comment by RoyShmuli** [comment]
Thanks for quick responding
The change make sense, but I'm getting 3 times empty list using your code.

Is there a doc of upgrade from version 7 to 8?

**Comment by mscuthbert** [comment]
That'd be https://github.com/cuthbertLab/music21/releases/tag/v8.1.0

But I'm not seeing this there.  I'll need to look at it over the weekend when I've recovered from an illness unless someone else remembers exactly what the issue is.  I'm not sure my syntax above was exact, only that I remember the change being consciously made.

We're trying to have a better changelog for v9.

**Comment by RoyShmuli** [comment]
Feel well 🙏

I think you right with the syntax

**Comment by mscuthbert** [comment]
Am trying to replicate, but now seeing that there was no attached file.  Can you attach?

**Comment by mscuthbert** [comment]
hmmm, the relevant changes seem to have happened in 2018, that's why they're so vague in my memory: https://github.com/cuthbertLab/music21/pull/323

**Comment by RoyShmuli** [comment]
The file is a simple chord, adding it here 

[myFile.zip](https://github.com/cuthbertLab/music21/files/9883753/myFile.zip)

I think the issue on nullify the articulations of the notes, in xmlToM21.py -> function xmlToChord
code:
`n.articulations = []` # Removing this line resolve this issue (maybe cause another issue)
Maybe have the same issue with
`n.expressions = []`

I don't know if we can just remove them or there is another reason they exist

**Comment by RoyShmuli** [comment]
Moreover (another related issue) I think in xmlToChord we copy the first finger to chord object, that's why I received one finger

```
for generalNote in music21.converter.parse(f"myFile.xml").parts[0].flat.notes:
  fingers = []

  # On version 8.1.0 print "generalNote.articulations.size: 1" for chord object
  print(f"generalNote.articulations.size: {len(generalNote.articulations)}")
```

**Comment by jacobtylerwalls** [comment]
I bisected the change to b624ef360aeaedf8e5819465a3674d76328d2922's changing `pass` to `continue` to match the way the surrounding code was documented. It improved some use cases but removed the support for importing multiple fingerings on one chord.

**Comment by mscuthbert** [comment]
Thanks @RoyShmuli and @jacobtylerwalls -- I completely misdiagnosed the issue.  It turns out we never did the movement of fingerings to notes also.
