### ISSUE TITLE
Grace note (acciaccatura)

### ISSUE THREAD

**Issue by garncarz** [cuthbertLab/music21#148]
I'm able to produce grace notes which are shown in MuseScore as appoggiaturas, and they sound half the bar (tooo long :train:), but how do I produce acciaccaturas, sounding just very briefly? :zap:

Even the following note sounds half the bar.

```py
note.Note(
    name,
    duration = duration.GraceDuration(
        quarterLength=0.05,
        type='64th',
        makeTime=True,
        stealTimeFollowing=True,
    ),
)
```

**Comment by garncarz** [comment]
The best hack I could come up with is like this:

```py
GRACE_LEN = 0.125
dur_stolen = 0  # global for grace notes

def gn(name, dur=GRACE_LEN):
    """grace note"""
    global dur_stolen
    dur_stolen += dur
    return note.Note(name, quarterLength=dur)

def c(notes, dur=1, **kwargs):
    """chord"""
    global dur_stolen
    c = chord.Chord(notes, quarterLength=dur-dur_stolen, **kwargs)
    dur_stolen = 0
    return c

chords = stream.Part(id='chords')
chords.append(gn('c4'))
chords.append(c(['a4', 'c5', 'f5']))
```

But it doesn't look good (there are no actual grace notes, shortened chords are decomposed into tied parts) and it's not a very robust solution (working with a global variable, one has to append the chord following the "grace" note immediately to be safe).

**Comment by mscuthbert** [comment]
I'm going to try to write up a bit on grace notes in the User's Guide, and hopefully doing that will let me squash some bugs and see what's up.  Documenting is always the best way to see what works...

btw -- I'm 90% sure that grace notes and MIDI don't currently mix well.

**Comment by mscuthbert** [comment]
Documentation at:

http://web.mit.edu/music21/doc/usersGuide/usersGuide_27_graceNotes.html

Let me know if there's still a problem after that.
