### ISSUE TITLE
When midi parsing is performed in music21, instrument is changed from drum to piano.

### ISSUE THREAD

**Issue by midgetfx** [cuthbertLab/music21#1487]
**music21 version**

`5.5.0` 

**Problem summary**

I'm trying to compose a song through music21. However, I am having great difficulty generating drum sounds.

First, I imported a midi with drum instrument, re-write it as a midi, and created a wav with fluidsynth. 
But, a piano sound was heard, and I confirmed that the instrument was set to piano in music21.

Is there a way to input drum information when saving a midi in music21?

- midi file : https://commons.wikimedia.org/wiki/File:12-8_equals_4-4_drum_pattern.mid

**Steps to reproduce**

```
import music21 as m
mf = m.midi.MidiFile()
mf.open('/content/12-8_equals_4-4_drum_pattern.mid')
mf.read()
mf.close()
print(len(mf.tracks))
s = m.midi.translate.midiFileToStream(mf)
filename = s.write('mid')
!fluidsynth -ni FluidR3_GM.sf2 $filename -F $filename\.wav -r 32000 > /dev/null
print(filename + '.wav')
display(Audio(filename + '.wav'))
```

```
from music21 import converter,instrument # or import *
file = converter.parse('/content/12-8_equals_4-4_drum_pattern.mid')
components = []
for element in file.recurse():
    components.append(element)
components
[<music21.stream.Part 0x7f295c2d9090>,
 <music21.instrument.Piano Piano>,
 <music21.tempo.MetronomeMark Quarter=99.0>,
 <music21.key.Key of C major>,
 <music21.meter.TimeSignature 12/8>,
 <music21.stream.Voice 0x7f295c90c6d0>,
 <music21.note.Note F#>, ...]
```

**Expected vs. actual behavior**

- Drum sounds are heard when converting downloaded-midi with fluidsynth to wav

- Piano sounds are heard when parsing the midi in music21, saving a new midi file and creating the wav by fluidsynth

**More information**

I am working in Colab.

**Comment by mscuthbert** [comment]
Please upgrade to at least v7.3 (last Colab supported version) before filing a report -- there is nothing that can be done to fix v5.  music21 can be upgraded in a colab session via `%pip install --upgrade music21`.

If the problem persists in v7, please reopen the report.
