### ISSUE TITLE
PitchedInstrumentsPresentFeature 

### ISSUE THREAD

**Issue by supersational** [cuthbertLab/music21#150]
Hi, fantastic library! 

Currently trying to extract all features from a midi file:
```python
for f in file_list:
	print f
	s = converter.parse(f.strip())
	for f in features.jSymbolic.featureExtractors:
		print f.__name__
		fe = f(s)
		print getattr(fe, 'description', 'no description')
		print fe.extract().vector
```
currently fails at PitchedInstrumentsPresentFeature:
```
Traceback (most recent call last):
  File "C:\feature_extractors.py", line 21, in <module>
    print fe.extract().vector
  File "C:\Python27\lib\site-packages\music21\features\base.py", line 198, in extract
    self._process() # will set Feature object to _feature
  File "C:\Python27\lib\site-packages\music21\features\jSymbolic.py", line 2933, in _process
    self._feature.vector[i.midiProgram] = 1
TypeError: list indices must be integers, not NoneType
```

midi file here;
[009count.zip](https://github.com/cuthbertLab/music21/files/181381/009count.zip)

Is this expected behaviour? the midifile in question seems to have standard messages for setting instruments as far as I can tell (from mido analysis):
```
program_change channel=0 program=1 time=0
program_change channel=2 program=8 time=0
program_change channel=3 program=25 time=0
program_change channel=4 program=33 time=0
program_change channel=7 program=48 time=0
program_change channel=9 program=16 time=0
program_change channel=10 program=52 time=0
program_change channel=9 program=16 time=0.193661875
```

**Comment by alexandermorgan** [comment]
This doesn't address your question but it is definitely less than ideal to assign f to the elements in both of your nested loops.

**Comment by supersational** [comment]
Ah, agreed! Seems to be harmless in this instance at least.

**Comment by mscuthbert** [comment]
Not expected at all -- can you trim down the MIDI file and the code until as small as possible while giving the same error, so that the programming team can debug faster.  The first thing I'd see is if either something in channel 9 (the only one that has a time message later) or channel 10 (which isn't a pitched instrument) is causing the problem.  I'm going to guess that channels 0-7 all behave the same.

**Comment by supersational** [comment]
Hi, this should trigger it:
```python
import music21
f = "009count.mid"
s = music21.converter.parse(f)
e = music21.features.jSymbolic.PitchedInstrumentsPresentFeature
fe = e(s)
print fe.extract().vector
```

**Comment by mscuthbert** [comment]
Hi -- that's a minimal code, but it's a 90 measure, 7-track midi file -- can you find the track or tracks and then the measure or measures that causes the problem and make a new file just with that?  Thanks!

**Comment by supersational** [comment]
Sure, it's not my midifile but I'll have a go.. The bug only occurs on the first and third 'parts' (out of seven) from testing.
```python
import music21
f = "009count.mid"
s = music21.converter.parse(f)
e = music21.features.jSymbolic.PitchedInstrumentsPresentFeature
for idx, i in enumerate(s):
	print idx, i
	try:
		fe = e(i)
		print fe.extract().vector
	except:
		print "error"
		continue
```

Any examples of how to only parse part of a file?

**Comment by mscuthbert** [comment]
Hi Sven -- thanks for being such a good sport.  It's not your MIDI file, but it's more yours than mine.  :-)  

Parse the whole file, but then run each of "for p in s.parts" through the extraction vector and that should help you figure out if one part is causing the problem.  And then you can run each measure through separately later.

Thanks!

**Comment by supersational** [comment]
Sure, well the above code finds error in parts 1 and 3, and this code as far as I can tell processes each measure (without any errors):

```python
import music21
f = "009count.mid"
s = music21.converter.parse(f)
e = music21.features.jSymbolic.PitchedInstrumentsPresentFeature
for idx_j, j in enumerate(s.parts):
	print idx_j, j
	for idx_i, i in enumerate(j.measures(0, None)):
		print idx_i, i
		try:
			fe = e(i)
			print fe.extract().vector
		except:
			print "error"
			continue
```
From there on I'm a bit lost, but changing the line 2932 in jSymbolic.py from 
```python 
for p in s.parts:
                # always one instrument
                x = p.getElementsByClass('Instrument')
                if x:
                    i = x[0]
                    if p.recurse().notes:
into
if p.recurse().notes and i is not None:
```
seems to fix the error, but I can't figure out what this class method is trying to do or where the data is supposed to be defined, is this fix ok?

**Comment by supersational** [comment]
I guess a general question: are we supposed to expect that a midi file could fail feature extraction if it's malformed in some way? or is the feature extractor supposed to be robust enough to handle any file?

**Comment by mscuthbert** [comment]
Sven -- while it'd be great if any feature extractor could work on any file, it's not a requirement but, more importantly, not tested enough to ensure that [hence why we're getting that].  However, if you use a DataSet instance (as described in the Cuthbert, Ariza, Friedland paper) then it will continue extracting around errors (by default; there's a way to turn that off).

Thanks you've given me a ton to work with -- it looks like the error therefore comes from changing from one instrument to another within a part.

**Comment by supersational** [comment]
Ah cheers, hadn't noticed that part of the API! (there's a typo 'ClassLable' in the docs at DataSet.addData FYI)

Very helpful, thanks. If I find more errors running the feature extractor would you prefer I post them here or start a new issue?
(just found `'I20': 'the object (<music21.tempo.MetronomeMark allegrissimo Quarter=140.0>, id()=165815440) is already found in this Stream (<music21.stream.Part object at 0x07EB29B0>, id()=132852144)'`)

**Comment by mscuthbert** [comment]
Except for the (fixed!) "ClassLable" typo (which actually helped debug a major problem in the documentation system), it'd be best if you created a new issue for each error that seems like it might be a separate issue.  It helps people to find the bug (if it's not yet fixed) and makes it a meaningful sized thing to fix.

**Comment by mscuthbert** [comment]
We can move everything that is still there to a new issue.  Thanks!
