### ISSUE TITLE
`ChordSymbol.figure` setter is not idempotent

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1500]
**music21 version**
dev

**Problem summary**
Setting `figure` on a `ChordSymbol` to a same or slightly varying value can raise `ChordSymbolModificationException` when a "subtract" modification refers to a pitch that has already been removed from `.pitches` the first time the figure was set.

**Steps to reproduce**

```python
>>> cs = harmony.ChordSymbol('CM7omit5')
>>> cs.figure = cs.figure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../music21/music21/harmony.py", line 337, in figure
    self._updatePitches()
  File "/Users/.../music21/music21/harmony.py", line 2123, in _updatePitches
    pitches = list(self._adjustPitchesForChordStepModifications(pitches))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../music21/music21/harmony.py", line 1795, in _adjustPitchesForChordStepModifications
    typeSubtract(chordStepModification)
  File "/Users/.../music21/music21/harmony.py", line 1759, in typeSubtract
    raise ChordStepModificationException(
music21.harmony.ChordStepModificationException: Degree not in specified chord: 5
```

**Expected vs. actual behavior**
No exception

**More information**
A more realistic use case:
```python
>>> cs = harmony.ChordSymbol('CM7omit5')
>>> cs.addChordStepModification(harmony.ChordStepModification(modType='add', degree=4))
>>> cs.findFigure()  # new
'Cmaj7 subtract 5 add 4'
>>> cs.figure  # old
'CM7omit5'
>>> cs.figure = cs.findFigure()  # store new figure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../music21/music21/harmony.py", line 337, in figure
    self._updatePitches()
  File "/Users/.../music21/music21/harmony.py", line 2123, in _updatePitches
    pitches = list(self._adjustPitchesForChordStepModifications(pitches))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../music21/music21/harmony.py", line 1795, in _adjustPitchesForChordStepModifications
    typeSubtract(chordStepModification)
  File "/Users/.../music21/music21/harmony.py", line 1759, in typeSubtract
    raise ChordStepModificationException(
music21.harmony.ChordStepModificationException: Degree not in specified chord: 5
```

**Comment by mscuthbert** [comment]
yuk.  I don't like anything that's not idempotent.  At the very least there should be a `if newFigure == self.figure: return`  :-) 

I think that something in harmony.Harmony needs to be changed significantly to make .figure setting (or a lot of post-hoc changing) possible.  I want to thoroughly type the Harmony and RomanNumeral objects first though -- there were places where changes to make setting accidental attributes, Chord attributes etc. after creation ended up revealing major problems in the type system, so I'd be good to get everything working and typed first, and hopefully get rid of a lot of "X | None" types with a Sentinel X object instead to simplify the typing.

But maybe setting .figure for a ChordSymbol or RN is as simple as creating a new temporary ChordSymbol, etc. and then moving over its pitches and figure and ... a bunch of other things, and then discarding the temporary one?  What would someone expect to be preserved from the original ChordSymbol after setting figure?  duration, sites/offset, editorial, groups, id... okay, so maybe more things to keep than to remove, but most of the attributes defined in Harmony/ChordSymbol etc. itself would be removed.

**Comment by jacobtylerwalls** [comment]
> What would someone expect to be preserved from the original ChordSymbol after setting figure?

I was pleasantly surprised that things Just Work™ in the case above of adding a chord step modification. The pitches are already correct after the modification. There's already a good algorithm to find the new figure. I just need to store that new figure somewhere once it's calculated. I could put it in editorial, I suppose, but that's not the first thing you'd think of. Something like that.

The other use case I had was an algorithm that pops off certain chord extensions (e.g. take an arbitrary chord symbol, and pop off sevenths, ninths, elevenths, thirteenths, etc. and recalculate the figure so that C9 becomes C7). Looking again, I see that I can just set `.figure = None` before calling `findFigure()`.

Still perhaps worth catching this deeper failure in `_adjustPitchesForChordStepModifications`, so I'll open a quick PR.

**Comment by jacobtylerwalls** [comment]
The culprit is not what I thought it was. Looks like this workflow gives duplicative ChordStepModifications. So I can roll it up with #1482 and add a guard against appending an equivalent ChordStepModification.
