### ISSUE TITLE
Support for rendering (a.k.a. writing MusicXML) trills/mordents/turns with accidentals

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1507]
**Motivation**
music21 supports half-step and whole-step trills, for example, but if the half or whole step up needs an accidental (due to key signature, or previous accidentals in the measure), they are missing.  

**Proposed implementation**
This requires new support in m21ToXml.py to add an `<accidental-mark>` as follows:
```
<ornaments>
    <trill-mark placement="above" />
    <accidental-mark placement="above">natural</accidental-mark>
</ornaments>
```

I believe this will also require support in makeAccidentals, and the addition of an Accidental field (or two) in Trill/Mordent/Turn objects that makeAccidentals will configure (and pay attention to), and parsers can also configure directly from their own analysis.  I would, for example, modify xmlToM21.py to support _reading_ such `<accidental-mark>` elements, which would end up setting (e.g.) `turn.upperAccid.displayStatus` and `turn.lowerAccid.displayStatus` appropriately.

I am looking for review of the above proposal, before I start blazing away.  I'm quite sure I'm not thinking of everything.

I _have_ started experimenting to see which MusicXML renderers support ornaments with an `<accidental-mark>`, and Finale is pretty good (except for double sharps and double flats, for some reason, but those will be fairly rare).  Musescore ignores `<accidental-mark>` entirely, but maybe I can help them fix that.  Dorico does OK, but is buggier than Finale.

If you want to play with other renderers (or see what I think m21ToXml.py should be generating), see the attached MusicXML file (zipped).  I have annotated the trills in the score with "half" and "whole" text fields so you can figure out what the accidentals should be as you look at any particular rendering of the score.
[trillaccid.musicxml.zip](https://github.com/cuthbertLab/music21/files/10328155/trillaccid.musicxml.zip)

**Intent**

[x] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by mscuthbert** [comment]
Thank you.  I never thought about this, but of course it's another thing more complex than it seems.

Did not think that makeAccidentals would someday be looking at expressions!

**Comment by mscuthbert** [comment]
(p.s. thanks for the huge pushes on other PRs last week -- I've seen them now and they're on my radar)

**Comment by gregchapman-dev** [comment]
Oh, another missing bit that should be implemented at the same time: Turns currently don't have two intervals (upper and lower), just one interval that is used for both (I think).  Also, we should decide if Turn.lowerInterval should default to GenericInterval(2) or maybe it should always be a semitone, even if that's not in the key; I've seen both descriptions in various tutorials about how to play turns on the piano.

**Comment by gregchapman-dev** [comment]
@mscuthbert I am starting to figure this out now.  First issue: If I add an accidental to {Half,Whole}Step{Mordent,InvertedMordent,Trill} then they will each have two (possibly conflicting) definitions of what the additional note is: the class itself, and the accidental.  So the question is, do we remove the HalfStep/WholeStep variants entirely?  Or do we allow them to exist, but ignore their class (only obeying the accidental)?  Or is there some other option I haven't thought of?

**Comment by gregchapman-dev** [comment]
Oh damn.  There are actually three definitions of the additional note: class name, ornament.size, and ornament.accid.  I might need to get rid of ornament.size as well?  There are two sorts of clients that I can imagine:  parsers/writers (my world), which really should be dealing strictly in accidentals, and music analysis software (e.g. realize()), which probably wants to deal with intervals.  Maybe I should allow you to set ornament.accidental, and only get ornament.interval (which would require keysig and original note).  realize() already takes the original note as a parameter, so it would need to be enhanced to also take the key signature, so it can figure out the interval.

**Comment by gregchapman-dev** [comment]
Proposal (note that I am using Mordent as an example, but this applies to Trill and Turn, too):
    0. `GeneralMordent.__init__ ` takes a new (keyword only) parameter `accid: pitch.Accidental | None = None` (Turn will get `upperAccid` and `lowerAccid`, of course).  `GeneralMordent.accid` is a read-only property.  In other words, the accidental cannot be changed after `__init__()`.
    1. `GeneralMordent.size` becomes a method that takes `srcObj` (the original note), and also takes into account any accidental that might have been set. Note that Turn will get `upperSize(srcObj)` and `lowerSize(srcObj)` instead of `size(srcObj)`.
    2. `HalfStepMordent`, `WholeStepMordent`, `HalfStepInvertedMordent`, and `WholeStepInvertedMordent` will remain as "old-style" objects that cannot have accidentals. If you pass `accid` to `__init__`, it will be ignored (like any other unsupported keyword parameter).  `size` will still be changed (same as above) to a method that takes `srcObj` (the original note), but it takes into account the class name (HalfStep/WholeStep) instead of the accidental, since there is no accidental.

**Comment by gregchapman-dev** [comment]
Hmmm... ornamentRecognizer.py needs a bit of going over in this new world.

**Comment by gregchapman-dev** [comment]
One last point: for the sake of ornamentRecognizer.py, I need to also allow you to set `.size`, but only if you haven't created the ornament with `accid` (and _never_ for the WholeStep/HalfStep ornaments).  Note that this is not the case for `Turn`, since there I am _removing_ `size`, and replacing it with `getUpperSize(srcObj)` and `getLowerSize(srcObj)`.  Fortunately, ornamentRecognizer.py does not get/set `turn.size`.

**Comment by gregchapman-dev** [comment]
PR #1545 is where this is all being implemented.
