### ISSUE TITLE
ERROR: Package 'music21' requires a different Python: 3.8.10 not in '>=3.10'

### ISSUE THREAD

**Issue by asudakov** [cuthbertLab/music21#1519]
**music21 version**
Latest github

**Problem summary**
ERROR: Package 'music21' requires a different Python: 3.8.10 not in '>=3.10'

**Comment by jacobtylerwalls** [comment]
The development branch only supports Python >=3.10 See https://groups.google.com/g/music21list/c/W2AFRValaJE/m/lE8k5JLSBAAJ.
