### ISSUE TITLE
slightly unexpected behavior in writing midi from score

### ISSUE THREAD

**Issue by pepperpepperpepper** [cuthbertLab/music21#152]
from music21.note import Note  
from music21.stream import Score, Part  
from music21.tempo import MetronomeMark                                          
# if I create a score with

s = Score()                                                                      
# and then insert a tempo marker with...

s.insert(MetronomeMark(referent=1, number=85))                                   
# and then append to the score with...

part1 = Part()  
part1.append(Note())  
s.append(part1)                                                                  

part2 = Part()  
part2.append(Note())  
s.append(part2)                                                                  
# and then finally look at the midi file...

s.write('midi', '/tmp/mytest.midi')                                              

"""  
looking at the midifile...  
0, 0, Header, 1, 2, 1024  
1, 0, Start_track  
1, 0, Title_t, ""  
1, 0, Pitch_bend_c, 0, 8192  
1, 0, Tempo, 705882  
1, 0, Note_on_c, 0, 60, 90  
1, 1024, Note_off_c, 0, 60, 0  
1, 1024, End_track  
2, 0, Start_track  
2, 0, Title_t, ""  
2, 0, Pitch_bend_c, 0, 8192  
2, 0, Note_on_c, 0, 60, 90  
2, 1024, Note_off_c, 0, 60, 0  
2, 1024, End_track  
0, 0, End_of_file                                                                

Above the tempo event is attached to track 1,  
when it was originally added to the Score instance,  
not a Part instance. I suppose this is totally cool,  
but is somewhat inconsistent with what I would  
expect if score is supposed to directly relate  
to the multitrack midifile, and track is supposed to directly  
relate to a track on the midifile. Abjad/Lilypond work a bit  
differently, with a separate track in the beginning of the file  
without note events to hold things like an initial global tempo.  
"""

**Comment by rmattes** [comment]
Sorry to drop in so late: this is a result of the requirement in the multitrack midifile standard: tempo related information must reside in the first track. Most applications writing multitrack midi file will create a separate track (a conductor track) that _only_ holds tempo and related information.
Many applications reading multitrack midi files will actually expect timing/tempo information in such a sepatate track. Note also that SMF doesn't even have a data structure representing a _score_.

**Comment by mscuthbert** [comment]
Aha! Got it. When I (or someone? :-) ) takes on rewriting MIDI translate (best as classes parallel to how MusicXML translate takes place) we should rewrite to have a conductor track. Thanks!
