### ISSUE TITLE
About the tempo setting

### ISSUE THREAD

**Issue by shansongliu** [cuthbertLab/music21#1523]
**music21 version**

`9.8.7`   

**Problem summary**

Is there a way to change the tempo of an existing stream? Suppose I have a stream with tempo set as 60, now I want to change the tempo to 120. How can I do this?

**Comment by jacobtylerwalls** [comment]
Hi, Github is for bug reports, but helpful folks answer questions on the mailing list. That said, you might try searching for MetronomeMark objects in your stream and manipulating the number.

In v7+ you can search for nested elements with bracket syntax like this:

```python
>>> s = corpus.parse('joplin')
>>> len(s["MetronomeMark"])
4
>>> for mm in s["MetronomeMark"]:
...   mm.number = 120
... 
>>> s.show()
```
