### ISSUE TITLE
Error when running stream.show() using a Docker container with Visual Studio. No MuseScore found

### ISSUE THREAD

**Issue by Dazzid** [cuthbertLab/music21#1528]
**music21 version**

` 8.1.0`   

**Problem summary**

I'm running python 3.10.8 in a container using docker, a remote connection to run GPUs. 

I can not run stream.show() it gives the following error:
`SubConverterException: Cannot find a path to the 'mscore' file at /usr/bin/mscore3 -- download MuseScore`

I installed MuseScore following two options, first by 
`sudo apt-get install musescore`
and then
```
import music21 as m21
m21.environment.set("musicxmlPath", "/usr/bin/musescore")
```

also installed the AppImage and run the installer 
`./MuseScore-4.0.1.230121751-x86_64.AppImage install`
**Steps to reproduce**

```
myChords = ['Dm', 'G7', 'F#7 add #11', 'Fm7', 'C#m add 6']
stream = m21.stream.Score(id='mainScore')
formated_cords = []
for chords in myChords:
    notesPerChord = m21.harmony.ChordSymbol(chords)
    #notesPerChord.writeAsChord = True
    #print(" | ", end=' ')
    notes_in_chord = []
    for notes in notesPerChord.pitches:
        notes_in_chord.append(notes.name)
    #print(notes_in_chord)
    formated_cords.append(notes_in_chord)

loc = 0
for chords in formated_cords:  
    print(chords)  
    myChords = m21.chord.Chord(chords)
    myChords = myChords.closedPosition(forceOctave=4, inPlace=False)
    myChords.duration = m21.duration.Duration(4)
    myBass = m21.note.Note(chords[0])
    myBass.duration = m21.duration.Duration(4)
    myBass.octave = 3
    myChords.add(myBass)
    myChords.root(myChords.bass()) #this line avoids sharp chords to be read as two chords
    stream.insertIntoNoteOrChord(loc, myChords)
    loc += 4

stream.show()
```

**Expected vs. actual behavior**

**More information**

**Comment by mscuthbert** [comment]
Hello. Docker and remote GPU is not a supported system for the github issues. Either post to the public mailing list or consult the FAQ for paid support. Thanks!
