### ISSUE TITLE
is this the simplest use case? for rendering sheet music for custom music?

### ISSUE THREAD

**Issue by basicpitch** [cuthbertLab/music21#1529]
**music21 version**

`8.1.0`   

**Problem summary**

Hi. I am puzzled by how to get started with music21, but a friend of mine who writes operas mentioned the software a few years ago. Everything I try to do seems not to work.

```
filename = "mz_311_1_format0.mid"
from music21 import converter, instrument

s = converter.parse(filename)
s.show(fmt=None)
with open("write.png", "w") as f:
     s.write(fmt=None, fp="write.png")
```

For instance, in the above code, `s.show()` does not generate any sheet music rendering. IT is also unclear what list of `fmt` variables are acceptable. Using `fmt=text` does generate the parsing of the Midi file correctly. The documentation for `s.write()` says that `fp=` should be a file pointer, but that throws an internal error that a downstream variable `path` should be a string, not a file pointer. When I change `fp` to a path, a `write.png` file is generated but cannot be opened by any of my image editors, so the file is most likely corrupted. :( All I want to do is use the software to build simple original scores of guitar pieces I have written in tabs in notebooks over the years and generate sheet music. All I need is to add notes and their durations; none of the challenging production player notes.

I am using `music21 8.1.0` on a MacBook 2021 running Ventura.

**Comment by mscuthbert** [comment]
Hello -- please use the Google music21list mailing list for help on basic music21 operations.  The issues are for bugs only.  Thanks!
