### ISSUE TITLE
Cannot Write Percussion to Midi

### ISSUE THREAD

**Issue by m2-weisskopf** [cuthbertLab/music21#1537]
I'm new to music 21 am trying to batch-quantise a corpus of midi drums. I can load in a midi file fine and quantise it, but I can't seem to write it using .write. The following code just outputs a blank midi file. 

```
drum_stream = converter.parse('groove/drummer1/session1/1_funk_80_beat_4-4.mid', quantizePost=False)
drum_stream.write(fmt='midi', fp='test_drums.mid') 
```

The midi file plays fine before being loaded into music21, and it writes non-percussion tracks fine. Can someone advise me as to why this might be happening? Might it be something to do with how music21 handles unpitched percussion? 

Many thanks

**Comment by jacobtylerwalls** [comment]
What version of music21 are you running? Exporting percussion to midi was added in v8.1.0.

**Comment by m2-weisskopf** [comment]
I think you've found the problem - I'm running version 7.3.3. This was the default that installed using `pip install music21`. When a try and install 8.1.0 using pip install `music21==8.1.0`, I get the following:

`ERROR: Could not find a version that satisfies the requirement music21==8.1.0 (from versions: 1.9.3, 2.0.0, 2.0.5, 2.0.10, 2.0.11, 2.1.0, 2.1.2, 2.2.1, 3.1.0, 4.1.0, 5.0.3a1, 5.0.5a2, 5.0.6b1, 5.1.0, 5.3.0, 5.5.0, 5.7.0, 5.7.1, 5.7.2, 6.1.0, 6.3.0, 6.5.0, 6.7.0, 6.7.1, 7.1.0, 7.3.0, 7.3.1, 7.3.3)`

Any ideas why I can't install 8.1.0? I'm using OSX Catalina with Python 3.7.3.

**Comment by m2-weisskopf** [comment]
I've just learned that 8.1.0 requires Python 3.8 or higher. By upgrading to Python 3.11, I can install 8.1.0, and have functionality to export percussion to midi. Thanks for your help!
