### ISSUE TITLE
Inserting notes in 7/32 measure

### ISSUE THREAD

**Issue by juancopi81** [cuthbertLab/music21#1538]
**music21 version**

`8.1.0 `   

**Problem summary**
I am trying to create a measure with 7/32 time signature. I added a 1/32, a 1/16, and a 1/8 notes, that should fill the measure. However, some strange rests are added. Maybe I am doing something wrong, but I tried different things and nothing seems to work.

**Steps to reproduce**

```Python

from music21 import *

# Create a measure with 7/32 time signature
measure = stream.Measure(number=1)
time_signature = meter.TimeSignature('7/32')
measure.insert(0, time_signature)

# Create a voice and add it to the measure
voice = stream.Voice()
voice.insert(0,time_signature)

# Note pitches and durations in quarterLength
note_pitches = ['B4', 'C5', 'A4']
note_durations = [4/32, 4/16, 4/8]  # Fusa (1/32), semicorchea (1/16), corchea (1/8)

# Create notes with specified durations and pitches, and add them to the voice
for pitch, duration in zip(note_pitches, note_durations):
    note_instance = note.Note(pitch, quarterLength=duration)
    voice.append(note_instance)

# Add voice to the measure
measure.insert(0, voice)
measure.write("midi", "test.mid")
```
This is what I get:

![image](https://user-images.githubusercontent.com/4313860/226455153-d00c0900-0563-4f3d-9b72-ed64bc7ab25b.png)

**Expected vs. actual behavior**
I am trying to create this measure:
![image](https://user-images.githubusercontent.com/4313860/226455259-712338c5-2763-4f35-9215-519db8d75596.png)

I am unsure if the problem appears when I create the MIDI file.

**Comment by jacobtylerwalls** [comment]
This is an issue with MuseScore's display of MIDI files. Finale and GarageBand open your example just fine! Feel free to discuss on the MuseScore forums.

**Comment by juancopi81** [comment]
Hey @jacobtylerwalls 

Thank you very much for your answer. I am unsure but something seems strange on my end. Even without using MuseScore. If I run this code:

```python
from music21 import *

# Create a measure with 7/32 time signature
measure = stream.Measure(number=1)
time_signature = meter.TimeSignature('7/32')
measure.insert(0, time_signature)

# Create a voice and add it to the measure
voice = stream.Voice()
voice.insert(0,time_signature)

# Note pitches and durations in quarterLength
note_pitches = ['B4', 'C5', 'A4']
note_durations = [4/32, 4/16, 4/8]  

# Create notes with specified durations and pitches, and add them to the voice
for pitch, duration in zip(note_pitches, note_durations):
    note_instance = note.Note(pitch, quarterLength=duration)
    voice.append(note_instance)

# Add voice to the measure
measure.insert(0, voice)
measure.show('text')
```
It shows the expected output:

```
{0.0} <music21.meter.TimeSignature 7/32>
{0.0} <music21.stream.Voice 0x7faf89b44580>
    {0.0} <music21.meter.TimeSignature 7/32>
    {0.0} <music21.note.Note B>
    {0.125} <music21.note.Note C>
    {0.375} <music21.note.Note A>
```

But right after that, when doing:

```python
measure.write("mid", "test.mid")
song = converter.parse("test.mid")
song.show("text")
```
The output changes:

```
{0.0} <music21.metadata.Metadata object at 0x7faf8aaac9a0>
{0.0} <music21.stream.Part 0x7faf8aaac7c0>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.instrument.Instrument ''>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.tempo.MetronomeMark animato Quarter=120.0>
        {0.0} <music21.meter.TimeSignature 7/32>
        {0.0} <music21.chord.Chord B4 C5>
        {0.3333} <music21.note.Note A>
        {0.8333} <music21.note.Rest 1/24ql>
        {0.875} <music21.bar.Barline type=final>
```

Now the offset for B4 and C5 is {0.0}.

I created a [simple Colab](https://colab.research.google.com/drive/1jV5u3BjTttBBUVjTK-q2A_Utjzik9ylA?usp=sharing) with this code.

**Comment by jacobtylerwalls** [comment]
Good question @juancopi81 -- when you parse a MIDI back into music21, you need to choose a quantization level that the rhythms will be rounded to. By default, music21 picks triplet-eighths (0.333) and eighths (0.25). 0.125 is too small, so the first two notes get collapsed into a chord.

You can turn this off with `quantizePost=False`, or just use different `quarterLengthDivisors`:

```python
song = converter.parse("test.mid", quarterLengthDivisors=[8])
```
