### ISSUE TITLE
freezeThaw docs typo

### ISSUE THREAD

**Issue by alexandermorgan** [cuthbertLab/music21#154]
In the freezeThaw [documentation](http://web.mit.edu/music21/doc/moduleReference/moduleFreezeThaw.html#music21.freezeThaw.JSONFreezeThawBase):

```
>>> sf2 = freezeThaw.StreamFreezer(c) # do not reuse StreamFreezers
>>> data2 = sf2.writeStr(fmt='jsonpickle')
>>> st2 = freezeThaw.StreamThawer()
>>> st2.openStr(data2)
>>> s3 = st.stream
>>> len(s3.parts[0].measure(7).notes) == 6
True
```

it seems the s3 line should read:

`>>> s3 = st2.stream`

**Comment by mscuthbert** [comment]
but does it work if we change it?  Let me check...

**Comment by mscuthbert** [comment]
Seems to.  Thanks!  Committed and will rebuild docs too.
