### ISSUE TITLE
Error: fail to write the file

### ISSUE THREAD

**Issue by Justinfungi** [cuthbertLab/music21#1546]
**music21 version**
8.1.0

**Problem summary**

> ['C3', 'C3', '6', 'A3', '6', 'C3', 'C3', 'F2', 'C4', 'A2']
> 6
> 6
> 6
> 6
> GNU LilyPond 2.24.1 (running Guile 2.2)
> Changing working directory to: `static/images/Jus'
> Processing `static/images/Jus/lily'
> Parsing...
> /home/ImMusic/public_html/myfourthapp/static/images/Jus/lily:37:5: error: unknown escaped string: `\RemoveEmptyStaffContext'
>     
>     \RemoveEmptyStaffContext
> /home/ImMusic/public_html/myfourthapp/static/images/Jus/lily:38:5: error: syntax error, unexpected \override, expecting '='
>     
>     \override VerticalAxisGroup #'remove-first = ##t
> /home/ImMusic/public_html/myfourthapp/static/images/Jus/lily:38:33: warning: deprecated: missing `.' in property path VerticalAxisGroup.remove-first
>     \override VerticalAxisGroup 
>                                 #'remove-first = ##t
> /home/ImMusic/public_html/myfourthapp/static/images/Jus/lily:40:2: error: syntax error, unexpected '}'
>  
>  }
> /home/ImMusic/public_html/myfourthapp/static/images/Jus/lily:40:3: error: Unfinished main input
>  }
>   
> Interpreting music...
> Preprocessing graphical objects...
> Calculating line breaks... 
> Drawing systems... 
> Converting to PNG...
> fatal error: failed files: "static/images/Jus/lily"

**Steps to reproduce**

```
Paste minimal code example here. Most issues can be reproduced with just a few elements.
Attach external files only after attempting to reproduce using a simple stream.

myStream1 = converter.parse('tinynotation: 4/4 c4 e4 g2')
myStream2 = stream.Stream()
myStream2.write("lily.png", "./res/lily")
```

**More information**

OS: CentOS

**Comment by jacobtylerwalls** [comment]
Hi, can you provide enough instructions to reproduce the issue? The provided example (writing an empty stream) succeeds for me.

**Comment by mscuthbert** [comment]
Closing -- centOS is not a free supported OS.  Please choose paid support for this issue.
