### ISSUE TITLE
When lilypond/mscore are not found the traceback error message does not specify the correct path to set

### ISSUE THREAD

**Issue by chr15m** [cuthbertLab/music21#156]
This the last line of the traceback:

`SubConverterException: Cannot find a valid application path for format lilypond. Specify this in your Environment by calling environment.set(None, 'pathToApplication')`

Is it supposed to say e.g. `lilypondPath` instead of `None` above?

A similar situation arises when music21 cannot find other binaries such as mscore.

My operating system is a GNU/Linux based distribution. Thank you for your time.

**Comment by mscuthbert** [comment]
The latest version now has a more helpful error message.  You were trying to convert to .svg, so the .music21rc item you'll need to set there is "vectorPath" which is the path to an SVG reader.

Beyond this, unfortunately I can't offer any support for GNU/Linux/UNIX systems; sorry! they're just too much to debug.

**Comment by chr15m** [comment]
Hi @mscuthbert, thanks for taking the time to review the issue.

> The latest version now has a more helpful error message.

Great to hear that is fixed, thank you!

> the .music21rc item you'll need to set there is "vectorPath" which is the path to an SVG reader.

Thanks. Which "SVG reader" binaries are supported - what are the possible values for that item?

Is there somewhere in the documentation I can find a list of the possible values/binaries that can go into `.music21rc` and their suggested/possible values?

> Beyond this, unfortunately I can't offer any support for GNU/Linux/UNIX systems

I think it would make sense to say in the music21 documentation that GNU/Linux is not as well supported as the other platforms. Users can use that information to inform the decision about which software to use.

For your reference - it does not make sense to include "UNIX" in the list above as OSX is a UNIX system.

Thanks for your time.

**Comment by chr15m** [comment]
> I think it would make sense to say in the music21 documentation that GNU/Linux is not as well supported as the other platforms. Users can use that information to inform the decision about which software to use.

I'm sorry, I noticed that your website says "by choosing to use Unix-like systems you should be an advanced user" so I think that addresses my point already. Thanks.

**Comment by mscuthbert** [comment]
No worries -- I really really really wish I could support GNU/Linux also, because it's such a great platform, but there are just too many flavors of it, and this type of support is mostly just me.  If someone wanted to make lots of well-tested pull requests to improve our GNU/Linux /FreeBSD etc support, I'd welcome it!
