### ISSUE TITLE
Let `makeTies()` iterate over parts

### ISSUE THREAD

**Issue by TimFelixBeyer** [cuthbertLab/music21#1561]
**music21 version**
`master`

**Problem summary**
makeTies throws `StreamException: cannot process a stream without measures` on score with measures.

**Steps to reproduce**

```python3
from music21 import stream, note, meter, tie

s = stream.Score(id='mainScore')
p0 = stream.Part(id='part0')

m01 = stream.Measure(number=1)
m01.append(meter.TimeSignature('4/4'))
d1 = note.Note('D', type="half", dots=1)
c1 = note.Note('C', type="quarter")
c1.tie = tie.Tie("start")
m01.append([d1, c1])
m02 = stream.Measure(number=2)
c2 = note.Note('C', type="quarter")
c2.tie = tie.Tie("stop")
c3 = note.Note("D", type="half")
m02.append([c2, c3])
p0.append([m01, m02])

s.insert(0, p0)
s.show("text")  # just to verify that there are measures in the score 
s = s.stripTies()
# s = s.makeMeasures()  # does not help
s = s.makeTies()
```

**More information**
Related to #1557

***
**3**
Your example is a score that has had `stripTies()` run on it, yielding an overfilled first measure and an underfilled second measure. I think I would expect that making rests on that would fill the second measure.

If you want to display the stripped ties score (are you sure you want to display that?) then you could makeTies() on it first, which restores the output I think you're expecting.

***

_Originally posted by @jacobtylerwalls in https://github.com/cuthbertLab/music21/issues/1557#issuecomment-1538586419_

**Comment by mscuthbert** [comment]
I've never really worked with stripTies() except in the context of a flatten()'d stream, so I'm not surprised this is a problem.

**Comment by TimFelixBeyer** [comment]
Just found out that it also fails without stripTies():
```python3
from music21 import stream, note, meter, tie

s = stream.Score(id='mainScore')
p0 = stream.Part(id='part0')

m01 = stream.Measure(number=1)
m01.append(meter.TimeSignature('4/4'))
d1 = note.Note('D', type="half", dots=1)
c1 = note.Note('C', type="quarter")
c1.tie = tie.Tie("start")
m01.append([d1, c1])
m02 = stream.Measure(number=2)
c2 = note.Note('C', type="quarter")
c2.tie = tie.Tie("stop")
c3 = note.Note("D", type="half")
m02.append([c2, c3])
p0.append([m01, m02])

s.insert(0, p0)
s.show("text")  # just to verify that there are measures in the score 
# s = s.makeMeasures()  # does not help
s = s.makeTies()
```
This also fails when called on the example score from here (`makeMeasures` does not help there either): https://web.mit.edu/music21/doc/usersGuide/usersGuide_06_stream2.html

**Comment by jacobtylerwalls** [comment]
Here, "with" means "directly containing", not "recursively containing". Your score doesn't directly contain measures, the parts do.

Try:
```
>>> for p in s.parts:
...   p.makeTies(inPlace=True)
...
```

Leaving the issue open for now to discuss the possibility of adding the trivially easy enhancement to iterate over parts of a score automatically.

**Comment by TimFelixBeyer** [comment]
I think that `makeTies` should be the conceptual opposite to `stripTies`, which itself already iterates over parts and voices if required https://github.com/cuthbertLab/music21/blob/42534a3977422457c4618268ca08a82ecab4ce52/music21/stream/base.py#L7257-L7278

LMK if that's something I should prepare a PR for or whether further discussion is required!

**Comment by jacobtylerwalls** [comment]
I'd welcome such a PR, it brings that method into alignment with other related stream methods without significantly increasing the API footprint. Many thanks!

**Comment by mscuthbert** [comment]
I'm okay with having it in, but I think it is an extremely complex undertaking for an early PR to the project.  Having makeTies iterate over parts (and for Opus objects, also Scores) is a more managable start.

**Comment by jacobtylerwalls** [comment]
> Having makeTies iterate over parts (and for Opus objects, also Scores) is a more managable start.

That's all I was referring to. @TimFelixBeyer were you referring to something else?
