### ISSUE TITLE
Guard import of `requests` or make it a minimum dependency

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1562]
**music21 version**
dev

**Problem summary**
A minimal install of `requirements_minimum.txt` should allow importing music21, so we should either guard the import of `requests` in converter.py, or we should make it a minimally-required dependency.

**Steps to reproduce**

```
pip install -r music21/requirements_minimum.txt
python -c "import music21"
```

**Expected vs. actual behavior**
Import succeeds.

Actual:
```python
ModuleNotFoundError: No module named 'requests'
```

**Comment by mscuthbert** [comment]
Thanks Jacob -- you're absolutely right.  Requests is pure-python and under 200k and loading from URLs is deeply integrated to the project, so I think it should be in the minimum requirements.

The module that is in requirements_minimum that shouldn't be there is joblib.  It's used in rarely used functions and joblib is pretty big, so I'll make a separate request to remove it from minimum.
