### ISSUE TITLE
By default music21 does not find lilypond or mscore binaries on GNU/Linux when they are on the user's path

### ISSUE THREAD

**Issue by chr15m** [cuthbertLab/music21#157]
On my GNU/Linux system the binaries mscore and lilypond are on my path:

```
$ which lilypond
/usr/bin/lilypond
$ lilypond --version
GNU LilyPond 2.16.2

$ which mscore
/usr/bin/mscore
$ which musescore 
/usr/bin/musescore
$ mscore --version
MuseScore: Music Score Editor; Version 1.3; Build 5702
```

When invoking e.g. `mynotes.show("lily.png")` in jupyter/ipython notebook (after doing `%load_ext music21.ipython21`) I get a traceback saying the binary cannot be found. If I set the location in the user settings I get the same traceback.

Thanks for your time and work on this software.

**Comment by chr15m** [comment]
Here is the full traceback, which occurs regardless of whether I have specified the lilypond path or not in the settings:

```
---------------------------------------------------------------------------
SubConverterException                     Traceback (most recent call last)
<ipython-input-4-bbea914fb30f> in <module>()
----> 1 melody.show(u'lily.svg')

/home/chrism/Documents/Notebooks/virtualenv/local/lib/python2.7/site-packages/music21/base.pyc in show(self, fmt, app, **keywords)
   2374                                  app=app,
   2375                                  subformats=subformats,
-> 2376                                  **keywords)
   2377 
   2378     #--------------------------------------------------------------------------

/home/chrism/Documents/Notebooks/virtualenv/local/lib/python2.7/site-packages/music21/converter/subConverters.pyc in show(self, obj, fmt, app, subformats, **keywords)
    347         if app is None:
    348             app = environLocal.formatToApp(outFormat)
--> 349         self.launch(returnedFilePath, app=app)
    350 
    351 

/home/chrism/Documents/Notebooks/virtualenv/local/lib/python2.7/site-packages/music21/converter/subConverters.pyc in launch(self, filePath, fmt, options, app, key)
    145                     "Specify this in your Environment by calling "
    146                     "environment.set({!r}, 'pathToApplication')".format(
--> 147                         self.registerFormats[0], self.launchKey))
    148         elif platform == 'win':  # note extra set of quotes!
    149             cmd = '""%s" %s "%s""' % (app, options, filePath)

SubConverterException: Cannot find a valid application path for format lilypond. Specify this in your Environment by calling environment.set(None, 'pathToApplication')
```

I have also tried restarting the iPython notebook server between changes.

Thank you.

**Comment by mscuthbert** [comment]
This is expected behavior -- for GNU/Linux and other non-Win/OS X software, users need to specify all paths directly because there are too many system variants to support.

**Comment by chr15m** [comment]
Hi @mscuthbert, thanks for taking the time to review the issue.

> users need to specify all paths directly because there are too many system variants to support.

On all Posix systems (including OSX), and indeed Windows, if the binary is on the user's own `PATH` then it will be found without the software being told where to find it. That is the point of the `PATH` environment variable.

To demonstrate, here is a Python one-liner which finds `lilypond` on my GNU/Linux system without my having to input the full path (I just provide the name of the binary `lilypond`):

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.Popen(["lilypond", "--version"], stdout=subprocess.PIPE).communicate()[0]
"GNU LilyPond 2.16.2\n\nCopyright (c) 1996--2012 by\n  Han-Wen Nienhuys <hanwen@xs4all.nl>\n  Jan Nieuwenhuizen <janneke@gnu.org>\n  and others.\n\nThis program is free software.  It is covered by the GNU General Public\nLicense and you are welcome to change it and/or distribute copies of it\nunder certain conditions.  Invoke as `lilypond --warranty' for more\ninformation.\n\n"
```

In almost all situations on all GNU/Linux distributions it will be the case that the user has the binaries for e.g. lilypond, mscore, etc. on their path already.

What would be great (and I understand this is a feature request for a system that you don't support so you're welcome to ignore it) is if music21 could do the sensible thing and first check whether the binary is available on the path before trying the full-path version. This would be useful to people on OSX and Windows as well as GNU/Linux. Respecting the system-wide `PATH` is the expected behaviour from modern software.

Here is a snippet of code for checking if some binary is on the path in Python: https://stackoverflow.com/questions/377017/test-if-executable-exists-in-python/377028#377028

Thanks again for your time and your work on music21.
