### ISSUE TITLE
Unable to create a Pitch corresponding to '#-1'

### ISSUE THREAD

**Issue by cye2020** [cuthbertLab/music21#1576]
**music21 version**

`8.3.0`   

**Problem summary**

Unable to create a Pitch corresponding to '#-1'

**Steps to reproduce**

```
Paste minimal code example here. Most issues can be reproduced with just a few elements.
Attach external files only after attempting to reproduce using a simple stream.

dPitch = pitch.Pitch('D2')
lowC = dPitch.transpose('m-23')
print(lowC) # C#-1
print(lowC.accidental) # sharp
print(pitch.Pitch('C#-1')) 
```

**Expected vs. actual behavior**

I expected
```
print(pitch.Pitch('C#-1') # C#-1
```
However It results in
```
music21.pitch.AccidentalException: #- is not a supported accidental type
```
I got this Error when analyze('key')

**More information**

OS: Ubuntu 22.04.2 LTS
python version: 3.10.11

**Comment by mscuthbert** [comment]
This is a known and documented limitation covered in the User's Guide and is expected behavior.  Set the pitch with `name="C#", octave=-1`
