### ISSUE TITLE
part.write("midi", ) output different tempo MIDI file.

### ISSUE THREAD

**Issue by NeroBlackstone** [cuthbertLab/music21#1578]
**music21 version**

`8.1.0`   

**Problem summary**

Parse `.musicxml` file to music21 stream, then output parts to MIDI file, only the first part have the correct tempo.

**Steps to reproduce**
Files for reproduce:
[sample.zip](https://github.com/cuthbertLab/music21/files/11498226/sample.zip)

``` python
from music21 import *

score = converter.parse("sample.musicxml")

for p in score.parts:
    p.atSoundingPitch = False
    for m in p.getElementsByClass("Measure"):
        m.removeByClass("ChordSymbol")

piano_rh = score.parts[0]
piano_rh.write("midi","sample_rh.mid")
piano_lh = score.parts[1]
piano_lh.write("midi","sample_lh.mid")
```

**Expected vs. actual behavior**

Expected behavior:
Both MIDI files have tempo = 40.

Actual behavior:
Only the first part output with the correct tempo.

![image](https://github.com/cuthbertLab/music21/assets/17470335/9586edf2-aa33-45dc-97e1-6262838c4db9)
![image](https://github.com/cuthbertLab/music21/assets/17470335/97df1e2f-7431-4d89-9eb1-5093bc54bc10)

**More information**

I don't know if this is expected behavior. Because as I know "Part" object does not contain tempo information.

**Comment by TimFelixBeyer** [comment]
This is a known limitation - music21 currently does not parse all tempo tags in musicxml files. I have a fix almost ready that I will prepare a PR for when I find some time.
