### ISSUE TITLE
Problems creating and showing tuplets

### ISSUE THREAD

**Issue by AlmogCohen** [cuthbertLab/music21#158]
Hi guys,
I was working with music21 for a while and I appreciate your work here greatly :)

I'm trying to create tuplets (all kinds of them) and then trying to show them. I was searching online and was not able to find the proper way to create those tuplets. I tried following the documentation [herer](http://web.mit.edu/music21/doc/moduleReference/moduleDuration.html#music21.duration.Tuplet) by doing so:
```
>>> myNote = note.Note("C#4")
>>> myNote.duration.quarterLength = 0.8
>>> myNote.duration.fullName
'Quarter Quintuplet (4/5 QL)'
```

I thought that I've created a tuplet (although I expected that I'll need to add the rest of the notes somehow...). What I get when doing `myNote.show()` is the [this](http://cl.ly/1Q18380b2i2s).

Could someone please help me understand where my problem is and whats the best to create such tuplet? I'd like to create something of this form. http://cl.ly/160j2O0S273Y (Creating triplet is good enough for me as I'll understand the way to create the others as well).

Thanks!

**Comment by mscuthbert** [comment]
Hi Almog,

What you have is actually a correct representation of a quintuplet in isolation.  But that's not what you'd normally think they should look like, because we want to see 5 of them.  Try adding to your code:

```
>>> s = stream.Stream()
>>> s.repeatAppend(myNote, 5)
>>> s.show()
```

And it should work fine.

For a triplet, set quarterLength to 1.0/3 and then create 3 of them. 

Best,
Myke

**Comment by mscuthbert** [comment]
Feel free to keep commenting or Reopen if you think I've misunderstood the issue.

**Comment by AlmogCohen** [comment]
Thanks for the prompt replay! Trying to apply your advices, which were seems to be working I also tried adding the stream to a measure but then it all stops working. Could you advise?
```
    myNote = note.Note("C#4")
    myNote.duration.appendTuplet(duration.Tuplet(3, 4 / 4, 'eighth'))
    #
    s = stream.Stream()
    s.repeatAppend(myNote, 2)

    m = stream.Measure()
    m.append(s)
    m.show()
```
Shows my an empty score. Although `s.show()` is working completely fine. Thanks!

**Comment by mscuthbert** [comment]
I think that you'll enjoy going through the User's Guide if you haven't already -- it'll show you things such as you don't need a stream inside a Measure -- if there are other questions please join the music21list (on google groups) -- it's a better place for learning than here.  Glad you like it.  Michael
