### ISSUE TITLE
error in jupyter when calling .show()

### ISSUE THREAD

**Issue by luka1618033988** [cuthbertLab/music21#1587]
I had a problem which I fixed, I don't know if you fixed it in newer versions. There were several posts on the web about it without solution so I decided to share.

I have music21==7.3.3 installed with pip and I'm using python 3.7.
I tried to run :
from music21 import *
n = note.Note('C4')
n.show()

but I got this error:
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

after fixing it with:
us = environment.UserSettings()
us['musicxmlPath'] = 'C:/MuseScore3/bin/MuseScore3.exe'
us['musescoreDirectPNGPath'] = 'C:/MuseScore3/bin/MuseScore3.exe'

I got error:
[TypeError: argument of type 'WindowsPath' is not iterable](https://stackoverflow.com/questions/63987965/typeerror-argument-of-type-windowspath-is-not-iterable-in-django-python)

Finally, I changed 
C:\Users\[USER]\anaconda3\envs\[ENV]\Lib\site-packages\music21\converter\subConverters.py
line 947 with: musescoreRun = [str(musescorePath), str(fp), '-o', fpOut, '-T', '0']
and it works.

it seems subprocess expected strings but subConverters was sending windowspath object.

**Comment by mscuthbert** [comment]
yes, this is fixed -- definitely suggest upgrading to v8.
