### ISSUE TITLE
Implicit accidentals for repeated notes not handled when converting from ABC

### ISSUE THREAD

**Issue by samuelbradshaw** [cuthbertLab/music21#1588]
**music21 version**

`8.3.0`   

**Problem summary**

When a note with a written accidental is repeated in the same measure, the accidental symbol isn't usually written the second time. So, in the example below, both the first and fourth notes are played as a G flat:
<img width="441" alt="Screenshot 2023-06-01 at 11 02 57 PM" src="https://github.com/cuthbertLab/music21/assets/7323052/2566bea3-417b-4688-ab52-b19e34f2a627">
This is written in ABC notation by leaving off the `_` (which indicates a flat symbol) on the second instance of the note:
```
X:0
Q:1/4=120
M:4/4
L:1/4
K:Eb
_G =E D G yy
```
Unfortunately, when converting this ABC snippet to a music21 score, `_G` is treated as G flat (MIDI pitch 66) and `G` is treated as G natural (MIDI pitch 67).

**Steps to reproduce**

```
from music21 import converter

abc = '''X:0
Q:1/4=120
M:4/4
L:1/4
K:Eb
_G =E D G yy'''

score = converter.parseData(abc, format='abc')

midi_pitches = []
for n in score.recurse().notes.stream().stripTies():
  midi_pitches.append(n.pitch.midi)

# Expected: [66, 64, 62, 66]
# Actual: [66, 64, 62, 67]
print(midi_pitches)
```

**Expected vs. actual behavior**
Expected: Implicit (unwritten) accidentals from an ABC document should be interpreted correctly. Both the first and fourth notes from the example ABC snippet should be interpreted as G flat (MIDI pitch 66).

**More information**
In case it's helpful, my use case is a tune search engine, where a user types the first few notes of a melody, and it searches a database for tunes with a similar relative melody. I discovered music21 recently, and it's a very helpful library!

EDIT: Potentially a clue, or potentially unrelated: If I try to get the key of the converted snippet with `score.analyze('key')`, it gives me D major. D major might be a better real-world key for this sequence of notes, but I expected E flat major because that's what's specified in the ABC snippet.

**Comment by mscuthbert** [comment]
accidental usage in this way is left undefined in ABC v1.6 and assumed to be like how music21 supports -- it wasn't until ABC 2.0 that the `%%propagate-accidentals` format was defined and the default set to `pitch`.  Music21 implements the `none` format for ABC files that don't define themselves as v2.0 or higher, which is what we've found that most ABC files in the wild without version tags use.  If you want the newer behavior, set the version in the first comment field:

```
In [10]: abc = '''%abc-2.1
    ...: X:0
    ...: Q:1/4=120
    ...: M:4/4
    ...: L:1/4
    ...: K:Eb
    ...: _G =E D G yy'''

In [11]: score = converter.parseData(abc, format='abc')

In [12]: score.show('text')
{0.0} <music21.metadata.Metadata object at 0x110d76c50>
{0.0} <music21.stream.Part 0x111f33490>
    {0.0} <music21.clef.TrebleClef>
    {0.0} <music21.tempo.MetronomeMark animato Quarter=120.0>
    {0.0} <music21.key.Key of E- major>
    {0.0} <music21.meter.TimeSignature 4/4>
    {0.0} <music21.note.Note G->
    {1.0} <music21.note.Note E>
    {2.0} <music21.note.Note D>
    {3.0} <music21.note.Note G->
```

**Comment by samuelbradshaw** [comment]
Hooray, that works! Thank you for the quick reply!

**Comment by mscuthbert** [comment]
Thanks @samuelbradshaw  -- I did realize from this that music21 does not support the newest `%%abc-version 2.1` format (instead of the more common and older `%abc-2.1` w/ one `%`) -- patching that now.

These ambiguities in ABC are one reason why I think it's mainly useful for non-chromatic folk music.  See my answer at https://music.stackexchange.com/questions/23841/what-are-the-limitations-of-the-abc-notation-format/24394#24394
