### ISSUE TITLE
partitionByInstrument putting all music events in one part.

### ISSUE THREAD

**Issue by juancopi81** [cuthbertLab/music21#1590]
**music21 version**

`8.3.0`   

**Problem summary**

Sorry if this is not a bug and it's me not understanding something. I am using `partitionByInstrument` to create a Stream from a Score so that the parts are in different instruments. However, all notes get added in just one of the Parts (in one instruments) and the other parts (instruments) have empty bars.

**Steps to reproduce**
Here is an example with this [Midi file](https://drive.google.com/file/d/10ACL2hjfaLXRhsYuR7YyreAH2Bq71rts/view?usp=sharing), but I tried with others and the same happened.

For context, this is how the Midi file looks like in MuseScore (first bars)
![image](https://github.com/cuthbertLab/music21/assets/4313860/3ebc9ed0-0fe1-4a74-adf0-423222c57630)

```py
from music21 import *

crazy = converter.parse("/content/Crazy.1.mid", quantizePost=True)

crazy.show("text")
```
![image](https://github.com/cuthbertLab/music21/assets/4313860/5d3c67f5-eeb7-4040-84f4-48151980b38b)

```py
s2 = instrument.partitionByInstrument(crazy)

# TODO: this step might not be necessary...
for p in s2.parts:
    p.makeRests(fillGaps=True, inPlace=True)

# TODO: this step SHOULD not be necessary (.template())
for p in s2.parts:
    p.makeMeasures(inPlace=True)
    p.makeTies(inPlace=True)

s2.show("text")
```
S2 is now in the different instruments, but only one (Electric Guitar) has all the music events.

![image](https://github.com/cuthbertLab/music21/assets/4313860/79454b2f-53a3-4724-8884-a16d2121c60e)

And if I download the stream with:

`s2.write(fp="test.mid", fmt="mid")`

and then open the midi file in MuseScore, I see all notes under Electric Guitar:

![image](https://github.com/cuthbertLab/music21/assets/4313860/bc96e997-c401-4b6c-a6af-f5115c63153f)

I've tried different combinations of adding/removing makeMeasures, makeTies, etc. with no succes.

**Expected vs. actual behavior**

I was expecting the after using `partitionByInstrument` the new object will have different parts, each one with the respective instrument, and each instrument with the notes. But what I got it is an object with all notes in the same part.

**More information**

**Comment by jacobtylerwalls** [comment]
In this case, the instrument events in the MIDI file are roughly all at the same time point. That's not what partitionByInstrument expects: it assigns notes to the parts based on the most recent instrument. That's why they're all getting assigned to one part.

You will probably have to remap this manually, unfortunately!
