### ISSUE TITLE
music21 write xml error

### ISSUE THREAD

**Issue by liusw02** [cuthbertLab/music21#1598]
**python code:**
from music21 import converter,instrument  
file = converter.parse('The Shadow of Your Smile.mid')
components = []

Recurse = file.recurse()
alto = Recurse.parts[0]
#print(alto)
excerpt = alto.measures(1,1)
excerpt.show('text')

**Text**
{0.0} <music21.stream.Measure 1 offset=0.0>
    {0.0} <music21.instrument.Piano 'Piano: Piano'>
    {0.0} <music21.instrument.Instrument 'None'>
    {0.0} <music21.instrument.ElectricPiano 'Electric Piano'>
    {0.0} <music21.clef.TrebleClef>
    {0.0} <music21.tempo.MetronomeMark adagietto Quarter=65.0>
    {0.0} <music21.meter.TimeSignature 4/4>
    {0.0} <music21.note.Rest dotted-quarter>
    {1.5} <music21.note.Note E>
    {2.0} <music21.note.Note A>
    {2.5} <music21.note.Note B>
    {3.0} <music21.note.Note C>
    {3.5} <music21.note.Note E>
**text shows no problem**

**music21 write xml note duration error**
score = stream.Score()  
score.insert(0,excerpt) 
score.insert(0,metadata.Metadata())
score.metadata.title = 'The Shadow of Your Smile'
score.metadata.composer = 'example composer'
print(type(file),type(excerpt))
score.write('xml',fp=r'The Shadow of Your Smile.xml') 

**xml**
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE score-partwise  PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>The Shadow of Your Smile</work-title>
  </work>
  <movement-title>The Shadow of Your Smile</movement-title>
  <identification>
    <creator type="composer">example composer</creator>
    <encoding>
      <encoding-date>2023-06-10</encoding-date>
      <software>music21 v.8.1.0</software>
    </encoding>
  </identification>
  <defaults>
    <scaling>
      <millimeters>7</millimeters>
      <tenths>40</tenths>
    </scaling>
  </defaults>
  <part-list>
    <score-part id="Pc8314276f3d2ee2de4984a1fa236c2c9">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno</part-abbreviation>
      <score-instrument id="Ia7bbc16b90c3dc42c6fc452d0c8e20c2">
        <instrument-name>Piano</instrument-name>
        <instrument-abbreviation>Pno</instrument-abbreviation>
      </score-instrument>
      <score-instrument id="Id54329604eea85ebef84279117c611bc">
        <instrument-name>None</instrument-name>
      </score-instrument>
      <score-instrument id="Iea79b5021dcadb56d0d92baef6b113d7">
        <instrument-name>Electric Piano</instrument-name>
        <instrument-abbreviation>E.Pno</instrument-abbreviation>
      </score-instrument>
      <midi-instrument id="Ia7bbc16b90c3dc42c6fc452d0c8e20c2">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
      </midi-instrument>
      <midi-instrument id="Iea79b5021dcadb56d0d92baef6b113d7">
        <midi-channel>3</midi-channel>
        <midi-program>5</midi-program>
      </midi-instrument>
    </score-part>
  </part-list>
  
  <part id="Pc8314276f3d2ee2de4984a1fa236c2c9">
    
    <measure number="1">
      <attributes>
        <divisions>10080</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <direction>
        <direction-type>
          <metronome parentheses="no">
            <beat-unit>quarter</beat-unit>
            <per-minute>65</per-minute>
          </metronome>
        </direction-type>
        <sound tempo="65" />
      </direction>
      <note>
        <rest />
        <duration>15120</duration>
        <type>quarter</type>
        <dot />
      </note>
      <note dynamics="101.11">
        <pitch>
          <step>E</step>
          <octave>4</octave>
        </pitch>
        <duration>5040</duration>
        <instrument id="Iea79b5021dcadb56d0d92baef6b113d7" />
        <type>eighth</type>
      </note>
      <note dynamics="73.33">
        <pitch>
          <step>A</step>
          <octave>4</octave>
        </pitch>
        <duration>5040</duration>
        <instrument id="Iea79b5021dcadb56d0d92baef6b113d7" />
        <type>eighth</type>
      </note>
      <note dynamics="81.11">
        <pitch>
          <step>B</step>
          <octave>4</octave>
        </pitch>
        <duration>5040</duration>
        <instrument id="Iea79b5021dcadb56d0d92baef6b113d7" />
        <type>eighth</type>
      </note>
      <note dynamics="71.11">
        <pitch>
          <step>C</step>
          <octave>5</octave>
        </pitch>
        <duration>6720</duration>
        <instrument id="Iea79b5021dcadb56d0d92baef6b113d7" />
        <type>quarter</type>
        <time-modification>
          <actual-notes>3</actual-notes>
          <normal-notes>2</normal-notes>
          <normal-type>quarter</normal-type>
        </time-modification>
        <notations>
          <tuplet bracket="no" number="1" placement="above" type="start">
            <tuplet-actual>
              <tuplet-number>3</tuplet-number>
              <tuplet-type>quarter</tuplet-type>
            </tuplet-actual>
            <tuplet-normal>
              <tuplet-number>2</tuplet-number>
              <tuplet-type>quarter</tuplet-type>
            </tuplet-normal>
          </tuplet>
          <tuplet number="1" type="stop" />
        </notations>
      </note>
      <note dynamics="78.89">
        <pitch>
          <step>E</step>
          <octave>5</octave>
        </pitch>
        <duration>5040</duration>
        <instrument id="Iea79b5021dcadb56d0d92baef6b113d7" />
        <type>eighth</type>
      </note>
    </measure>
  </part>
</score-partwise>

Importing xml sheet music with overt
![The Shadow of Your Smile(F)](https://github.com/cuthbertLab/music21/assets/34398035/cd64ef79-4514-45f4-bdeb-0b31a75bc38a)

The red circled part should be eighth notes, but it is wrongly written in xml as quarter notes, the note duration of this bar is longer than 4 (See Figure 1-1)
![The Shadow of Your Smile(F)1-1](https://github.com/cuthbertLab/music21/assets/34398035/a0f3d546-d331-402a-8e86-1d4073b7d0d0)

Using music21 preview also gives an error
The red circled part should be eighth notes, but it is wrongly written in xml as quarter notes, the note duration of this bar is longer than 4
There are also eighth rests and thirds.
 (See Figure 1-2)
![The Shadow of Your Smile(F)1-2](https://github.com/cuthbertLab/music21/assets/34398035/8f3632bc-d109-4e68-8bd6-0d4ccf8d18b6)

**Correct**
![The Shadow of Your Smile(Tur)](https://github.com/cuthbertLab/music21/assets/34398035/02a8623c-d2e9-4d08-85a4-0b927f7501ac)

**Comment by mscuthbert** [comment]
Please use the bug report and give your music21 version number and operating system before filing a bug report.  These are necessary for diagnosing.  Feel free to open a new Issue with this information and link to this one.
