### ISSUE TITLE
Quicktime7 setup for MIDI

### ISSUE THREAD

**Issue by robwell** [cuthbertLab/music21#160]
I've just installed music21 on my mac running El Capitan tried out a bit of the tutorial and then got to the part about Apple's maddening removal of MIDI from Quicktime. I downloaded and installed Quicktime7 but it seems I need to do something more (f.play('midi') tries to open Quicktime 10 so far as I can tell). I've searched around for a way to change preferences, looked at the system preferences, etc. I am sadly ignorant of how file types bind to apps so I was hoping that someone who has already gone through this could give me a hint as to what to do. I know that this is not a bug in music21 - it looks really cool!

**Comment by mscuthbert** [comment]
See if something in ~/.music21rc is pointing to the wrong location.  MIDI playback works for me on El Cap., but I've upgraded from a lot of older versions, so I don't know what a clean install would be like,

**Comment by mscuthbert** [comment]
Any update?

**Comment by mscuthbert** [comment]
Closed for inactivity.  Feel free to reopen if still relevant.
