### ISSUE TITLE
v9 beta incompatibility: unregisterSubconverter has been renamed unregisterSubConverter

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1604]
**music21 version**

This appears to have happened within the last couple of weeks; I just updated my fork to latest to make sure all was well, and ran into this.

**Problem summary**

unregisterSubconverter (lower-case 'c') has been renamed unregisterSubConverter (upper-case 'C').  This breaks the shipping version of converter21 (2.0.1).  Can we keep the old name as well (deprecated) for a few months?  I have a whole new v3 coming that depends on music21 v9, so I'm happy to make the change there, but in the meantime it would be good to continue working as is.

**Comment by gregchapman-dev** [comment]
Ah.  registerSubconverter/registerSubConverter as well.

**Comment by gregchapman-dev** [comment]
Thanks!

**Comment by mscuthbert** [comment]
you got it in the nick of time -- I was about the declare "no objections" and release, but i'll give a bit more time now to check.

**Comment by gregchapman-dev** [comment]
Give me a few hours to run through my big test suite; I'll let you know ASAP as soon as I know all is well.

**Comment by mscuthbert** [comment]
You got it -- will not publish before tomorrow w/o a checkin from you.

(btw -- if it's a pain and annoyance, I can make the @common.deprecated on this not be a user-facing-error until v10)

You're right, I should've offered both ways for at least one version.  I just had a moment of self-rage against all the incompatible subConverter vs subconverter code and decided to go one way once and for-all.

**Comment by mscuthbert** [comment]
I'm currently developing an MNX converter for music21 as a separate project, so getting to use the whole register/deregister system myself for once, which should yield some improvements in the future.
