### ISSUE TITLE
v9 incompatibility: Converter.subconvertersList vs Converter.subConvertersList

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#1606]
Can we get a deprecated old guy here, too?  I use this in converter21's `__main__.py` if you screw up the command line, so I can list available formats you can use.

**Comment by mscuthbert** [comment]
Sure!  I'll look at 55207a2 and put back things that were changed.

These will not be exported by "from music21.converter import *" -- hope that's okay.

**Comment by gregchapman-dev** [comment]
That's fine.

**Comment by gregchapman-dev** [comment]
My tests have all run, and I have found no other issues.  Thanks!

**Comment by mscuthbert** [comment]
Fixed in #1607
