### ISSUE TITLE
Add Percussion Sample to Music21 Corpus Demo Section

### ISSUE THREAD

**Issue by kir12** [cuthbertLab/music21#1609]
**Motivation**
Currently (as established in [this music21 Google Groups post](https://groups.google.com/u/1/g/music21list/c/CUEkMFYY9JA)) there aren't any scores inside the music21 corpus that have Percussion parts, since all the pieces in the corpus (as well as probably all *eligible* pieces) are old enough that Percussion/Drumset parts hadn't really existed yet. Having at least one reference for what a Percussion part in MusicXML *should* look like for maximum compatibility with music21 would be great for verifying the correctness of our own MusicXML files. (As well as pre-emptively ruling out music21 as the source of any problems)

**Feature summary**
The aim of this feature is to add [this MusicXML sample](https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/tutorial-percussion/) coming directly from the W3C Community Group (which created the MusicXML spec) to the music21 corpus. It's likely the most authoritative a MusicXML example for Percussion parts can get, and the MusicXML Specification's [license](https://www.w3.org/community/about/process/final/) seems to allow usages such as this.

**Proposed implementation**
A file titled `drum_sample.xml` will be placed in `music21/corpus/demos/drum_sample.xml` which will have the contents of the MusicXML example.

**Intent**

[x] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[ ] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

**Comment by mscuthbert** [comment]
Good issue. Glad to take a commit.
