### ISSUE TITLE
Instrument name parsing fails in certain cases

### ISSUE THREAD

**Issue by sonovice** [cuthbertLab/music21#163]
`print(instrument.fromString('Clarinetti in A.'))` returns `Alto`
`print(instrument.fromString('Clarinetti in B.'))` returns `Bass`

The dot `.` at the end mixes it up.

Something like [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) might be useful for finding the best match.

**Comment by mscuthbert** [comment]
Fixed by https://github.com/cuthbertLab/music21/commit/28cfb6dcee1a2430094097d1ea8b964b704dfd0f

**Comment by mscuthbert** [comment]
Also changed, so that Clarinetti in B. should return B-flat not B natural.  To get a B-natural clarinet, give H or "B-natural"
