### ISSUE TITLE
translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=0, channel=None, data

### ISSUE THREAD

**Issue by gg22mm** [cuthbertLab/music21#1640]
d:\Anaconda3\envs\mygpt\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=0, channel=None, data=b'CLANNAD              \x82\xcd\x81`\x82\xe8\x82\xa1\x82\xb7\x82\xbd\x81[\x82\xd3\x82\xa1\x82\xc1\x82\xb5\x82\xe3      for SC-88Pro'>; getting generic Instrument
  warnings.warn(

down mid file:
https://aistudio.baidu.com/datasetdetail/236184

**Comment by jacobtylerwalls** [comment]
Warning is expected.
