### ISSUE TITLE
Instrument parsing unstable

### ISSUE THREAD

**Issue by sonovice** [cuthbertLab/music21#165]
One of the latest commits changed the parsing of instrument names leading to some new errors.
This is a minimal MEI file with the instrument label "Clarinetti in A", which is obviously not a key in the `instrumentNames` dictionary.

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-model href="http://www.music-encoding.org/schema/2.1.1/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="http://www.music-encoding.org/schema/2.1.1/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" xmlns:xlink="http://www.w3.org/1999/xlink" meiversion="2013">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title/>
            </titleStmt>
            <pubStmt/>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef meter.count="4" meter.unit="4" meter.sym="common" key.sig="3s" key.mode="major">
                        <staffGrp n="1" barthru="false">
                            <staffDef n="1" lines="5" label="Clarinetti in A" key.sig="0" trans.semi="-3" trans.diat="-2" clef.line="2" clef.shape="G"/>
                            <staffDef n="2" lines="5" label="Piano" clef.line="2" clef.shape="G"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1" xml:id="d23378e68">
                            <staff n="1">
                                <layer n="1">
                                    <note xml:id="d23378e100" pname="d" accid="s" oct="5" dur="4"/>
                                </layer>
                            </staff>
                            <staff n="2">
                                <layer n="1">
                                    <note xml:id="d23378e325" pname="c" oct="4" dur="4"/>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

[(Download)](https://www.dropbox.com/s/a8melv3l1ct0xwn/minimal.mei?dl=1)

Trying to read this file and export it to MIDI gives 2 warnings, that completely screw up the file:

```
midi.base.py: WARNING: Conversion error for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1>: Got incorrect data for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1> in .data: None,cannot parse Program Change; ignored.
midi.base.py: WARNING: Conversion error for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1>: Got incorrect data for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1> in .data: None,cannot parse Program Change; ignored.
```

Even the timing of the played notes is off. If the label is changed to "Clarinet", everything works fine. Maybe the "default behaviour" for unrecognized instruments could be stabilized in some way, especially since--at least in MEI files--the transposition informations are given as additional attributes.

Looking at the stream like this

``` python
from music21 import *

stream = converter.parseFile('minimal.mei', None, "mei", True)

print('Instruments:')
for i in stream.recurse().getInstruments():
    print(i.transposition)

print('\nWritten stream:')
stream.show('text')

print('\nSounding stream:')
stream.toSoundingPitch(inPlace=True)
stream.show('text')
```

outputs

```
Instruments:
<music21.interval.Interval m-3>
None

Written stream:
{0.0} <music21.metadata.Metadata object at 0x000001F4E00F2A90>
{0.0} <music21.stream.Part 0x1f4e00e5160>
    {0.0} <music21.instrument.Instrument >
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 3 sharps, mode major>
        {0.0} <music21.key.KeySignature of no sharps or flats>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note D#>
{0.0} <music21.stream.Part 0x1f4e00e50b8>
    {0.0} <music21.instrument.Instrument 2: Piano: Piano>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 3 sharps, mode major>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note C>

Sounding stream:
{0.0} <music21.metadata.Metadata object at 0x000001F4E00F2A90>
{0.0} <music21.stream.Part 0x1f4e00e5160>
    {0.0} <music21.instrument.Instrument >
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 6 sharps, mode major>
        {0.0} <music21.key.KeySignature of 3 sharps>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note B#>
{0.0} <music21.stream.Part 0x1f4e00e50b8>
    {0.0} <music21.instrument.Instrument 2: Piano: Piano>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 6 sharps, mode major>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note C>
```

Sorry for the long post...

**Comment by mscuthbert** [comment]
MIDI output and MEI input are quite separate. Is the problem that the MEI is not being parsed into correct music21 objects or that the music21 objects which are correctly defined are not being output properly as MIDI? The latter I'll get onto. For MEI errors we'll need the Mcgill team to be involved. I don't know anything about MEI

The parsing of an instrument name from an approximate string should be a sort of last resort for formats such as OMR processing which don't have a better way of specifying precise instrument names separate from display names. I trust that MEI has another way of Doing this? Thanks!

On May 19, 2016, at 19:38, Simon Waloschek <notifications@github.com<mailto:notifications@github.com>> wrote:


One of the latest commits changed the parsing of instrument names leading to some new errors.
This is a minimal MEI file with the instrument label "Clarinetti in A", which is obviously not a key in the instrumentNames dictionary.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-model href="http://www.music-encoding.org/schema/2.1.1/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="http://www.music-encoding.org/schema/2.1.1/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" xmlns:xlink="http://www.w3.org/1999/xlink" meiversion="2013">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title/>
            </titleStmt>
            <pubStmt/>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef meter.count="4" meter.unit="4" meter.sym="common" key.sig="3s" key.mode="major">
                        <staffGrp n="1" barthru="false">
                            <staffDef n="1" lines="5" label="Clarinetti in A" key.sig="0" trans.semi="-3" trans.diat="-2" clef.line="2" clef.shape="G"/>
                            <staffDef n="2" lines="5" label="Piano" clef.line="2" clef.shape="G"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1" xml:id="d23378e68">
                            <staff n="1">
                                <layer n="1">
                                    <note xml:id="d23378e100" pname="d" accid="s" oct="5" dur="4"/>
                                </layer>
                            </staff>
                            <staff n="2">
                                <layer n="1">
                                    <note xml:id="d23378e325" pname="c" oct="4" dur="4"/>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>

(Download)<https://www.dropbox.com/s/a8melv3l1ct0xwn/minimal.mei?dl=1>

Trying to read this file and export it to MIDI gives 2 warnings, that completely screw up the file:

midi.base.py: WARNING: Conversion error for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1>: Got incorrect data for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1> in .data: None,cannot parse Program Change; ignored.
midi.base.py: WARNING: Conversion error for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1>: Got incorrect data for <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1> in .data: None,cannot parse Program Change; ignored.


Even the timing of the played notes is off. If the label is changed to "Clarinet", everything works fine. Maybe the "default behaviour" for unrecognized instruments could be stabilized in some way, especially since--at least in MEI files--the transposition informations are given as additional attributes.

Looking at the stream like this

from music21 import *

stream = converter.parseFile('minimal.mei', None, "mei", True)

print('Instruments:')
for i in stream.recurse().getInstruments():
    print(i.transposition)

print('\nWritten stream:')
stream.show('text')

print('\nSounding stream:')
stream.toSoundingPitch(inPlace=True)
stream.show('text')

outputs

Instruments:
<music21.interval.Interval m-3>
None

Written stream:
{0.0} <music21.metadata.Metadata object at 0x000001F4E00F2A90>
{0.0} <music21.stream.Part 0x1f4e00e5160>
    {0.0} <music21.instrument.Instrument >
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 3 sharps, mode major>
        {0.0} <music21.key.KeySignature of no sharps or flats>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note D#>
{0.0} <music21.stream.Part 0x1f4e00e50b8>
    {0.0} <music21.instrument.Instrument 2: Piano: Piano>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 3 sharps, mode major>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note C>

Sounding stream:
{0.0} <music21.metadata.Metadata object at 0x000001F4E00F2A90>
{0.0} <music21.stream.Part 0x1f4e00e5160>
    {0.0} <music21.instrument.Instrument >
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 6 sharps, mode major>
        {0.0} <music21.key.KeySignature of 3 sharps>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note B#>
{0.0} <music21.stream.Part 0x1f4e00e50b8>
    {0.0} <music21.instrument.Instrument 2: Piano: Piano>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 6 sharps, mode major>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.stream.Voice 1>
            {0.0} <music21.note.Note C>


Sorry for the long post...

**Comment by sonovice** [comment]
> The parsing of an instrument name from an approximate string should be a sort of last resort for formats such as OMR processing which don't have a better way of specifying precise instrument names separate from display names. I trust that MEI has another way of Doing this?

Unfortunately not. MEI is meant to be a semantic layout describing markup language. Therefore, instrument names are coded like they are written in the score.

> Is the problem that the MEI is not being parsed into correct music21 objects or that the music21 objects which are correctly defined are not being output properly as MIDI?

I think it might be both. I will try to talk to @crantila and @ahankinson about the MEI part after the Music Encoding Conference that is currently taking place. But the main problem seems to be the `instrumentFromString(...)` method, which is not really related to the MEI converter.

Nevertheless, the MIDI output gets it wrong, if no correct instrument is given though all the needed data like transposition are available in the stream as shown in the opening post.

Sorry for the constant nagging...

**Comment by ahankinson** [comment]
MEI has the `data.MIDINAMES` datatype which specifies the instruments in General MIDI (https://github.com/music-encoding/music-encoding/blob/develop/source/specs/mei-source.xml#L1779)

These can be used as valid values for the `@midi.instrname` on an `<instrDef>` element, http://music-encoding.org/documentation/2.1.1/instrDef/

`<instrDef>` can be used as a child of `<staffDef>,` so your encoding might be modified to look something like this:

```xml
...
<staffDef n="1" lines="5" label="Clarinetti in A" key.sig="0" trans.semi="-3" trans.diat="-2" clef.line="2" clef.shape="G">
    <instrDef midi.instrname="clarinet" />
</staffDef>
...
```

**Comment by sonovice** [comment]
Thanks for clarifying on this, @ahankinson. I definitely overlooked this. But I believe to make music21 universally usable with MEI, one should not be forced to edit all of their MEI files.

**Comment by ahankinson** [comment]
I'm not sure how else we could do this, though -- the `@label` attribute can be free text, so you will always have this problem if the encoder has taken the label from a printed score, for example, and it says something like "Posaune" or "Faggotti". So automatic mapping to MIDI instruments from the values of `@label` is a pretty unstable method.

The alternative is that we simply render everything in "Piano" (000) _unless_ it has an `instrDef@midi.instrname`definition. That's perhaps the most stable method, but you will still need to edit your MEI files.

**Comment by mscuthbert** [comment]
@ahankinson "The alternative is that we simply render everything in "Piano" (000) unless it has an `instrDef@midi.instrnamedefinition`" -- I think that something like this is the best solution -- render as an "Instrument" object (which will use the MIDI GM Grand Piano sound, but is semantically different than Piano) but with the display name taken from the @label attribute and transposition from the @trans attributes.  

Then if a user wants to replace these with instruments generated from instrument.fromString() they can do so later, but they'll know exactly what is happening.

Making music21 "universally usable with MEI" should definitely be listed as an enhancement or as another project -- it's definitely not something the team has ever promised music21 is or will be.  It's a bit like filing "no graphical interface" as a bug.

Andrew -- actually, "Posaune" works great in .fromString() and gives you back a trombone object.  I didn't believe that "Clarinetti in A" wouldn't work, and then I realized, we don't have plurals in the database.  I've added a few, but yes, that's a major missing part.  Among other frequently encountered forms, we don't have Russian cyrillic mappings.

This issue still needs to be whittled down to one thing that is causing a problem before I can fix.

**Comment by sonovice** [comment]
> render as an "Instrument" object (which will use the MIDI GM Grand Piano sound, but is semantically different than Piano) but with the display name taken from the @label attribute and transposition from the @trans attributes.

This sounds like a very good solution. I will look into this this weekend. 

>Making music21 "universally usable with MEI" should definitely be listed as an enhancement or as another project -- it's definitely not something the team has ever promised music21 is or will be. It's a bit like filing "no graphical interface" as a bug.

Alright, I might have used unspecific language. With "universally usable" I meant the support of as much MEI as possible for import.

**Comment by mscuthbert** [comment]
housekeeping closing for non-activity on pull request.  Feel free to reopen.
