### ISSUE TITLE
change music program (instrument)

### ISSUE THREAD

**Issue by sugizo** [cuthbertLab/music21#1661]
**Motivation**
nice to have ability to change music program (instrument) because many midi generator already have this feature e.g. mido, pretty_midi, etc

**Feature summary**
can change music program (instrument) 

**Proposed implementation**
like another midi generator can set program (instrument)
e.g. program = 0 (the sound output is acoustic grand piano)

**Intent**

[ ] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[X] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

thanks and best regards

**Comment by jacobtylerwalls** [comment]
music21 offers two representations of midi files, one as raw midi events, the other as streams like all other formats. (See #1662). The raw midi events can have program events set manually. The streams can have program changes implied by inserting `Instrument` objects into the stream.
