### ISSUE TITLE
read midi file

### ISSUE THREAD

**Issue by sugizo** [cuthbertLab/music21#1662]
**Motivation**
nice to have ability to read midi file, like some python midi e.g. mido, miditoolkit

**Feature summary**
users can read midi file, to analyse the note, duration, etc

**Proposed implementation**
pretty_midi
![image](https://github.com/cuthbertLab/music21/assets/2418295/879198fd-43c0-42aa-9583-2450e43dc8db)

mido
![image](https://github.com/cuthbertLab/music21/assets/2418295/e77b6ff6-4629-47aa-9da1-d8166b39abad)

miditoolkit
![image](https://github.com/cuthbertLab/music21/assets/2418295/59bf406f-6046-4a03-8157-998beb08f4bf)

**Intent**

[ ] I plan on implementing this myself.
[ ] I am willing to pay to have this feature added.
[X] I am starting a discussion with the hope that community members will volunteer their time to create this. I understand that individuals work on features of interest to them and that this feature may never be implemented.

thanks and best regards

**Comment by jacobtylerwalls** [comment]
Hi :wave:

Music21 reads midi files. One entrypoint is through `converter.parse`; the other is through MidiFile() -- both described [here](https://web.mit.edu/music21/doc/moduleReference/moduleMidi.html#music21.midi.MidiFile).
