### ISSUE TITLE
Normal Form isn't computed correctly

### ISSUE THREAD

**Issue by teymuri** [cuthbertLab/music21#1663]
```python

# Example from https://musictheory.pugetsound.edu/mt21c/NormalForm.html

names = ("B5", "G4", "D5", "E-5", "D6")
c = chord.Chord(names)
print(f"Normal form is [11, 2, 3, 7], not {c.normalOrder}")
```

> Normal form is [11, 2, 3, 7], not [7, 11, 2, 3]

**Comment by mscuthbert** [comment]
Note that there is (I believe) a significant difference between the definition of normal form there and the one from Forte, _Structure of Atonal Music_ on how to break ties (looking at pitches 1-2 not 1-penultimate):

<img width="590" alt="Screenshot 2024-01-02 at 11 05 43" src="https://github.com/cuthbertLab/music21/assets/3521479/ea0c2c48-34dc-4f70-b786-102ab5acf99d">

I had up until now thought that music21 would follow Forte throughout, and indeed renamed normalForm to normalOrder at some point.  But reading Forte again, I'm finding so many contradictions (is there one prime form? or two prime forms, but one is better?  Where is "best normal order" defined? and really, in case of all ties, like 0-4-8, one order is to be chosen arbitrarily??) that I think it is better to start shifting to a more modern definition like the one used here.
