### ISSUE TITLE
Error on show() method call

### ISSUE THREAD

**Issue by prashant2018** [cuthbertLab/music21#167]
Hi, 
when i am try to call show() method i get this error : 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/music21-3.0.4-py2.7.egg/music21/base.py", line 2585, in show
    **keywords)
  File "/usr/local/lib/python2.7/dist-packages/music21-3.0.4-py2.7.egg/music21/converter/subConverters.py", line 820, in show
    self.launch(returnedFilePath, fmt=fmt, app=app)
  File "/usr/local/lib/python2.7/dist-packages/music21-3.0.4-py2.7.egg/music21/converter/subConverters.py", line 159, in launch
    fmt, launchKey))
music21.converter.subConverters.SubConverterException: Cannot find a valid application path for format musicxml. Specify this in your Environment by calling environment.set(None, '/path/to/application')
`
Please help,
Thanks

**Comment by mscuthbert** [comment]
Run python -m music21.configure

**Comment by prashant2018** [comment]
hi, I ran the command but it still gives the error

**Comment by jrc03c** [comment]
I too am experiencing this error, even after running `python -m music21.configure`. :(

**Comment by mscuthbert** [comment]
Where is your musicxml reader installed, and what does ~/.music21rc say?

**Comment by jrc03c** [comment]
```
<settings>
  <preference name="autoDownload" value="allow" />
  <preference name="braillePath" />
  <preference name="debug" value="0" />
  <preference name="directoryScratch" />
  <preference name="graphicsPath" />
  <preference name="ipythonShowFormat" value="ipython.musicxml.png" />
  <preference name="lilypondBackend" value="ps" />
  <preference name="lilypondFormat" value="pdf" />
  <preference name="lilypondPath" value="lilypond" />
  <preference name="lilypondVersion" />
  <localCorporaSettings />
  <localCorpusSettings />
  <preference name="manualCoreCorpusPath" />
  <preference name="midiPath" />
  <preference name="musescoreDirectPNGPath" />
  <preference name="musicxmlPath" />
  <preference name="pdfPath" />
  <preference name="showFormat" value="musicxml" />
  <preference name="vectorPath" />
  <preference name="warnings" value="1" />
  <preference name="writeFormat" value="musicxml" />
</settings>
```

**Comment by mscuthbert** [comment]
And your musicXML reader?

**Comment by jrc03c** [comment]
MuseScore?

**Comment by mscuthbert** [comment]
Is this on Mac or PC?  (per the FAQ, Linux/Unix needs a paid support contract for assistance).

**Comment by mscuthbert** [comment]
Comments removed by poster.  Closing for now.  Can reopen later.
