### ISSUE TITLE
Issues with install the music21 library in kaggle notebook

### ISSUE THREAD

**Issue by sarmiSiva** [cuthbertLab/music21#1698]
**music21 version**

`9.8.7`   

**Problem summary**

When attempting to install the music21 library in a Kaggle notebook using the command  **!pip install music21**  , I encountered an error message stating "**ERROR: No matching distribution found for music21**" . This issue is similar to the one encountered when attempting the installation in Google Colab. 

**### _Kaggle notebook_**
![Screenshot from 2024-03-21 11-04-40](https://github.com/cuthbertLab/music21/assets/63119157/d1fb8a75-bd19-400b-85ca-c96814608b93)

**### _Google Colab_**
![Screenshot from 2024-03-21 11-06-15](https://github.com/cuthbertLab/music21/assets/63119157/b96ee0bb-ade9-439a-91ef-88f765ae853a)

**Comment by jacobtylerwalls** [comment]
Hi. The text in yellow suggests you didn't have an internet connection. Did you retry with a working connection?
