### ISSUE TITLE
midi.translate doesn't find tracks

### ISSUE THREAD

**Issue by jonathan-scholbach** [cuthbertLab/music21#171]
When I run (with `filename` being the path to a midi-file)

```
mf = midi.MidiFile()
mf.open(filename)
mf.read
mf.close
s = midi.translate.midiFileToStream(mf)
```
I get the error

```
File "/usr/local/lib/python2.7/dist-packages/music21-3.0.3-py2.7.egg/music21/midi/translate.py", line 2067, in midiFileToStream
    raise exceptions21.StreamException('no tracks are defined in this MIDI file.')
```
But there *are* tracks in the midi - I created the file with LilyPond, it plays correctly and examining it with [python-midi](https://github.com/vishnubob/python-midi) shows tracks. I get the error with every midi-file I tried, even those midi-files from `music21-3.0.3/music21/midi/testPrimitive`
What do I do wrong?

**Comment by mscuthbert** [comment]
Your code is incorrect above (`read` `close`, etc.)-- you don't need to use `MidiFile`, just do `converter.parse('filename.mid')`

**Comment by jonathan-scholbach** [comment]
Oh, thanks. I'm pretty beginning it...
