### ISSUE TITLE
Tiny doc clarification

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#1711]
**Problem summary**

Erroneously calling for the pitch attribute on a rest raises:

`AttributeError: 'Rest' object has no attribute 'pitch'. Did you mean: 'pitches'?`

I.e., when you have an existential error by requesting a rest with a pitch, solve it by asking for more pitches. ;)

We could replace with something like:

`AttributeError: 'Rest' object has no attribute 'pitch'. Only notes do. Did you perhaps call '.notesAndRests' when you meant '.notes'?`

Not a priority; simply making a "note" here ... and now taking a "rest". ;)

**Comment by gregchapman-dev** [comment]
I’m pretty sure that message is generated by Python itself, not music21.  I see that exact wording in non-music21 code as well.

Greg

**Comment by ahankinson** [comment]
Yeah, since Python 3.10 the error messages can suggest “did you mean” when calling a non-existent property or method.

**Comment by MarkGotham** [comment]
Ah, ok good shout.

A design critique of either python, or music21, or perhaps both.

In any case, forces beyond our control ;). Let's call it an easter egg.

Closing
