### ISSUE TITLE
The documentation not found

### ISSUE THREAD

**Issue by lzqlzzq** [cuthbertLab/music21#1719]
![image](https://github.com/user-attachments/assets/eec67bbd-7560-4336-b0b2-93107c77b6a2)
As the image, the documentation is not found.
![image](https://github.com/user-attachments/assets/4883a472-c623-468f-a28f-bf63559e8026)
And in Internet Archive we can see the last update is 18 Feb 2024.

**Comment by gregchapman-dev** [comment]
Here's what Myke said 3-4 weeks ago:

On Sunday, June 30, 2024 at 4:16:37 PM UTC-7 michael.asa...@[gmail.com](http://gmail.com/) wrote:
Hi all -- I'm leaving MIT officially in 8 hours, so I'm frantically trying to get all the redirects from 17 years worth of projects to all point to somewhere that will still be in my or the community's control.  So I've pointed the old [web.mit.edu/music21](http://web.mit.edu/music21) to go to [www.music21.org](http://www.music21.org/) -- over the next couple of weeks I'll get everything that used to be on the [web.mit.edu](http://web.mit.edu/) site to work at [www.music21.org](http://www.music21.org/)

For now, https://web.archive.org/web/20240516122334/http://web.mit.edu/music21/  will help you out.

**Comment by lzqlzzq** [comment]
Seems to be good now: `https://www.music21.org/music21docs/index.html`.
