### ISSUE TITLE
Tests rely on corpus files

### ISSUE THREAD

**Issue by douglaseck** [cuthbertLab/music21#172]
The corpus is licensed differently than the rest of music21. See music21/corpus/license.txt. 
In instances where a user decides to only install the BSD/LGPL part of music21, it would be helpful to have minimal dependencies against the corpus. In general there are quite a few dependencies:
> grep corpus music21/*/*py | wc -l
980
 
Most of these can likely be avoided. Many tests rely on corpus files, for example testTonalAmbiguityA in music21/key.py. It would be helpful if (a) tests were not in the same files as code being tested [but that's perhaps a personal choice] :-) and more importantly (b) tests for BSD/LGPL code didn't depend on data running under a different license.  I suspect most or all tests can be run against test data explicitly designed to exercise the code being tested. 

Thanks!

**Comment by mscuthbert** [comment]
I don't think that this is something we'll be able to commit to. People developing the system will need to accept the corpus license to be developers. For many of the pieces there are no good PD or BSD licensed substitutes especially since the BSD license isn't a good choice for music compositions. 

What is the practical problem that the presence of the difference in licensing is causing?

**Comment by douglaseck** [comment]
There may be no practical issues. But it does mix and match licenses in a
way that is difficult to audit. It would be easier if the corpus were a
separate repo, perhaps divided by license type.  But I don't think it poses
a serious issue.  And wow that would be a lot of work.  Cheers!

**Comment by mscuthbert** [comment]
Thanks for opening this issue -- it'll still be here and if someone wants to undertake the task, we'll have this as a tracking issue.

**Comment by ahankinson** [comment]
For the record, separate framework and corpus installations have been a secret wish of mine for years. :)

**Comment by douglaseck** [comment]
Not all of our secret wishes come true. But this one can, Andrew. It only
takes time and several approved pull requests. :-)

**Comment by mscuthbert** [comment]
if you want a copy w/o the corpus, just download the nocorpus version: https://github.com/cuthbertLab/music21/releases/download/v3.0.3-alpha/music21-noCorpus-3.0.3.tar.gz

the corpus w/o music21 -- nah.  :-) 

default music21 installed w/o a corpus: never.  it's one of the fundamental principles of the project: "batteries included".  :-)

**Comment by mscuthbert** [comment]
In a more cheerful mood, I just wanted to say, if you need a particular installation for you own research that removes the corpus more than what we offer with the noCorpus install, let me know and I'm sure I can get that set up.  And if you want the opposite: the corpus without music21, I would think that d/l music21, and then delete all but the corpus directory, would not have BSD license entanglements (not that being entangled in BSD is so onerous. :-)  )
