### ISSUE TITLE
can't add voices to the part ??  

### ISSUE THREAD

**Issue by Junny13** [cuthbertLab/music21#1729]
using this code i get an empty music21 fragment when i print the score. Am I doing something wrong or is it a bug?  

This is the code I used: 

s = stream.Score()
part= stream.Part()
part.append(clef.TrebleClef())
time_signature = meter.TimeSignature("4/4")
part.append(time_signature)

voice1= stream.Voice()
voice2= stream.Voice()

notes= ["C4","D4",'E4','F4','G4','A4','B4','C5'] 
for notenames in notes:
    melody_note= note.Note(notenames)
    voice1.append(melody_note)

    harmony=melody_note.transpose(+12)
    voice2.append(harmony)
part.append([voice1,voice2])
s.insert(0,part)

The result of this code prints a music21 fragment with 4 empty meters.

**Comment by mscuthbert** [comment]
Please post to music21list for more help. This is for bugs obky. Please read the tutorials for proper stream formatting.

**Comment by Junny13** [comment]
So is the code correct or not? Cause if the code is correct then there is
an actual bug

Στις Δευ, 9 Σεπ 2024, 02:03 ο χρήστης Michael Scott Asato Cuthbert <
***@***.***> έγραψε:
