### ISSUE TITLE
show() throws TypeError: stat: can't specify None for path argument in jupyter notebook on ubuntu 16.04

### ISSUE THREAD

**Issue by davidthewatson** [cuthbertLab/music21#173]
I'm trying to run the following code from the music21 site using python 3.5 and jupyter notebook. I have matplotlib and numpy and scipy installed. But when I run the following:

    from music21 import *
    converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#").show()

I get TypeError: stat: can't specify None for path argument:

    TypeError                                 Traceback (most recent call last)
    <ipython-input-10-f5206fee4cb5> in <module>()
          1 from music21 import *
    ----> 2 converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#").show()

    /home/watson/.virtualenvs/muzak/lib/python3.5/site-packages/music21/base.py in show(self, fmt, app, **keywords)
       2374                                  app=app,
       2375                                  subformats=subformats,
    -> 2376                                  **keywords)
       2377 
       2378     #--------------------------------------------------------------------------

    /home/watson/.virtualenvs/muzak/lib/python3.5/site-packages/music21/converter/subConverters.py in show(self, obj, fmt, app, subformats, **keywords)
        277 
        278         if 'Opus' not in obj.classes:
    --> 279             fp = helperSubConverter.write(obj, helperFormat, subformats=helperSubformats)
        280 
        281             defaults.title = savedDefaultTitle

    /home/watson/.virtualenvs/muzak/lib/python3.5/site-packages/music21/converter/subConverters.py in write(self, obj, fmt, fp, subformats, **keywords)
        713 
        714         if subformats is not None and 'png' in subformats:
    --> 715             fp = self.runThroughMusescore(fp, **keywords)
        716         return fp
        717 

    /home/watson/.virtualenvs/muzak/lib/python3.5/site-packages/music21/converter/subConverters.py in runThroughMusescore(self, fp, **keywords)
        660         if musescorePath == "":
        661             raise SubConverterException("To create PNG files directly from MusicXML you need to download MuseScore")
    --> 662         elif not os.path.exists(musescorePath):
        663             raise SubConverterException("Cannot find a path to the 'mscore' file at %s -- download MuseScore" % musescorePath)
        664 

    /home/watson/.virtualenvs/muzak/lib/python3.5/genericpath.py in exists(path)
         17     """Test whether a path exists.  Returns False for broken symbolic links"""
         18     try:
    ---> 19         os.stat(path)
         20     except OSError:
         21         return False

    TypeError: stat: can't specify None for path argument

Any ideas? Thanks!

**Comment by mscuthbert** [comment]
Do you have MuseScore installed?

**Comment by mscuthbert** [comment]
The particular stat bug should be gone in v3.

**Comment by mscuthbert** [comment]
Close on inactivity.
