### ISSUE TITLE
MEI should put instruments in the same place in Stream as MusicXML

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#185]
See #140 

MEI places instruments in a different part of the Score hierarchy as MusicXML -- should be the same (easier to change MEI probably).

Mind if I assign you, @crantila ?

**Comment by crantila** [comment]
Yes, I can do this. In September I hope to dedicate some time to cleaning up the `mei` module a bit, so I'll start here!

**Comment by mscuthbert** [comment]
Thanks Christopher! You're great!

**Comment by mscuthbert** [comment]
Hi @crantila -- does it look like there'll be time to hit this anytime soon, or should I close this as an enhancement that's not active.  Thanks!

**Comment by crantila** [comment]
Hmm... this has been in the back of my mind since last August...

Sorry to say, but it doesn't seem too likely I'll be able to fix it soon, especially considering there haven't been too many problems as a result—at least not as far as I know!

**Comment by mscuthbert** [comment]
Okay -- I'll close for "low-activity" since I try to keep the "issues" list to be things that must be fixed or are actively being worked on, but feel free to reopen if you ever have the time.  Thanks!
