### ISSUE TITLE
Invalid harmony.ChordSymbol() behavior with sus|aug

### ISSUE THREAD

**Issue by Atorich** [cuthbertLab/music21#197]
When i tried to ignore #196 then I have the next bug:
With `harmony.ChordSymbol('A7sus4')` it generates weird notes: `['A1', 'G#3']`

**Comment by mscuthbert** [comment]
I don't think that A7sus4 is in our chord database.  It'd need to be an enhancement to add it.  (w/ a citation from a theory text of what it would mean).  Thanks!

**Comment by Atorich** [comment]
I have tried to make some enhancements but it needs to go more deeper to understand the algorithm of ChordSymbol creation that I supposed before :/

**Comment by Atorich** [comment]
Is there (undocumented, maybe) a way to alter A7 to A7sus4 (change step from 3 to 4) or A7sus2 (3 -> 2) ?

**Comment by Atorich** [comment]
I'm sorry @mscuthbert for disturbing again about this but is there a way to get ```7th suspended``` chords with few casualties?

**Comment by mscuthbert** [comment]
Can you provide a citation from a theory text about what this would mean.  Thanks!

**Comment by Atorich** [comment]
I don't fluent enough in music theory to provide that. But A7sus2 & A7sus4 chords are used in guitar playing. I tried to developed yet another chords generator last year using music21 but I had some issues with this type of chords.

**Comment by mscuthbert** [comment]
There are ways to add custom chord names to music21's Harmony dictionary -- look at the docs there.  That's the way you'll need to add these chords.  I'm afraid that without citations from the literature, we don't add anything to music21; it's the only way to ensure that a chord that means one thing to person X isn't meaning another thing to someone who plays in a different style or instrument.

**Comment by Atorich** [comment]
It is not literature, but 
piano:
https://www.google.ru/search?newwindow=1&q=piano+asus7&oq=piano+asus7&gs_l=psy-ab.3...5558.5957.0.6155.5.5.0.0.0.0.189.189.0j1.1.0....0...1.1.64.psy-ab..5.0.0....0.wOZXrHIILLs

guitar:
https://www.google.ru/search?newwindow=1&q=guitar+asus7&oq=guitar+asus7&gs_l=psy-ab.3..0i7i10i30k1j0i30k1j0i8i30k1j0i8i13i30k1.59193.61657.0.61943.13.12.0.0.0.0.266.1328.0j8j1.9.0....0...1.1.64.psy-ab..6.4.584...0i8i13i10i30k1j0i7i30k1j0i7i5i10i30k1j0i7i5i30k1.0.JxwtulEwv94

What literature proof do you mean?

A7sus4 it is just A7 (A C# E G) with alteration on 3rd: (A C## E G) or (A D E G), isn't it?

**Comment by Ghadjeres** [comment]
Hi,
I'm having the exact same issue.
Also, adding this chord to the CHORD_TYPES list is not working.
```
music21.harmony.addNewChordSymbol(
		'seventh-suspended-fourth', '1,4,5,-7', ['7sus4', '7sus'])
chord = music21.chord.Chord(['C4', 'F4', 'G4'])
chord_symbol = music21.harmony.chordSymbolFromChord(chord)
print(chord_symbol)
# <music21.harmony.ChordSymbol Csus>
chord = music21.chord.Chord(['C4', 'F4', 'G4', 'B-4'])
chord_symbol = music21.harmony.chordSymbolFromChord(chord)
print(chord_symbol)
#   File "music21/harmony.py", line 1826, in _parseFigure
# if int(justints) > 20: # MSC: what is this doing?
# ValueError: invalid literal for int() with base 10: 'hordSym'
```
On the importance of this chord, see for instance
https://en.wikipedia.org/wiki/Suspended_chord
It is a chord often used in Schubert's works. It is just a 5 4 chord as in Bach's works but where the minor seventh is played at the same time. It resolves to a dominant seventh chord.

**Comment by xhevahir** [comment]
I see 7sus4 was added to the chord dictionary quite a while ago, but after following the steps in Ghadjeres' previous comment, I'm getting 'Chord Symbol Cannot Be Identified."
