### ISSUE TITLE
Note doesn't keep accidental key when transposed

### ISSUE THREAD

**Issue by Atorich** [cuthbertLab/music21#198]
Is this ok?

```
>>> from music21 import note
>>> Ab = note.Note('A-')
>>> Ab
<music21.note.Note A->
>>> Ab.transpose(24)
<music21.note.Note G#>
```

Why G# instead of A-?

**Comment by mscuthbert** [comment]
Yes. This is acceptable. By transposing 24 semitones you are telling the program that spelling does not matter. If you want to keep the spelling then transpose P15 (=P8 twice)

**Comment by Atorich** [comment]
Thank you!

**Comment by mscuthbert** [comment]
you're welcome.

btw -- fastest still would be:

import copy
AbHigh = copy.deepcopy(Ab)
AbHigh.pitch.octave += 2

(or omit the copy statement if you want to alter Ab directly)
