### ISSUE TITLE
ABC parsing: Double repeat swallows preceding note?

### ISSUE THREAD

**Issue by cls0** [cuthbertLab/music21#202]
I'm not sure why, but (current repo version, Ubuntu) the ABC notation `::` seems to swallow an immediately preceding alphabetic character which should provide a note, so the following two files parse differently in the sense that the Stream contains different notes.

Correct parse result:
```
X:40
T:Kerry Jig, The
R:jig
M:6/8
L:1/8
K:G 
BAB AGE|DB,D EDB,|G,B,D GBd|edB AGA|
BAB AGE|DB,D EDB,|G,B,D EDE|FEF G2 A ::
BAB dBG|cAB cdc|BAB dBd|edB AGA|
BAB AGE|DB,D EDB,|G,B,D EDE|FEF G2 A:|
```

Missing the A before the double repeat (note the absent space by the `::`):
```
X:40
T:Kerry Jig, The
R:jig
M:6/8
L:1/8
K:G 
BAB AGE|DB,D EDB,|G,B,D GBd|edB AGA|
BAB AGE|DB,D EDB,|G,B,D EDE|FEF G2 A::
BAB dBG|cAB cdc|BAB dBd|edB AGA|
BAB AGE|DB,D EDB,|G,B,D EDE|FEF G2 A:|
```

**Comment by mscuthbert** [comment]
Thanks.  Can you reduce this to a minimum example that causes the problem; I'm going to need to step letter by letter through the parser to make sure that I have the fix right.  So if it can be just a few notes long then I'll get in a patch.  Tahnks!

**Comment by mscuthbert** [comment]
Pinging on if this is important to you.  thanks!

**Comment by mscuthbert** [comment]
Closing for now -- feel free to reopen later when a minimum example appears.

**Comment by mscuthbert** [comment]
Feel free to reopen with a minimum example.
