### ISSUE TITLE
Python 2.7 unicode translation error

### ISSUE THREAD

**Issue by PeterMitrano** [cuthbertLab/music21#208]
Trying to import the following score I made in musescore, then show it again gives and error.

Brief error:

```
/opt/miniconda2/envs/magenta/lib/python2.7/site-packages/music21/musicxml/m21ToXml.pyc in instrumentToXmlScoreInstrument(self, i)
   1986         mxScoreInstrument.set('id', str(i.instrumentId))
   1987         mxInstrumentName = SubElement(mxScoreInstrument, 'instrument-name')
-> 1988         mxInstrumentName.text = str(i.instrumentName)
   1989         if i.instrumentAbbreviation is not None:
   1990             mxInstrumentAbbreviation = SubElement(mxScoreInstrument, 'instrument-abbreviation')

UnicodeEncodeError: 'ascii' codec can't encode character u'\u266d' in position 1: ordinal not in range(128)

```

Full error stack here: (https://gist.github.com/PeterMitrano/3cbcef0e06e4a233bc8b97a8e7fdd7dd)[https://gist.github.com/PeterMitrano/3cbcef0e06e4a233bc8b97a8e7fdd7dd]

To reproduce, download the attached zip, pick either the xml or the mid file and parse it. then try showing it (I'm using musescore to show it).
[backing.zip](https://github.com/cuthbertLab/music21/files/786332/backing.zip)
```
import music21

stream = music21.converter.prase('backing_ii-V-I-vi_1.xml')
stream.show()
```

**Comment by mscuthbert** [comment]
And this is why music21 will become python 3 only soon. Please reduce the MusicXML or MIDI file to the smallest snippet that causes the error if you want it investigated. Is it an instrument name, a lyric, etc.? Does the input MusicXML correspond to the specification? (I.e. What program made it and can it be trusted?) thanks!

**Comment by PeterMitrano** [comment]
Working on minimizing the example. For what it's worth, I'm only using
Python 2 because Google's Magenta isn't on 3 yet.

**Comment by mscuthbert** [comment]
since Magenta now supports Py3 and the newest music21 v.5. only supports Py3, I'm afraid the bug is superseded by events.  I'll take a patch for older versions if you want to patch them, but otherwise closing.  Thanks!
