### ISSUE TITLE
MusicXML PNG: explanation of Environment Keys

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#21]
When outputting to PNG, I get the ``EnvironmentException`` raised in ``environment.py:L685``. It's because there's no ``environmentKey`` set for ``"musicxml.png"``. That's easy to solve by inserting an ``"elif"`` clause around line 648.

For that matter, I'm not clear why there's a ``"musicxml.png"`` format at all, and especially why LilyPond outputs to that format. A few comments around ``common.fileExtensions`` (lines 32 to 57) would be helpful for that reason. Maybe a brief description of how music21 uses each format.

I wondered which environment setting it should use---probably ``graphicsPath``? Maybe, but I have ``graphicsPath`` set to "gimp" so maybe at some point something said it should be a graphics editing application? The environment module's documentation doesn't say what any of the settings are for, so it's hard to know.

**Comment by mscuthbert** [comment]
I'm following the Enhancement model suggested at http://brianegranger.com/?p=249 -- closing the issue here; if others believe it is important, they can reopen the issue.
