### ISSUE TITLE
lilypond SVG output is fixed to A4

### ISSUE THREAD

**Issue by TLATER** [cuthbertLab/music21#210]
Perhaps I'm missing something, but I cannot find a way to change the size of SVGs created by `stream.write("lily.svg")`.

This seems to be a default setting in lilypond, however sometimes having non-A4 output may be useful - especially for SVG output, since this format is usually embedded in websites.

**Comment by mscuthbert** [comment]
Hi, there's no support for \paper settings from music21, so the default is always the lilypond default.  Since lilypond output is not anywhere close to complete, it'd probably take a pull request or a funded contribution to get motion on this issue.

**Comment by mscuthbert** [comment]
closing on no movement -- happy to reopen if someone submits a patch.
