### ISSUE TITLE
abcFormat mid-tune change of key treated as chords

### ISSUE THREAD

**Issue by saber47** [cuthbertLab/music21#213]
I have an abc format file that use square bracket to change key in mid-tune. When I tried to parse it using `converter.parse`, the converter will recognize it as an `ABCChord` object. I then looked at the source code, apparently abcFormat.tokenize will read any token that starts with '[' as an `ABCChord`:
This is from `music21/abcFormat/__init__.py`

            # get chords
            if (c == '['):
                j = currentIndex + 1
                while (j < lastIndex and strSrc[j] not in ']'):
                    j += 1
                j += 1 # need character that caused break
                # prepend chord symbol
                if activeChordSymbol != '':
                    collect = activeChordSymbol+strSrc[currentIndex:j]
                    activeChordSymbol = '' # reset
                else:
                    collect = strSrc[currentIndex:j]
                #environLocal.printDebug(['got chord:', repr(collect)])
                self._tokens.append(ABCChord(collect))
                skipAhead = j - (currentIndex + 1)
                continue

Is there any way for `abcFormat` to support inline square bracket mid-tune change like '[K:C]'? For reference, I'm on Windows 10 using python 3.5 with latest version of music21-3.1.0
Thanks

**Comment by mscuthbert** [comment]
Hi -- you've definitely isolated the correct place in the code; I don't think that this will happen any time soon unless it's funded [(Funding Link)](http://web.mit.edu/music21/doc/about/faq.html#consulting) but next time I have a student looking for a project I'll consider it strongly.

**Comment by dvdrndlph** [comment]
Okay, I just got burned on this (again). So I am going to take a crack at fixing it.

**Comment by dvdrndlph** [comment]
My plan is to leverage a slightly modified version of Wim Vree's abc2xml utility to music21 for all abc 2.x usage. The idea is simply to transform any newer abc into MusicXML and use the music21 xml transformer to ingest the content. This seems to be working fine for me as a preprocessing step, and it handles the inline key changes described here just fine. It also attends to "octave" modifiers in "V:" and "K:" fields that are also being ignored (even when not inlined).

The current abc2xml Python code will probably make your linter cough up blood. It uses globals in a way I really dislike, which betrays its roots as a command-line tool.

What do you think of this approach?

**Comment by dvdrndlph** [comment]
I am not sure how best to integrate this unobtrusively. I started hacking on the converter.parse() and converter.parseData() functions to take a "via_xml" argument. This way abc strings representing only one tune can be transformed to an xml string and then handed off to the musicxml subconverter.

The only other idea I have is to hack up abcFormat (and its inherited method) to leverage its own musicxml subconverter.

Do you have any suggestions?

Also, abc2xml cannot produce opus files, so we would have to add such functionality to abc2xml. This shouldn't be too difficult.

**Comment by dvdrndlph** [comment]
It does not seem the Opus in MusicXML is much used. I am not even sure it is supported by the MusicXML subconverter. So this complicates the one-to-one correspondence I was envisioning. Given a multi-tune abc file, I would need to run multiple MusicXML conversions and aggregate them into a music21 Opus. This would be a bigger hack best left for another day.

**Comment by mscuthbert** [comment]
Hi -- I won't be including abc2xml as part of the dependency tree for music21.

**Comment by dvdrndlph** [comment]
What does it mean to be part of the dependency tree? Do you not incorporate forks of other projects in music21 as a matter of policy?

**Comment by dvdrndlph** [comment]
It seems I should move the LGPL abc2xml and xml2abc (for output) directories under music21/ext/. Is this not correct?

Do you object to the hacky way I have shoehorned abc2xml into converter.parse()?

**Comment by dvdrndlph** [comment]
Issue #409 has been closed with this comment: "I'm not interested in needing to maintain another person's code in order to do something built into music21." From this, I assume my approach here is similarly unpalatable, if not downright nauseating. Is this correct?

I do disagree with the "[not invented here](https://en.wikipedia.org/wiki/Not_invented_here)" rationale provided. I think what I am proposing is more in the spirit of "leveraging another person's code in order to do something that music21 cannot do" (or at least cannot do well). Granted, my integration here is inelegant. But in principle, I think music21 should be open to incorporating other open source code.
