### ISSUE TITLE
Incorrectly calculated note offsets (due to wrong duration of full-measure rests?)

### ISSUE THREAD

**Issue by maxalbert** [cuthbertLab/music21#214]
I have a bunch of MusicXML files (exported from Sibelius) containing two-part vocal music. See following image for an example.

<img width="400" alt="sample" src="https://cloud.githubusercontent.com/assets/2692805/24333102/79ee0d4a-124a-11e7-880c-b30adba29954.png">

I'd like to calculate the offset of notes relative the beginning of the piece. Unfortunately, this gives wrong results for notes in the lower part, presumably because the durations of full-measure rests are calculated incorrectly.

Example: the offset of the first note in measure 4 should be 43.0 because the previous three measures have the following quarter durations: 19 + 12 + 12 = 43.

However, music21 reports the offset of that note as 35.0:
```
>>> import music21
>>> s = music21.converter.parseFile('sample_piece.xml')
>>> tenor = s.parts[1]
>>> second_tenor_note = tenor.flat.notes[1]
>>> print(second_tenor_note.getOffsetInHierarchy(s))
35.0
```

Inspecting the .xml file, my best guess is that this happens because the second and third measure are notated using a rest of type 'breve', so the quarter duration of these rests is assumed to be 8. However, since they are full-measure rests their duration should be the duration of the measure itself, which is 12 in both cases. Here is the relevant part of the .xml file:

```
   <part id='P2'>
     <measure number='1'>
     [...]
     </measure>
     <measure number='2'>
        <print new-system='yes'/>
        <attributes>
           <time>
              <beats>24</beats>
              <beat-type>8</beat-type>
           </time>
         </attributes>
         <note>
            <rest measure='yes'/>
            <duration>9216</duration>
            <voice>1</voice>
            <type>breve</type>
         </note>
      </measure>
      <measure number='3'>
         <note>
            <rest measure='yes'/>
            <duration>9216</duration>
            <voice>1</voice>
            <type>breve</type>
         </note>
       </measure>
       [...]
   </part>
```

Is this a bug in `music21`, or is there something wrong with the exported MusicXML format?

Is there currently any workaround for computing the correct note offsets? Many thanks for any pointers!

**Comment by mscuthbert** [comment]
What is the most recent "divisions" tag? I wouldn't be surprised if there was either a music21 or a Sibelius bug here and the divisions number will say which it is. :-)

**Comment by maxalbert** [comment]
By "most recent", do you mean the one immediately preceding the `<measure>` tags I quoted above?

In that case, it's `<divisions>768</divisions>`.

Here is the full XML code snippet of the lower part for the first four bars (up to the first note in measure 4).


```
<part id='P2'>
   <measure number='1'>
      <print>
         <system-layout>
            <system-margins>
               <left-margin>21.875</left-margin>
               <right-margin>0</right-margin>
            </system-margins>
            <top-system-distance>200</top-system-distance>
         </system-layout>
      </print>
      <attributes>
         <divisions>768</divisions>
         <key>
            <fifths>0</fifths>
            <mode>major</mode>
         </key>
         <time>
            <beats>19</beats>
            <beat-type>4</beat-type>
         </time>
         <clef>
            <sign>C</sign>
            <line>4</line>
         </clef>
      </attributes>
      <note>
         <pitch>
            <step>F</step>
            <octave>3</octave>
         </pitch>
         <duration>768</duration>
         <voice>1</voice>
         <type>quarter</type>
         <lyric number='1' name='verse' default-y='-80'>
            <syllabic>single</syllabic>
            <text>Be</text>
         </lyric>
      </note>
      <note>
         <rest/>
         <duration>6144</duration>
         <voice>1</voice>
         <type>breve</type>
      </note>
      <note>
         <rest/>
         <duration>6144</duration>
         <voice>1</voice>
         <type>breve</type>
      </note>
      <note>
         <rest/>
         <duration>1536</duration>
         <voice>1</voice>
         <type>half</type>
      </note>
   </measure>
<!--=========================================================-->
   <measure number='2'>
      <print new-system='yes'/>
      <attributes>
         <time>
            <beats>24</beats>
            <beat-type>8</beat-type>
         </time>
      </attributes>
      <note>
         <rest measure='yes'/>
         <duration>9216</duration>
         <voice>1</voice>
         <type>breve</type>
      </note>
   </measure>
<!--=========================================================-->
   <measure number='3'>
      <note>
         <rest measure='yes'/>
         <duration>9216</duration>
         <voice>1</voice>
         <type>breve</type>
      </note>
   </measure>
<!--=========================================================-->
   <measure number='4'>
      <print new-system='yes'/>
      <attributes>
         <time>
            <beats>45</beats>
            <beat-type>4</beat-type>
         </time>
      </attributes>
      <note>
         <pitch>
            <step>F</step>
            <octave>3</octave>
         </pitch>
         <duration>768</duration>
         <voice>1</voice>
         <type>quarter</type>
         <notehead parentheses='yes'>normal</notehead>
      </note>
```

**Comment by maxalbert** [comment]
In fact, I just realised that the measure durations themselves are also calculated incorrectly (the second number should be 12.0 instead of 8.0):
```
>>> upper_part = s.parts[0]
>>> lower_part = s.parts[1]
>>> print(upper_part.measure(2).quarterLength)
12.0
>>> print(lower_part.measure(2).quarterLength)
8.0
```

**Comment by mscuthbert** [comment]
The divisions number is set correctly so it's a music21 bug, not Sibelius. I'm out of the country with family until April 3 but I will look at this again then esp with a prod!

**Comment by maxalbert** [comment]
Many thanks!

**Comment by mscuthbert** [comment]
Hi!  I'm finally finding time to return to this and having a bit of trouble reproducing it from the snippet.  Would you mind making a minimal MusicXML file from Sibelius (as close to the fewest measures/notes possible) that still has the problem, and attaching it as a comment here. Thanks!

**Comment by maxalbert** [comment]
Thank you Mike!

Here is a [heavily redacted version](https://github.com/cuthbertLab/music21/files/938837/sample_piece_redacted.txt) of the original .xml file which still exposes the bug. (I had to change the suffix to .txt because Github wouldn't let me upload it as .xml)

I removed all measures except the first four, and have removed most notes from these measures, too (altering the time signatures accordingly).

If you run the code snippet from my post above on this .xml file, the output is 21.0 for the offset of the first note in bar 4 of the lower part. However, it should be 8.0 because the first bar has quarter duration 5.0 and the second and third bar both have quarter duration 1.5.

The key thing seems to be that `music21` doesn't honour the `<rest measure='yes'/>` tags in measures 2 and 3 in the lower part?

Here is a screenshot of the redacted file generated from MuseScore. (Not sure why MuseScore seems to add "ghost" rests in the second and third measure, I can't see them in the .xml file.)
<img width="400" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2692805/25205352/fda5022a-2559-11e7-87d9-c7b8527605bb.png">

**Comment by mscuthbert** [comment]
My guess is that the change of time signature to 24/8 might be the problem.  I'll see what happens if the time signature is also 3/8 -- does Sibelius require the different time signatures?  Sibelius might decide that in all cases a measure represents an equal length of time -- in music21 we haven't decided that this is necessarily the case, but I'll investigate whether this should be true.  In any case, I think that the correct representation for the 'note' object should be a duration of 1152, which would be 1.5 quarter notes.  But there may be a way of doing this the way you'd like easily, even if this doesn't become the default for musicxml parsing.

**Comment by maxalbert** [comment]
Argh, sorry! In my attempt to make the sample file as small as possible I edited it manually and forgot to make all required changes to make the time signatures and durations consistent.

In particular, as you correctly pointed out, I forgot to change the time signature in the second measure of the bottom part to 3/8, and also forgot to adapt the durations of the full-measure rests in those measures (which should indeed be 1152).

Here is the (hopefully) [correct version](https://github.com/cuthbertLab/music21/files/943835/sample_piece_redacted_v2.txt) of the MusicXML file; also see corrected screenshot below.

If you run the sample Python code on this new file it turns out that `music21` still reports the offset of the last note in the bottom part as 21.0 - even though the durations of the full-measure rests have now been altered. As far as I can see this is because it ignores the actual durations of both full-measure rests and simply treats them as "breve" rests (which is what it says in the XML file), assuming that a breve rest has a duration of two whole notes (8.0 = 2 x 4.0).

<img width="400" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2692805/25237735/68edc3c6-25e3-11e7-9f0f-3b3b9abae728.png">

**Comment by mscuthbert** [comment]
Great!  Now this is something music21 should definitely do the right thing for.  I'll give it a look -- now I know where to look for the bug -- I think there's a two-step fix -- first have the full-measure rest import as a dotted-quarter rest; and then have it make it a breve-worth-1.5-quarter-notes.  The first one I think I can get in by the weekend; the second might have larger consequences so it might take a few more weeks for testing.

I'm super curious what you're inputting.  :-)

**Comment by mscuthbert** [comment]
Sorry to be slow on this.  Still working on it.

**Comment by mscuthbert** [comment]
Fixed -- the breve rest was indeed the culprit -- the fix turned out not to be too hard, but the consequences and what it revealed about our problems with full measure rests ended up being more difficult to fix.  Thank you so much for your patience, @maxalbert ! And good luck with the project!
