### ISSUE TITLE
Inserting parts with offset don't working

### ISSUE THREAD

**Issue by pabloriera** [cuthbertLab/music21#215]
Hi, I can't get two parts to be played contiguously

```
s = music21.stream.Score()
s.insertAndShift(0,part0)
s.insertAndShift(4,part1)
music21.midi.realtime.StreamPlayer(s).play()
```

if I plot the s score, I can see the parts in order, but when played they sound at the same time.

**Comment by mscuthbert** [comment]
Parts can't follow each other in most cases -- instead take the measures out of the parts and append them to the first part and put that in the score..

**Comment by pabloriera** [comment]
Ok, I tried to append a part into another part, and it worked, but I couldn't make the tempo right. The situation I have for example is that you have a small score, and I want to make a new score that plays 2 times the first score. This is the kind of score I have (flatted)

score.flat.elements

(<music21.instrument.Instrument Piano>,
 <music21.tempo.MetronomeMark larghetto Quarter=60>,
 <music21.note.Note C>,
 <music21.note.Note C>,
 <music21.note.Note F>)

how could I manage to have repetition like doing 

newscore = [score,score]

Thanks!
