### ISSUE TITLE
How to contribute to documentation?

### ISSUE THREAD

**Issue by andrewsanchez** [cuthbertLab/music21#218]
I'm wondering about how I can best contribute to documentation.

Running `python documentation/make.py` from my local fork produces an error, since it can't import music21.  However, I don't believe it should be necessary to build the documentation in order to edit the source files which the .html docs are being built from.

So for example, I wanted to correct the spelling error found here:  http://web.mit.edu/music21/doc/tutorials/examples.html

"excuding repeated notes" should be "excluding repeated notes"

Am I correct that http://web.mit.edu/music21/doc/tutorials/examples.html is built from `documentation/source/tutorials/examples.ipynb`, and that therefore, the best way to correct that spelling error is to simply edit `documentation/source/tutorials/examples.ipynb` directly ?

**Comment by mscuthbert** [comment]
Hi Andrew -- Thanks for being willing to contribute!  Indeed, the most work needs to be done on the Jupyter notebook (.ipynb) files, but you'll need Jupyter to work on them.  

See the (newly updated and corrected):
http://web.mit.edu/music21/doc/developerReference/documenting.html

**Comment by andrewsanchez** [comment]
Hi @mscuthbert !  I haven't read the link you provided yet, but after following instructions here:  https://python-packaging-user-guide.readthedocs.io/installing/#installing-from-vcs

I am now able to edit .ipynb files, rebuild documentation, and see the results.  The only caveat I can think of at this point is to be careful what I commit, as saving .ipynb files results in additional sneaky changes to the .ipynb files aside from what I explicitly change.  I guess it might be better to edit the .ipynb files directly instead of via the jupyter notebook interface in my browser, after I identify the changes I want to make, at least in the case of minor spelling corrections, etc.

**Comment by mscuthbert** [comment]
please don't edit directly and instead use the instructions there.  If edited directly, then the files are no longer considered trusted and won't run.

**Comment by mscuthbert** [comment]
In the newest git version, Documentation is moved out of music21/ directory to the root folder -- this way we can reduce the file size of the .tar.gz by 80%

**Comment by andrewsanchez** [comment]
`python  documentation/make.py` did not work for me on macOS 10.13.5.

I finally got it to work like this, from within the documentation directory:

```  bash
mkdir -p html build/html
cp -r cp -r source/ html/
python make.py html build/html/
```

Also, regarding
> please don't edit directly and instead use the instructions there. If edited directly, then the files are no longer considered trusted and won't run.

The problem with this is that if a committer's environment is not identical to the environment expected by the build tools in this repo, there's a chance that the commit will end up with undesirable changes like this:

```
-   "version": "3.6.2"
+   "version": "3.6.3"
```

It might be good to create a CONTRIBUTING file with detailed instructions for creating an environment that will eliminate this, allowing people to contribute by editing the notebooks without worrying about this.  Conda makes this super easy.

**Comment by mscuthbert** [comment]
`python documentation/make.py did not work for me on macOS 10.13.5.`

I'm going to need more information than this to see what the problem to be fixed is.

If you edit the files directly, they will just be overwritten the next time though.  Having a changed version number in the source directory is no big deal.

**Comment by mscuthbert** [comment]
ah, it's an issue with newer versions of sphinx.

**Comment by mscuthbert** [comment]
Sphinx changed their commands for building in v 1.7.1 and this version wasn't compatible.  There's nothing that a contributing document would do to change this since it wasn't known.
