### ISSUE TITLE
Tracking Bug for "the lilypondFormat is not yet consulted"

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#22]
As of svn revision 3647...

The TODO in ``base.py:L3439`` ("the lilypondFormat is not yet consulted").

This is a tracking bug, to help interested parties know when the task is finished, or to encourage community members to contribute a fix.

**Comment by mscuthbert** [comment]
any progress on this? I'm trying to close issues that are not vital so that the (small) team can focus more on ones that have large community interest.  Thanks!

**Comment by crantila** [comment]
It looks like this was fixed at some point in May 2014 with the switch to SubConverter objects, but nobody noticed. All three subformats work for me (PDF, PNG, and SVG).

Issues #24 and #25, although they refer to obsolete code that no longer exists, do refer to a standing issue.

**Comment by mscuthbert** [comment]
thanks.  SVG was a patch and had a separate bug.
