### ISSUE TITLE
An error occurred as follow when I load a midi file, how can I get measures object from midi file?

### ISSUE THREAD

**Issue by handsomeyewenhao** [cuthbertLab/music21#221]
m = converter.parse('C:/Users/Administrator/Desktop/mozart/kv_172_2.mid')
ka = analysis.floatingKey.KeyAnalyzer(m)
Error:music21.analysis.floatingKey.FloatingKeyException: Stream must have Measures inside it

**Comment by mscuthbert** [comment]
Hi -- this board is for reporting bugs in the system -- for Qs on how to do a particular task, please ask on the mailing list (googlegroups music21list).  Thanks!
