### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'append'

### ISSUE THREAD

**Issue by p-himik** [cuthbertLab/music21#222]
Relevant part of the stack trace:
```
   chord = MeasureParser().xmlToChordSymbol(xml_element)
  File "/app/.heroku/python/lib/python3.5/site-packages/music21/musicxml/xmlToM21.py", line 3336, in xmlToChordSymbol
    cs._updatePitches()
  File "/app/.heroku/python/lib/python3.5/site-packages/music21/harmony.py", line 1899, in _updatePitches
    pitches.append(self._bass)
AttributeError: 'tuple' object has no attribute 'append'
```

In file `harmony.py`, there are lines:
```python
        pitches = self._adjustOctaves(pitches)

        if self._root.name != self._bass.name:

            inversionNum = self.inversion()
        
            if not self.inversionIsValid(inversionNum):
                #there is a bass, yet no normal inversion was found....must be added note 
            
                inversionNum = None
                self._bass.octave = 2 # arbitrary octave, must be below root, 
                                    # which was arbitrarily chosen as 3 above
                pitches.append(self._bass)
```

The problem here is that `_adjustOctaves` returns a tuple, so calling `pitches.append` is incorrect. I guess `_adjustOctaves` should just return a list - I don't think it will break anything because the method is only used in one place.

**Comment by mscuthbert** [comment]
Thanks for catching this. We should probably modify the Tuple because most places that work with chord pitches expect tuples now. Do you have a minimum xml excerpt that causes the bug to add as a regression test?

**Comment by p-himik** [comment]
Unfortunately, I don't have an example - I don't have enough permissions to view the data, I can access only the logs.
`_updatePitches` can just assign `tuple(pitches)` to `self.pitches` - other functions that use `pitches` inside `_updatePitches` don't care whether it's a list or a tuple.

**Comment by mscuthbert** [comment]
You were right, casting to a list in _adjustOctaves was the better fix.  Thanks!
