### ISSUE TITLE
Environment setup for png conversion without musescore.

### ISSUE THREAD

**Issue by G3zz** [cuthbertLab/music21#225]
Hi, apologies for opening another issue on environment setup...
I am wondering whether anyone can advise the correct environment settings for setting up music21 png conversion without the use of musescore?

Conversion to png using musescore requires an X server (because of a Qt dependency), which is not going to be possible on my machine.  I noticed a reference in the docs that it is possible to setup without musescore, but I can't find any more details.

For reference, I am running a chroot of ubuntu 14.04.  Currently my .music21 rc is pretty empty apart from a pointer to the lilypond binary: `/usr/bin/lilypond`.

Any terminal-only solutions are welcome!  I'd be happy to update the docs with this info.
Thanks,
Geraint

**Comment by mscuthbert** [comment]
output to lilypond .write('lily.png'), but this option might go away soon because it's not well enough supported.  `music21` on linux/BSD/unix I'm afraid isn't supported -- too many variations, with different issues for each.

**Comment by G3zz** [comment]
Thank you for your quick reply - this works nicely without Musescore.  Sorry to hear about the lack of Unix support, but I understand that it's a lot of work.  
Closing.
