### ISSUE TITLE
chordify: addPartNameAsGroup option?

### ISSUE THREAD

**Issue by musicnerd** [cuthbertLab/music21#226]
In Chapter 9 of the User guide, at the bottom of the page it says:
"We will get to the option, addPartNameAsGroup later, which will let you know exactly where each pitch in the chordified Chord comes from."

A quick search through the user guide for "addPartNameAsGroup" doesn't show up anywhere else besides ch.9, and a quick attempt to enter it as an option to chordify returns an 'unexpected keyword' error.

I am exactly trying to get this functionality, and it seems that getContextByClass('Part') returns None, and similarly trying to use contextSites returns None.
Is there any implemented way to return the part location for a given note in a chordify chord object?

**Comment by musicnerd** [comment]
I do see in the chordify documentation, I see that in fact the option is "addPartIdAsGroup". So just a simple text error, there.

However, changing the default to True still doesn't seem to allow me to use getContextByClass('Part') on each note in the chord. (see below for example)

>>>from music21 import converter, stream
>>>pieces = corpus.getComposer('palestrina')
>>>x = converter.parse(pieces[0])
>>>xChords = x.chordify(x, addPartIdAsGroup=True)

>>>for i in xChords.recurse().getElementsByClass('Chord'):
            print(max(i).getContextByClass('Part'))

**Comment by musicnerd** [comment]
I found an answer here: https://groups.google.com/forum/#!searchin/music21list/chordify|sort:relevance/music21list/7caQbG_XrtQ/A2iw44plvXMJ

I guess the problem is that it isn't clear that the method to call would be called ".group". It would be great if this could be added into the documentation for chordify. I know a lot of people doing stuff like Bret for whom this would be really useful.

**Comment by mscuthbert** [comment]
reopening, because the confusing docs are something I need to fix.  thanks!

**Comment by mscuthbert** [comment]
fixed docs -- need more, but at least they're not wrong.
