### ISSUE TITLE
LilyPond Backend Selection Doesn't Work

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#24]
I'm having problems with backend selection. In lily.translate:L182, there's a note: "I had a note that said 2.12 and > should use ``self.backendString = '--formats='`` but doesn't seem true." Indeed that's not true, because output format and backend are distinct. For the if/else statements just above (lines 175--81), the "if self.minorVersion >= 11" statement doesn't make sense because 2.11 was the development series for 2.12, meaning (A) there are probably some 2.11 releases with the old behaviour, and (B) nobody should be using 2.11.x in a production environment anyway.

**Comment by mscuthbert** [comment]
I'm following the Enhancement model suggested at http://brianegranger.com/?p=249 -- closing the issue here; if others believe it is important, they can reopen the issue.
