### ISSUE TITLE
Reference Bugs

### ISSUE THREAD

**Issue by rmattes** [cuthbertLab/music21#240]
Where can we report bugs/problems with the Reference?
For example, http://web.mit.edu/music21/doc/developerReference/buildingDocumentation.html links to https://github.org/cuthbertLab/music21/releases which seems wrong (github.con would be correct afaik).
The build instructions on that page don't work here, I get an ```: No module named 'docbuild'``` error.

**Comment by mscuthbert** [comment]
This is as good a place as any to report.  What is the last thing that you did before getting the error?  Are you on version 4 (release) or higher of music21?

Fixing the buildingDocumentation bug.

**Comment by rmattes** [comment]
I'm on the current git master branch.
I first installed  muisc21 with ```python3 setup.py install``` and then changed to the documentation directory
and ran ```python3 make.py```. This resulted in:
```
Traceback (most recent call last):
  File "make.py", line 12, in <module>
    db.run()
  File "/usr/local/src/music21/documentation/docbuild/make.py", line 47, in run
    self.runBuild()
  File "/usr/local/src/music21/documentation/docbuild/make.py", line 65, in runBuild
    os.mkdir(self.autogenDirectoryPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/documentation/autogenerated'
```

After that I tried to run the code in make.py from ipython but, alas, the same error.

**Comment by mscuthbert** [comment]
Building docs doesn't play very well with the system installation, and it looks like you have two different versions of music21 installed -- one is the developer version (with music21/documentation and music21/music21) and one is the code only (just with the inner music21 directory)  Uninstall the version installed with setup.py in your /usr/local/lib and it should work, but to build documentation you'll probably want to have music21 not installed under /usr but in a development directory of your own (you'll need to set PYTHONPATH to be able to find it).

**Comment by rmattes** [comment]
Thanks. 
Uninstalling the installed version did help to solve the initial problem, but I still encountered errors:
```
/usr/local/src/music21$ python3 documentation/make.py 
Traceback (most recent call last):
  File "documentation/make.py", line 11, in <module>
    db = DocBuilder(runMode)
  File "/usr/local/src/music21/documentation/docbuild/make.py", line 38, in __init__
    self.getPaths()
  File "/usr/local/src/music21/documentation/docbuild/make.py", line 117, in getPaths
    'documentation')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

So, it looks like the documentation build really needs a Python > 3.5
Building with Python3.6 seems to work.
Maybe this is worth documenting.

**Comment by mscuthbert** [comment]
I'll try to make some patches so it works on Py3.4 and up. Since I moved the docs dir not all the tests of it are running. 

Better still -- I'm going to start uploading a gzip of the docs with each release to github so it's easier to download.
