### ISSUE TITLE
Install Raspberry Pi

### ISSUE THREAD

**Issue by gkvoelkl** [cuthbertLab/music21#242]
Hi,

I tried to install Music21 on an Raspberry Pi.

I took the current version on Music21 and Musescore 1.3

When I used the show method I got an error

SubConverterFileIOException: png file of xml not found. Is your file >999 pages?

How to install correctly on Raspberry Pi?

Does Music21 work with Musescore 1.3?

Best Regards

Gerhard

**Comment by mscuthbert** [comment]
I'll bet that there is a way to get it to work and it's designed to work fine, but only Windows and macOS are directly supported platforms.  There's an open pull request that might fix this issue for you, but I can't merge it yet since the last merge broke Mac users, so there need to be tests that it works on Windows and macOS before merging.

**Comment by mscuthbert** [comment]
It's #233.

Btw -- I'd be fascinated to know what Raspberry Pi/music21 project you're working on.

**Comment by gkvoelkl** [comment]
Thanks for the quick answer. I will wait for the next version.

I am using Raspberry Pi as  Jupyter server. Primarily I try to learn music21. 
So I started to make an interactive Jupyter notebook about playing Ukulele.The focus is on the use of the theory of harmony  in pop music

**Comment by rmattes** [comment]
May I ask why you try to use MuseScore 1.3? Version 2.0 was released in 2015 and has way better MusicXML import, 2.1 would even be better.
If learning Music21 is your main goal, why deviate and spend time on a m21-on-raspi project?

**Comment by gkvoelkl** [comment]
I simple did

sudo apt-get install musescore
And version 1.3 was there.

If you have any description how to install 2.0 send it to me

**Comment by rmattes** [comment]
What type of Rasberry do you have? Anything >= version 2 supports armhf binaries, so you can just use the AppImage version from Musecore.org. Go to https://musescore.org/en/download and choose Linux/AppImage/ARM-architectures

**Comment by gkvoelkl** [comment]
Thanks.
So I could install the ne version

The error is the same

SubConverterFileIOException: png file of xml not found. Is your file >999 pages?

**Comment by mscuthbert** [comment]
Hence the mention of the pull request earlier.  It doesn’t work on Mac or PC but seems to work on some *NIX.

**Comment by mscuthbert** [comment]
Closing because nothing more needs to happen specifically for Raspberry PI.  Continue discussion on other PR #233
