### ISSUE TITLE
stream to midi adding rest

### ISSUE THREAD

**Issue by KKONZ** [cuthbertLab/music21#243]
I have downloaded a number of Beethoven Quartet midi files from KunstDerFuge.com and am splitting up the files into smaller chunks to use as training data for a neural network. This code for some reason is adding rests to the beginning of each of the output midi files and I am not sure why or how to avoid adding the rests. Thank you!!

I saw the Google Docs question from Devon that is similar, I tried the suggested logic but am having issues finding anything that works for me so far.

I am also trying to find the section in the MIDI module here in the music21 GitHub repo that adds the rest for Windows Media player/quicktime 7 player midi reads but haven't found anything edgewise at this point.

**Comment by mscuthbert** [comment]
Fixed in #246  -- THANKSS!

**Comment by KKONZ** [comment]
Woo! Exciting! Thank you for bearing through my rookie mistakes. Hope you have a great weekend!!

**Comment by mscuthbert** [comment]
You too!  But I'd rather have an EXCITING weekend where I'm merging lots of great patches like this one!

**Comment by mscuthbert** [comment]
Reopening because the rest is necessary for the javascript MIDI player -- will need to make a fix that also works with http://web.mit.edu/music21/doc/about/what.html  -- see #315

**Comment by KKONZ** [comment]
Thank you for the heads up! I may be misinterpreting dianyo's message after you reverted to #234 but it sounded like the issue he was experiencing was due to some of the chrome extensions he had running. He stated he disabled the extensions and the playback worked correctly. Would it be possible to check if he experiences the issue on #246 now that he has the extensions disabled? It sounded like maybe the issue was not because of the note offset, but the extension. I may have read that incorrectly. The note offset was causing issues when I was trying to write midi files, Devon was having the same issue. I could not find any other work around to that issue than what was pushed through with #246.

**Comment by KKONZ** [comment]
It looks like the commit I made on Sept. 16, 2017 is still committed to the translate.py file. I just switched the parameter default for addStartDelay from True to False. I am guessing that the revert to #234 didn't effect translate.py. Let me know if there is something I am missing something, otherwise this can be closed!

**Comment by mscuthbert** [comment]
yes, I'm keeping it in, but I decided to open this again because I'll leave it alone as a default, but make it so that IPython MIDI defaults to True for addStartDelay, and want to make it a parameter for .show('midi', addStartDelay=True)  -- so it's more of a tracking bug for me, since other IPython-generated files need the parameter.  See for instance, http://web.mit.edu/music21/doc/about/what.html

**Comment by KKONZ** [comment]
Ok, so if I understand correctly you're envisioning that when using .show(), the default will be addStartDelay = False, and .show('midi) will be defaulted to addStartDelay = True? That would make sense to me! [object].show(), in an IPython notebook, was adding a rest to the beginning of the score and offsetting all of the notes when I opened this ticket. So for example if I wanted to parse a midi file that had 1 measure of 4 quarter notes in 4/4 it would show something like a beat of rest then quarter notes on 2, 3, and 4 with an additional measure with a quarter note on the downbeat. 
I'll play around with the code and see if I can adjust the defaults for both cases. I'll open a pull request if I can get something working! Seems like it should be pretty straight forward, hopefully I am not misinterpreting your plan.

**Comment by mscuthbert** [comment]
The MIDI files generated in Jupyter now default to putting the rest in.  Those generated outside Jupyter do not.  Thanks!
