### ISSUE TITLE
wrong normalOrder

### ISSUE THREAD

**Issue by luiselroquero** [cuthbertLab/music21#248]
Hello, this is the code I've tried:

>>> a = chord.Chord([44, 45, 50, 55])
>>> a
<music21.chord.Chord G#2 A2 D3 G3>
>>> a.normalOrder
[2, 3, 4, 9]

It is returning a transposition of the set, not the actual normalOrder which should be [7, 8, 9, 2]

**Comment by luiselroquero** [comment]
It is also happening with this code:

a = chord.Chord([55,62,68,69,72,76])
a
<music21.chord.Chord G3 D4 A-4 A4 C5 E5>
a.normalOrder
[0, 1, 2, 5, 7, 9]

In this case it should return [7, 8, 9, 0, 2, 4]

**Comment by mscuthbert** [comment]
thanks -- looking at it now.  Can you find a 3 element chord that also reproduces the problem?  The diagnosis is easier the fewer elements there are.  Thanks!

**Comment by mscuthbert** [comment]
Smushed this bug -- thanks for noticing.  In the latest github version
