### ISSUE TITLE
runThroughLilyPond() Uses Hardcoded Backend

### ISSUE THREAD

**Issue by crantila** [cuthbertLab/music21#25]
In lily.translate:L2320, the createPNG() method uses a hardcoded "eps" backend, which doesn't make sense to me, since the LilyPond documentation<http://lilypond.org/doc/v2.16/Documentation/usage/command_002dline-usage#advanced-command-line-options-for-lilypond>says "png" output format implies "ps" backend, which makes that seem like a default.[1] Looks like that's because you append all the systems in a single, large image file, but (A) it's unexpected for there to be only one page and for you to change the inter-system spacing, so an admonition in the documentation would be helpful. Also, what about users who prefer the default PNG-format output from LilyPond? This should be the default behaviour, and music21 should optionally append all systems into one file---behaviour that is indeed useful in many situations.

All the calls to runThroughLilyPond() (lines 2298, 2329, 2385) should use the "lilypondBackend" environment setting rather than hardcoded "backend" arguments. If "lilypondBackend" is ignored for some of the output formats (like "png in one file"), this should be noted in the documentation.

**Comment by mscuthbert** [comment]
I'm following the Enhancement model suggested at http://brianegranger.com/?p=249 -- closing the issue here; if others believe it is important, they can reopen the issue.
