### ISSUE TITLE
Keep ChordSymbol on Chordify

### ISSUE THREAD

**Issue by HarkDev** [cuthbertLab/music21#251]
It would be nice if the chordsymbol could be optionally kept on the chordify method.
I could help but can't seem to find where the chordify() method is on the source.

**Comment by mscuthbert** [comment]
Can you give more details about what you're hoping to do and what the current behavior is?  Is there not a custom classes option to Chordify that would do this for you?

**Comment by HarkDev** [comment]
Actually, I if you chordify() the score, you lose the Chord Symbol.
In my case, I'm working on code where I need both, the chord as it is (all the pitches) and the ChordSymbol that comes on the file (MXL).
If you chordify, the chord symbol is lost.

Is it clear enough? If not, let me know and I'll try to explain mor in detail.
Cheers!

**Comment by mscuthbert** [comment]
If you want both the notes and the chord symbols, it's not something we're likely to add to chordify -- best would be to chordify and then put the chord symbols back into the chordified score at the appropriate places.

Best,
Myke

**Comment by HarkDev** [comment]
Although it would be a nice feature,  I can understand it's not in plan.
Thanks
