### ISSUE TITLE
Saving a local corpus fails

### ISSUE THREAD

**Issue by rmattes** [cuthbertLab/music21#255]
I'm trying to create a a local corpus but saving the corpus fails:
```
/usr/local/lib/python3.5/dist-packages/music21-5.0.4a2-py3.5.egg/music21/corpus/corpora.py: WARNING: newCorpus metadata cache: starting processing of paths: 1
/usr/local/lib/python3.5/dist-packages/music21-5.0.4a2-py3.5.egg/music21/corpus/corpora.py: WARNING: cache: filename: /tmp/user/1000/music21/local-newCorpus.p.gz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/music21-5.0.4a2-py3.5.egg/music21/corpus/corpora.py", line 880, in save
    self.cacheMetadata()
  File "/usr/local/lib/python3.5/dist-packages/music21-5.0.4a2-py3.5.egg/music21/corpus/corpora.py", line 202, in cacheMetadata
    verbose=verbose
  File "/usr/local/lib/python3.5/dist-packages/music21-5.0.4a2-py3.5.egg/music21/metadata/bundles.py", line 755, in addFromPaths
    if self.filePath is not None and os.path.exists(self.filePath):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

**Comment by mscuthbert** [comment]
Ah! Thank you! This part of the code doesn't get auto tested so I didn't realize that it needs py3.6 to run. Will fix.

**Comment by rmattes** [comment]
Thank's a lot.

**Comment by mscuthbert** [comment]
Fixed in the latest pull request, I hope!

**Comment by rmattes** [comment]
Yes, thank's a lot. I just finished some tests and the local corpora seem to build fine.
Not completely unrelated: is there any doxumentation on how the metadata is extracted? We need to store some (probably custom) metadata for our corpus items.
I toying with the idea to add RDF data to the musicxml files. But I would need to be able to access this data as metadata from the corpus.

**Comment by mscuthbert** [comment]
Not as much info as I'd like.  Look at the docs for the metadata module, especially the RichMetadata object.
