### ISSUE TITLE
MusicXML Import Problem

### ISSUE THREAD

**Issue by rmattes** [cuthbertLab/music21#257]
When I import a score in musicxml format with ```converter.parse()``` or ```corpus.parse()``` the resulting music stream lacks all fermatae. This is unfortunate since the fermata is needed as a marker to split chorales into segments for further analysis.

**Comment by rmattes** [comment]
My wrong. ```core.show(fmt='txt')``` seems to swallow fermatae but they still show up in the MusicXML export.

**Comment by mscuthbert** [comment]
show('text') only shows the basic info about the elements, not anything that's attached to the notes.
