### ISSUE TITLE
Saving key signatures

### ISSUE THREAD

**Issue by 00sapo** [cuthbertLab/music21#267]
If you set a key signature in stream object and save the score, key signature is note saved.
If stream object is not designed to store key signatures, this should raise an Exception.

```python
>>> t = stream.Stream()
>>> t.append([note.Note('E'), note.Note('C')])
>>> t.keySignature = key.Key('E')
>>> t.write(fp='temp.xml')
>>> s = converter.parse('temp.xml')
>>> t.keySignature is None
False

>>> s.keySignature is None
True

```

**Comment by mscuthbert** [comment]
I think you misunderstand what .write() does -- it converts to a file format.  If you want very good round tripping, use the freezeThaw module instead.  MusicXML does not support storing a generic stream, measure, or Part.  Musicxml only supports scores, so s is a Score object.  See the FAQ about file formats.

**Comment by pconerly** [comment]
@mscuthbert @00sapo I think this is bug #367.  I'm hoping to have a fix this weekend.
