### ISSUE TITLE
Behavior of PitchClassDistributionFeature doesn’t match documentation

### ISSUE THREAD

**Issue by mjwalter** [cuthbertLab/music21#273]
The documentation for the jSymbolic class `PitchClassDistributionFeature` reads as follows:

> A feature array with 12 entries where the first holds the frequency of the bin of the pitch class histogram with the highest frequency, and the following entries holding the successive bins of the histogram, wrapping around if necessary.

This is similar to the original jSymbolic implementation. However, the actual music21 implementation doesn't reorder the array to put the highest-frequency. Furthermore, the music21 implementation normalizes the highest frequency to 1 and expresses the frequencies of the other pitch classes as fractions of that.

(I do not know which other classes, if any, have an implementation that varies from the documentation.)

**Comment by mscuthbert** [comment]
Is still an issue or did the recent pull request address it?

**Comment by mjwalter** [comment]
I'll be making another pull request soon that addresses this!
