### ISSUE TITLE
interval.direction of compositions parsed from kern

### ISSUE THREAD

**Issue by Jicol95** [cuthbertLab/music21#294]
I am encountering an error with interval.direction. When I parse a .krn file and then check the interval direction, sometimes it is wrong. Is this a bug or is it a caveat of the method used to parse .krn files?

**Comment by mscuthbert** [comment]
If you could isolate down to a single case that produces the incorrect intervals, I can look into it.

**Comment by Jicol95** [comment]
I have a krn file for Palestrina's , Missa Assumpta est Maria, for 6 voices. I have the Gloria movement of this piece. I used the converter.parse() function as provided to parse this document. When I tried to get the interval direction, some of the results were incorrect. I have attached the krn file, as this could also be the source of the problem. 
[Example.zip](https://github.com/cuthbertLab/music21/files/1936225/Example.zip)

**Comment by mscuthbert** [comment]
If you can trim down to a single measure in one or two parts, that would help -- it's quite possible that the encoding is wrong or the notes are wrong -- I can't run step through debugging on a whole Palestrina Gloria.  The interval routines are very well tested, so I doubt the problem is there.

**Comment by Jicol95** [comment]
Bar 71, 72 and 73 in the second soprano voice. I see three oblique intervals where Music21 has returned either increasing or decreasing. I think your assumptions might be correct. I have no issues on the Bach four-part chorale dataset.

**Comment by mscuthbert** [comment]
Could you edit the file so that only the lines necessary to reproduce the problem exist?  I'm a bit time constrained on other projects right now, and your doing so will make the debugging time go down to 1/10th what it would take otherwise.  thanks!
