### ISSUE TITLE
Unable to export Stream of notes (with articulations) to PDF

### ISSUE THREAD

**Issue by ifilonenko** [cuthbertLab/music21#296]
I am having trouble doing the following:
```python
def output_pdf_and_mid(file_name, p_q_f_lst):
    s = Stream()
    for (p,q,f) in p_q_f_lst:
        n = note.Note(pitch.Pitch(p),quarterLength=q)
        n.articulations.append((Fingering(f)))
        print(n.articulations)
        s.append(n)
    location = str(s.write("lily.pdf"))
    os.rename(location,'{}.pdf'.format(file_name))
    mf = translate.music21ObjectToMidiFile(s)
    mf.open('{}.mid'.format(file_name), 'wb')
    mf.write()
    mf.close()

output_pdf_and_mid("example", [(60.0,1.0,1),(61.0,2.0,1),(62.0,2.0,3)]
```
Given a `p_q_f_lst` which is a tuple list of (pitch,quarterLength,Fingering) I am hoping to build a stream that I can then convert to `PDF` and into a `MID` file. The problem that I have encountered is that the articulations are being set ( and are visible with a `s.show()`) but aren't included in the MID or PDF. Is there a reason for this? Or how do I get around this. I am looking to include fingerings programmatically. 
@mscuthbert @flexatone

**Comment by mscuthbert** [comment]
Hi -- I think that this is a question more suited to the music21list than this forum.  Sorry for long no reply.
