### ISSUE TITLE
Clear caches before running unit tests

### ISSUE THREAD

**Issue by HalfVoxel** [cuthbertLab/music21#300]
Surprisingly, one of the unit tests started failing on my machine (only a single specific test), while it did succeed on CI. This was checking out the master branch without any changes (commit f348dd8).

It turns out that the issue is caused by the caching that is done with midi files. In this particular test (testImportChordVoiceA) a midi file is loaded from the disk, however if this file is first loaded with a buggy implementation (because one was testing out changes to the system) it will then continue to fail on all later tests even if the buggy implementation is fixed because the midi file load has been cached.

This is a highly unintuitive behavior and makes it really confusing for new users if they want to run the unit tests locally.

The best solution would be to clear the cache directory before the unit tests run.

**Comment by HalfVoxel** [comment]
Having unit tests that do not actually test what they are supposed to test is far far worse than the unit tests being slow imo. That is literally what unit tests are for. If speed is necessary, then having a flag that can be passed to the unit test runner to not clear the cache could perhaps be added. However it really should be explicit when you run the unit tests, the default should enforce correctness.

**Comment by mscuthbert** [comment]
In this case I believe that when a unit test uses "converter.parse()" it is testing what it says it will do, run the normal converter.parse() routine which may or may not have a cached version.  In any case, this is not something I'm open to changing now; if after a few hundred commits throughout all parts of the source code you still feel the behavior should change we can revisit the question.
