### ISSUE TITLE
rU mode is invalid for zipFile in python3.6

### ISSUE THREAD

**Issue by Daikon-Sun** [cuthbertLab/music21#302]
In line 203 in "converter/__init__.py", the zipfile tries to open in mode "rU". However, in python3.6, the mode can only be either "r" or "w". I believe it is because in python "open()" function, there is an argument "newline" that handles universal newline mode.

**Comment by mscuthbert** [comment]
ah -- as far as I know there are now no longer any publicly available musedata files that can be redistributed so we're not testing any of the musedata code anymore.  It'd be helpful to get a patch -- I looked at the new Zipfile docs and they don't really give a clear roadmap for making the transition.  Happy to review a pull request.

**Comment by mscuthbert** [comment]
This gave me the docs:
https://stackoverflow.com/questions/7857225/python-zipfile-module-with-textiowrapper

**Comment by mscuthbert** [comment]
fixed!
