### ISSUE TITLE
Specify no chord symbol

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#309]
Hi,
I'd like to be able to specify in a Score that there is no ChordSymbol occurring during some time interval. Currently, the convention is that a ChordSymbol lasts until a new one is found. Of course, we can always set the duration of a particular ChordSymbol, but that's very fragile, for example, applying a music21.harmony.realizeChordSymbolDurations(piece) would break the durations.
Is there currently any way of doing this?
Otherwise, I was thinking of implementing a special type of "No Chord" or "N.C." ChordSymbol. I believe that should be pretty straightforward, but is there anything special I should look out for?

**Comment by mscuthbert** [comment]
Great idea.  I think that maybe a ChordSymbol subclass called NoChordSymbol would be best?  As a subclass it would still be found with .getElementsByClass(ChordSymbol) but it would have more configuration options.  

I'm not sure what we're currently doing when we parse something from MusicXML with no-chord though... will investigate.

**Comment by a-papadopoulos** [comment]
I've investigated this a bit, at the moment music21 parses them correctly. MusicXML [encodes them with the "none" kind](https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-kind-value.htm), and this is exactly how it gets parsed in music21.
So I was wondering if we shouldn't just keep things like that (kind == "none") instead of having a specific subclass. I'll check that a bit more to verify that this doesn't entail too many special cases that would justify subclassing.

**Comment by mscuthbert** [comment]
Okay, so it seems that the only thing we need to do is make sure docs are clear about how to do this.  Happy to take a documentation edit pull-request.  Thanks!

**Comment by a-papadopoulos** [comment]
Yes the doc will need to be updated (hadn't though about this), but I think there's be some more work. 

For example, parseFigure will need to be able to parse things like 'N.C.' or 'NC' or 'No Chord'. I believe this should make it possible to parse abc with NCs in it (even if that's not standard abc), but that will probably break some parts of the code that check for well-formed figures...

Also, there's little tricks to take care of when exporting back to MusicXML (e.g. hide the root of the chord which is required for all chords in MusicXML including "none" chords).

Anyway, I'll get started and come back with updates.

**Comment by mscuthbert** [comment]
Thanks!  Note that there are two different settings for chord symbols when exported to MusicXML -- one where a representation of the chord is added to the staff as pitches, and one where only the text-symbol is added.  For the case of 'N.C.', 'NC', 'No Chord', or None (should also be allowed), then probably the setting should automatically be changed to not display pitches.

**Comment by a-papadopoulos** [comment]
I came back to this. In the end, subclassing turned out to be a wiser choice, in order to avoid too many special sub-cases.

Just a quick question, I supposed you're talking about the writeAsChord property? In that case I supposed overriding it to always return False is what we need?

**Comment by mscuthbert** [comment]
yep, I think that overwriting it so that it always returns False is best.

**Comment by a-papadopoulos** [comment]
I'm back to this after another absence. I've just encountered some weird behaviour, which might actually not be related to any of this (please tell me if I should move this somewhere else). When exporting to musicxml even the simplest of scores, I get a phantom empty voice in the MusicXML output.
For example, when exporting this:
```python
s = stream.Score()
s.repeatAppend(note.Note('C'), 8)
s = s.makeMeasures()
```
I get this at the start of the second measure:
```xml
<forward>
  <duration>40320</duration>
</forward>
```
which shows an unsightly whole rest at the start of the second measure. Is this normal? Should I care about this?

**Comment by mscuthbert** [comment]
Alex -- you posted a comment but deleted it -- the behavior is normal -- Scores expect a certain hierarchy of Score, Part, Measure.  Use Stream for a generic stream that does not expect a hierarchy.  If the problem continues, please make a different issue.  Thank you.

**Comment by a-papadopoulos** [comment]
Yes sorry about that. I just figured that out by myself and didn't want to clutter the discussion here -- should have left a note though. Thanks!
