### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andrewsanchez** [cuthbertLab/music21#311]
`documentation/source/index.rst` does not seem to reflect what is shown at this page 

http://music21.readthedocs.io/en/latest/index.html

For example, the following directive is included in that .rst file
```
.. toctree::
   :maxdepth: 2

   usersGuide/index
```

Yet the user's guide is nowhere to be found on readthedocs.

this page, however, does seem to reflect what is in that index.rst file:  http://web.mit.edu/music21/doc/

Why are there two different sites with different documentation?

Also, there is no usersGuide folder here:
```
~ $ ls build/html/
_images			about			index.html		search.html
_sources		developerReference	installing		searchindex.js
_static			genindex.html		objects.inv
```

Perhaps related to my issues with documentation/make.py as discussed in #218

**Comment by mscuthbert** [comment]
The readthedocs site is apparently failing.  Fixing now; but we've had lots of timeout problems: https://github.com/rtfd/readthedocs.org/issues/1767  so not sure if it will ever work; it might just need to be deleted.
