### ISSUE TITLE
Subdivisions larger than 16th notes not parsing correctly

### ISSUE THREAD

**Issue by KKONZ** [cuthbertLab/music21#316]
When parsing midi files that contain subdivision greater than 16 notes the notes appear incorrectly, but still sound correct. I created a notebook to show an example here: https://github.com/KKONZ/Music21-Subdivisons-greater-than-16th-notes-Issue/blob/master/Smaller%20than%2016th%20subdivisions%20not%20processing%20in%20Music21.ipynb.

**Comment by mscuthbert** [comment]
Change the quanization settings in MIDI parsing.  This is a known "feature" for rendering recorded midi properly.

**Comment by mscuthbert** [comment]
But see #192 for a bug that it's harder to disable than it should be.

**Comment by KKONZ** [comment]
Great, I will try this out soon. Thank you!
