### ISSUE TITLE
harmony.realizeChordSymbolDurations() returns flat piece

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#318]
I've just figured out that realizeChordSymbolDurations() always returns the flat piece, and not the original one, in all cases where it does something (i.e. when there's at least one chord). Now that not a major annoyance, since the durations are set in place, I can always conserve the original piece, but I was wondering what's the use of this? Unless I'm missing something, it feels like a potentially undesirable side-effect? Thanks!

**Comment by mscuthbert** [comment]
it's a very old function -- I believe it depends on something so old that it predates nested streams(!!) [before v.0.2 there were just barline markers].  Agreed, an option that preserves the hierarchy would be nice.  But recall that you'll have many chord symbols that overflow their measures (i.e., a Cmin chord in m. 1 might continue till measure 4), so I don't think there's necessarily a problem with making flattening (at least at the part level) remain the default.

`.stripTies()` also does the same thing with creating unusual measures.

**Comment by a-papadopoulos** [comment]
Thanks for the clarifications! So you're saying that I shouldn't use the original stream, for those cases where a ChordSymbol spans several sub-streams?

**Comment by mscuthbert** [comment]
It all depends on what you plan to do with it later, but if you want to show it, best not to.  Or at least run makeMeasures() beforehand.

**Comment by a-papadopoulos** [comment]
All right, I get it. I'm closing this one so, thanks!
