### ISSUE TITLE
Python 3 Unicode Encode Error

### ISSUE THREAD

**Issue by opengeekv2** [cuthbertLab/music21#324]
I'm getting this error while trying to write a Bach Chorale to a file in png or svg via lilypond.

UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 4677: ordinal not in range(128)

Unicode error hint

The string that could not be encoded/decoded was: "Bräu" --

The Bach Chorale is bach/bwv335.mxl

**Comment by psychemedia** [comment]
For use with `music21` in Jupyter notebooks, score previews in a browser using Javascript and `OpenSheetMusicDisplay` almost look to be there? (Issue https://github.com/cuthbertLab/music21/issues/306 and PR https://github.com/cuthbertLab/music21/pull/326 )

**Comment by mscuthbert** [comment]
Just tested this -- are you using an old version of music21? Works fine for me.  Reopen if you are using music21 v.5 and still have the bug.
