### ISSUE TITLE
How to extract features/information from a midi file and again reconstruct it via music21?

### ISSUE THREAD

**Issue by Carbonil** [cuthbertLab/music21#325]
I want to encode a midi file and then decode it.So far i have done this but the decoder output midi is horrible to listen comparing original.

`from music21 import *

def encoder(url):

   midi=converter.parse(url)
   midi.show('text')
   comp=[]

   for e in midi.recurse():
      comp.append(e)

   return comp

def dec(object):

   write_=stream.Stream(object)
   fp = write_.write('midi', fp='decoder.mid')
   write_.show('midi')

 a=encoder('BlankSpace.mid')
 n=dec(a)`

I want to get back the original midi through decoder.How do i do it?.Anyone please Help

check out more on https://stackoverflow.com/questions/52061238/how-to-extract-every-features-information-from-a-midi-file-and-again-reconstruct

**Comment by mscuthbert** [comment]
That's not what music21 does.  It's not a MIDI editor.  It extracts notes and rhythms from MIDI, quantizing them to symbolic notation, and then writes that back out.

**Comment by Carbonil** [comment]
Actually i thought someone working behind this repo would give me the answer as i am struggling to get the answer.Thanks for the suggestion.I will check it out.
