### ISSUE TITLE
Certain chord names are incorrect in pitchedCommonName

### ISSUE THREAD

**Issue by ZakirG** [cuthbertLab/music21#327]
An example input:

`from music21 import chord as music21_chords`
`zz = music21_chords.Chord(['A#2', 'D3', 'F3']) `
`zz.pitchedCommonName   # returns 'D3-major triad'`

The chord above is definitely not a D major triad, which would need an F# instead of an F, and an A instead of an A#. 

If the A# input is changed to the enharmonic Bb, the function produces the correct output.

` zz = music21_chords.Chord(['Bb2', 'D3', 'F3']) `
`zz.pitchedCommonName  # returns 'B-2-major triad'`

**Comment by mscuthbert** [comment]
Are you on the most recent version in GitHub?  I think the first one might still be an error, but I think that the result would be different.

**Comment by mscuthbert** [comment]
ah, it does do this.  Will try to find a fix.

**Comment by mscuthbert** [comment]
It will not find the A# as a root -- happy to take a patch to add that feature, but it will not give a misleading statement anymore.  Thank you.
