### ISSUE TITLE
First note not played when using `.show('midi')`

### ISSUE THREAD

**Issue by xdl** [cuthbertLab/music21#330]
I'm running into an issue with the midi player preview that's embedded into Jupyter notebook (and online) with `.show('midi')` not playing the first note, e.g. with the following snippet:

```
note1 = note.Note("C4")
note2 = note.Note("D4")
note3 = note.Note("E4")
stream1 = stream.Stream()
stream1.append(note1)
stream1.append(note2)
stream1.append(note3)

stream1.show('midi')
```

Only the D4 and E4 notes are played when the Play button is pressed. This is the case with the online docs as well, e.g. there is no sound at all in the example here http://web.mit.edu/music21/doc/usersGuide/usersGuide_02_notes.html (one note long), and only the last two notes of the stream example http://web.mit.edu/music21/doc/usersGuide/usersGuide_04_stream1.html (three notes long). I've tried it on:

* Chrome 69, Safari 11.1 and Firefox 62 on MacOS High Sierra 1.13.5
* Chrome 68 and Firefox 61  on Android 6

even with disabling any Chrome plugins as suggested in this issue https://github.com/cuthbertLab/music21/issues/315

Any other suggestions or settings I could try would be appreciated!

**Comment by adammichaelwood** [comment]
I'm having the same problem.
Mac OS - both Chrome and Firefox, in a Jupyter notebook

**Comment by adammichaelwood** [comment]
I don't know how to solve this problem "for real", but I wrote a work around wrapper function. It has not been extensively tested, so I don't know if it will work for all types of streams. But for my relatively simple examples in Jupyter notebooks, it is great.

https://gist.github.com/adammichaelwood/2c575c1bbae356c3d6d300486bec5f6e

**Comment by jacobtylerwalls** [comment]
playback in docs looks good now. how about on your end?

**Comment by mscuthbert** [comment]
Ah! I fixed this a few weeks ago and forgot to close this.  Thanks!
