### ISSUE TITLE
[WinError 123] when using show() function

### ISSUE THREAD

**Issue by edtky** [cuthbertLab/music21#331]
I am using Windows 10 and have Muse Score 2 and Finale Notepad 2012 installed in the following directory: C:\\Program Files (x86)\\MuseScore 2\\MuseScore.exe

When I run the following code in my Jupyter notebook:
```
f = note.Note("F5")
f.show()
```

I get this error:
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\User1\\Desktop\\UC Berkeley\\intro_music21\\C:\\Program Files (x86)\\MuseScore 2\\MuseScore.exe'`

How do I fix this?

**Comment by mscuthbert** [comment]
rerun the configure file or edit music21rc directly.  See the docs for environment for more info or ask for help on m21 list.  Thanks!
