### ISSUE TITLE
bug when parsing abc key

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#333]
Hi, I've just discovered a tiny bug in the code that parses abc keys. In [line 429 of file `abcFormat/__init__.py`](https://github.com/cuthbertLab/music21/blob/218217d5306737d71789fc7031ac5ae9056ace7b/music21/abcFormat/__init__.py#L429%20https://github.com/cuthbertLab/music21/blob/218217d5306737d71789fc7031ac5ae9056ace7b/music21/abcFormat/__init__.py#L429), the `for` loop should stop after a match has been made. In the current form, it will keep matching key signatures that are a prefix of another.

For example, this causes `'F#m'` to be matched as an F major with one flat, instead of an F# minor with three sharps.

I will submit a fix in the next couple of days, that should be an issue one.

**Comment by mscuthbert** [comment]
Thanks! Ah I see it.  When fixing, can you test that G and Gb still work as expected -- I'm thinking that a fix for F vs. F# (where F# comes before F) might break G and Gb (where G comes before Gb).

**Comment by a-papadopoulos** [comment]
Exactly. I believe it's only a matter of testing longer prefixes first, but I'll obviously include all those tests.
By the way, I've discovered another tiny "annoyance": when the key doesn't say major, `_getKeySignatureParameters` doesn't return a mode, and `getKeySignatureObject` only returns a `KeySignature` object, and not a nice `Key`. Is there any reason against assuming a default major when no mode is specified (i.e. `_getKeySignatureParameters` returns `mode='major'` when `modeCandidate` is empty)?
