### ISSUE TITLE
Error when parsing *some* .xml files

### ISSUE THREAD

**Issue by maximoskp** [cuthbertLab/music21#334]
Hi!

I noticed that when trying to parse some files, e.g.,

[this file](https://github.com/maximoskp/COINVENT_HTD/blob/master/training_data/BachChorales/BC_001_026900B_a1.xml)

I had the following error:

**AttributeError: 'NoneType' object has no attribute 'strip'**

coming from

**music21/musicxml/xmlToM21.py", line 1255, in identificationToMetadata
    md.software.append(software.text.strip())**

I don't know if I'm doing something wrong or if there is an "official" workaround, but for the time being I modified the code to just check if software.text is empty before trying to append to the metadata.

Thanks - cheers!
max.

**Comment by mscuthbert** [comment]
Fixed in newest commit -- there's no point in creating an empty <software> tag, but I guess some exporters do it anyhow.  Added many more tests for empty tags.
