### ISSUE TITLE
AttributeError: 'Score' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by yurivict** [cuthbertLab/music21#339]
This example from your homepage breaks:

```
catalog = stream.Opus()
for workName in corpus.chorales.Iterator():
  work = converter.parse(workName)
  firstTS = work.recurse().getElementsByClass('TimeSignature')[0]
  if firstTS.ratioString == '6/8':
    catalog.append(work.measures(0, 2))
catalog.show()
```

> AttributeError: 'Score' object has no attribute 'startswith'

**Comment by mscuthbert** [comment]
Thanks.  Fixed -- I need to make that page automatically generated from an iPython script somehow, since all our iPython code gets autochecked.
