### ISSUE TITLE
NotImplementedError: cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by sshlien** [cuthbertLab/music21#341]
while attempting 
 sixEight = corpus.search('6/8')
[PosixPath.txt](https://github.com/cuthbertLab/music21/files/2578364/PosixPath.txt)

**Comment by Risottorie** [comment]
Yes, I am on Windows. B, Rie

Zitat von Michael Scott Cuthbert <notifications@github.com>:

> Are you both by chance on windows?

**Comment by sshlien** [comment]
I got the error on Windows 10 -- Seymour


----- Original Message -----

**Comment by blueCat11** [comment]
I'm on Windows10.

**Comment by Lutzifer** [comment]
We are currently trying to rebuild the Cache using http://web.mit.edu/music21/doc/moduleReference/moduleCorpusCorpora.html?highlight=rebuild#music21.corpus.corpora.Corpus.rebuildMetadataCache

Looks to me as if the Posix version is being deserialised and windows dies on that...

cp. mscuthberth et.al. https://groups.google.com/forum/#!msg/music21list/eSPp32seBXY/zeWuzmAkBgAJ

**Comment by sshlien** [comment]
By the way, I am running Python 3.7.1 on Windows 10.

This could be an issue with newer versions of Python.

Seymour


----- Original Message -----

**Comment by sshlien** [comment]
Hello Myke Cuthbert,

For your information, I am still working on some graphic
user interfaces for music21 using tkinter. I have attached
my latest program still in progress. Progress is somewhat
slow since I am still getting used to Python, object coding,
tkinter, and music21. I am also working on Humdrum which
is written in C++.

Seymour

**Comment by blueCat11** [comment]
> We are currently trying to rebuild the Cache using http://web.mit.edu/music21/doc/moduleReference/moduleCorpusCorpora.html?highlight=rebuild#music21.corpus.corpora.Corpus.rebuildMetadataCache

I tried this method as well. First, I deleted core.p.gz file in \music21\corpus\_metadataCache folder. Then I used rebuildMetadataCache() .
It took over an hour, but now I can use the core-corpus on Windows. 

Thanks @Lutzifer !

**Comment by Lutzifer** [comment]
@mscuthbert Maybe it would be a workaround to include two prebuilt metadata files, one for windows and one for posix systems and use them depending on the OS type?

**Comment by LLight** [comment]
I am running into the same problem, using Python 3.7 on Windows 10 (see the attached code and error message). When I use the corpus.search function, I am getting the same metadata error related to the PosixPath.
[corpus_search_err.txt](https://github.com/cuthbertLab/music21/files/3691578/corpus_search_err.txt)

**Comment by mscuthbert** [comment]
I think that I've fixed this in #459 -- can someone on Windows test this on the latest git?  If so, I'll backport release a new v.5 version as well.

**Comment by mscuthbert** [comment]
Fixed in #459
