### ISSUE TITLE
show() doesn't work in Windows 10

### ISSUE THREAD

**Issue by danshorstein** [cuthbertLab/music21#348]
show() is not working. Using Windows 10. Getting "SubConverterFileIOException: png file of xml not found. Or file >999 pages?".

I can see the xml tmep files are created, but no png temp files are being created. 

I've installed MuseScore using the microsoft app store, which is the MuseScore recommended way to install. However this puts the musescore.exe in a hidden folder under c:\program files\windowsapps. I was able to locate the path and set "musicxmlPath" and "musescoreDirectPNGPath" to the path, and am still getting an error when trying to run show(). I also installed lilypad and when I run show('lily'), that works.

**Comment by Wind4Greg** [comment]
I'm seeing the same issue. Brand new Music21 and MuseScore install, using Python 3.6.6 (Anaconda), with Jupyter Notebooks. Ran some tests with `show()` and saw the following for this test case:

```python
temp = "text" # works
# "midi" works
#  "musicxml" opens up and shows in MuseScore
# "vexflow" showed it in a new tab, 
# "musicxml.png" gets the error condition mentioned above
f = note.Note("F5")
f.show(temp)
```

Note that temporary music XML files are being created in the *scratch* directory specified in:

```
<preference name="directoryScratch" value="C:\tmp" />
```
After `f.show("musicxml.png")` or `f.show()` is called a new MusicXML file shows up in the *scratch* directory. If I run MuseScore in command line mode show below it correctly turns the MusicXML file into a PNG.

```
$ "C:\Program Files (x86)\MuseScore 2\bin\MuseScore.exe" tmp4hkcsxd7.xml -o temp.png
```

If you can point me to the Python file that calls MuseScore I can try to figure out what's going wrong.

Cheers

Greg B.

**Comment by LucasLoerch** [comment]
I am also having trouble with the show() function. I have Windows 10 64bit, Anaconda3/Python 3.7 and MuseScore3 all installed recently. I already set the musicxmlPath to the correct folder containing MuseScore. When I run the show() command I get the following error:
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\Lucas Loerch\\C:\\Program Files (x86)\\MuseScore 2\\MuseScore.exe'
(in english: the syntax for the file name, directory name or volume name are wrong).

I also tried to uninstall MuseScore and install Finale. I adapted the musicxmlPath accordingly, but the error remains the same.

**Comment by musicEnfanthen** [comment]
There is two times "C:" in your path. Probably it is sufficient to use `C:\Program Files (x86)\MuseScore 2\MuseScore.exe`. 

If this is not working, try to use forward slashes ("`/`") instead of winodws back slashes ("`\`"). It's maybe weird but working for me on Windows 10. 

After all, I have to set `musicxmlPath` to

`C:/Program Files (x86)/MuseScore 2/bin/MuseScore.exe
`
(be aware of the additional `bin` folder and check for it in your path)

**Comment by LucasLoerch** [comment]
Thanks for you answer. Setting the musescoreDirectPNGPath definitely was one part of the problem. Now I get the following error:
melody1.show()
Traceback (most recent call last):

  File "<ipython-input-16-f122afa7aab0>", line 1, in <module>
    melody1.show()

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\stream\__init__.py", line 258, in show
    return super().show(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\base.py", line 2580, in show
    **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 360, in show
    subformats=helperSubformats, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 938, in write
    fp = self.runThroughMusescore(fp, subformats, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 895, in runThroughMusescore
    return self.findPNGfpFromXMLfp(fpOut)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 807, in findPNGfpFromXMLfp
    "png file of xml not found. Or file >999 pages?")

SubConverterFileIOException: png file of xml not found. Or file >999 pages?

**Comment by bperak** [comment]
Hello,
I have the same error
SubConverterFileIOException: png file of xml not found. Or file >999 pages?


My config file is set like this:
<settings encoding="utf-8">
  <preference name="autoDownload" value="allow" />
  <preference name="braillePath" />
  <preference name="debug" value="0" />
  <preference name="directoryScratch" />
  <preference name="graphicsPath" />
  <preference name="ipythonShowFormat" value="ipython.musicxml.png" />
  <preference name="lilypondBackend" value="ps" />
  <preference name="lilypondFormat" value="pdf" />
  <preference name="lilypondPath" value="C:\Users\Korisnik\lilypond" />
  <preference name="lilypondVersion" />
  <localCorporaSettings />
  <localCorpusSettings />
  <preference name="manualCoreCorpusPath" />
  <preference name="midiPath" />
  <preference name="musicxmlSettings" value="C:/Program Files/MuseScore3/bin/MuseScore3.exe" />
  <preference name="musescoreDirectPNGPath" value="C:/Program Files/MuseScore3/bin/MuseScore3.exe" />
  <preference name="musicxmlPath" value="C:/Program Files/MuseScore3/bin/MuseScore3.exe"/>
  <preference name="pdfPath" value="C:/Program Files/MuseScore3/bin/MuseScore3.exe"/>
  <preference name="showFormat" value="musicxml" />
  <preference name="vectorPath" />
  <preference name="warnings" value="1" />
  <preference name="writeFormat" value="musicxml" />
  </settings>


The error is 

  File "<ipython-input-18-cffed12d428f>", line 1, in <module>
    f.show()

  File "C:\Users\Korisnik\Anaconda3\lib\site-packages\music21\base.py", line 2580, in show
    **keywords)

  File "C:\Users\Korisnik\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 360, in show
    subformats=helperSubformats, **keywords)

  File "C:\Users\Korisnik\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 938, in write
    fp = self.runThroughMusescore(fp, subformats, **keywords)

  File "C:\Users\Korisnik\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 895, in runThroughMusescore
    return self.findPNGfpFromXMLfp(fpOut)

  File "C:\Users\Korisnik\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 807, in findPNGfpFromXMLfp
    "png file of xml not found. Or file >999 pages?")

SubConverterFileIOException: png file of xml not found. Or file >999 pages?

**Comment by GaetanBaert** [comment]
It worked for me by changing` os.system(musescoreRun)` line 891 of subconverters.py by `subprocess.run(musescoreRun)`. You need also to `import subprocess` at the start of subconverters.py.

Enjoy !

**Comment by Wind4Greg** [comment]
Still having the problem myself GaetanBaert's approach may be the correct fix. For those that don't want to hack the code (and have the environment settings set correctly) I wrote the following helper function that I use in my Jupyter notebooks:

```python
# Create my own function to show stuff
# Note the height constraint to Image doesn't seem to work.
import pathlib
import os
from IPython.display import Image

def show_m21(mObj, width=None, height=None):
    # Save defaults
    author = m21.defaults.author
    title = m21.defaults.title
    # Remove them
    m21.defaults.author = None
    m21.defaults.title = None
    
    us = m21.environment.UserSettings() 
    scratchPath = pathlib.Path(us['directoryScratch'])
    fname = mObj.write() #  This writes a temp musicXML file and returns the name
    p_mxml = pathlib.Path(fname)
    p_out = p_mxml.with_suffix(".png")
    # Create command string
    musescorePath = us['musescoreDirectPNGPath']
    musescoreRun = '"' + str(musescorePath) + '" ' + str(p_mxml) + ' -o  ' + str(p_out) + ' -T 0 '
    os.system(musescoreRun)
    png_files = scratchPath.glob("*.png")
    base_name = p_mxml.stem
    # Restore defaults
    m21.defaults.author = author
    m21.defaults.title = author
    for png in png_files:
        if png.match(base_name + "*"):
            return Image(filename=str(png), width=width, height=height)
```

**Comment by mscuthbert** [comment]
hi all -- please see #233  -- it might solve some of the problems, but I could not get the person who contributed the patch to run a test on windows.  If someone can see if that goes the right direction or can write a new PR for this, I'd appreciate it.  Thanks!

**Comment by Wind4Greg** [comment]
I'll take a look. May take me a couple days to get things setup and understand what he did.

Cheers
Greg B.

**Comment by Wind4Greg** [comment]
Hi all [#233](https://github.com/cuthbertLab/music21/pull/233) and GaetanBaert both update to using the recommended `subprocess`  standard library module. 

The command string manipulations in #233 don't work correctly on windows, while GaetenBaert's solution **does** as it doesn't change from the the *current code*. 

If there is interest I can try GaetenBaert's solution on my Ubuntu Linux machine, but I don't have a Mac. Note that his solution is a two line change, #233 has a bunch of testing stuff added that looks nice but seems behind on where Music21 is currently, i.e., has the old `six` stuff still in it.

Cheers
Greg B.

**Comment by LucasLoerch** [comment]
I am sorry if I am outing myself as a Newby here, but @GaetanBaert , how do I make alterations at the subconverter.py?
I found the subConverter.py function on Github. On line 891 it says subformatExtension = 'png'. I just do not get how to imply your advice. Could you explain it in more detail, please? Thanks!

**Comment by GaetanBaert** [comment]
@LucasLoerch The file has been updated since my comment. The line to change now is the line 912.
To change it on your computer : 
You need to find your python installation path (and maybe your venv path if you use one). 
then you can go to path\to\python\lib\site-package\music21\converter\subconverters.py and change the line by subprocess.run(musescoreRun).

**Comment by LucasLoerch** [comment]
Thanks! it now works for me using the change on the subconverter.py suggested by GaetanBaert combined with using the forward slashes instead of the double-backslashes in the path to MuseScore as as suggested by musicEnfanthen.

**Comment by BevanBroun** [comment]
I also needed the GaetanBaert subprocess.run(musescoreRun) fix. Issue with os.system(musescoreRun) seems to be the code moved on before png file was ready.

**Comment by tomscag** [comment]
> 
> 
> It worked for me by changing` os.system(musescoreRun)` line 891 of subconverters.py by `subprocess.run(musescoreRun)`. You need also to `import subprocess` at the start of subconverters.py.
> 
> Enjoy !

This works perfectly for me in Windows 10 and Anaconda

**Comment by eraoul** [comment]
I had the same (or maybe a related) problem with show() in a jupyter notebook I was running until Linux (and viewing on a Mac via ssh forwarding). 

For me the problem was due to how musescore tries to open its GUI momentarily, even in commandline mode. 

Simple fix: run this in a jupyter notebook cell before using .show():

`%env QT_QPA_PLATFORM=offscreen`

**Comment by mscuthbert** [comment]
Thanks @eraoul .  We've switched to subprocess.run() for calling so the Windows side of the issue is closed.  While I try to make music21 work in Linux, it's not a fully supported platform (because of the sheer number of variants) so I'm glad to have this information in the "Install Linux" doc, I'll need a PR to that doc to include it.  Thanks!
