### ISSUE TITLE
music21 doesn't respect harmony offset when importing musicxml

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#350]
I think we've found a bug in the way music21 imports harmony objects from musicxml. In the musicxml file [pasted here](https://gist.github.com/a-papadopoulos/f4d4bdee859706a8b690c158a9da0ed0), the first measure contains only a whole note, but two chord symbols C and G at beat 1 and 3 of the measure respectively. However, when imported in music21, the ChordSymbol object corresponding to the G chord has an offset of 0 too.

I can dive into this a bit further, but my intuition is that the `offset` element of the G chord isn't taken into account by music21, and that music21 expects a chord symbol to occur at the start of a new note. Can you confirm this?

**Comment by mscuthbert** [comment]
Fixed in #361
