### ISSUE TITLE
calling stripTies breaks measures

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#352]
Hi, I've found a quite annoying bug, which I can reproduce in the following code:

```python
from music21 import corpus

score = corpus.parse('bach/bwv1.6.mxl')

notes = list(score.stripTies().recurse().notesAndRests)
note = notes[0]

note.getContextByClass('Measure').elementOffset(note) # raises an exception
self.assertEqual(4, note.beat) #note.beat returns 1
```

The issue is that the measure of the note doesn't contain the note itself. This seems to happen for every score with a pickup measure, but only if stripTies() is called. This causes note.beat to silently return 1 (which is actually how I discovered this issue).

I haven't looked into stripTies() yet, so I don't know what might be causing this.

**Comment by mscuthbert** [comment]
not a bug -- I'm writing up a user's guide article about why this answer comes out what it does -- it is a necessary design situation and has nothing to do particularly with stripTies(), but has to do with "note" no longer is associated with any existing Stream objects after garbage collection.

You'll find that if you assign intermediate variables, things work:

```
score = ..
st_score = score.stripTies()
notes = list(st_score.recurse().notesAndRests)
... rest the same ...
```

will work fine.  When User's Guide chapter 58 is done, it'll explain what's up.

**Comment by mscuthbert** [comment]
The `.getContextByClass()` is a related problem but somewhat separate that comes from following derivation chains. I've put more information on that in the docs for base.py

Here's the explanation written up:
http://web.mit.edu/music21/doc/usersGuide/usersGuide_58_sitesContext.html
