### ISSUE TITLE
Stream.expandRepeats errors if score has no repeats

### ISSUE THREAD

**Issue by maxrothman** [cuthbertLab/music21#355]
As a researcher, I'd like to be able to expand a stream into an "as-performed" view, i.e. a flat  list of notes. One of the steps in that process is expanding repeats, but `Stream.expandRepeats` errors if a score has no repeats.

**Expected behavior**: when calling `Stream.expandRepeats` on a score with no repeats, the score is returned unchanged.

**Actual behavior**: calling `Stream.expandRepeats` on a score with no repeats raises an `ExpanderError("cannot expand Stream: badly formed repeats or repeat expressions")` ([ref](https://github.com/cuthbertLab/music21/blob/master/music21/repeat.py#L774)). Turning on debug mode reveals that the cause is `"no dc/segno, no repeats"` ([ref](https://github.com/cuthbertLab/music21/blob/master/music21/repeat.py#L1728)).

The cause of this issue seems to be that the semantics of `Expander.isExpandable` are overloaded to mean both "is the stream expandable" and "is the stream well-formed". An easy fix would simply be to remove the first case. If backwards compatibility is required, I'd propose breaking out all the cases in `isExpandable` after the first into a new method (named `isWellFormed` or something) and have `isExpandable` and `expandRepeats` call it (or have `expandRepeats` call it conditionally based on an option).

I'd also propose that `isExpandable` should raise the exception itself or at least return a tuple of `(bool, reason)` so that a more useful error message can be propagated to the user.

I'm happy to make a PR for this change, but I wanted to run it by y'all first.

**Comment by Sinnerboy89** [comment]
Hi @maxrothman, did you ever make any progress on this?

**Comment by maxrothman** [comment]
I did not. As mentioned above, I had some ideas for how to fix the issue but I was looking for feedback from the maintainers as to their preferred approach.

**Comment by mscuthbert** [comment]
Sorry about that -- I had no time till the summer.  Summer is finally here!

Most helpful thing would be the smallest piece of code that triggers the error that shouldn't.  If you get that (even just as a cut and paste here) I can work on fixing the problems.  Thanks!

**Comment by maxrothman** [comment]
As I detailed in the issue description above, the code is just `Stream.expandRepeats`. The cause of the error comes from the data in the stream itself, not the code being used on it.

I tried to include detailed repro info above, is there any other information that'd help? As I said above, I'm happy to make a PR to fix this issue, but I'd like your input on which approach to take (options detailed in the description).

**Comment by mscuthbert** [comment]
I still need a minimum code that replicates the problem with the smallest number of measures, etc. thanks!

**Comment by giamic** [comment]
Hi, I'm interested in the issue as well. Here is a minimal example.
[score.txt](https://github.com/cuthbertLab/music21/files/3381411/score.txt)
just rename the file score.musicxml and put it in your python current working directory. Then try

`from music21 import converter

score = converter.parse("score.musicxml").expandRepeats()`

Hope this helps to fix the issue.

**Comment by maxrothman** [comment]
Hi, looks like an example has been posted (thanks @giamic!). Any progress, @mscuthbert? Alternatively, I'm happy to fix the issue if you can indicate which of the possible approaches (as detailed in the issue report) you'd prefer.

**Comment by maxrothman** [comment]
Just wanted to ping this again. Did you see my prior comment @mscuthbert?

**Comment by mscuthbert** [comment]
Hi -- I still needed a MINIMAL score example -- something like:

```
In [1]: s = stream.Score()                                                                                                                                            

In [2]: s.expandRepeats()                                                                                                                                             
Out[2]: <music21.stream.Score 0x108841748>
```

this works, but

```
In [10]: p = stream.Part()                                                                                                                                            

In [11]: m = stream.Measure()                                                                                                                                         

In [12]: p.append(m)                                                                                                                                                  

In [13]: p.expandRepeats()                                                                                                                                            
---------------------------------------------------------------------------
ExpanderException                         Traceback (most recent call last)
<ipython-input-13-2da7e8dfc09c> in <module>
----> 1 p.expandRepeats()

~/git/music21base/music21/stream/__init__.py in expandRepeats(self, copySpanners)
   8385 
   8386         ex = repeat.Expander(self)
-> 8387         post = ex.process()
   8388 
   8389         # copy all non-repeats

~/git/music21base/music21/repeat.py in process(self, deepcopy)
    772         if not self.isExpandable():
    773             raise ExpanderException(
--> 774                     'cannot expand Stream: badly formed repeats or repeat expressions')
    775 
    776         # need to copy source measures, as may later measures before copying

ExpanderException: cannot expand Stream: badly formed repeats or repeat expressions
```

does not.

The musicxml file had font information, encoding-date, margins, midi-ports, etc. -- all of which I would need to wade through to get to a point where I could see what the error is.  Making minimal test examples is really important to save developer time in figuring it out.  Now I can check why something is not expandable.

**Comment by maxrothman** [comment]
Thanks for clarifying that. Just so we're on the same page, is there anything else you need from me, or do you have what you need to fix this bug?

**Comment by mscuthbert** [comment]
Nope -- I'll merge this once all tests pass and then let me know if there are any problems.
