### ISSUE TITLE
Parsing musicxml with non-traditional key signature and normal sharps fails

### ISSUE THREAD

**Issue by maxrothman** [cuthbertLab/music21#360]
Given this bit of musicxml:
```xml
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
   ...
   <part id="P1">
    <measure number="1" width="367.48">
      <barline location="left">
        <bar-style>heavy-light</bar-style>
        <repeat direction="forward"/>
      </barline>
      <attributes>
        <divisions>4</divisions>
        <key>
          <key-step>G</key-step>
          <key-alter>1</key-alter>
          <key-accidental>sharp</key-accidental>
        </key>
        ...
      </attributes>
      ...
    </measure>
  </part>
</score>
```
And the following code:
```python
converter.parseFile('./my-file.mxl')
```
The following exception is thrown:
```
music21/musicxml/xmlToM21.py in nonTraditionalKeySignature(self, mxKey)
   5202             p = pitch.Pitch(thisStep)
   5203             if thisAccidental is not None:
-> 5204                 p.accidental = pitch.Accidental(self.mxAccidentalNameToM21[thisAccidental])
   5205                 p.accidental.alter = thisAlter
   5206             else:

KeyError: 'sharp'
```
([line ref](https://github.com/cuthbertLab/music21/blob/master/music21/musicxml/xmlToM21.py#L5203))

This appears to occur because `thisAccidental` has the value `sharp`, and `self.mxAccidentalNameToM21` ([ref](https://github.com/cuthbertLab/music21/blob/master/music21/musicxml/xmlToM21.py#L314)) has no key for `sharp` (or `flat` for that matter).

I'm happy to contribute a fix, but I'm not sure what the right path forward is. There's a lot of other possible values for `<accidental-value>` [in the spec](https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-accidental-value.htm), should they all have mappings in `mxAccidentalNameToM21`? Or should there be a fallthrough behavior where if there's no mapping in `mxAccidentalNameToM21` the parser should try to use the value anyways?

**Comment by maxrothman** [comment]
Thanks for the quick turnaround! How soon should I look for the fix to be on pypi?

**Comment by mscuthbert** [comment]
Usually every 2 months or so.  You can always install from Git to be on the latest version
