### ISSUE TITLE
Estimating scale?

### ISSUE THREAD

**Issue by xhevahir** [cuthbertLab/music21#362]
I've been looking through the music21 docs and was wondering: Are there any built-in functions for estimating the scale--as in, tonic+mode--of a (monophonic) passage? For example, in a sequence ranked by likelihood?  I see that the Key object has parameters for different modes, and that there are lots of methods for estimating key, but the examples there show only major and minor.

**Comment by mscuthbert** [comment]
Stream().analyze('key')  :-)

**Comment by xhevahir** [comment]
This seems to distinguish only major and minor; I was looking for something that could detect the church modes, too.
