### ISSUE TITLE
Time Signatures only end up in one part on MIDI import

### ISSUE THREAD

**Issue by eraoul** [cuthbertLab/music21#363]
I am importing a MIDI file that has 2 tracks, with an initial time signature message only occurring in the first track.

When importing via midiFileToStream, I get 2 Parts, but the time signature only appears in part 1.

Now, if I try to do operations on the score given a range of measures, such as score.measures(1,4), I get weird results since the 2nd part has a different time signature than the first.

Steps to reproduce:

```
from music21.meter import TimeSignature
import music21.midi as midi
from music21.midi import MidiFile, MidiTrack, MidiEvent
from music21.midi.translate import midiFileToStream

mf = MidiFile()
mt0 = MidiTrack(0)
mt1 = MidiTrack(1)

# Make track 1
mt0.events.append(midi.DeltaTime(mt0, 0))
me = MidiEvent(mt0)
me.type = 'TEMPO'
bpm = 96
mspq = int(round(60000000 / bpm)) # microseconds per quarter note
me.data = midi.putNumber(mspq, 3)
mt0.events.append(me)
mt0.events.append(midi.DeltaTime(mt0, 0))

me = MidiEvent(mt0)
me.type = 'TIME_SIGNATURE'
me.data = midi.putNumbersAsList([3, 3, 24, 4]) # 3/8 time, 24
mt0.events.append(me)
mt0.events.append(midi.DeltaTime(mt0, 0))

me = MidiEvent(mt0)
me.type = 'NOTE_ON'
me.channel = 0
me.pitch = 60
me.velocity = 127
mt0.events.append(me)
mt0.events.append(midi.DeltaTime(mt0, 4096))

me = MidiEvent(mt0)
me.type = 'NOTE_OFF'
me.channel = 0
me.pitch = 60
mt0.events.append(me)

# Make track 2

mt1.events.append(midi.DeltaTime(mt1, 0))
me = MidiEvent(mt1)
me.type = 'NOTE_ON'
me.channel = 0
me.pitch = 48
me.velocity = 127
mt1.events.append(me)
mt1.events.append(midi.DeltaTime(mt1, 4096))

me = MidiEvent(mt1)
me.type = 'NOTE_OFF'
me.channel = 0
me.pitch = 48
mt1.events.append(me)

mf.tracks = [mt0, mt1]

# Import MIDI object to stream (score)
score = midiFileToStream(mf)

for e in score.recurse():
    print(e)
```

Output:

```
<music21.stream.Part 0x114e2afd0>
<music21.meter.TimeSignature 3/8>
<music21.note.Note C>
<music21.stream.Part 0x114e451d0>
<music21.note.Note C>
```

Note that we get the expected 3/8 TimeSignature in the first part, but nothing shows up explicitly in the 2nd part. Also, the `measures(1,3)` function below results in the first part having 3 measures, while the 2nd part only has a single measure, even though the two notes had the same duration.

```
ms = score.measures(1,3)
for e in ms.recurse():
    print(e)
```
Results:
```
<music21.stream.Part 0x114e45278>
<music21.stream.Measure 1 offset=0.0>
<music21.clef.TrebleClef>
<music21.meter.TimeSignature 3/8>    # <-----
<music21.note.Note C>
<music21.stream.Measure 2 offset=1.5>
<music21.note.Note C>
<music21.stream.Measure 3 offset=3.0>
<music21.note.Note C>
<music21.bar.Barline style=final>
<music21.stream.Part 0x114e18dd8>
<music21.stream.Measure 1 offset=0.0>
<music21.clef.BassClef>
<music21.meter.TimeSignature 4/4>*    # <-----
<music21.note.Note C>
<music21.bar.Barline style=final>
```

I'm not sure if I'm using music21 incorrectly, if my MIDI file input is broken somehow, or if this is actually a bug in the code that collects TimeSignatures and applies them to all tracks on MIDI import.

**Comment by mscuthbert** [comment]
I'm not sure this is a bug -- is there docs that say that Time Signatures in Track 1 apply to all tracks?  What happens if there's an explicit conflicting Time Signature in Track 2?

**Comment by eraoul** [comment]
This is confusing. It's not clear to me that the use of time signature messages is well-specified in MIDI. In practice, it seems like many software packages only write the time signatures to a single track, so for a large number of MIDI files music just can't parse them in a reasonable way.

**Comment by eraoul** [comment]
Updated: I did find this in the spec after all.  From http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html :

All MIDI Files should specify tempo and time signature. If they don't, the time signature is assumed to be 4/4, and the tempo 120 beats per minute. In format 0, these meta-events should occur at least at the beginning of the single multi-channel track. **In format 1, these meta-events should be contained in the first track.** In format 2, each of the temporally independent patterns should contain at least initial time signature and tempo information.

**Comment by jacobtylerwalls** [comment]
heya @eraoul -- my impression is that the source you quoted is not describing common practice with conductor tracks: it should say something like "In format 1, the first track should consist of all and only such meta-events", which is the concept of a conductor or "tempo" track.

I believe m21 handles this just fine if the conductor track does not contain other notes, as your example does. I don't think a conductor track with note_on events is accepted by most software, at least according to this back and forth on the subject of MuseScore sometimes putting note events in the "conductor" track: https://musescore.org/en/node/207346

**Comment by mscuthbert** [comment]
I believe that that's correct :  a conductor track in music21 should be a conductor only track.  But I haven't worked on this feature in a long time.

**Comment by mscuthbert** [comment]
This has been fixed by @jacobtylerwalls this month!

**Comment by jacobtylerwalls** [comment]
@mscuthbert unfortunately, I doubt there is any change here -- the conductor track PR doesn't do anything with nonstandard MIDI files such as MuseScore is still exporting where tempo events are jumbled up with note events.

Only the `conductorPart` is searched, which any track with notes will NOT be:

https://github.com/cuthbertLab/music21/blob/747316f350319f0832d704c5d06a0c0bc2f07cbe/music21/midi/translate.py#L2317-L2326

Now, whether we care to do anything about it in music21 is yet another matter.
