### ISSUE TITLE
TinyNotation validates some bad inputs

### ISSUE THREAD

**Issue by ryaanahmed** [cuthbertLab/music21#366]
The TinyNotation parser currently throws away anything that it doesn't tokenize, which means it permits some inputs that it probably shouldn't.

e.g., `g1 a g; g1 a g` is fine (n.b. the semicolon), since `;` is never captured by a regex.

It probably should check the input string after tokenizing to see if there's anything leftover and complain.

**Comment by mscuthbert** [comment]
Confirmed and will get to it.  Note that it will only complain if `raiseExceptions=True` is set -- in general, TinyNotation--as a human input format--is designed to try as much as it can to work around encoding errors.

**Comment by mscuthbert** [comment]
Testing code:

```
converter.parse('tinyNotation: g1 a g; g1 a g', raiseExceptions=True).show('text') 
```

should raise an exception.
