### ISSUE TITLE
parsing with lilypond fails

### ISSUE THREAD

**Issue by LucasLoerch** [cuthbertLab/music21#375]
Hi there.
I am using Win 10 with Python 3.7 in Spyder 3.3.2 and lilypond 2.18.2. I have a music21 stream object (created in numerous steps that seem to long to write down in detail here) that I want to export as a .png. The elements of the stream are as follows:
```
(<music21.stream.Measure 1 offset=0.0>,
 <music21.clef.TrebleClef>,
 <music21.tempo.MetronomeMark andante Quarter=70>,
 <music21.key.Key of C major>,
 <music21.meter.TimeSignature 4/4>,
 <music21.note.Note E>,
 <music21.note.Note D>,
 <music21.note.Note B>,
 <music21.stream.Measure 2 offset=4.0>,
 <music21.note.Note D>,
 <music21.note.Note B>,
 <music21.note.Note D>,
 <music21.stream.Measure 3 offset=8.0>,
 <music21.note.Note B>,
 <music21.note.Note D>,
 <music21.note.Note C>,
 <music21.stream.Measure 4 offset=12.0>,
 <music21.note.Note D>,
 <music21.note.Note C>,
 <music21.note.Note B>)
```
If I export a midi file and open it in Forte 7 Basic, everything looks fine 
![item1](https://user-images.githubusercontent.com/46963758/53826462-edd07d80-3f78-11e9-8bc7-409c844b85eb.png)
. But if I use
`conv=m21.converter.subConverters.ConverterLilypond()

conv.write(myMelody, fmt="lilypond", fp=myMelody, subformats=["png"])
`
a png file is produced, but with completely wrong notes. There are no rests and the bar lines are set completely wrong 
![slowtempo_threenotes_item1](https://user-images.githubusercontent.com/46963758/53826470-f4f78b80-3f78-11e9-8ed6-f8f5f98ce486.png)
. I have no rests in my stream, indeed, but the note offsets are all set correctly.  Does anyone have a tip why lilypond cannot parse my stream correctly? The information is all there apparently as it works fine. with midi...

Thank you

**Comment by mscuthbert** [comment]
Hi -- for q and support, can you use the music21list at Google Groups.  Thanks -- you'll find that there isn't a bug here, but the User's Guide discusses this case in makeRests.
