### ISSUE TITLE
Can't configure music21 to invoke Sibelius to display MusicXML on Windows

### ISSUE THREAD

**Issue by BoarGules** [cuthbertLab/music21#380]
If I take this beginners' example

`>>> music21.converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#").show()`

on Windows the method `.show()` invokes Notepad to display the MusicXML. This lacks impact. The [user's guide](http://web.mit.edu/music21/doc/usersGuide/usersGuide_08_installingMusicXML.html) suggests that I can do `music21.configure.run()` to configure a different program to display the MusicXML:

> Run this command (after the `from music21 import *`):
> `configure.run()`
> You can say “no” to everything that is “Yes/No”, but make sure that it is finding your copy of MuseScore, Finale, or Sibelius.

I did this, but there wasn't any mention of a notation program in the dialogues, and no obvious way to make sure (or even see) that `music21` had found the notation program. Needless to say, it hadn't. 

The code of `configure.py` suggests that the reason for this is that the class `SelectMusicXMLReader` at line 1314  specifies that the search for a MusicXML renderer is only to be run on OSX:

```
def __init__(self, default=None, tryAgain=True, promptHeader=None):
    SelectFilePath.__init__(self,
                            default=default,
                            tryAgain=tryAgain,
                            promptHeader=promptHeader)

    # define platforms that this will run on
    self._platforms = ['darwin']                  # <-- errm, about the rest of us?
```
which is a odd because there exist internal class methods that perform this search on all 3 supported platforms: only, the code is not calling them.

Now, I could easily fix that by adding `'win'` to the list, and I tried that.

But even if the Windows search method is actually called, it is expecting to find the notation programs in directories pointed to by the environment variables `ProgramFiles`, `ProgramFiles(x86)`, `ProgramW6432`, which for most normal applications would be a reasonable expectation. 

But many Windows systems have an SSD boot device of modest dimensions. To install huge programs like Sibelius 7 on the boot device, with 27Gb of samples that it insists must live in `Program Files (x86)`, lies somewhere between inadvisable and impossible.

So on Windows systems, searching for the MusicXML renderer exclusively on the boot device reflects an expectation not well aligned with real-world setups. You may object, _but that is where the environment variables say to look_. I know it is an OSX/Linux habit to look for such information in environment variables, but on Windows, the place to look is the registry. The correct invocation of Sibelius 7 to open a MusicXML file, for example, is given by registry key `HKLM\SOFTWARE\Classes\Sibelius\shell\open\command`.

I can of course stomp over the code to make it look in the right place on my system. But as this issue affects all Windows users (and to a lesser extent Linux users too) I thought it proper to report it here as a bug. It is the sort of roadblock that has beginners googling the syntax for `pip uninstall`.

I think the advice in the user's guide needs amplification, since it currently tells the user what to do (_make sure that it is finding your copy of MuseScore, Finale, or Sibelius_), but not how to do it, or what to do if it doesn't.

And to this bug report and documentation fix proposal, I would like to add a feature request: please add Dorico to the list of MusicXML renderers: on Windows, registry key `HKLM\SOFTWARE\Classes\Dorico.Project\shell\open\command`.

**Comment by mscuthbert** [comment]
happy to take pull requests for any of these features.  But unlikely to make it to the dev group's feature list before 2021 at earliest if not.

**Comment by jlquispec** [comment]
https://groups.google.com/forum/#!topic/music21list/0woOce3KRy0

Setting environment path:

from music21 import *
environment.set('musicxmlPath', r'C:\Program Files\Avid\Sibelius\Sibelius.exe')

**Comment by mscuthbert** [comment]
Has any of this been tested on the newest master branch?  I believe that this is fixed.

**Comment by mscuthbert** [comment]
Closing -- no action since May, and believed to be fixed.
