### ISSUE TITLE
Incorrect link at https://web.mit.edu/music21/

### ISSUE THREAD

**Issue by lflee** [cuthbertLab/music21#390]
Under the heading **Interested in learning more?**, Get Started links to [https://web.mit.edu/music21/doc/http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html](https://web.mit.edu/music21/doc/http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html). I think it should link to [https://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html](https://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html) instead.

**Comment by mscuthbert** [comment]
thank you!  Fixed!
