### ISSUE TITLE
Unconsistency with chord syntax

### ISSUE THREAD

**Issue by DGothrek** [cuthbertLab/music21#391]
Hello, and thank you for this great package.

I was just wondering why the chord notations `F#/C#` and `F+/C#` are accepted in

```py
music21.harmony.ChordSymbol("F#/C#")
```
but not `F+/C+`

Is it a desired behavior?

Thanks in advance.

**Comment by a-papadopoulos** [comment]
`+` never means sharp (someone correct me if I'm wrong). For example, `Note('F+')` raises an `AccidentalException: + is not a supported accidental type`.
`+` is an abbreviation for an augmented triad:
```python
>>> ChordSymbol('F+').pitches
(<music21.pitch.Pitch F3>, <music21.pitch.Pitch A3>, <music21.pitch.Pitch C#4>)
```
whereas 'F#' is simple an F# major:
```python
>>> ChordSymbol('F#').pitches
(<music21.pitch.Pitch F#3>, <music21.pitch.Pitch A#3>, <music21.pitch.Pitch C#4>)
```

**Comment by mscuthbert** [comment]
Agreed!  Can @DGothrek show where this notation comes from?  We won't be able to support it in any case, but I'd like to know and if it's common in some communities I'll put it into the docs.

**Comment by DGothrek** [comment]
Hi, I'm sorry of course you are right. 
I cannot remember where I saw something that made me think this in the doc, I'll post an update here if I find it again.
Thanks.
