### ISSUE TITLE
Notes in chordify don't exist in parts

### ISSUE THREAD

**Issue by rayleigh** [cuthbertLab/music21#392]
For a project, I've been looking at the Bach chorales in music21. I ran across the following issue for `bach/bwv374`. 

If I run the following code:
```
c = corpus.parse("bach/bwv374")
for chord in c.measure(6).chordify().recurse().getElementsByClass('Chord'):
    print(chord)
```
I get the following output:
```
<music21.chord.Chord E-3 E-4 G4 B-4>
<music21.chord.Chord B-2 F4 B-4 D5>
```

On the other hand, if I run the following code:
```
c = corpus.parse("bach/bwv374")
for p in c.parts:
    for n in p.measure(6).notes:
        print(n)
```
I get the following output
```
<music21.note.Note B->
<music21.note.Note G>
<music21.note.Note E->
<music21.note.Note E->
```
In essence, one of the chords has been dropped from the part.

Based on your [documentation on chordify](http://web.mit.edu/music21/doc/moduleReference/moduleStream.html), I have the following workaround:
```
c = corpus.parse("bach/bwv374")
cChords = c.measure(6).chordify(addPartIdAsGroup = True)
for chord in cChords.recurse().getElementsByClass('Chord'):
    for p in chord.pitches:
        print(p, p.groups)
```

Then, I get the following output.
```
E-3 ['Bass']
E-4 ['Tenor']
G4 ['Alto']
B-4 ['Soprano']
B-2 ['Bass']
F4 ['Tenor']
B-4 ['Alto']
D5 ['Soprano']  
```

Interestingly enough, when I use `len(c.parts)`, I get 4. 

Because of the workaround, it's not a big issue for me. However, I wanted to open this issue to let you know about it.

**Comment by rayleigh** [comment]
I ran into an issue with the workaround as well. In measure 16, one of the chords isn't labeled correctly:

```
In [43]: cChords = c.measure(18).chordify(addPartIdAsGroup = True)

In [44]: cChords
Out[44]: <music21.stream.Part Soprano>

In [45]: for chord in cChords.recurse().getElementsByClass('Chord'):
    ...:     for p in chord.pitches:
    ...:         print(p, p.groups)
    ...:         
G3 ['Bass']
D4 ['Tenor']
G4 ['Alto']
B-4 ['Soprano']
G3 ['Bass']
D4 ['Tenor']
G4 ['Alto']
C5 ['Soprano']
F3 ['Bass']
A3 ['Tenor']
A4 ['Alto']
D5 ['Soprano']
G3 ['Bass']
B-3 ['Tenor']
E4 ['Alto']
D5 ['Soprano']
A3 ['Bass', 'Tenor']
E4 ['Alto']
C#5 ['Soprano']
**A3 ['Tenor']**
**F#4 ['Alto']**
**C#5 ['Soprano']**
A2 ['Bass']
A3 ['Tenor']
G4 ['Alto']
C#5 ['Soprano']
```
Looking at the score, the bolded section should probably be:
```
**A3 ['Bass', 'Tenor']**
**F#4 ['Alto']**
**C#5 ['Soprano']**
```

It also might be happening in `bach/bwv226.2`.

**Comment by mscuthbert** [comment]
For the first issue note that there are two measures that are numbered 6: the first contains 3 beats, the second 1 beat.   measure(6) gets only the first of the two measures here.  Might need to update docs on `.measure()` to explain that.

there may be an issue with pitches that appear in multiple parts only getting one group when split.  If you can make the most minimum score (probably 3 parts and 4 notes) that reproduces the bug, it'd help me be able to fix it faster.

**Comment by mscuthbert** [comment]
Debugging further -- Score.measure(6) gets both 6 and 6a, while Score.parts[0].measure(6) only gets 6 not 6a -- there's a reason for this, but it's likely confusing.  Note that `.measures(6, 6)` works in both cases.

**Comment by rayleigh** [comment]
I see. I tried what you suggested, but the following happens for me:

```
In [93]: len(c.parts[0].measures(6,6).notes)
Out[93]: 0

In [94]: len(c.parts[0].measure(6).notes)
Out[94]: 1

In [95]: len(c.parts[0].measures(6,7).notes)
Out[95]: 0

In [96]: for n in c.parts[0].measure(6).notes:
    ...:     print(n)
    ...:     
<music21.note.Note B->

In [97]: for n in c.parts[0].measures(6,6).notes:
    ...:     print(n)
    ...:     

In [98]: for n in c.parts[0].measures(6,7).notes:
    ...:     print(n)
    ...:

```

Also, for the most minimum score, does this help?

```
In [109]: for chord in c.measure(18).chordify(addPartIdAsGroup=True).recurse().g
     ...: etElementsByClass('Chord'):
     ...:     if chord.beat >= 3 and chord.beat < 4:
     ...:         for p in chord.pitches:
     ...:             print(p, p.groups)
     ...:             
A3 ['Bass', 'Tenor']
E4 ['Alto']
C#5 ['Soprano']
A3 ['Tenor']
F#4 ['Alto']
C#5 ['Soprano']

In [122]: for p in c.parts:
     ...:     for n in p.measure(18).notes:
     ...:         if n.beat >= 3 and n.beat < 4:
     ...:             print(str(p), n.pitch, n.beat, n.duration)
     ...:             
<music21.stream.Part Soprano> C#5 3.0 <music21.duration.Duration 2.0>
<music21.stream.Part Alto> E4 3.0 <music21.duration.Duration 0.5>
<music21.stream.Part Alto> F#4 3.5 <music21.duration.Duration 0.5>
<music21.stream.Part Tenor> A3 3.0 <music21.duration.Duration 2.0>
<music21.stream.Part Bass> A3 3.0 <music21.duration.Duration 1.0>
```

**Comment by mscuthbert** [comment]
Be sure you’re really clear on how recursion and nested streams works in music21

**Comment by rayleigh** [comment]
I just wanted to follow up. Based on your last comment, I was able to pull that information out. However, for my project, I think I need `chordify` to correctly label which parts the pitches are coming from.

As such, is this a sufficient minimal example?
```
c = corpus.parse("bach/bwv374")
cChords = c.measure(18).chordify(addPartIdAsGroup = True)
for chord in cChords.recurse().getElementsByClass('Chord'):
    if chord.beat >= 3 and chord.beat < 4:
        for p in chord.pitches:
            print(p, p.groups)
```

That should give you the following output:
```
A3 ['Bass', 'Tenor']
E4 ['Alto']
C#5 ['Soprano']
A3 ['Tenor']
F#4 ['Alto']
C#5 ['Soprano']
```

But, if you run this,
```
c = corpus.parse("bach/bwv374")
cChords = c.measure(18).chordify(addPartIdAsGroup = True)
for chord in cChords.recurse().getElementsByClass('Chord'):
    if chord.beat >= 3 and chord.beat < 4:
        for p in chord.pitches:
            print(str(p), n.pitch, n.beat, n.duration)
```
you should get this:
```
<music21.stream.Part Soprano> C#5 3.0 <music21.duration.Duration 2.0>
<music21.stream.Part Alto> E4 3.0 <music21.duration.Duration 0.5>
<music21.stream.Part Alto> F#4 3.5 <music21.duration.Duration 0.5>
<music21.stream.Part Tenor> A3 3.0 <music21.duration.Duration 2.0>
<music21.stream.Part Bass> A3 3.0 <music21.duration.Duration 1.0>
```

**Comment by rayleigh** [comment]
I just wanted to follow up on this issue. Have you had a chance to look into it some more? Or, is there more information that I can provide?

**Comment by mscuthbert** [comment]
The newest v. 5.7 release includes improvements for getting measure suffix measures from the .measures() routine.  Feel free to reopen if the improvement doesn't solve the problem.

**Comment by rayleigh** [comment]
Thanks for making those changes and adding it to the new release.
