### ISSUE TITLE
How does music21 parse multiple repeat endings from MusicXML files?

### ISSUE THREAD

**Issue by kir12** [cuthbertLab/music21#394]
I have a MusicXML piece that has two endings for a repeat, (see [here](http://web.mit.edu/music21/doc/_images/repeat-SimplifyExample_ChoraleSimplified.PNG) for an example) where the relevant portion of the `xml` file looks like
```
   <measure number="28" width="319.91">
      ...
      <barline location="left">
        <ending number="1" type="start"/>
        </barline>
      ...
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        <ending number="1" type="stop"/>
        <repeat direction="backward"/>
        </barline>
      </measure>
    <measure number="29" width="214.14">
      <barline location="left">
        <ending number="2" type="start"/>
        </barline>
      ...
```
As you can see, the `barline` objects have a specific attribute `ending` which at least *appears* to indicate that a 1st or 2nd ending bracket is written over the measure. However, examination of the [documentation for `barline`](http://web.mit.edu/music21/doc/moduleReference/moduleBar.html#barline) indicates *no mention of* `ending` as an attribute of `barline`. I also tried looking over the [documentation for `repeat`](http://web.mit.edu/music21/doc/moduleReference/moduleRepeat.html) but nothing came up either. For the purposes of ieterating through a `MusicXML` file using `music21`, how can I check and see if a measure is a 1st or 2nd ending for a repeat?

**Comment by kir12** [comment]
It has now been over a month since I first asked my question ... I would like an answer to it if possible.

**Comment by ronggong** [comment]
I am also curious about this problem.

**Comment by MarkGotham** [comment]
Hi both! Have a look at .expandRepeats() and see if that helps.

**Comment by fosfrancesco** [comment]
I'm dealing with this too. It looks like music21 don't parse multiple endings to me. Maybe I am missing something.

**Comment by fosfrancesco** [comment]
It worked! I was doing a mistake calling 

`e = m21.repeat.Expander(streamObj= score.parts[0].recurse())`
In this case all the repetitions were correctly expand, except the alternate ending.

If I do 
` e = m21.repeat.Expander(streamObj= `score.parts[0])`
then it expand also the alternate endings.
