### ISSUE TITLE
Possible to generate images in memory directly?

### ISSUE THREAD

**Issue by petercheng00** [cuthbertLab/music21#396]
Hi, I'd like to be able to generate images of music samples on the fly, and get those images as e.g. numpy arrays directly. Currently I'm doing a workaround of calling write(), and then loading the image file, which isn't great. Is there a better alternative? I also see that with jupyter notebook, show() visualizes an image directly in the notebook, but I'm not aware if there's a way to intercept the image there.

**Comment by mscuthbert** [comment]
There isn't native code to do this, but look into the guts of graph/primitives and you should be able to make a work around for this.  It's not on our roadmap, but happy to take a PR that makes it easier to do.
