### ISSUE TITLE
MusicXML: add support for (at least) fretted string tabulator

### ISSUE THREAD

**Issue by metalmike** [cuthbertLab/music21#40]
MusicXML: add support for (at least) fretted string tabulator

Steps needed: 
- [x] Add support for TABClef
- [x] Add support for 'staff-lines'
- [ ] Sub-class for Note
- [ ] Sub-class for Cord

**Comment by mscuthbert** [comment]
Any work able to happen on this? It'd be great to add or close for now and reopen later. Thanks!

**Comment by mscuthbert** [comment]
Closing for now.  Happy to reopen when @metalmike or someone else has time.
