### ISSUE TITLE
Notes from one measure jumping to another

### ISSUE THREAD

**Issue by dejawooh** [cuthbertLab/music21#405]
Hey there,
Firstly, thanks a lot for creating this amazing project. I am trying to explore the various methods and objects so that I can use this in future. I ran into an issue when trying to show the measures I created in MuseScore. here's my code.

`m3 = stream.Measure(number=3)
m4 = stream.Measure(number=4)
sScore = stream.Score(id='sScore')
sPart2 = stream.Part(id='sPart1')

n9 = note.Note('C')
n9.volume.velocity = 70
n9.quarterLength = 1.0

n13 = note.Note('C')
n13.volume.velocity = 70
n13.quarterLength = 1.0
n14 = note.Note('C')
n14.volume.velocity = 70
n14.quarterLength = 1.0
n15 = noe.Note('C')
n15.volume.velocity = 70
n15.quarterLength = 1.0

n16 = note.Note('C')
n16.volume.velocity = 70
n16.quarterLength = 1.0

m3.insert(0, n9)
m4.insert(0, n13)
m4.insert(1, n14)
m4.insert(2, n15)
m4.insert(3, n16)

sPart2.append(m3)
sPart2.append(m4)
sScore.insert(0,sPart2)`

Look at the result below
![Notes Incorrect in Measure](https://user-images.githubusercontent.com/9595168/59240383-19d34e80-8bb9-11e9-9d05-9f002777ed05.png)

I am expecting as below. 
![Corrected Notes in Measure](https://user-images.githubusercontent.com/9595168/59240445-5737dc00-8bb9-11e9-8bc9-045dac707287.png)

Here is what it prints
![Incorrect Notes Print](https://user-images.githubusercontent.com/9595168/59241119-42f4de80-8bbb-11e9-8ce2-88f32d3af004.png)

Looks like the offset printed above is not correct.
I can get it work by adding this line of code but I am not sure if that is the correct way. It can be bug in MuseScore as well but checking with you guys before I go there.
`nr = note.Rest()
nr.quarterLength = 1.0
m3.repeatInsert(nr,[1,2,3])`
prints as
![Print With Rest Notes Included](https://user-images.githubusercontent.com/9595168/59241136-53a55480-8bbb-11e9-8571-9a72c4b70879.png)

This looks perfect. 

Please let me know if this is intended functionality or is it a bug or am I missing something here.

**Comment by dejawooh** [comment]
Hey Guys- Any update? Let me know if you need further clarification on the question.

**Comment by mscuthbert** [comment]
look at the docs for measure.paddingLeft

**Comment by jacobtylerwalls** [comment]
howdy @dejawooh -- sounds like you are expecting a 4/4 default for your stream, but there is no way to know whether that is a pickup measure or whether you want there to be a gap, or whether you want to fill it with rests, or how many rests! Add a `meter.TimeSignature('4/4')` to the first measure before you add the measures to anything, and you should be golden.

**Comment by mscuthbert** [comment]
Closing for now -- this is expected behavior.  Docs could be improved.
