### ISSUE TITLE
Can't translate from .mxl to lilypond

### ISSUE THREAD

**Issue by giamic** [cuthbertLab/music21#419]
I have some compressed musicXML files that I want to export in lilypond format. When I try to do that I get an 
`AttributeError: : 'Rest' object has no attribute 'hideObjectOnPrint'`

This doesn't happen for all mxl files but it is consistently reproducible when they contain an invisible rest. Here is a minimal example:
```python
from music21 import converter

s = converter.parse('./score.xml')
s.write('lily)
```
where the file `score.xml` is attached (unzip it first)
[score.zip](https://github.com/cuthbertLab/music21/files/3426990/score.zip)

**Comment by giamic** [comment]
I actually think that I have a solution for this. In the file music21/lily/translate.py, inside the function `lySimpleMusicFromNoteOrRest(self, noteOrRest)` around line 1289, one should change
```python
        elif 'Rest' in c:
            if noteOrRest.hasStyleInformation and noteOrRest.hideObjectOnPrint:
                simpleElementParts.append("s ")
```
to
```python
        elif 'Rest' in c:
            if noteOrRest.hasStyleInformation and noteOrRest.style.hideObjectOnPrint:
                simpleElementParts.append("s ")
```

I would like to contribute and submit a pull request to correct this. Should I?

**Comment by mscuthbert** [comment]
Fixed in my copy of master and will be in the next push / release.  THANKS!
