### ISSUE TITLE
ambiguous interpretation for pitch 'B-1'

### ISSUE THREAD

**Issue by mdf-github** [cuthbertLab/music21#422]
I am interpreting the [YCAC corpus](https://ycac.yale.edu/) and the Chord column is given as a string in the following format: `<music21.chordChord B-0 B-3 D3 D4 B-1>`.  As this is from Bach's BWV596 where some pitches correspond to very low pitch codes (as low as midi=5, I believe?), the `-1` octave becomes very important.

However, when I do:

```
for i in range(30):
     print(pitch.Pitch(midi=i))
```

I get two "B-1": one for `midi=11`, and another for `midi=34`. Is there a way to determine which one is which automatically? Given that the YCAC was generated using a previous version of music21, would it be possible to fix this ambiguity in future releases?

**Comment by mscuthbert** [comment]
why not do: 

```
p = pitch.Pitch(midi=i)
print(p.name, p.octave)
```

**Comment by mdf-github** [comment]
> why not do:
> 
> ```
> p = pitch.Pitch(midi=i)
> print(p.name, p.octave)
> ```

The problem is that the CSV files that are given in the YCAC corpus have the music21 Chord instance as a string: as in "<music21.chordChord B-0 B-3 D3 D4 B-1>". It is not a music21 object, but rather maybe the `__repr__` of it.

**Comment by mscuthbert** [comment]
Then there's really nothing that can be done w/o the originals, I'm afraid.  You'll need to ask the creators of YCAC -- that's not me.
