### ISSUE TITLE
Whole note triplet duration fails equality with itself

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#429]
We have a MusicXML file that looks like this:

![image](https://user-images.githubusercontent.com/7258463/62626620-c863e900-b8f5-11e9-9bce-fef33fb6f36e.png)

When reading the file twice into different stream objects and comparing the duration of the first note (bottom staff) in both instances of the same file, the equality fails. 

```python
(Pdb) x.duration
<music21.duration.Duration 8/3>
(Pdb) n.duration
<music21.duration.Duration 8/3>
(Pdb) x.duration == n.duration
False
```

I think this is a bug or am I missing something?

**Comment by mscuthbert** [comment]
The bug is that the two tuplets have to be equal and apparently our Tuplet equality parameter isn't working properly:

```python
In [4]: t = duration.Tuplet(3, 2)                                                             

In [5]: y = duration.Tuplet(3, 2)                                                             

In [6]: t == y                                                                                
Out[6]: False
```

**Comment by mscuthbert** [comment]
Well, it was noted in the docs that Duration == Duration did not work with tuplets.  So at least it was a known limitation, not a true bug.  But it's fixed now!  Thank you!

**Comment by napulen** [comment]
I just saw the comment in the Duration.__eq__() about not having a tuplet equality test... and the commit you just did adding the equality test. That was fast! Thank you very much!

**Comment by mscuthbert** [comment]
Keep finding things like this and reporting them.  These are the sort of fundamental holes in the system that I want to fix.
