### ISSUE TITLE
exporting chordified stream to midi gives inaccurate scores

### ISSUE THREAD

**Issue by mdf-github** [cuthbertLab/music21#430]
I was able to follow the tutorial for `chordify` as given in the User Manual:

```
from music21 import *
b = corpus.parse('bwv66.6')
bChords = b.chordify()
fp = bChords.write('musicxml', fp='sample_bwv66.6.xml')
```

and I get the same results as in the tutorial. However, when I convert this to midi:
`fp = bChords.write('midi', fp='sample_bwv66.6_bchords.mid')`

and I play or open this file on Musescore, the sheet music (as well as the audio) is something very different from the xml output. Is this an issue with chordify, or with converting to MIDI in general? Thank you.

EDIT: This is definitely an issue with converting a chordified stream to MIDI. If I skip chordify and export directly to MIDI:
`fp = b.write('midi', fp='sample_bwv66.6_b.mid')`
the result is okay

**Comment by mdf-github** [comment]
By the way, if I do `b.chordify(addTies=False)` I get the correct results.

**Comment by mscuthbert** [comment]
Then probably the results you are getting are accurate but just not the ones you want.  :-)  MIDI is always going to be different than XML -- that's why it's an obsolete format for scores.  :-)

**Comment by mscuthbert** [comment]
I'll need a lot more information to reproduce, along with a minimal test case of the smallest amount of data that reproduces the problem.

**Comment by mdf-github** [comment]
Thank you. The code I mentioned above is a minimal test case:
```
from music21 import *
b = corpus.parse('bwv66.6')
bChords = b.chordify()
fp = bChords.write('musicxml', fp='sample_bwv66.6.xml')
fp = bChords.write('midi', fp='sample_bwv66.6_bchords.mid')
```

The first two chords in the XML file (with E3 connected by a tie) are somehow merged as a single chord in the MIDI file that is only equivalent to the 1st chord (so the 2nd chord disappears). In the XML file, the duration is 1/8 of a beat for both chords, but in the MIDI file, it is just the 1st chord with 1/4 beat duration.

**Comment by mscuthbert** [comment]
Hi -- the case you've submitted has 165 pitches.  A minimal score example would probably be two parts and just a few notes.  I can't debug a score this long by hand.
