### ISSUE TITLE
fingering articulation problem

### ISSUE THREAD

**Issue by marcomusy** [cuthbertLab/music21#431]
Hi I'm unable to put an offset to fingering text associated to a note. I tried different combinations but they seem to have no effect:
```python 
# ...
            an = note.Note(name)
            x = Fingering(abs(int(finger)))
            #x.placement = 'below'
            #x.style.absoluteY = 20
            #tst = style.TextStyle()
            #tst.absoluteY = 20
            #x.style = tst
            an.articulations.append(x)
```
the result is always something like:
![image](https://user-images.githubusercontent.com/32848391/63446521-a6607f80-c43a-11e9-8acb-23e27ca6f6f3.png)

Also, the example at
http://web.mit.edu/music21/doc/moduleReference/moduleArticulations.html#articulation
doesn't seem to work..
What am I doing wrong?

**Comment by mscuthbert** [comment]
What is your musicxml renderer?  Maybe it doesn't support positioning of fingering elements.

**Comment by marcomusy** [comment]
you are right!
musescore 2.3 indeed doesnt support it, the latest version 3.2 does:
![image](https://user-images.githubusercontent.com/32848391/63512291-bb451d80-c4e3-11e9-9fd7-7d722476f4ec.png)
thanks
