### ISSUE TITLE
Typo in StreamSearcher

### ISSUE THREAD

**Issue by maxrothman** [cuthbertLab/music21#435]
In this code: 
https://github.com/cuthbertLab/music21/blob/4fdac4f1bdef5c4e872f638d6e2690ca237ec9c8/music21/search/base.py#L189

`searchStream` should be `streamSearch`. The current code should raise a `NameError` if it were called, but it doesn't appear to be, which seems like a good reason to investigate.

**Comment by mscuthbert** [comment]
thanks! fixed!
