### ISSUE TITLE
XML to M21 converter sets attribute "notesize" instead of "noteSize"

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#439]
The xml to M21 converter inappropriately sets the attribute 'notesize' rather than 'noteSize' on a music21 noteStyle. This means noteSize can return None while notesize returns "cue".

>>> c._stream._elements[-2]._elements[-1]._elements[-2]._notes[0].style.noteSize
>>> c._stream._elements[-2]._elements[-1]._elements[-2]._notes[0].style.notesize
'cue'

This is because lines 3350 and 3359 of noteToXml() pass the string 'notesize' to the fourth argument of setStyleAttributes(), which is music21Names. When music21Names is not an iterable, the argument is converted by common.hyphenToCamelCase() from 'noteSize' to the incorrect 'notesize'.

I see two solutions:
- alter noteToXml() to send a tuple ('noteSize') rather than the string 'notesize' in both instances
- alter the elif condition in setStyleAttributes line 761 to:
    elif not common.isIterable(m21Names) **and '-' in m21Names**:

The second fix seems more robust. I am happy to make either fix and submit a pull request.

**Comment by mscuthbert** [comment]
Thanks! hope it works now!  Verifying the bug was real suggested an immediate solution; I'd _LOVE_ a PR that added tests for this or tested `setStyleAttributes()` better though!
