### ISSUE TITLE
parsing midi file show zero duration

### ISSUE THREAD

**Issue by burcehan** [cuthbertLab/music21#440]
Hi ,I parse a midi file using music21 ,the duraton of the note is 0.125 ,but music21 shows zero , why?
please help me
Thanks!

**Comment by mscuthbert** [comment]
I think you'll need to look at the Quantization settings for music21 midi parsing.  This is expected behavior.

**Comment by burcehan** [comment]
> I think you'll need to look at the Quantization settings for music21 midi parsing. This is expected behavior.

t

> I think you'll need to look at the Quantization settings for music21 midi parsing. This is expected behavior.


I add the quarterLengthDivisors, but it not work
the original  code is ------------stream = converter.parse(midi_file)
now the code is ---------------------stream = converter.parse(midi_file,quarterLengthDivisors=[16,3])
I read the quarterLength of the note is also zero, not 0.125
I don't know what the problem is ,please help me
Thanks!

**Comment by jacobtylerwalls** [comment]
Was midi_file a filepath string or raw data? If it was raw data you should check if it will be fixed by my pull request fixing #548

If you have the file saved to disk try passing the filepath to parse() as a workaround.
