### ISSUE TITLE
Can't open musicxml output in MuseScore; "corrupted" file

### ISSUE THREAD

**Issue by xhevahir** [cuthbertLab/music21#448]
I have a MIDI I've been using to test music21's file functions and, while music21 can read it and convert it into a plausible-looking musicxml file, the two MuseScore versions I've tried that musicxml file on (v2.3.2 and v3.3 Release Candidate) can't open it. I've attached the original MIDI file and the .mxl in a zip archive.
[Desktop.zip](https://github.com/cuthbertLab/music21/files/3688816/Desktop.zip)

**Comment by mscuthbert** [comment]
Sorry that we won't be able to debug general "this doesn't work" messages here (except under paid support plans).  I'll need you to get the bug down to what specifically is causing the error and check to see if it's already a known issue first.
