### ISSUE TITLE
Better document behavior of chordify on grace notes.

### ISSUE THREAD

**Issue by giamic** [cuthbertLab/music21#451]
If one chordifies a score containing grace notes, these get a duration equal to the one of the notes they are referring to. This seems like a wrong behavior to me: grace notes should be kept as grace notes or, at most, suppressed.

A minimal working example is just:

`converter.parse('grace.mxl').chordify().write('musicxml', fp='grace_ch.mxl')`

where 'grace.mxl' is a file containing grace notes, for example like the one attached.
[grace.zip](https://github.com/cuthbertLab/music21/files/3717888/grace.zip)

**Comment by mscuthbert** [comment]
This is currently the expected behavior, and I believe documented as such somewhere -- if not will document it.  

The reason for doing so is -- if you don't want this behavior, it is easy to remove all gracenotes from a stream:

```
notesToRemove = []
for n in s.recurse().notes:
     if n.duration.isGrace:
           notesToRemove.append(n)

for n in notesToRemove:
    n.activeSite.remove(n)
```

whereas if they were removed by default then it would be very hard to get the behavior that we currently have.

Will turn this into an issue of documenting better the behavior and the workaround.

**Comment by MarkGotham** [comment]
Thank you both - this is helpful. Grace notes have had an undue influence on something I've been working on recently, so it's good to know what it (and isn't) planned for their future!

**Comment by giamic** [comment]
Michael, would that be possible to add an option to choose the behavior? Something like `converter.parse('grace.mxl').chordify(keep_grace=False)`

**Comment by mscuthbert** [comment]
Very unlikely -- it would add an additional thing to test and keep up to date with every combination of parameters.

**Comment by wilsonify** [comment]
I submitted #742 to update 
documentation/source/usersGuide/usersGuide_27_graceNotes.ipynb

which I believe will effect
http://web.mit.edu/music21/doc/usersGuide/usersGuide_27_graceNotes.html

![image](https://user-images.githubusercontent.com/26659886/103380736-ce90d180-4ab7-11eb-9acc-488882ad9679.png)
