### ISSUE TITLE
Howto distribute music21 script without missing package warnings?

### ISSUE THREAD

**Issue by Daniel-at-github** [cuthbertLab/music21#453]
I have developed a [script](https://github.com/Daniel-at-github/abc2beep) using music21 library. This script works without matplotlib, numpy or scipy. How can I disable this warning?

~~~
music21: Certain music21 functions might need these optional packages: matplotlib, numpy, scipy;
                   if you run into errors, install them by following the instructions at
                   http://mit.edu/music21/doc/installing/installAdditional.html
~~~

Ideally disable the warning inside the script. Anything like...?
~~~ py
os.environ("MUSIC21_WARNING_MISSING_PACKAGES") = "OFF"
~~~

If this disable option is documented, please add it to http://mit.edu/music21/doc/installing/installAdditional.html

**Comment by mscuthbert** [comment]
It's currently a setting in .music21rc warnings=false.

**Comment by Daniel-at-github** [comment]
Thanks!
