### ISSUE TITLE
Using the extension mxl for compressed musicxml when writing to file

### ISSUE THREAD

**Issue by giamic** [cuthbertLab/music21#456]
I can not open MusicXML files generated from imported krn files. Whenever I try to do so, Musescore says _Cannot read file [path]: bad format_  . I tried to import those MusicXML files back into music21 and, while it eventually processes them, it gives lots of warnings:

> musicxml.xmlToM21: WARNING: Cannot put in an element with a missing voice tag when no previous voice tag was given.  Assuming voice 1... 
> musicxml.xmlToM21: WARNING: Cannot find voice 1; putting outside of voices.
> musicxml.xmlToM21: WARNING: Current voiceIds: ['139734311396297', '139734311398537']
> musicxml.xmlToM21: WARNING: Current voices: [<music21.stream.Voice 139734311396297>, <music21.stream.Voice 139734311398537>]

This same warning is repeated identical several times for each score.

The code I'm using is the following:
```
from music21 import converter

path_krn = 'score.krn'
path_mxl = 'score.mxl'
converter.parse(path_krn).write('mxl', fp=path_mxl)
```

The following krn file of [a Bach chorale](https://kern.humdrum.org/cgi-bin/ksdata?file=chor001.krn&l=users/craig/classical/bach/371chorales&format=kern) would do just fine to test.

**Comment by giamic** [comment]
I actually already found the problem, sorry for spamming.

Music21 will output a plain MusicXML file and not a compressed version, which is commonly associated with the mxl extension. Musescore, when opening the file, will expect a compressed MusicXML and get crazy. The solution is simply to change the extension of the output file to 'xml'. BTW, the warnings when importing the MusicXML with music21 won't go away.

I think that the association of the extension 'mxl' with compressed MusicXML is strong enough to cause misunderstandings, like in this case. Maybe one should stop accepting 'mxl' as the format for `score.write(format, fp)`, instead raising an error? Something like 

> Music21 doesn't support compressed MusicXML as output files. You can choose uncompressed MusicXML by specifying as format 'xml'

**Comment by mscuthbert** [comment]
Indeed -- that is a good thing to have.  We do support writing compressed musicxml files -- could you change the title of this issue to reflect the problem and I'll leave it open until I can get to it (or someone else can pick it up).

I will also sometime before releasing v6 make .musicxml the new default extension for uncompressed files.

**Comment by giamic** [comment]
I'm not sure I understand what you mean when you say that writing compressed musicxml is supported: choosing 'mxl' as a format redirects to standard musicxml. Anyway, I hope that the new issue name reflects the problem you have in mind.

**Comment by MarkGotham** [comment]
Thanks @jacobtylerwalls !

 For everyone's quick reference the magic word is 'compress', now settable at the point of writing like this:

`score.write(fp='/Path/To/Your/File', compress=True)`

**Comment by jacobtylerwalls** [comment]
Absolutely, or even just score.write('mxl')!

**Comment by MarkGotham** [comment]
Nice!
