### ISSUE TITLE
KeyAnalyzer.smoothInterpretationByMeasure key miss 

### ISSUE THREAD

**Issue by ZM-J** [cuthbertLab/music21#463]
In `music21.analysis.floatingKey.KeyAnalyzer`, we have method `smoothInterpretationByMeasure` to predict tones. In floatingKey.py line 129, we have `newInterpretations[k]` to get a value in a dict using a key. However, the dict generated from `getInterpretationByMeasure` cannot guarantee that the generated keys are complete.

In discrete.py, there is a method called `process` in line 598 which give us the prediction result and confidence by keys generated by `self._likelyKeys(sStream)`. In `_getLikelyKeys` method in line 395, the library uses `someList.index(someEntry)` method to look up the original position of the sorted list, which is inappropriate, especially in condition that the confidence has a tie.

E.g., construct a bar whose `pcDistribution` is [2.0, 2.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], say, 'C C D- D-'.
The confidence of this bar being of g minor is exactly equal to that of being of g# minor. So the `_getLikelyKeys` will return a result with 2 g minor prediction, rather than that with 1 g minor prediction and 1 g# minor prediction, triggering error in `smoothInterpretationByMeasure` method.

**Comment by ZM-J** [comment]
```python
import unittest
from music21 import *

class Test(unittest.TestCase):
    def KeyAnalyzer(self):
        s = stream.Stream()
        # Measure 1
        s.append(note.Note('C5', type='quarter'))
        s.append(note.Note('D5', type='quarter'))
        s.append(note.Note('F5', type='quarter'))
        s.append(note.Note('G5', type='quarter'))
        # Measure 2
        s.append(note.Note('C5', type='quarter'))
        s.append(note.Note('C5', type='quarter'))
        s.append(note.Note('C#5', type='quarter'))
        s.append(note.Note('C#5', type='quarter'))
        # Measure 2
        s.append(note.Note('D5', type='quarter'))
        s.append(note.Note('D5', type='quarter'))
        s.append(note.Note('E5', type='quarter'))
        s.append(note.Note('E5', type='quarter'))

        m = s.makeMeasures()

        ka = analysis.floatingKey.KeyAnalyzer(m)
        ka.windowSize = 4
        res = ka.run()

        self.assertEqual(len(res), len(m.elements), 'Length of result should be the same as that of measures')

if __name__ == "__main__":
    t = Test()
    t.KeyAnalyzer()
```

First of all, it will get exception. Second, the assertion will fail.

**Comment by mscuthbert** [comment]
Thanks to all for this!
