### ISSUE TITLE
ambiguity in syntax for specifying pitch + octave due to flat being '-'

### ISSUE THREAD

**Issue by bwagner** [cuthbertLab/music21#481]
There's an ambiguity in the syntax for specifying pitch and octave due to **flat** being specified as **'-'**. The '-' from a following negative integer indicating the octave gets conflated into a flat.

Example 1:
```
p1 = pitch.Pitch()
p1.midi = 0
p2 = pitch.Pitch(p1.nameWithOctave)
p1.accidental == p2.accidental
-> False
```

Example 2:
```
note.Note(note.Note("B2").transpose(+48).nameWithOctave).transpose(-48).pitch.accidental == note.Note(note.Note("B2").transpose(-48).nameWithOctave).transpose(+48).pitch.accidental
-> False
```
A solution would be to define a symbol for flat that has no ambiguity with the following integer. A candidate would be underscore: '_'.

**Comment by mscuthbert** [comment]
This case is covered in the user's guide.  Such a massive breaking change is impossible with tens of thousands of active users.  There are easy ways around the case you've given such as setting the name and octave separately.  It is what we do in the music21 code.
