### ISSUE TITLE
wrong figure for transposed chords

### ISSUE THREAD

**Issue by a-papadopoulos** [cuthbertLab/music21#486]
I've found a little issue with the transpose method for `ChordSymbol`s. Basically, the `transpose()` method isn't being redefined in `ChordSymbol`, and as a result, the figure is not updated.
```
c = ChordSymbol('Am')
c = c.tranpose(5)
c.figure
```
still returns 'Am', even if `c.findFigure()` correctly returns 'Dm'. The only way I've found around this is to manually set `c._figure = None` to force `c.figure` to recompute the figure, but that's not very satisfying, plus I might be missing other stuff.
Am I doing something wrong?

**Comment by mscuthbert** [comment]
Nope -- this isn't supported yet, but SHOULD BE!  :-)  Can we get your other PR into the system first -- we just needed to unify the sort mechanism and we'd be set.  Then this is something to work on.  

One cool thing about ChordSymbols and transposition by diatonic or chromatic intervals is that it changes only the note name not the quality.  So:

Am  + P5 = Em
Am + 5 (semitones) = Dm

but do we then need to transpose by generic intervals?

Am + Generic 2nd = B...dim? B- maj?

But transposition by generic intervals might not be possible or simply doing the same routine and keeping the quality might be "good enough for now"
