### ISSUE TITLE
The problem of stream.analyze('key')

### ISSUE THREAD

**Issue by fnyhy** [cuthbertLab/music21#493]
Hello! The problem happened when I use the stream.analyze('key') to achieve the key info of a midi file. The KEY_SIGNATURE event is as followed but the function result is <music21.key.Key of D major>.
<MidiEvent KEY_SIGNATURE, t=None, track=0, channel=None, data=b'\x04\x00'>
Other midi files with the same KEY_SIGNATURE event get the result <music21.key.Key of E major>.

**Comment by mscuthbert** [comment]
Analyze key has nothing to do with key signature -- it's using the K-S probe-tone algorithm to determine the key.
