### ISSUE TITLE
Wrong scaleDegreeWithAlteration for augmented sixth chords

### ISSUE THREAD

**Issue by giamic** [cuthbertLab/music21#495]
The root for augmented sixth chords such as Italian, German, or French 6th is conventionally considered to be the raised fourth. For example, for a German sixth in a minor, the root is D#. This is correctly implemented in music21. However, if one asks for the scaleDegreeWithAlteration, one obtains the tuple (4, None), indicating the diatonic fourth degree. I'm no musicologist so I might be wrong, but it feels like this is a mistake?

MWE:

```
>>> import music21
>>> c = music21.roman.RomanNumeral('Ger65', 'a')
>>> c.root()
<music21.pitch.Pitch D#6>
>>> c.scaleDegreeWithAlteration
(4, None)
```

**Comment by mscuthbert** [comment]
That does seem wrong.  The question is what's the correct answer -- `(4, <sharp>)` is certainly better than the current, but I want to be sure that this is the best answer.

Also need to check that `N6` gives `(2, <flat>)`
