### ISSUE TITLE
Calling converter.parse in script fails with AttributeError

### ISSUE THREAD

**Issue by xhevahir** [cuthbertLab/music21#508]
I'm trying to tally the chordKinds on every score in a directory, but I can't figure out what to do about this AttributeError: '_io.TextIOWrapper' object has no attribute 'startswith'. Here's the code:

path = r'/home/xhevahir/Desktop/MXLs
        
    for filename in os.listdir(path):
        with open(os.path.join(path, filename)) as f:
            s = music21.converter.parse(f)
            for thisSym in s.flat.getElementsByClass(harmony.ChordSymbol):
                print(thisSym)
                if thisSym.chordKind == 'dominant-seventh':
                    dominant_seventh += 1
                elif thisSym.chordKind == "major-seventh":
                    major_seventh += 1

Apologies if I've missed something that's basic Python.

**Comment by mscuthbert** [comment]
converter.parse takes in a filename not a filehandle.
