### ISSUE TITLE
make corpus a separate package

### ISSUE THREAD

**Issue by gesellkammer** [cuthbertLab/music21#510]
the corpus adds 65 mb to the music21 package. It would be desirable to move the corpus to its own package to make it optional.

**Comment by mscuthbert** [comment]
It is already optional.  Download the no-corpus version of music21 from here.

**Comment by gesellkammer** [comment]
Could that be be uploaded to pypi? As such it would be pip installable and can be used as install_depends inside other projects' setup.py

**Comment by bjourne** [comment]
I could also use a no corpus version. I have so little space on my remote filesystem.

**Comment by mscuthbert** [comment]
Hi all -- this is a big issue that would increase my development time substantially, so it's not likely to happen without external funding.  Thanks!
