### ISSUE TITLE
When generating xml, barline disappeared.

### ISSUE THREAD

**Issue by CreadDiscans** [cuthbertLab/music21#519]
I added barline and checked it like this.

```
...
{28.0} <music21.stream.Measure 7 offset=28.0>
        {0.0} <music21.note.Note C>
        {4.0} <music21.bar.Barline type=double>
```

After that, I generated xml

```
GEX = music21.musicxml.m21ToXml.GeneralObjectExporter(m21_score)
out = GEX.parse()
outStr = out.decode('utf-8')
```

But the xml didn't have the barline.

```
...
<measure number="7">
      <note>
        <pitch>
          <step>C</step>
          <octave>5</octave>
        </pitch>
        <duration>40320</duration>
        <type>whole</type>
      </note>
</measure>
...
```

**Comment by mscuthbert** [comment]
Can you give a minimum set of commands with no loading of external files that replicates the problem?  Does the problem happen with .write('musicxml') -- if it does not happen then it's probably the structure of the score.

**Comment by jacobtylerwalls** [comment]
@CreadDiscans try setting `.rightBarline`:

```m21_score.measure(7).rightBarline = bar.Barline(type='final')```

**Comment by CreadDiscans** [comment]
@jacobtylerwalls Thanks.

**Comment by jacobtylerwalls** [comment]
np!
`makeMeasures()` is the other thing you can try rather than manually setting `.rightBarline` if you've been adding a number of them.
