### ISSUE TITLE
converter.parse() fails to convert <bytes> of compressed musicxml (.mxl)

### ISSUE THREAD

**Issue by trantinan2512** [cuthbertLab/music21#520]
converter.parse() is unable to parse bytes like data from file's `.read()` method of .mxl files, it works with .musicxml files however.

```py
# file is musicxml (uncompressed) => works
fd = open('path/to/file.musicxml', 'rb')
f = music21.converter.parse(fd.read())

# file is .mxl (compressed musicXML) => does not work
fd = open('path/to/file.mxl', 'rb')
f = music21.converter.parse(fd.read())
```

He's the traceback of the exception
```bash
File "...\lib\site-packages\music21\converter\__init__.py", line 608, in parseData
    dataStrMakeStr)
music21.converter.ConverterException: File not found or no such format found for: PK upSÖw         META-INF/container.xmlU0@wr;T76W=SL&8ge
[;'Tm7Hf~7c+PK upSO'  %    file.xml][s븑~_ջ wn8dfR$SI摖c%d;ί_PWxAIˌ	Q׍{m&Q|XߦI]Voӿ̟߿49,wq4ۇs}&w'|?
Xǻv7y?yj#U=_Ⱦr{GqO_t{Q<}z.'?ūp_]>l[t<'_p̾r
ar>1&gg1ݹ.~v
... and a lot more of characters like above
```

---

I'm making a website that is powered by music21 in the backend to convert mxl files (obtaining from user uploaded content) to format that my app can read.

I have a work-around for this (by uploading to my cdn and use parseURL to parse), and am using it for now, until this is fixed, or someone shows me how to do it the local way :D

**Comment by mscuthbert** [comment]
These are the types of things that you're going to need to go lower level and look at the converter.subconverters.MusicXMLConverter or even deeper to musicxml.xmlToM21 directors.  converter.parse() is designed for simpler cases than this.  It's not something we'll be able to change here.

**Comment by trantinan2512** [comment]
I figured out the way to parse bytes-like object for this. Here's a code snippet for it if you're interested.
```py
file_buffer = file.read()
# file is .mxl
if file.content_type == 'application/vnd.recordare.musicxml':
    # make a zip file from buff by using BytesIO
    z = zipfile.ZipFile(io.BytesIO(file_buffer))
    # get the actual xml file from zip archive
    for index, zipname in enumerate(z.namelist()):
		if 'META-INF/container' in zipname:
			continue
		file_buffer = z.read(z.infolist()[index])
```

**Comment by mscuthbert** [comment]
thank you!  It may be possible in ArchiveTools to add a routine that can take in a buffer of compressed musicxml and return a buffer of musicxml or something of that sort?

**Comment by trantinan2512** [comment]
Yes, for now `ArchiveManager` only allows `fp` as its first argument and bytes-like object is parsed into `str` using the `.parse()` method. Adding a route would be doable.
I will try to make a pull request for this if possible 😄
