### ISSUE TITLE
Generated midi file looks awful when there are some staccatos

### ISSUE THREAD

**Issue by Shoko-Makinohara** [cuthbertLab/music21#531]
It should be 
![image](https://user-images.githubusercontent.com/58494957/80318259-855af480-883b-11ea-92f4-ab51bf798aec.png)
rather than
![image](https://user-images.githubusercontent.com/58494957/80318265-8db32f80-883b-11ea-9205-17589b19b361.png)

**Comment by mscuthbert** [comment]
Hello Shoko, thank you for the note -- I think you've misunderstood what music21 is for.  It's not for converting MIDI to notation;  The midi input is a convenience.  It is generally better to use a dedicated MIDI to Notation converter first before loading into music21 (or don't use MIDI and use MusicXML instead).

I use Finale when I need to get one piece right.  And I use MuseScore when I need to convert a whole directory.  These do better than music21.

母は沖縄出身です。だから私はいつも日本のユーザーを助けたいと思っています。  :-) <3

**Comment by Shoko-Makinohara** [comment]
@mscuthbert Hello Cuthbert! Thanks a lot for your reply:) In fact, I'm working with algorithmic composition these days. When I'm using deep learning techniques, the first thing for me it to make a bridge between music and machine / midi files and neural networks. I was looking for a toolkit to convert midi files to notation, and vice versa. After trying all the python packages, I found music21 was the best. But there are some flaws so that I cannot use it directly...  
Now my pipeline is: midi files --**MuseScore**--> musicxml --**Music21**--> notes/chords/rests --ML system--> --**Music21**--> midi file. It might be the best solution at the present.

**Comment by jacobtylerwalls** [comment]
See #811 for some discussion toward avoiding gaps from stream quantization. If the source MIDI actually had note off messages halfway through the eighth note, then the stream representation is probably correct. Thanks for the note, we can continue discussion at #811 if you like.
