### ISSUE TITLE
Suggest removing @property on a few items in class StreamIterator

### ISSUE THREAD

**Issue by pkirlin** [cuthbertLab/music21#536]
There are a number of functions in `StreamIterator` that are tagged with the `@property` decorator, including `notes()`, `notesAndRests()`, `parts()`, etc.  These functions, when called, modify a `StreamIterator` to add a filter to it.  

This creates a slight problem when music21 is used in an IDE that assumes any function with the `@property` decorator can be called without inherently modifying the object's state.  I believe PyCharm makes this assumption, and therefore it causes problems when inspecting a `StreamIterator` object during debugging or in an interactive session.

In particular, PyCharm includes a window listing all active variables, and when inspecting a `StreamIterator` object, all of the object's instance variables, *including properties*, are examined.  This effectively calls `notes()`, `notesAndRests()`, `parts()`, etc on all StreamIterator objects when they are inspected, which then affects the way those objects work as the program keeps running, because now a bunch of filters have been added to the `StreamIterator`.  Effectively, this breaks any `StreamIterator` object during any sort of debugging or interactive session, because when PyCharm inspects the object, six filters are added (notes, notesAndRests, parts, spanners, variants, and voices), and this therefore filters out *all* objects from the `StreamIterator`, which is most likely not what the user intended.

I don't have a good work-around or solution to this, as no-doubt many people rely on calling these functions as properties and not as functions, so removing the decorator would be problematic.  But I wanted to bring this to people's attention.

**Comment by pkirlin** [comment]
Small example:

```python
from music21 import *

score = stream.Score()
score.append(note.Note('C'))
score.append(note.Note('D'))
score.append(note.Note('E'))
score.append(note.Note('F'))

iter = score.iter
```

After running this code, when I look in Pycharm, I see the following filters have been added:

![image](https://user-images.githubusercontent.com/18583940/80840501-14149c00-8bc3-11ea-9544-e72ce8a374b2.png)

**Comment by mscuthbert** [comment]
yeah, I know that and it was a design mistake at the start..  Unfortunately, it's already used in thousands of lines of code everywhere so there's nothing that can be done about it at this point.  

Having .flat be a property on Stream is a particular annoyance.

Most IDEs have some way to ignore reporting on properties; I haven't used the debugger in PyCharm, so I don't know if there's something I can add that will make PyCharm not look at the property.

**Comment by pkirlin** [comment]
Thanks for your reply, @mscuthbert.  I'll see if this can be turned off in PyCharm.  Maybe down the road there's a chance of deprecating them, but I understand right now it's staying.  Thanks for all your hard work.

**Comment by mscuthbert** [comment]
I don't think it'll ever be possible to deprecate them.  It's almost as bad a problem as what I should've done with Notes/Chords (Notes are Chords with exactly one pitch), but it's in that realm.  At least it's slightly easier than "Python should be 1-indexed"  :-)

**Comment by mscuthbert** [comment]
Maybe there'll someday be a substantial breaking version of music21 -- but it'd be worse than Python 3 was and might permanently split the community (Perl 6!)

**Comment by mscuthbert** [comment]
Aha!  PyCharm is on it:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000016220-How-to-disable-automatic-variable-evaluation-when-debugging-

https://youtrack.jetbrains.com/issue/PY-39729?_ga=2.123447554.824529241.1588532717-2126218008.1588532717

**Comment by mscuthbert** [comment]
Actually, I can think of something that might be possible and be a breaking change to far fewer people AND probably be something that should have been the initial design choice:  I could make each of those properties return a new StreamIterator with the appropriate filter added.  Then the only people affected would be those who depend on things like:

```
x = s.recurse()
x.notes
for n in x:
    ...
```

to me that second line (`x.notes`) as having side effects has always looked a bit funny.  

This is something I'd be willing to change for v6 of Music21.

**Comment by pkirlin** [comment]
Super! Yeah, it's exactly the idea of a @property having side affects that seemed off.

**Comment by mscuthbert** [comment]
All set now, I think!
