### ISSUE TITLE
Get Started Link Broken

### ISSUE THREAD

**Issue by GadgetSteve** [cuthbertLab/music21#538]
On the web page http://web.mit.edu/music21/ there is a Get Started link under "Interested In learning more" to:
`http://web.mit.edu/music21/doc/http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html` 
this should link to:
`https://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html` 

Looking at the raw html show the link as `doc/http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html` which is presumably a result of mixing relative and absolute anchors.

**Comment by mscuthbert** [comment]
Thank you!  I've had so much problems with this static site -- I'll be switching it out soon, but thanks for finding this. 

Should be fixed in an hour or so when the next push takes place.

**Comment by mscuthbert** [comment]
closing even though it's sort of whack that the top Get Started link goes to one page and the bottom Get Started link goes to another...  Thanks GadgetSteve!
