### ISSUE TITLE
Strange behavior with ties when accessing Bach chorales from music21.corpus.chorales

### ISSUE THREAD

**Issue by asdfang** [cuthbertLab/music21#543]
I have a Counter object counting up the durations from notes and rests from a chorale:
```
def get_rhythm_histogram(chorale):
    rh = Counter()
    for note_or_rest in chorale.flat.notesAndRests:
        rh[note_or_rest.duration.quarterLength] += 1
    return rh
```

When I retrieve the chorale from music21.corpus.chorales:
```
b = music21.corpus.parse('bwv' + str(music21.corpus.chorales.ChoraleList().byRiemenschneider[16]['bwv']))
print(get_rhythm_histogram(b))
# outputs: Counter({1.0: 193, 0.5: 96, 3.0: 7, 2.0: 5})
```

However, when I first write the chorale to midi and _then_ parse it, e.g.
```
chorale_mid = '16.mid'
chorale = music21.converter.parse(chorale_mid)
print(get_rhythm_histogram(chorale_mid))
# outputs: Counter({1.0: 188, 0.5: 95, 2.0: 6, 3.0: 6, 1.5: 1, 5.0: 1})
```

The output for 'b' is what one would get if ties were taken out, and the original tied note is then split up into two separate notes. My guess is that since we retrieve `music21.stream.Score`'s from `music21.corpus.chorales`, ties are lost in accurately formatting notes across `music21.stream.Measure`'s. I understand the need to preserve the `Score` format, but at least I think it shouldn't split tied notes apart after calling `flat`. And, when writing to then reading from midi, the simplified notes and durations is what is preserved, and not the `music21.stream.Score` format.

**Comment by mscuthbert** [comment]
Sorry, I'm going to need a more concise explanation of what you perceive to be the problem -- my guess is that this has nothing to do with Bach or rhythm histograms, etc., but is about whether tied notes should count as notes or not; music21 has an ecosystem of thousands of programmers who depend on this behavior staying constant.  So my guess is that .stripTies() is what you are looking for.

**Comment by asdfang** [comment]
Ah, it was. Thank you!
