### ISSUE TITLE
Support <arpeggiate/> for xmlToM21.py

### ISSUE THREAD

**Issue by ponpondev** [cuthbertLab/music21#547]
Is this planned?
If I could make a pull request to support this, what should I do, to be exact: In musicXML arpeggio lives in the `<notations/>` tag, but `music21` puts extra elements in `articulations`. So for the pull request I should make an `Arpeggiate` class inside `articulations`?
There are working parsers in the file so I guess it's worth a shot. I just want to know your opinion before making it for extra cover :D

**Comment by mscuthbert** [comment]
Hi!  I would very much like to have this, but don't have any immediate plans to do it myself.  What I ask is that new contributions try to do both input and output -- so both xmlToM21 and m21ToXml -- I think that it makes testing easier.

Let's call the class `ArpeggioMark` -- Googling Arpeggiation Symbol/Arpeggio Sign/etc. suggests that "arpeggio mark" is the most commonly used term.  I think that it'd be better thought of as an Expression in the expressions.py and in the `.expressions` list than an articulation.  It's probably not an Ornament, but like an ornament it can [eventually] have a "`realize()`" method which could turn it into an actual rolled chord.  

Thanks!

**Comment by mdsjazz-kena** [comment]
If anybody else would like this feature and it hasn't been resolved, I am willing to implement it myself. I need it for my own musical analysis. @mscuthbert let me know if you would like to discuss this, and whether or not you have particular design choices other than what I'll do, which is likely try my best to emulate the rest of the code. Assuming it works, would you want it to be added to the music21 suite?

**Comment by jacobtylerwalls** [comment]
Hello! It's always great to have more contributors. If you want some feedback you can always open a draft PR before it's polished to make sure it's on the right track. I'm sure you've already noticed where the stubs are e.g. `# TODO: arpeggiate` in both the input and output modules. I would advise to strike while the iron (of interest) is hot! Best/Jacob

**Comment by gregchapman-dev** [comment]
@mdsjazz-kena Was there ever any progress on this?  I'd like to take a shot at it.

**Comment by gregchapman-dev** [comment]
> Let's call the class ArpeggioMark -- Googling Arpeggiation Symbol/Arpeggio Sign/etc. suggests that "arpeggio mark" is the most commonly used term. I think that it'd be better thought of as an Expression in the expressions.py and in the .expressions list than an articulation. It's probably not an Ornament, but like an ornament it can [eventually] have a "realize()" method which could turn it into an actual rolled chord.

Any ideas how to handle cross-staff arpeggios?  Should there be a Spanner version of ArpeggioMark?  What should it be called?

<img width="213" alt="CrossStaffArpeggio" src="https://user-images.githubusercontent.com/75333244/177053829-9736d252-2f82-4d26-8bb8-5f8727dc6e43.png">

**Comment by mscuthbert** [comment]
ArpeggioMarkSpanner would be the best name.

**Comment by mdsjazz-kena** [comment]
> @mdsjazz-kena Was there ever any progress on this? I'd like to take a shot at it.

Hey @gregchapman-dev ! Sorry to be the bearer of bad news, but I didn't even touch this. I'm pretty sure I had a two-month-long work emergency start that very day. 

I might be interested to jump into this if you wanted to collaborate, but otherwise I have faith you'll make swift work of it. Thanks for checking.

**Comment by mscuthbert** [comment]
Thanks to @gregchapman-dev for the Amazing PR.  Super great!
