### ISSUE TITLE
update documentation : ```durationToMidi``` function

### ISSUE THREAD

**Issue by johncwok** [cuthbertLab/music21#555]
The formerly named ```durationToMidiTicks``` function now named ```durationToMidi``` is still referenced by it's old name in the doc.

**Comment by mscuthbert** [comment]
??  There is a function called durationToMidiTicks still -- where are you seeing it has been changed?

**Comment by mscuthbert** [comment]
Pinging @johncwok again.  Closing for now, but reopen if still a problem.
