### ISSUE TITLE
suggestion: add beat() method to voiceLeading.Verticality

### ISSUE THREAD

**Issue by snarrenberg** [cuthbertLab/music21#573]
Could the following be added to the methods of Verticality in the voiceLeading module? I'm finding it very useful in sorting out whether a sonority is on or off the beat in analyzing counterpoint.

```python
def beat(self, leftAlign=True):
    '''
    returns the overall beat of the Verticality, either the beat of the 
    earliest offset (leftAlign=True)
    or the beat of the latest (leftAlign=False)
    '''
    if leftAlign:
        return sorted(self.objects, key=lambda m21Obj: m21Obj.beat)[0].beat
    else:
        return sorted(self.objects, key=lambda m21Obj: m21Obj.beat)[-1].beat
```
Robert Snarrenberg

**Comment by mscuthbert** [comment]
I'll consider a pull-request, but some things would need to change:  (1) we won't have a method called beat which will be confused with the property called beat, so it needs another name.  (2) it needs to consider what to do in the situation that ther eare no objects in the verticality.  (3) need the redundant code factored out.  (4) tests and example code.  Thanks!

**Comment by mscuthbert** [comment]
Thinking a little more -- in what case would, say 4/4 with a whole note in it, would someone expect Verticality-at-1.5 to return beat = 1 instead of 2.5?  I'm trying to understand the use case for this.

**Comment by snarrenberg** [comment]
A couple of these issues also arise, I think, with the voiceLeading.Verticality.offset() method. It, too, has a name that duplicates a property. And I can't imagine at the moment what use there is for leftAlign=True with either the offset() method or my proposed beat() method. But verticality.beat(leftAlign=False) could be useful if, say, you want to find all of the verticalities that are on the beat or all those that are off the beat. So, for example, in second or third species counterpoint in two parts, I want to know what percentage of off-the-beat sonorities are dissonant, I can just loop through all the verticalities, count the offbeat ones that are dissonant, and divide that number by the length of the verticality list. Perhaps I'm missing an easier way to locate offbeat verticalities?

**Comment by mscuthbert** [comment]
If s is a Stream, what does this do that `[c.beat for c in s.chordify().recurse().getElementsByClass('NotRest')]` wouldn't do?  Just want to be sure.

**Comment by snarrenberg** [comment]
I'll work with that and see whether it does the trick. May take me a while, given the exigencies of prepping for online teaching ...

**Comment by mscuthbert** [comment]
Hi @snarrenberg -- let me know if that works; I'll close this for now, because I think it should solve your issue, but feel free to reopen if need be.
