### ISSUE TITLE
voicesToParts

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#575]
voicesToParts seemingly doesn't transfers initial time and key signatures if the first measure doesn't contain a second voice (even if subsequent measures do).

The images show how this looks when opened in MuseScore, (some other notation softwares will 'correct' the issue, masking the problem).

![Before](https://user-images.githubusercontent.com/19486660/87411703-fe0e5900-c5bf-11ea-822a-7f71bea1a8b2.png)
![After](https://user-images.githubusercontent.com/19486660/87411716-023a7680-c5c0-11ea-8a09-f2ddb1551ec3.png)

**Comment by jacobtylerwalls** [comment]
I took a look and `Barlines` don't propagate either, even when voices are present, due to a typo where the code is looking for the module `Bar` instead of the class `Barline`.

**Comment by mscuthbert** [comment]
Thanks @jacobtylerwalls and also @MarkGotham !  Merged.
