### ISSUE TITLE
Missing measureNumber information in spanners

### ISSUE THREAD

**Issue by deepio** [cuthbertLab/music21#579]
I expected the measureNumber of the first tag of a spanner pair to be returned but instead i'm presented with None. Is this by design? 

```python
file_ = music21.converter.parseFile("./hairpins_1.xml")

for part in file_.recurse().getElementsByClass("Part"):
	for span in part.recurse().getElementsByClass("Spanner"):
		print(span.measureNumber)  # Only returns none? 
```

But when I do the following, I get the measures correctly. Why is this? 
```python
for part in file_.recurse().getElementsByClass("Part"):
	for measure in part.recurse().getElementsByClass("Measure"):
	        print(measure.spanners.measureNumber)
```

**Comment by mscuthbert** [comment]
Spanners tend to be collected at the beginning of the piece, so for your first code look at the measure number of the first (or last) spanned element:

print(span.getFirst().measureNumber)
print(span.getLast().measureNumber)

Spanners are spanners because they don't fit neatly in a measure.
