### ISSUE TITLE
ScoreExporter resets measure offsets if measures aren't contained in Parts 

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#580]
Based on a case from music21 list, Jan 2019:

```
s = stream.Score()
s.append(meter.TimeSignature('1/4'))
s.append(note.Note())
s.append(note.Note())
s.show()
```

<img width="249" alt="Screen Shot 2020-07-20 at 4 36 45 PM" src="https://user-images.githubusercontent.com/38668450/87983976-3eca0e80-caa7-11ea-8f08-832a6211b36f.png">

`ScoreExporter.setPartsAndRefStream()` resets offsets on substreams and transfers those offsets to the contained elements, but here, the substreams are Measures, not Parts--meaning this stream isn't totally well-formed. Still, it would be simple to handle Measures differently in this routine.

**Comment by mscuthbert** [comment]
I'm wondering if Score().show('musicxml') should eventually raise an Exception if it is not well-formed?  Fixing all the whackamoles on this could be a job for a lifetime (what if there's a note in a measure in a voice (not vice versa) in a score?)  But nice to accept the PR for this if it works.

**Comment by jacobtylerwalls** [comment]
Being permissive is nice, so I could see the value in an ugly print statement rather than raising Exceptions. Otherwise issue tickets will proliferate. Something like: `stream failed isWellFormedNotation() -- conversion prone to errors`

**Comment by mscuthbert** [comment]
I'm generally against prints for conveying information, since they are so hard to catch and hide -- a warning would be better, but almost no one runs Python in Warning mode.  So let's just leave alone for now.
