### ISSUE TITLE
Trouble linking MuseScore 3 to music21

### ISSUE THREAD

**Issue by dasklavier** [cuthbertLab/music21#587]
**Problem summary**
.show() is pulling up an OSError when I try to use MuseScore 3 as an xml reader.
I am on windows 10, using anaconda 3 through the Jupyter Notebook

I have coded the environment to the exact path of my MuseScore3 application as follows 
```
env['musicxmlPath'] = 'C:\Program Files\MuseScore 3\bin\MuseScore3.exe'
env['musescoreDirectPNGPath'] = 'C:\Program Files\MuseScore 3\bin\MuseScore3.exe'
```
But I am receiving this error:

```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Program Files\\MuseScore 3\x08in\\MuseScore3.exe'
```
Additionally, when I ran configure.run() earlier in the same notebook, it did not prompt me for a musicxml reader location. I'm not sure if it is supposed to or not, but that is implied in the documentation.

Thanks!
ds

**Comment by mscuthbert** [comment]
put an `r` before your quotes on windows.
