### ISSUE TITLE
Null value when try to write musicXML (score-part element)

### ISSUE THREAD

**Issue by BerdinEge** [cuthbertLab/music21#588]
**music21 version**

`5.7.2`   

**Problem summary**

When I convert a midi file to stream and write it as a musicXML file, musicXML file's score-parts of the Partlist element are null.

**Steps to reproduce**

```
stream = converter.parse('A_PATH/name.mid')
stream .write('musicxml', 'A_PATH/name.xml')
```

**Expected vs. actual behavior**

Expected:
```
<score-part id="P1">
      <part-name print-object="no">Voice</part-name>
      <score-instrument id="P1-I6">
           <instrument-name>Voice</instrument-name>
           <instrument-sound>voice.vocals</instrument-sound>
      </score-instrument>
      <midi-instrument id="P1-I6">
           <midi-channel>1</midi-channel>
           <midi-program>55</midi-program>
           <volume>80</volume>
           <pan>0</pan>
      </midi-instrument>
</score-part>
```
Actual:
```
<score-part id="P7405f5e02cbdff2ce4f225216b93bacd">
      <part-name />
</score-part>
```

**More information**

Windows 10 Home.
It looks like music21.Parser cannot read score-part's internal elements' data from MIDI file or stream.write() method cannot write the data read from MIDI.

**Comment by mscuthbert** [comment]
We we need something more specific -- MIDI files get read into music21 and output as MusicXML thousands of times a day.  There is probably something particular about your MIDI file that is causing the problem.  What does `stream.show('text')` show has been read in?

P.S. -- using stream as a variable name is highly discouraged, because it prevents access to the `stream` module.

**Comment by BerdinEge** [comment]
I downloaded and unzipped the xmlsamples.zip from https://www.musicxml.com/music-in-musicxml/example-set/ to the 'D:/newSamples/' path. So BrookeWestSample.musicxml is an official musicxml sample.
my whole code:

```
from music21 import converter

s1 = converter.parse('D:/newSamples/BrookeWestSample.musicxml')
s1.show('text')
s1.write('midi', 'D:/newSamples/BrookeWestSample.mid')

s2 = converter.parse('D:/newSamples/BrookeWestSample.mid')
s2.write('musicxml', 'D:/newSamples/BrookeWestSamplenew.musicxml')
```

And this is the part-list element of the BrookeWestSamplenew.musicxml:
```
<part-list>
    <score-part id="P5a1e121a4f52306e326f762792f711f5">
      <part-name />
    </score-part>
    <score-part id="P2fa4b80d1ffa4ba95af0fa867b60641f">
      <part-name />
    </score-part>
  </part-list>
```

Also I attached a file named "text.txt", it stores the s1.show('text') output.
[text.txt](https://github.com/cuthbertLab/music21/files/5105054/text.txt)

I need part names from the part-list element of the BrookeWestSamplenew.musicxml.

**Comment by BerdinEge** [comment]
And this is the original BrookeWestSample.musicxml's part-list element:
```
<part-list>
    <score-part id="P1">
      <part-name print-object="no">Voice</part-name>
      <score-instrument id="P1-I3">
        <instrument-name>Voice</instrument-name>
        <instrument-sound>voice.vocals</instrument-sound>
        <solo/>
      </score-instrument>
      <midi-instrument id="P1-I3">
        <midi-channel>1</midi-channel>
        <midi-program>55</midi-program>
        <volume>80</volume>
        <pan>0</pan>
      </midi-instrument>
    </score-part>
    <score-part id="P2">
      <part-name print-object="no">Guitar</part-name>
      <score-instrument id="P2-I2">
        <instrument-name>Acoustic Guitar (steel)</instrument-name>
        <instrument-sound>pluck.guitar.steel-string</instrument-sound>
      </score-instrument>
      <midi-instrument id="P2-I2">
        <midi-channel>2</midi-channel>
        <midi-program>26</midi-program>
        <volume>80</volume>
        <pan>0</pan>
      </midi-instrument>
    </score-part>
  </part-list>
```

**Comment by mscuthbert** [comment]
Thank you Jacob!
