### ISSUE TITLE
Appoggiatura misspelled in one method sig and one class name

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#593]
I only remember that it's two P's and two G's on account of a copy of David Lewin's course notes on counterpoint where he had scrawled in the margin "impress your musicology professors: two P's and two G's".

https://github.com/cuthbertLab/music21/blob/a78617291ed0aeb6595c71f82c5d398ebe604ef4/music21/duration.py#L2057

https://github.com/cuthbertLab/music21/blob/a78617291ed0aeb6595c71f82c5d398ebe604ef4/music21/duration.py#L2955

It's spelled correctly elsewhere:

https://github.com/cuthbertLab/music21/blob/a78617291ed0aeb6595c71f82c5d398ebe604ef4/music21/expressions.py#L889

Any interest in renaming these?

**Comment by mscuthbert** [comment]
PLEASE!  :-)  And I'll send you the funniest comments of David Lewin's notes on my homework some day.
