### ISSUE TITLE
Invalid midi-instrument id produced when instrument has midi program but no instrument name

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#594]
**music21 version**

`6.0.5.a1`

**Problem summary**

An `Instrument` object with a `.midiProgram` but no `.instrumentName` produces upon .xml export a `<midi-instrument>` id matching no other id in the document. This causes validation issues in Finale:

<img width="422" alt="id_validation" src="https://user-images.githubusercontent.com/38668450/91174372-2dc77b00-e6ad-11ea-9adb-fb0242a4778c.png">

Such instruments can arise from parsing musicXML into m21, since m21 will set `.midiProgram` but only create generic `Instrument` instances without names, etc. In other words, this is an issue on a roundtrip back to .xml.

**Steps to reproduce**

```
from music21 import converter, musicxml
from music21.musicxml import testFiles

mxString = testFiles.ALL[5]  # contains Electric Guitar midi program
scoreObj = converter.parseData(mxString)  # midiProgram stored; no instrumentName stored
scoreObj.show()

scex = musicxml.m21ToXml.ScoreExporter(scoreObj)
tree = scex.parse()
mxScoreInstrument = tree.findall('.//score-instrument')[0]
mxPart = tree.findall('.//part')[0]
```

**Expected vs. actual behavior**
```
>>> print(mxMidiInstrument.get('id')
I8f4138faff93acfe295ec826023c467a
>>> print(mxPart.get('id')
P0
```
Expected equality with `<part>` id or with a `<score-instrument>` id.

**More information**

Spec says the id of `<midi-instrument>` should match that of the part or the `<score-instrument>`. My intended patch consists of creating a `<score-instrument>` when we only have a `.midiProgram`. That turns out to be enough to get a matching id with the `<midi-instrument>`.

**Comment by mscuthbert** [comment]
FANTASTIC diagnosis and fix!  Thank you!
