### ISSUE TITLE
Math domain error for repeat finder dependency in search/base.py

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#608]
**Summary**
- File: music21/music21/search/base.py
- Line: 945
- Error message: `ValueError: math domain error`
- Context / reproducing: dependency for the repeat finder.

**Relevant part of the Traceback**
```
"music21/music21/repeat.py", line 2569, in getSimilarMeasureGroups
   mList = self.getMeasureSimilarityList()
"music21/music21/repeat.py", line 2138, in getMeasureSimilarityList
   mLists[i] = [
"music21/music21/repeat.py", line 2139, in <listcomp>
   hashFunction(mLists[i][j].notesAndRests)
"music21/music21/search/base.py", line 659, in translateStreamToString
   b += translateNoteWithDurationToBytes(n)
"music21/music21/search/base.py", line 945, in translateNoteWithDurationToBytes
duration1to127 = int(math.log(n.duration.quarterLength * 256, 2) * 10)
ValueError: math domain error
```

**Issue**
`duration1to127 = int(math.log(n.duration.quarterLength * 256, 2)*10)`
... will obviously fails in cases where the duration is <= 0 due to the log. There shouldn't be any notes of quarterLength <= 0, yet there somehow are (and they don't seem to come from the original score).

**Workaround**
```
if n.duration.quarterLength <= 0:
    [duration1to127 = 0 / or raise an error here]
else:
    duration1to127 = int(math.log(n.duration.quarterLength * 256, 2)*10)
```

**Version(s)**
I've reproduced this a few times over the past c.year on the Github dev version of music21.

Thanks for any tips!

**Comment by jacobtylerwalls** [comment]
Hey @MarkGotham just a quick note that 0.0 duration seems legitimate to me for grace notes or other anomalies (see #601), wasn't sure if you were saying they were inappropriate in all cases or just you didn't expect them in your stream. Seems unnecessary to raise an error here, we could just short circuit taking the log and then let the check for out of range values in the elif block enforce a minimum value of 1.

**Comment by mscuthbert** [comment]
We can make == 0 but I don't want any < 0 duration tests in music21.  We check for that at setting duration - it gives a cheeky error.

**Comment by MarkGotham** [comment]
Great thanks @jacobtylerwalls and @mscuthbert for this and for handling similar cases elsewhere in the code base in the same breath.
