### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 10: invalid start byte

### ISSUE THREAD

**Issue by saiftyfirst** [cuthbertLab/music21#610]
I am trying to use music21 to parse some midi files. I can use mido to open these files but I get the aforementioned UnicodeDecodeError when I try with music21.

Any clues on how I can work around this ?

Thanks,
Saif

**Comment by jacobtylerwalls** [comment]
Hi @saiftyfirst I reported this a few days ago in #606 and patched it in #607 . If you have a copy of music21 cloned from Git you could cherry pick the commit in #607, or if you haven't, just edit that one line of code yourself.

Could you share what midi writer created that file?

@mscuthbert open to your thoughts on whether this worth a version bump

**Comment by saiftyfirst** [comment]
Ok got it! Thanks @jacobtylerwalls

**Comment by jacobtylerwalls** [comment]
No problem, and sorry for introducing this behavior into music21! Can you help us out by letting us know what midi writer created your file, if you know? My code didn't anticipate a copyright symbol in the track name and I'd like to know how common that is.

**Comment by saiftyfirst** [comment]
Hi @jacobtylerwalls, I am using some files from here:
http://www.piano-midi.de/beeth.htm
