### ISSUE TITLE
PartStaffs exported to musicXML as distinct <part> elements

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#613]
**Version**
`6.1`

**Problem summary**

Two `PartStaff` objects representing a single part will be written to musicXML files as distinct `<part>` elements rather than  a single `<part>` element where `<staff>1</staff>` and `<staff>2</staff>`, etc. Importers will fail to collect them together as a grand staff.

**Steps to reproduce**
```
from music21.musicxml import testPrimitive
s = converter.parse(testPrimitive.pianoStaff43a)
exporter = musicxml.m21ToXml.ScoreExporter(s)
tree = exporter.parse()
exporter.dump(tree.findall('part-list')[0])
```

**Observed result:**
```
<part-list>
  <score-part id="P1">
    <part-name>MusicXML Part</part-name>
  </score-part>
  <score-part id="Pb14b43e5a3a10a087215097122972f89">
    <part-name>MusicXML Part</part-name>
  </score-part>
</part-list>
```

<img width="300" alt="partStaffs" src="https://user-images.githubusercontent.com/38668450/92407223-f4a8f500-f107-11ea-9221-3893209a42e0.png">

Expected one `<part>` in the `<part-list>` and ultimately `<staff>` tags under the notes.

**More information**

`fromPart()` is going to have to become `PartStaff`-aware, or better yet, a new method `fromPartStaff()` to handle this.

**Comment by jacobtylerwalls** [comment]
Another ramification:

```
s = corpus.parse('schumann_clara')
s.show()
```

Finale won't open this file because there is a slur between the PartStaffs that never closes because now it's a slur across two parts!

**Comment by mscuthbert** [comment]
AH! The second issue is one that boosts this to a high priority.  Right now, it's true that our musicxml output is not PartStaff aware.  Known issue since before v1 but something that I've never moved up the priority list.  These need to become notes in one staff with a staff tag designated.
