### ISSUE TITLE
show('rntxt') and write('rntxt') ?

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#619]
Not a bug report, but a request/discussion.

I had a conversation with someone recently about embedding `RomanNumeral` objects in a music21 stream.

As a result, I thought whether there was a `.show('rntxt')` and/or `.write('rntxt')` option to "export" your RomanNumeral annotations.

I gave a quick look at the source code for `stream.Stream.write()` and `stream.Stream.show()` and could not see an implementation for this.

Would it make sense to implement that?

As an immediate application for this, it would provide a "free" converter of `**harm` to `rntxt`, given the recent `**harm` parser included in `music21`.

I'd be happy to help with this. I imagined that maybe @MarkGotham already had some code in place for generating a `.rntxt` from a music21 `stream`.

I know you all are busy. I mostly want to know if you have concerns about it. I think I can implement it.

Cheers! And congrats on `v6.1.0`, it is blazing fast!

**Comment by MarkGotham** [comment]
Many thanks for this @napulen !

I do indeed have some basic code for writing RNTXT but within the context of other functionalities I'm working on -- processing complete and partial analyses as well as templates directly from (unanalysed) scores.

As there's interest in this, I'll submit a PR for the relevant code, even though there are issues with it and its dependencies (e.g. RomanNumeralFromChord). If you're interested, we can then collaborate on getting at least part of the offering up to the required level quicker than I would have time to manage on my own right now.

Thanks again; I hope the new functionality looks promising to you. Watch this space!

**Comment by napulen** [comment]
Thanks for replying @MarkGotham !

I am definitely up for collaborating, I think this would help to close a few gaps in roman numeral analysis workflows.

Please point me to the code that I should be looking at and I'll take a look as soon as I can.

And thanks for all the great work on this subject!

**Comment by mscuthbert** [comment]
I'm interested in taking this!  But concerned about taking on the maintenance burden of what happens if corner cases that are not found by the Writer class appear.  I think that the pieces in the music21 corpus need to not error on a .write('rntxt') -- even if so many of the pieces don't make much sense, and the output makes sense for many weird cases such as coda jumps, first/second endings, tuplets, measure numbers with suffixes, pickups, overfilled/incomplete bars, etc.   So it'd be a really welcome addition, but probably not a weekend project!  Thanks!

**Comment by MarkGotham** [comment]
Hi @napulen  and @mscuthbert ,

I’ve now been through the code I mentioned and It’s not immediately clear which parts will warrant inclusion in music21, so for now I’ve simply put it in here ... 
https://github.com/MarkGotham/When-in-Rome/blob/master/Code/skeletonHarmony.py
… as part of the ‘When-in-Rome’ code and corpus repo.

As I say, this code offers functionality for writing romanText from scores with full / partial analysis, templating, processing of metadata etc. So it’s partly about roman text specifically, but more concerned with wider processing of harmonic analysis. As such, (parts of) it may be a better fit for music21/analysis.

If you have a moment to review it, please also check out the partnering ‘Roman Umpire’ which seeks to help with the proof-reading of Roman numeral analysis. I welcome comments, suggestions, and requests, and I remain happy to integrate any parts of this into the main music21 repo that would be of use to the community.

Thanks and best

**Comment by napulen** [comment]
Thank you both for your comments! This is certainly looking more complex than a weekend project.

Before I try to contribute more to this conversation, I need to:

1. Look at the music21 corpus to get a better understanding of the complexity mentioned by Michael
2. Look at the code provided by Mark

I will try to do that soon and come back with further comments. Thank you for reading ths issue!

**Comment by MarkGotham** [comment]
Quick update: PR #651 is the latest on this. Feel free to add, adjust, and expand as necessary.
