### ISSUE TITLE
testSingleCoreAll shows test failures

### ISSUE THREAD

**Issue by rmapes** [cuthbertLab/music21#626]
**music21 version**

`6.2.0`  

**Problem summary**
When running testSingleCoreAll, I see 32 failures and 3 errors.

[testSingleCoreAll.out.txt](https://github.com/cuthbertLab/music21/files/5253900/testSingleCoreAll.out.txt)

**Steps to reproduce**

```
python3 music21/test/testSingleCoreAll.py

**Expected vs. actual behavior**
Test should have no failures

**Comment by mscuthbert** [comment]
It is likely that you do not have scipy, lilypond, or Py-Levensthein installed which give slightly different results than their fallback versions.  (or an older version of matplotlib).  Will leave this open to make testSingleCoreAll require these packages to be installed to run this test.
