### ISSUE TITLE
FAQ link on web site is broken

### ISSUE THREAD

**Issue by jaredkrinke** [cuthbertLab/music21#642]
(Omitting the template since this is an issue with the web site and not the code itself.

Currently, the web site (http://web.mit.edu/music21/) has a FAQ link that is broken (it points to http://web.mit.edu/music21/doc/systemReference/faq.html).

It looks like the correct link is probably: http://web.mit.edu/music21/doc/about/faq.html

**Comment by mscuthbert** [comment]
Thank you!  Fixed within 20 minutes (MIT Cache)
