### ISSUE TITLE
Reporting a serious unknown bug with stream.write

### ISSUE THREAD

**Issue by asigalov61** [cuthbertLab/music21#649]
Music21 6.0.1

stream.write stops working intermittently at least on my end w/o any errors or clues as to what may be wrong.

I tried my best debugger but it did not show anything either.

I confirmed online that other people experience this issue too.

I checked everything I could but could not pinpoint the issue.

Please escalate as when it does not work, it is not possible to dump MIDIs.

**Steps to reproduce** (sometimes it is impossible as it works fine)

https://github.com/asigalov61/Euterpe/blob/main/MUSIC21_TXT_MUSIC21.ipynb

```

midi_stream = stream.Stream(output_notes).chordify()
midi_out = midi_stream.write('midi', '/content/output.mid')
files.download('/content/output.mid')
```

**Comment by asigalov61** [comment]
I think it may be actual stream

midi_stream = stream.Stream(output_notes).chordify()

output_notes are good but midi_stream produce []

**Comment by asigalov61** [comment]
A little update

I think I narrowed it down to python and probably to your usual dependencies hell/conflicts. I was also thinking that maybe its the stream.write cache issue so, maybe adding direct write/proper overwrite option would solve this issue.

But definitely it would be cool to have a much better debug/error control for critical functions like stream.write and ideally it would be cool to have a backup class/function for critical components. Thats a standard practice in the industry AFAIk.

Thanks

**Comment by asigalov61** [comment]
Another little update:

I am pretty sure it's a cache issue. Not 100% cuz I have no debug and no access to your side.

Most likely it's the Python/browsers/whatever is being used. 

So please check this and if possible please implement direct-write or direct-overwrite in stream.write.

Thank you.

**Comment by asigalov61** [comment]
More helpful info:

I narrowed it down specifically to stream.write('midi). XML (MusicXML) seem to work w/o issues. But MIDI format fails quite consistently.

@jacobtylerwalls @mscuthbert Guys, I would really appreciate an update as soon as you will be able to. I can't use your software without MIDI output. Thank you very much.

P.S. I will take any workaround/hack for now.

**Comment by asigalov61** [comment]
@jacobtylerwalls Jacob, I am sorry to bother you guys, but is there any update on this issue?

I can't use Music21. It's very disappointing and discouraging :(

**Comment by jacobtylerwalls** [comment]
Sorry you're having trouble. An actionable bug report consists of enough lines of code for someone else to repro from scratch (but stripped down to only what's essential to repro) and some annotated output explaining what's incorrect.

All I can see from what you submitted so far is that sometimes your variable `midi_stream` is empty, but we don't have any instructions to know what's in `output_notes`, so it's impossible to attempt to reproduce this.

**Comment by jacobtylerwalls** [comment]
Try an example from scratch containing no more than two or three notes and build up from there until you find a problem, then strip out everything around the problem until you have just two or three notes around the problem part.

**Comment by asigalov61** [comment]
I just did, including Mr. Cuthberth special env. setup. It still does not work. I am attaching an example of MIDIs I get.

Or are you trying to say that there is a problem with my code? I am not quite understanding you?

Thank you for your response.
________________________________

**Comment by jacobtylerwalls** [comment]
I'm saying your bug report consisted of this:

```
midi_stream = stream.Stream(output_notes).chordify()

output_notes are good but midi_stream produce []
```

And you provided a link to an entire program you wrote to programmatically generate `output_notes`, and mentioned sometimes it works and sometimes it doesn't. That's asking us to debug your program. A bug report would show the reader exactly how to build `output_notes` from scratch, using a handful of lines of code or loading a very small example file, not by running a program. For some examples by others see #524 or #534

**Comment by asigalov61** [comment]
Ohhh...I am sorry...if it is the rule on your issue board, then you should've said so...

I can do it for you easily in like 5 minutes, no problem. But I did check everything and it seems to be fine.

Besides, my code is very basic and I code like an 8 yo girl cuz I lost some of my skills due to health issues. So I did not think it would be that hard for you guys.

Let me give you the exact debug and code snippet.

Sorry about the misunderstanding on my part...
________________________________

**Comment by jacobtylerwalls** [comment]
I encourage you to edit your comment to remove the offensive comparison. (This much *is* stated right on the homepage in the code of conduct.) For bug reports, we do lay out guidelines in the bug report template, much of which you deleted.

**Comment by asigalov61** [comment]
Yeah...I was almost certain you were gonna respond this way...

I think I will just close the issue.

My bad. Sorry that I have bothered you all.




________________________________

**Comment by mscuthbert** [comment]
Sexist comments will not be tolerated in any form by the music21 leadership.  The comment has been deleted.  Please consider this your only warning.
