### ISSUE TITLE
Empty measures in RomanText

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#655]
In harmonic analysis, there are often measures in which the chord doesn't change. e.g.:
```
m1 b1 Ab: I
m2 b1
m3 b1 V
```
Given this input, RomanText will currently create an empty m2 with no duration that therefore gives 'wrong' offset values for all subsequent measures (missing the duration of m2).

_(Aside: including or excluding the 'b1' makes no difference.)_

RomanText handles the equivalent notation without the empty measure differently:
```
m1 b1 Ab: I
m3 b1 V
```
In this case, RomanText extends the Roman numeral over from the previous measure – i.e. it remains in effect until replaced by the next Roman numeral. This is a better outcome, in my opinion, both musically and computationally.

_(Aside: including an empty line between the entries makes no difference.)_

Options:
1. Ignore empty measures in the RomanText. (Simple and effective).
2. Parse it all then fill in the empty measures with the preceding Roman numeral and update offsets (much more work for no better an outcome).

Before implementing option 1, does anyone see any issues with this or have a strong contrary preference for any reason?

**Comment by MarkGotham** [comment]
I.e. in `romanText.translate.PartTranslator.translateSingleMeasure`, insert a clause such that if there are no tokens other than the measure itself, then don't create the measure. That will trigger 'skipsPriorMeasures' option in `translateMeasureLineToken`

**Comment by MarkGotham** [comment]
#658

**Comment by mscuthbert** [comment]
Isn't this notation contrary to the Specification?

**Comment by mscuthbert** [comment]
See comments on PR for how this violates the specification.  It is a new specification and music21's implementation is the reference implementation, which others should follow.
