### ISSUE TITLE
Platform Version Retrieval Broken on macOS Big Sur

### ISSUE THREAD

**Issue by dnlfrst** [cuthbertLab/music21#656]
# What is the issue?

After updating from macOS Catalina (10.15.*) to macOS Big Sur (10.16), I am no longer able to import `music21`. Doing so fails with the following stacktrace:

```python
>>> import music21
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/__init__.py", line 169, in <module>
    from music21 import base  # noqa: E402
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/base.py", line 66, in <module>
    from music21 import environment
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/environment.py", line 816, in <module>
    _environStorage['instance'] = _EnvironmentCore()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/environment.py", line 175, in __init__
    self._loadDefaults(forcePlatform=forcePlatform)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/environment.py", line 405, in _loadDefaults
    versionTuple = common.macOSVersion()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/music21/common/misc.py", line 117, in macOSVersion
    major, minor, maintenance = tuple(int(v) for v in platform.mac_ver()[0].split('.'))
ValueError: not enough values to unpack (expected 3, got 2)
```

Indeed, retrieving the version of macOS Big Sur in Python 3.8 with `platform` yields:

```python
>>> import platform
>>> platform.mac_ver()
('10.16', ('', '', ''), 'x86_64')
```

This does no longer adhere to the assumption in `music21`'s implementation:

https://github.com/cuthbertLab/music21/blob/70a8dd272ba63a44cc4e0e1e8199c08b95612cbb/music21/common/misc.py#L107-L118

Instead, as seen above, Python 3.8 refers to macOS Big Sur as macOS version 10.16 which yields a tuple, not a triple:

```python
>>> import platform
>>> platform.mac_ver()
('10.16', ('', '', ''), 'x86_64')
>>> platform.mac_ver()[0].split('.')
['10', '16']
```

# What could be a solution?

To prevent this issue in further updates, I recommend going with a weaker assumption. Consider the following implementation:

```python
def macOSVersion() -> Tuple[int, int, int]:  # pragma: no cover 
     ''' 
     On a Mac returns the current version as a tuple of (currently 3) ints, 
     such as: (10, 5, 6) for 10.5.6.
  
     On other systems, returns (0, 0, 0) 
     ''' 
     if getPlatform() != 'darwin': 
         return (0, 0, 0) 
  
     major, minor, *maintenance = tuple(int(v) for v in platform.mac_ver()[0].split('.'))
     maintenance = maintenance[0] if maintenance else 0

     return (major, minor, maintenance)
```

which resolves the failing import on macOS Big Sur:

```python
>>> import music21
music21: Certain music21 functions might need the optional package matplotlib;
                  if you run into errors, install it by following the instructions at
                  http://mit.edu/music21/doc/installing/installAdditional.html
```

If you prefer to be even more cautious, one could apply the check of `maintenance` to `minor` likewise. Any thoughts on this?

# Package Information

```bash
$ pip3 show music21
Name: music21
Version: 6.1.0
Summary: A Toolkit for Computer-Aided Musical Analysis.
Home-page: https://github.com/cuthbertLab/music21
Author: Michael Scott Cuthbert, the music21 project, others
Author-email: cuthbert@mit.edu
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: chardet, joblib, more-itertools, webcolors
Required-by:
```

**Comment by jacobtylerwalls** [comment]
Many thanks for the report. Would you like to submit a PR? I suppose there's no harm in being extra cautious and treating `minor` the same way so that if `11` comes out instead of `11.0` one day we'll be set.

**Comment by dnlfrst** [comment]
@jacobtylerwalls you're welcome!

While introducing the described fix, I noticed that the code calling `macOSVersion()` suffers from a bug:

https://github.com/cuthbertLab/music21/blob/70a8dd272ba63a44cc4e0e1e8199c08b95612cbb/music21/environment.py#L404-L422

The implementation checks the result of `macOSVersion()` for a major version larger than or equal to 11. As we have just seen, macOS Big Sur does not correspond to the major version 11. Although this does not have an effect since the second condition catches macOS Big Sur, I am not sure whether it would be reasonable to remove the faulty check for a major version of 11 or larger.

**Comment by jacobtylerwalls** [comment]
Awesome, thanks for the PR. 

I don't think there's anything wrong with the check for version >= 11. We're trying to find versions >= 10.15, and the first part of the check isn't targeting Big Sur per se, it's targeting yet to be known versions.

**Comment by dnlfrst** [comment]
Alright, then that's fine! 👍🏼
