### ISSUE TITLE
MusicXML parsing doesn't use altered degrees that contradict chord kinds

### ISSUE THREAD

**Issue by pettter** [cuthbertLab/music21#665]
**music21 version**

`6.1.0`   

**Problem summary**

When parsing a MusicXML chord with kind "dominant" but a lowered fifth degree, this is not reflected in the chord pitches. I haven't tested if this is the case for other kinds and degree alterations.

**Steps to reproduce**

```
>>> from xml.etree.ElementTree import fromstring as EL
>>> MP = music21.musicxml.xmlToM21.MeasureParser()

>>> elStr = (r'<harmony><root><root-step>C</root-step></root><kind text="7b5">dominant</kind>' + 
... '<degree><degree-value>5</degree-value><degree-alter>-1</degree-alter>' +
... '<degree-type>alter</degree-type></degree></harmony>')
>>> mxHarmony = EL(elStr)

>>> cs = MP.xmlToChordSymbol(mxHarmony)
>>> cs.figure
'C7 alter b5'
>>> cs.pitches
(<music21.pitch.Pitch C3>, <music21.pitch.Pitch E3>, <music21.pitch.Pitch G3>, <music21.pitch.Pitch B-3>) # Should be G-3

**Comment by jacobtylerwalls** [comment]
Thanks for the report. At a glance I think the same issue is reproducible without involving XML or the `<kind>` tag.

```
>>> h = harmony.ChordSymbol('C')
>>> mod = harmony.ChordStepModification('alter', 5, -1)
>>> h.addChordStepModification(mod)
>>> h.pitches
(<music21.pitch.Pitch C3>, <music21.pitch.Pitch E3>, <music21.pitch.Pitch G3>)
```

**Comment by pettter** [comment]
Yep, looks like it's the for-loop in _adjustPitchesForChordStepModifications.typeAlter that doesn't actually change anything, as far as I can tell.

**Comment by jacobtylerwalls** [comment]
You would be welcome to start on a PR, of course! I would suggest adding the test case from my last comment as a doctest to `harmony.addChordStepModification`.

**Comment by pettter** [comment]
Right. Though for that there is, I think, an additional problem - _updatePitches() is not called from addChordStepModification(), so even after fixing the typeAlter loop, the pitches don't update from just adding an alteration.

**Comment by jacobtylerwalls** [comment]
Ah. I see that `xmlToChordSymbol` does call `_updatePitches`, however, so that may be sufficient for your use case. And then my suggested test could just call `_updatePitches`. We could let @mscuthbert opine on whether the update call should be automatic.

I'm curious where the fault is in `_adjustPitchesForChordStepModifications`, since I see there is an attempt to transpose an existing pitch. I haven't booted up a debugger to look just yet.

**Comment by pettter** [comment]
Basically, "p" acts as a locally scoped variable (perhaps doubly so, from the zip - not sure), so resetting that doesn't actually affect the pitch in the pitches list.

I've made a small patch that fixes it, dropping the zip and using ```pitches[degrees.index(degree)]``` instead.

**Comment by jacobtylerwalls** [comment]
Does it work with just `p.transpose(hD.interval, inPlace=True)`?

**Comment by pettter** [comment]
It does, very nice!
