### ISSUE TITLE
Second lyric in a note is not retrieved

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#666]
**music21 version** 
`6.1.0`  

**Problem summary**
Second lyric in a note is not retrieved.

![image](https://user-images.githubusercontent.com/52449822/99278752-bf1f3700-282f-11eb-87f7-68124eb3abe1.png)

In the example above, 'to' and 'o' are in different text annotations. This makes LyricSearcher to only retrieve 'to'.

**Steps to reproduce**

```python
music21.search.lyrics.LyricSearcher(self.score).indexText
```

**Expected vs. actual behavior**
The expected result is "ma to, o"
The actual result is "ma to,"

**Additional information**
In the documentation is indicated that currently it searches only the first lyric (http://web.mit.edu/music21/doc/moduleReference/moduleSearchLyrics.html) but I would sugest this to be a TODO instead of a restriction.

**Comment by jacobtylerwalls** [comment]
Agreed. (And I think the very first TODO listed underneath that restriction is making your point.) Would you like to investigate and propose an approach?

**Comment by mscuthbert** [comment]
This is an enhancement request, not a bug.  It's a known restriction -- would be glad to take a PR that fixes it.

**Comment by DIDONEproject** [comment]
We have proposed an approach to solve this problem. We would be glad if you can consider it :)

#673

**Comment by mscuthbert** [comment]
Fixed in #673

**Comment by mscuthbert** [comment]
After thinking through the consequences of this issue a bit more, I've decided to change the implementation a bit in #794
