### ISSUE TITLE
Asynchrony of parts lost during XML export

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#681]
**music21 version**
6.3

**Problem summary**
Asynchrony of parts not preserved when score exported to musicxml.

**Steps to reproduce**

```
import music21
s = music21.stream.Stream()
part1 = music21.stream.Part()
part1.insert(0, music21.note.Note("G4"))
part2 = music21.stream.Part()
part2.insert(0, music21.note.Note("A4"))
s.insert(0, part1)
s.insert(1, part2)
s.show('musicxml')
```

**Expected vs. actual behavior**
i expected to see that part2 starts with a rest, but it starts at the very beginning.

**More information**
From Stefaan, m21 list 11/27/20

**Comment by jacobtylerwalls** [comment]
Hi Stefaan, thanks for the question. I poked around, and I think the fact that .show() calls .makeNotation() is what is synchronizing your parts. There's a way to avoid this using ScoreExporter, which is smart enough to keep things asynchronized by not calling .makeNotation(), but it's cumbersome:
```
from music21.musicxml.m21ToXml import ScoreExporter()
scex = ScoreExporter(yourStream)
unused_root = scex.parse()
xml_string = scex.asBytes().decode('utf-8')  # asBytes() is one way to make sure the xml header gets written
with open('file.xml', 'w+') as f:
    f.write(xml_string)
```
This needs a usability improvement. Maybe:
- .show() and .write() take a makeNotation=False keyword argument (the "I know what I'm doing" argument)
- makeNotation needs to have a way to transfer the offset of the part to all of the part's elements (which is what ScoreExporter does)

**Comment by jacobtylerwalls** [comment]
Doesn't matter if it's well-formed notation, as in this example with score > part > measure > note:

```
>>> s = stream.Score()
>>> s.insert(0, p1)
>>> s.insert(1, p2)
>>> s.show('t')
{0.0} <music21.stream.Part 0x119b57e80>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.note.Note C>
        {4.0} <music21.bar.Barline type=final>
{1.0} <music21.stream.Part 0x118c31b80>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.meter.TimeSignature 4/4>
        {0.0} <music21.note.Note C>
        {4.0} <music21.bar.Barline type=final>
>>> s.write()
...
  <!--=========================== Part 2 ===========================-->
  <part id="P5cc2a0a19cde394de54dbfea2c8e560f">
    <!--========================= Measure 1 ==========================-->
    <measure number="1">
      <attributes>
        <divisions>10080</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <note>                 <!-- no rest here -->
        <pitch>
          <step>C</step>
          <octave>4</octave>
        </pitch>
        <duration>40320</duration>
        <type>whole</type>
      </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
      </barline>
    </measure>
  </part>
</score-partwise>
```

**Comment by jacobtylerwalls** [comment]
I suggested to the reporter that calling `.transferOffsetToElements()` before making measures would work. The issue is that once measures are made by `.show(), transferring offsets happens but has no impact because we only export the measures. Inserting a rest before measure 1 will be ignored.

This performed the same whether the input was well-formed or not (the code does a good job of inserting everything into score > part > measure).

This patch gets pretty close, as long as the duplicate clef is OK:
```
diff --git a/music21/musicxml/m21ToXml.py b/music21/musicxml/m21ToXml.py
index 22f51c2ca..32048136f 100644
--- a/music21/musicxml/m21ToXml.py
+++ b/music21/musicxml/m21ToXml.py
@@ -2377,9 +2377,11 @@ class PartExporter(XMLExporterBase):
         # Suppose that everything below this is a measure
         measureStream = self.stream.getElementsByClass('Stream').stream()
         if not measureStream:
-            self.fixupNotationFlat()
-            # Now we have measures
-            measureStream = self.stream.getElementsByClass('Stream').stream()
+            measureStream = self.fixupNotationFlat()
+        # Gapful stream, fixup from flat
+        elif not measureStream.isGapless:
+            self.stream = self.stream.flat
+            measureStream = self.fixupNotationFlat()
         else:
             self.fixupNotationMeasured(measureStream)
         # make sure that all instances of the same class have unique ids
@@ -2455,7 +2457,7 @@ class PartExporter(XMLExporterBase):
             if thisInstrument.instrumentId is None:
                 thisInstrument.instrumentIdRandomize()
 
-    def fixupNotationFlat(self):
+    def fixupNotationFlat(self) -> stream.Stream:
         '''
         Runs makeNotation on a flatStream, such as one lacking measures.
         '''
@@ -2483,6 +2485,8 @@ class PartExporter(XMLExporterBase):
         # only getting spanners at this level
         # spannerBundle = spanner.SpannerBundle(measureStream.flat)
         self.spannerBundle = part.spannerBundle
+        measureStream = self.stream.getElementsByClass('Stream').stream()
+        return measureStream
 
     def fixupNotationMeasured(self, measureStream):
         '''
@@ -6257,6 +6261,15 @@ class Test(unittest.TestCase):
             self.assertIsNone(direction.find('offset'))
 
 
+    def testPartOffset(self):
+        from music21 import stream
+
+        s = stream.Score()
+        p = stream.Part()
+        p.insert(note.Note())
+        s.insert(1, p)
+        s.show()
+

```
![duplicate-clef](https://user-images.githubusercontent.com/38668450/100549076-ca665f80-323e-11eb-97e6-4f8f7344ac5a.png)

**Comment by mscuthbert** [comment]
No musicxml notation software can deal with asynchronous parts.  The Q for what m21 should do is: make rests or treat them as synchronous.  Consider that if someone wants asynchronous parts it's easy for her or him to call makeRests() on it. But if someone messes up and runs score.append(part2) instead of .insert(0, part2), they're likely to complain that music21 screwed up, etc. etc. and lead to more headaches, I've chosen to have musicxml output largely treat parts as if they are meant to be synchronous.

**Comment by jacobtylerwalls** [comment]
Got it, this is definitely in the feature request side of the ledger, then, and you point out the risk of turning it on for everyone. I'll close this since there's already a workaround here for anyone interested.
