### ISSUE TITLE
Problems with parsing MIDI files with multiple tracks

### ISSUE THREAD

**Issue by GeorgeTouros** [cuthbertLab/music21#684]
**music21 version**

`6.3.0`

**Problem summary**
Parsing midi files fails to parse note duration and instrument information correctly

I try to parse and extract features from MIDI files that I have found on the Web. I am using the library found here: https://colinraffel.com/projects/lmd/
My goal is to use the feature extraction classes of music21 to build a classifier for my Thesis. 
When calling the converter.parse() method on the files, and then call the show() method, I get the following error:

```
meter: WARNING: Found a messed up beam pair <music21.beam.Beams <music21.beam.Beam 1/start>/<music21.beam.Beam 2/partial/right>>, <music21.beam.Beams <music21.beam.Beam 1/stop>/<music21.beam.Beam 2/stop>>, at index 5 of 
[None, <music21.beam.Beams <music21.beam.Beam 1/start>>, <music21.beam.Beams <music21.beam.Beam 1/stop>>, <music21.beam.Beams <music21.beam.Beam 1/start>/<music21.beam.Beam 2/partial/right>>, <music21.beam.Beams <music21.beam.Beam 1/stop>>, <music21.beam.Beams <music21.beam.Beam 1/start>/<music21.beam.Beam 2/partial/right>>, <music21.beam.Beams <music21.beam.Beam 1/stop>/<music21.beam.Beam 2/stop>>]
```

When the MuseScore application opens up to show the file, I get the following error:

![museScore3_error](https://user-images.githubusercontent.com/31730489/100544786-cd724780-3260-11eb-94b8-5e328a64b04c.png)

More importantly, the tempo and note duration is not parsed correctly, and neither is the track instrument information. 

**Steps to reproduce**
I've tested this using multiple files, but this one is the cleanest:

[0a2d626401e49eb46c59ec6dbd4f048fa305b001.zip](https://github.com/cuthbertLab/music21/files/5612297/0a2d626401e49eb46c59ec6dbd4f048fa305b001.zip)

```
>>> from music21 import *
>>> base_midi = converter.parse('0a2d626401e49eb46c59ec6dbd4f048fa305b001.mid', format='midi',
...                                                  forceSource=True, quantizePost=True)
>>> base_midi.show()
```

**Expected vs. actual behavior**
This is how the file is parsed when using MuseScore3 -> Open through the UI
![museScore3_parse_outcome](https://user-images.githubusercontent.com/31730489/100544494-c0ecef80-325e-11eb-9597-69f5a48c5761.png)
This is how the file is parsed using music_21.converter.parse()
![music21_parse_outcome](https://user-images.githubusercontent.com/31730489/100544437-3f955d00-325e-11eb-936c-afc1d4c5e643.png)

**More information**
I am using PyCharm in Ubuntu 20.04, Python 3.7.9 and MuseScore 3.2.3

I have also tried using `quarterLengthDivisors` with various combinations, to no avail. 

I have also tried to verify if the problem is in the show() method, by printing the partName for each part: 
```
>>> from music21 import *
>>> def list_instruments(midi):
...        part_stream = midi.parts.stream()
...        print("List of instruments found on MIDI file:")
...        for p in part_stream:
...            aux = p
...            print(p.partName)

>>> list_instruments(base_midi)
List of instruments found on MIDI file:
StringInstrument
Jazz Bass
StringInstrument
StringInstrument
None
None
Piano
None
```
For your reference, when viewing the track information using the [mido](https://mido.readthedocs.io/en/latest/) library, these are the results: 
```
>>> from mido import MidiFile
>>> file = '0a2d626401e49eb46c59ec6dbd4f048fa305b001.mid'
>>> mid = MidiFile(str(file), clip=True)
>>> for track in mid.tracks:
...        print(track)
<midi track 'untitled' 6 messages>
<midi track 'Marcato' 2228 messages>
<midi track 'Jazz Bass' 1129 messages>
<midi track 'Marcato' 2532 messages>
<midi track 'Marcato' 4832 messages>
<midi track 'New Tines' 3015 messages>
<midi track 'Bowed Glass' 326 messages>
<midi track 'Piano' 1265 messages>
<midi track 'GM Drums' 4710 messages>
<midi track '' 7 messages>
```

An idea for a potential workaround, would  be to use a different parser than the one that comes with music21. Is it possible to set mido as a parsing back-end, for example? 

At your disposal if more information is needed. 

Thanks in advance!

**Comment by jacobtylerwalls** [comment]
Hi @GeorgeTouros thanks for the report.

Can I ask you to check out #603 locally, and see if the results are any different? You should `forceSource=True` each time to ensure you are parsing it from the new code. It would be extremely helpful in terms of getting it merged to have more testers.

The smallest division in your screenshot is a triplet 32nd, so you need at least a quarterLengthDivisor of 12. I suggest using multiples, like `quarterLengthDivisors=[12, 16]`.

What does the `quantizePost=False` output look like?

***

For instruments, good catch that we can retrieve the part name from MIDI and stick it on `.partName`. Right now we're not doing that. Here is what we're grabbing from the SEQUENCE_TRACK_NAME and PROGRAM_CHANGE events:

```
>>> for track in mf.tracks:
...   for e in track.events:
...     if "PROGRAM" in repr(e) or "NAME" in repr(e):
...       value = e.data.decode('utf-8') if isinstance(e.data, bytes) else e
...       print("VALUE: ", value)
...       i = midi.translate.midiEventsToInstrument(e)
...       print("REPR: ", repr(i))
...       print("PART NAME: ", i.partName)
... 
VALUE:  untitled
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  Marcato
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=1, channel=1, data=48>
REPR:  <music21.instrument.StringInstrument 'StringInstrument'>
PART NAME:  None
VALUE:  Jazz Bass
REPR:  <music21.instrument.Bass 'Jazz Bass'>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=2, channel=2, data=32>
REPR:  <music21.instrument.AcousticBass 'Acoustic Bass'>
PART NAME:  None
VALUE:  Marcato
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=3, channel=3, data=48>
REPR:  <music21.instrument.StringInstrument 'StringInstrument'>
PART NAME:  None
VALUE:  Marcato
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=4, channel=4, data=48>
REPR:  <music21.instrument.StringInstrument 'StringInstrument'>
PART NAME:  None
VALUE:  New Tines
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=5, channel=5, data=4>
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  Bowed Glass
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=6, channel=6, data=92>
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  Piano
REPR:  <music21.instrument.Piano 'Piano'>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=7, channel=10, data=2>
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  GM Drums
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=8, channel=10, data=2>
REPR:  <music21.instrument.Instrument ''>
PART NAME:  None
VALUE:  <MidiEvent PROGRAM_CHANGE, t=0, track=9, channel=11, data=66>
REPR:  <music21.instrument.TenorSaxophone 'Tenor Saxophone'>
PART NAME:  None
>>> 
```

Can you let me know what you propose we do here? Is it enough to just store the instrument name detected on the `.partName` when we parse a SEQUENCE_TRACK_NAME but not when we find a PROGRAM_CHANGE?

**Comment by jacobtylerwalls** [comment]
This patch
```
diff --git a/music21/midi/translate.py b/music21/midi/translate.py
index 6196ee146..7fa847223 100644
--- a/music21/midi/translate.py
+++ b/music21/midi/translate.py
@@ -695,6 +695,7 @@ def midiEventsToInstrument(eventList):
         event = eventList[1]
 
     from music21 import instrument
+    decoded = None
     try:
         if isinstance(event.data, bytes):
             # MuseScore writes MIDI files with null-terminated
@@ -705,6 +706,8 @@ def midiEventsToInstrument(eventList):
             i = instrument.instrumentFromMidiProgram(event.data)
     except (instrument.InstrumentException, UnicodeDecodeError):  # pragma: no cover
         i = instrument.Instrument()
+    if decoded:
+        i.partName = decoded
     return i
 ```

yields this:

```
>>> from music21 import *
>>> s = converter.parse('~/Desktop/a.mid', forceSource=True)
>>> for i in s.flat.getInstruments():
...   print(repr(i))
... 
<music21.instrument.Instrument 'Marcato: '>
<music21.instrument.StringInstrument 'StringInstrument'>
<music21.instrument.Bass 'Jazz Bass: Jazz Bass'>
<music21.instrument.AcousticBass 'Acoustic Bass'>
<music21.instrument.Instrument 'Marcato: '>
<music21.instrument.StringInstrument 'StringInstrument'>
<music21.instrument.Instrument 'Marcato: '>
<music21.instrument.StringInstrument 'StringInstrument'>
<music21.instrument.Instrument 'New Tines: '>
<music21.instrument.Instrument ''>
<music21.instrument.Instrument 'Bowed Glass: '>
<music21.instrument.Instrument ''>
<music21.instrument.Piano 'Piano: Piano'>
<music21.instrument.Instrument ''>
<music21.instrument.Instrument 'GM Drums: '>
<music21.instrument.Instrument ''>
```

Looking better?

**Comment by GeorgeTouros** [comment]
Hi @jacobtylerwalls 
First of all, thanks for jumping in so fast and being so helpful! I'll try to address your multiple points in the tests I did below. I am comparing 3 versions of music21: The version in PyPI, the version in the current master branch, including the merged #685 and finally the #603 PR. 

- The quantizePost=False option will crash MuseScore in all 3 versions. There's a very long error log, most of it looks like this:
```
Error at line 75754 col 13: calculated duration (47/768) not equal to specified duration (617/10080) -> assuming rounding error
Error at line 75773 col 13: calculated duration (47/768) not equal to specified duration (617/10080) -> assuming rounding error
Error at line 75792 col 13: calculated duration (47/768) not equal to specified duration (617/10080) -> assuming rounding error
...
Error at line 90723 col 13: calculated duration (47/768) not equal to specified duration (617/10080) -> assuming rounding error
implicit tuplet start cr 0x55901401d900 tick 33450 track 28
...
Error at line 126720 col 13: calculated duration (239/768) not equal to specified duration (3137/10080) -> assuming rounding error
implicit tuplet start cr 0x5590147b70c0 tick 167373 track 30
determineTupletBaseLen(0x5590147b7330) cannot divide count 1 by 384
"Bar 1, stave 1 incomplete. Expected: 127259/80640; Found: 127260/80640"
"Bar 1, stave 3 incomplete. Expected: 127259/80640; Found: 127260/80640"
"Bar 1, stave 5 incomplete. Expected: 127259/80640; Found: 1212/768"
"Bar 1, stave 8 incomplete. Expected: 127259/80640; Found: 124949/80640"
"Bar 2, stave 1 incomplete. Expected: 57/32; Found: 143536/80640"
"Bar 2, stave 3 incomplete. Expected: 57/32; Found: 143536/80640"
"Bar 2, stave 8 incomplete. Expected: 57/32; Found: 140490/80640"
"Bar 3, stave 1 incomplete. Expected: 8/4; Found: 161176/80640"
"Bar 3, stave 3 incomplete. Expected: 8/4; Found: 161176/80640"
"Bar 3, stave 7 incomplete. Expected: 8/4; Found: 161070/80640"
...
Mscore: ticks_beat(): bad divisor 80640
Aborted (core dumped)
```

- I tried the `quarterLengthDivisors=(12, 16)` option in all 3 versions. It loads better than the default quantization, but the output is pretty consistent for all 3 versions I tested (see screenshots below): 
**v 6.3.0**
![v6_3_0__quantize12-16](https://user-images.githubusercontent.com/31730489/100667121-c0d61800-3362-11eb-90f4-81377e402d16.png)
**master**
![master_branch_quantize12_16](https://user-images.githubusercontent.com/31730489/100667184-d64b4200-3362-11eb-84e2-162d63ae6656.png)
**PR**
![pr_branch_quantize12_16](https://user-images.githubusercontent.com/31730489/100667223-e2cf9a80-3362-11eb-8302-fc59ec9ac731.png)

Please notice that on the PR version in the first bar the duration is shown 3 times. 

--------------------------------------------------------------------------------------------------------------------------------
As for the instruments patch, I tried it out, indeed it works for printing out as you describe, nevertheless it doesn't seem to fix how they are loaded withing musescore. I tried the patch on the master branch. I am no expert on how these are read when loading from the MuseScore3 UI, but it's correct there. 

![master_with_inst_patch](https://user-images.githubusercontent.com/31730489/100668808-2aefbc80-3365-11eb-9c5d-cccad1fdfe8f.png)


I hope all of this helps. Please let me know if I can help you any further. 

Cheers!

**Comment by jacobtylerwalls** [comment]
Cool, very helpful!

I think setting `.partName` on the instrument is the thing to do, because generally that should flow upstream to Parts if and when .partName is not set any other way.

Problem you're having viewing that in MuseScore is that you've discovered another bug with `makeNotation` and voices.

```
>>> p = stream.Part()
>>> i = instrument.Piccolo()
>>> p.insert(i)
>>> p.insert(note.Note())
>>> p.insert(note.Note())
>>> p.show('t', addEndTimes=True)
{0.0 - 0.0} <music21.instrument.Piccolo 'Piccolo'>
{0.0 - 1.0} <music21.note.Note C>
{0.0 - 1.0} <music21.note.Note C>
>>> p.makeNotation(inPlace=True)
<music21.stream.Part 0x10ff490d0>
>>> p.show('t', addEndTimes=True)
{0.0 - 1.0} <music21.stream.Measure 1 offset=0.0>
    {0.0 - 0.0} <music21.clef.TrebleClef>
    {0.0 - 0.0} <music21.meter.TimeSignature 4/4>
    {0.0 - 1.0} <music21.stream.Voice 0>
        {0.0 - 1.0} <music21.note.Note C>
    {0.0 - 1.0} <music21.stream.Voice 1>
        {0.0 - 1.0} <music21.note.Note C>
    {1.0 - 1.0} <music21.bar.Barline type=final>
```

Notice the Instrument object vanished. Voices strike again! This fix is going to be a little more invasive than the one I sketched above, so will probably become two PRs.

***

Then when I have a minute I'll dig into your results from testing the PR. Many thanks!

If you're game to help me continue debugging MIDI voices, maybe we can suggest an improvement to the parser. The durations from your file are not easy to work with in a literal sense. music21 is agreeing with mido's offsets, so I don't know what quantization algorithm MuseScore is using to produce a nicer result. I think there's value in the literalness of music21's approach. But if there's a way to improve the quantization algorithm (maybe: incorporating the sign of the previous note's quantization error when performing the rounding ... not sure....) then let's get it on the table!

Best/Jacob

**Comment by jacobtylerwalls** [comment]
Alright, next up: those metronome marks in the PR.

When parsing the MIDI there was an intentional change in the PR to put metronome marks in every single part. This was to ensure info was retained when parts become separated; ensure `.seconds` comes out correctly; support multitempo streams.

I see all eight here:
```
>>> for e in s.flat.getElementsByClass('MetronomeMark'):
...   print(e)
... 
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
<music21.tempo.MetronomeMark Quarter=43.0>
```

Why you only saw three in the xml file you exported seems like an xml export issue. I'll look more later.

**Comment by jacobtylerwalls** [comment]
So after rebasing #603 on the latest master, I get the result I expected, MetronomeMarks in every part:

![Screen Shot 2020-12-05 at 7 31 11 PM](https://user-images.githubusercontent.com/38668450/101268412-74a72100-3730-11eb-81c8-f993b70d298d.png)

@mscuthbert do you think this result is OK? It seems to me that parsing MIDI files into parts should have the metronome mark in every part so that `.seconds` is correct and so that when single parts are extracted and put in other streams they don't lose tempo info. Do we want to leave this as is or have some kind of reduction (if each one is equal) when writing out to xml so that we only end up with one?

**Comment by GeorgeTouros** [comment]
Hi @jacobtylerwalls , I pulled #603  and tried to recreate what you mention above. This is still the result:

![quantize-12_32](https://user-images.githubusercontent.com/31730489/101289057-b86a5b00-3802-11eb-9474-a650dca49577.png)

I am calling parse with the following params: 

```
base_midi = converter.parse(file, format='midi',
                            forceSource=True, quantizePost=True,
                            quarterLengthDivisors=(12, 32))
```

I'd also like to point out that for some reason Musescore never understands that the final staff should be played with drums, even though it is written on the left. If you see page two in the screenshot, the names for the instruments are also changed/corrupted. 

Is there something extra I should do except pulling the branch? Are you perhaps using different settings or a different MusicXML reader?

**Comment by jacobtylerwalls** [comment]
Yeah, I'm using Finale. Finale apparently supports metronome marks on every part; I guess MuseScore doesn't? All the more reason to get some input from Myke on the approach to take (whether to put metronome marks on every part in music21 when parsing MIDI; whether to consolidate them when writing out to xml, if they all match).

And that looks like a distinct issue with the part abbreviations on page 2. We've overridden `.partName` in the just merged features, but haven't overridden `.partAbbreviation`. We should, shouldn't we?

Also, music21 support for MIDI percussion has been missing for a while, see #398.

**Comment by mscuthbert** [comment]
I wonder if we can put them in each part but put .style.hideObjectOnPrint = True on all but the first?  When converting back to musicxml, the tempo marks on other parts is sort of unsightly.

Sabbatical starts monday.  I will get percussion in this spring.  It's embarrassing that I haven't done it -- that I've known for a long time -- but now I realize that by not having it in, it perpetuates a stereotype that non-western-classical, non-white music isn't worth analyzing, and that REALLY bugs me.

**Comment by jacobtylerwalls** [comment]
Nice.
And I checked out #703 but .hideObjectOnPrint didn't have any effect on the xml output, since 'print-style=' is not a valid attribute for <metronome> (although, funny thing: when I hacked in the attribute by hand, Finale v26 will alert you to the illegal attribute but then show a grayed out metronome mark to hide it from printing anyway...)

I think the xml writer is going to have to identify some conditions where it's safe to consolidate metronome marks?

**Comment by jacobtylerwalls** [comment]
On second thought I don't think we should override `.partAbbreviation`, because MIDI isn't giving us the literal part abbreviations, and they will print poorly in musicxml readers if we treat full names as abbreviations:

![Screen Shot 2020-12-08 at 11 02 42 PM](https://user-images.githubusercontent.com/38668450/101583537-ab3ba080-39a9-11eb-8cad-8f4bfd7707c3.png)

**Comment by GeorgeTouros** [comment]
Thank you both for jumping right on this! 

Since I'll be delivering my project by December 31st, it seems that we wouldn't be able to make all changes in time. 

My tests indicate that this issue is affecting MusicXML conversion much more than feature extraction (which is my main objective) especially for basic features, such as most common pitch, etc. It does have an effect on the more complex ones though, especially those that are around rhythm and instrumentation. Further to that, reading drums as pitches, for example, messes up the Melodic Intervals and other features. Since it's mostly pop songs I'm analyzing, they all tend to have prominent drums and percussion.

As a workaround, would it be possible for me to at least ignore drums and percussion at the feature extraction phase? Do you have any recommendations on handling pop and rock music at this stage? 

Thank you very much for your help, it's really appreciated.

**Comment by jacobtylerwalls** [comment]
Glad to help where I can. Sounds like you will want to remove unpitched percussion tracks from the streams you are sending to the extractor with minimal manual effort.

Check out things like `stream.Part.getInstrument()`, you can check if `isinstance(inst, UnpitchedPercussion)` and then filter out those parts before doing feature extraction. That will depend on having good instrument identification, though. In your example file the last part was "GM Drums" and our instrument identifier returned just a generic Instrument.

What would be AMAZING is if you could spot check a sample of your large corpus and let us know if there would be some filters we could add to the instrument identifier (for example, since "GM" means "General MIDI" --> we should strip that before sending that string to the instrument identifier, and then we can return something reasonable for "Drums").

Speaking of Drums, though, we need to define what to return. I suggest `class DrumSet(UnpitchedPercussion)`, which I think we should add.

**Comment by jacobtylerwalls** [comment]
Well, on that last point, maybe not. Once Myke gets into percussion maps and the like, maybe the idea is to pick apart every element of the drum set.

**Comment by mscuthbert** [comment]
> And I checked out #703 but .hideObjectOnPrint didn't have any effect on the xml output, since `print-style=` is not a valid attribute for `<metronome>` (although, funny thing: when I hacked in the attribute by hand, Finale v26 will alert you to the illegal attribute but then show a grayed out metronome mark to hide it from printing anyway...)
> 
> I think the xml writer is going to have to identify some conditions where it's safe to consolidate metronome marks?

`.hideObjectOnPrint` is a music21 attribute -- it's quite related to musicxml's `print-style` but not entirely.  I think that a MetronomeMark with .hideObjectOnPrint = True should create the `<sound><tempo>...</tempo></sound>` tag, but not the `<metronome>` tag on output?

I'll also see if the `print-style` can be added to `metronome` for next version of musicxml.

**Comment by jacobtylerwalls** [comment]
That's a fine idea. Here is the output after #703 for the second tempo mark (with `.hide...` = True)

```
      <direction>
        <direction-type>
          <metronome parentheses="no">
            <beat-unit>quarter</beat-unit>
            <per-minute>43</per-minute>
          </metronome>
        </direction-type>
        <sound tempo="43" />
      </direction>
```

So the task is to remove the <metronome> tag when `.hide...` is True, unless and until there is a richer, more flexible musicXML `<metronome>` definition.

**Comment by jacobtylerwalls** [comment]
Finale handles the hidden tempo marks well; MuseScore doesn't, so I chimed in on the issue on their tracker:
https://musescore.org/en/node/137091

**Comment by jacobtylerwalls** [comment]
Back to the instrument names, I think there is an improvement to be had here to consolidate instruments at the same offset. The scenario is when we have a `SEQUENCE_TRACK_NAME` immediately followed by a `PROGRAM_CHANGE` message, currently we generate two instruments:

```
>>> s.parts[0].show('t')
{0.0} <music21.instrument.Instrument 'Marcato: '>
{0.0} <music21.instrument.StringInstrument 'StringInstrument'>

>>> for ins in s.parts[0].getInstruments():
...   print('PART: ', ins.partName, 'INSTRUMENT: ', ins.instrumentName)
... 
PART:  Marcato INSTRUMENT:  None
PART:  None INSTRUMENT:  StringInstrument
```

This could cause problems with expecting the first instrument to be useful or have notes, which confused this user: https://stackoverflow.com/questions/64413988/reading-midi-file-using-music21-with-partitionbyinstrument-to-get-notes-and-ch)

Proposal: when a pair of instruments sit at the same offset and one of them isinstance generic `Instrument`, merge attributes that are either identical or None and delete the least specific instrument. Do we want this as a routine on the instrument module? `instrument.deduplicate()`?
