### ISSUE TITLE
Performance bottleneck in music21.key.Key.getLeadingTone()

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#699]
**music21 version**

`6.3.0`   

**Problem summary**

While optimizing an algorithm, I noticed an (odd) performance bottleneck, on the `getLeadingTone()` function. This operation was taking several orders of magnitude longer than, for example, comparing two pitches, or creating an Interval.

**Steps` to reproduce**

Here is a short snippet to show this:

```python
In [1]: import music21

In [2]: music21.__version__
Out[2]: '6.3.0'

In [3]: import timeit

In [4]: setup = """
   ...: import music21
   ...: 
   ...: k = music21.key.Key('C')
   ...: """

In [5]: timeit.timeit('k.getLeadingTone()', setup=setup)
Out[5]: 33.03134616499983

In [6]: setup2 = """
   ...: import music21
   ...: 
   ...: c = music21.chord.Chord(("C4", "E4", "G4"))
   ...: """

In [7]: timeit.timeit('c.root()', setup=setup2)
Out[7]: 0.161935043000085
```

Not sure if its fair to use a `chord.Chord.root()` to compare, but you get the idea. This is consistent with what I found across many music21 operations. 33 seconds to get the LeadingTone 10,000 times, compared to 0.16 seconds for the root() of a chord.

I looked at the code of `getLeadingTone()` to see if I could make a PR myself. It seems to be doing a fairly straightforward operation: compute the interval between the tonic and the seventh degree, if it's different than a `M7`, compute a `M7` from the tonic and return that. Not sure why that could be taking so long. Since a leading tone is a constant, maybe it could be a `@cached_property`?

As an "advanced" user of music21, I feel kinda guilty submitting issues rather than PRs. If I get a chance later, I'll take a closer look and work on a PR.

**Comment by jacobtylerwalls** [comment]
Identifying issues is useful work! :-)

First thing I see off the bat is that `self.pitchFromDegree(7)` is calculated twice.

What are the benchmarks for `.notesToInterval()` and `.pitchFromDegree()`?

**Comment by napulen** [comment]
Heres `notesToInterval()`

```python
In [9]: setup = """
   ...: import music21
   ...: 
   ...: n1, n2 = music21.note.Note('C4'), music21.note.Note('B4')
   ...: """

In [10]: timeit.timeit("music21.interval.notesToInterval(n1,n2)", setup=setup)
Out[10]: 19.901850692000153
```
and `pitchFromDegree()`
```python
In [11]: setup2 = """
    ...: import music21
    ...: 
    ...: k = music21.key.Key('c')
    ...: """

In [12]: timeit.timeit("k.pitchFromDegree(7)", setup=setup2)
Out[12]: 4.651218795999739
```

**Comment by jacobtylerwalls** [comment]
Very helpful! The repetitive call to `pitchFromDegree` won't be enough by itself, looks like.

With this patch I see an improvement of 76.48 sec on my machine for the existing routine to 13.96 sec, although I don't know if it's appropriate. Seems like checking for 11 semitones is all we are doing by trying to compare to "M7", but am I missing something?

```
diff --git a/music21/scale/__init__.py b/music21/scale/__init__.py
index 1273a9e2b..306e6a0f6 100644
--- a/music21/scale/__init__.py
+++ b/music21/scale/__init__.py
@@ -2503,12 +2503,12 @@ class DiatonicScale(ConcreteScale):
         <music21.pitch.Pitch B-4>
         '''
         # NOTE: must be adjust for modes that do not have a proper leading tone
-        interval1to7 = interval.notesToInterval(self.tonic, self.pitchFromDegree(7))
-        if interval1to7.name != 'M7':
+        seventhDegree = self.pitchFromDegree(7)
+        if (seventhDegree.midi - self.tonic.midi) % 12 != 11:
             # if not a major seventh from the tonic, get a pitch a M7 above
             return interval.transposePitch(self.pitchFromDegree(1), 'M7')
         else:
-            return self.pitchFromDegree(7)
+            return seventhDegree
 ```

**Comment by napulen** [comment]
Can't think of any errors if using the semitones in your patch!

**Comment by napulen** [comment]
Here is a proposal to get rid of the `.transposePitch`, which is kind of expensive

```python
        seventhDegree = self.pitchFromDegree(7)
        # interval1to7 = interval.notesToInterval(self.tonic, seventhDegree)
        if (seventhDegree.midi - self.tonic.midi) % 12 != 11:
            # if not a major seventh from the tonic, raise the seventh degre
            seventhDegree.accidental = pitch.Accidental(seventhDegree.alter + 1)
        return seventhDegree
```
This would work assuming that the reason why the seventh degree wasn't a `M7` was because it was a `m7`. Not sure if that's true, although a more robust solution would be store your subtraction and raise as many semitones as it needed to become a `M7`.

This reduced the computing time ~10-fold on my computer

**Comment by mscuthbert** [comment]
Thanks for identifying this.  The last one won't work if the seventh degree is for some reason a d7 or A7 or something else, as can be the case for an exotic scale.  We would need to figure out how far off the midi is from (11 % 12) and put that difference in here.  It'd still be substantially faster.

Can someone check that pitchFromDegree returns a copy of a pitch and not the same one each time?  Thanks!

**Comment by napulen** [comment]
`pitchFromDegree` returns a new `Pitch` object. There is `copy.deepcopy` inside and I checked that two returned pitches from `pitchFromDegree` fail a `k.pitchFromDegree(7) is k.pitchFromDegree(7)` check. That should indicate different copies, right?

Here is a snippet with the diff.

```python
seventhDegree = self.pitchFromDegree(7)
distanceInSemitones = seventhDegree.midi - self.tonic.midi
if distanceInSemitones % 12 != 11:
    # if not a major seventh from the tonic, raise the seventh degree
    alterationInSemitones = 11 - distanceInSemitones
    seventhDegree.accidental = pitch.Accidental(
        seventhDegree.alter + alterationInSemitones
    )
return seventhDegree
```

Bad news: After checking this version, I didn't notice the same 10-fold difference in performance that I originally reported. I don't remember what exactly I did last time and I am afraid I maybe made a mistake then. It is a bit faster than the current implementation. Maybe what @jacobtylerwalls is more appropiate in terms of current implementation vs this one.

**Comment by jacobtylerwalls** [comment]
I'm still seeing a dramatic difference.

Original implementation: 93.7 for happy path; 274.1 for altered path
My suggestion for happy path: 14.0; your suggestion for altered path: 26.5

***
My only reason for taking mod 12 was to account for the possibility of scales somehow spanning more than one octave. If that's not realistic (I'm skimming the docs and don't see how...) then we can use a plain old end - start == 11.

**Comment by napulen** [comment]
Good to know there is still a significant difference! About the mod 12, I do know of scales that span more than an octave, although probably not within the `Diatonic` category. In any case, I think the mod 12 is far from the most expensive computation there and it is maybe a good safeguard?

**Comment by jacobtylerwalls** [comment]
Néstor, are you inclined to submit a patch?

**Comment by mscuthbert** [comment]
Happy to take a PR.  This looks like a good path.  Yes, I was too was worried about exotic scales, but this is in class DiatonicScale, so should be fine.  Each step appears exactly once in a diatonic scale.

**Comment by napulen** [comment]
Hey, thank you both. Yes! I can submit a patch by Monday (currently modding the hardware on my laptop).

**Comment by napulen** [comment]
PR here #707.

**Comment by mscuthbert** [comment]
Thanks!  Merged!
