### ISSUE TITLE
music21 show() ... showing nothing

### ISSUE THREAD

**Issue by piercalderan** [cuthbertLab/music21#702]
Hi, I have installed Python 3.7.4, matplotlib, numpy and music21.
I write your example:

from music21 import *
b = corpus.parse('bach/bwv66.6')
b.show()

After a while the script end with no errors, but don't see nothing.
What should I do?

**Comment by mscuthbert** [comment]
Hi -- please ask others for help on the music21list.  This forum is for verified errors.  Make sure you've run the configuration assistant.
