### ISSUE TITLE
Chord symbol "FFr+6" can't be created

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#720]
**music21 version**

`6.4.1`

**Problem summary**
Chord symbol "FFr+6" can't be created.

**Steps to reproduce**

```
>>> cs = harmony.ChordSymbol('FFr+6')
Traceback (most recent call last):
  File "/Users/jwalls/music21/music21/harmony.py", line 1884, in _parseFigure
    justInts = int(justInts)
ValueError: invalid literal for int() with base 10: 'r+6'
```

**More information**
Found this by fixing up the test in #719. F#Fr+6 works fine.

**Comment by mscuthbert** [comment]
Do people use Aug6 names in Chord Symbols?
