### ISSUE TITLE
Root modification skipped on Roman numerals with notes omitted (e.g. 'viio[no5]')

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#725]
Hi @mscuthbert and @jacobtylerwalls 

Thanks for all the recent upgrades, esp. #713's docs and #715's fix on the specific case of V7b5. The latter reminds me to flag up a related issue with missing chord notes and modification for quality:

If we have a full triad, then all is well:
```
>>> r = roman.RomanNumeral('viio', 'a')
>>> r.pitches
(<music21.pitch.Pitch G#5>, <music21.pitch.Pitch B5>, <music21.pitch.Pitch D6>)
```

If the triad is incomplete, then we miss out on the default 'quality' modification that would root this triad on G# (instead of G natural):
```
>>> r = roman.RomanNumeral('viio[no5]', 'a')
>>> r.pitches
(<music21.pitch.Pitch G5>, <music21.pitch.Pitch B5>)
```
As you know, the 'quality' modifier is not dependent on the diminished quality specifically. So repeating the above with minor in place of diminished:
```
>>> r = roman.RomanNumeral('vii', 'a')
>>> r.pitches
(<music21.pitch.Pitch G#5>, <music21.pitch.Pitch B5>, <music21.pitch.Pitch D#6>)
```

... but ... 
```
>>> r = roman.RomanNumeral('vii[no5]', 'a')
>>> r.pitches
(<music21.pitch.Pitch G5>, <music21.pitch.Pitch B5>, <music21.pitch.Pitch D6>)
```

(That case also fails to remove the 5th.)

Perhaps the best solution is to maximise shared methods by first building up full triads on the basis of their being complete and then do the removal as a last step? Or is creating redundant pitches to be avoided for speed?

I'm happy to look more closely into what's currently happening if you like and / or draft a specific implementation if you have something in mind.

Thanks!

**Comment by mscuthbert** [comment]
Creating redundant pitches is generally to be avoided for speed reasons, but if it creates bugs then who cares about speed.  (And [noX] modifications are rare enough it shouldn't affect creation time in general)

It might just be a case of moving the parseOmitted and parseAdded steps down a few lines.

**Comment by mscuthbert** [comment]
@jacobtylerwalls fixed it!

**Comment by MarkGotham** [comment]
Thanks!
