### ISSUE TITLE
musicxml import might create a crashy tie of type None

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#728]
**music21 version**

`6.4.1`

**Problem summary**
MusicXML import is creating ties with types of None in some scenarios, which can crash on `.show()`

**Steps to reproduce**

```
>>> from music21.musicxml.testPrimitive import timeSignatures11c as t11c
>>> s = music21.converter.parse(t11c)
>>> s.parts[0].measure(2).notes[0]
<music21.note.Note A>
>>> s.parts[0].measure(2).notes[0].tie
<music21.tie.Tie>
>>> s.parts[0].measure(2).notes[0].tie.type is None
True
>>> s.write()
```

**Expected vs. actual behavior**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1052, in _escape_attrib
    if "&" in text:
TypeError: argument of type 'NoneType' is not iterable
```

**More information**
As you may have gathered, I've been testing some roundtrips with corpus files.

**Comment by mscuthbert** [comment]
Thank you!  Wow, is that an old example!  I should eventually do an audit that all examples open in Finale w/o errors.  Some are from MusicXML v0.2!
