### ISSUE TITLE
Performance bottleneck chord.Chord.isTriad()

### ISSUE THREAD

**Issue by napulen** [cuthbertLab/music21#740]
**music21 version**

`6.3.0`   

**Problem summary**

In my recent experiments optimizing an expensive algorithm, another performance bottleneck I noticed was this function `chord.Chord.isTriad()`. It is slower than `isMajorTriad()`, `isMinorTriad()`, `isDiminishedTriad()`, `isAugmentedTriad()`. It is also slower than `isSeventh()` although I haven't verified whether that was because I was calling `isSeventh()` afterward and there were some cached attributes already.

I spent some time looking at the implementation. This is the current implementation:
```python
        if self.pitchClassCardinality != 3:
            return False

        try:
            third = self.third
            fifth = self.fifth
        except ChordException:
            return False
        if third is None or fifth is None:
            return False
        for thisPitch in self.pitches:
            try:
                thisInterval = interval.notesToInterval(self.root(), thisPitch)
            except ChordException:
                return False
            if thisInterval.diatonic.generic.mod7 not in (1, 3, 5):
                return False
            if self.hasAnyRepeatedDiatonicNote():
                return False
        return True
```

I think this implementation can be improved. In fact, after looking at the `third` and `fifth` attributes, I wonder if this would be an equivalent (and much faster) check:

```python
        # if self.pitchClassCardinality != 3:
        #     return False
        # try:
        #     third = self.third
        #     fifth = self.fifth
        # except ChordException:
        #     return False
        # if third is None or fifth is None:
        #     return False
        # for thisPitch in self.pitches:
        #     try:
        #         thisInterval = interval.notesToInterval(self.root(), thisPitch)
        #     except ChordException:
        #         return False
        #     if thisInterval.diatonic.generic.mod7 not in (1, 3, 5):
        #         return False
        #     if self.hasAnyRepeatedDiatonicNote():
        #         return False
        if self.pitchClassCardinality == 3 and self.third and self.fifth:
            return True
        return False
```

`self.third` and `self.fifth` are implemented using `getChordStep()`, which always returns `None` if the diatonic step was not found (i.e., no need for the try/catch approach displayed in the current implementation?). The pitch class cardinality would make sure that there is not more than one "flavor" of third and one "flavor" of fifth, which is what `hasAnyRepeatedDiatonicNote()` is currently doing. By the way, the latter function (`hasAnyRepeatedDiatonicNote()`) seems to be the main bottleneck within the current implementation, as it is the most significant difference between this function and others (e.g., `isMajorTriad()`).

If the changes I propose make sense for this function, then the same applies to other functions related to triad/seventh chords, as they all share similarities in their implementation. I just thought about starting with this one.

**Comment by jacobtylerwalls** [comment]
Nice find! Figured I would go fishing for a counterexample, and sure enough:

```
>>> c = chord.Chord('C E G B#')
>>> c.pitchClassCardinality
3
>>> c.third
<music21.pitch.Pitch E>
>>> c.fifth
<music21.pitch.Pitch G>
>>> c.isTriad()
False
```

**Comment by napulen** [comment]
Haha, nice fishing @jacobtylerwalls!

Okay, so maybe not pitch classes but pitch names:

```python
        uniquePitchNames = set(self.pitchNames)
        if len(uniquePitchNames) == 3 and self.third and self.fifth:
            return True
        return False
```

Here is a short performance test:

```python
stmt = """
c = music21.chord.Chord("C4 E4 G4")
c.isTriad()
"""

setup = """
import music21
"""

print(timeit.timeit(stmt=stmt, setup=setup, number=50000))
```
Here is what I get:

```bash
(older) $ python tmp.py 
130.32809207900004

(newer) $ python tmp.py 
2.6925288789998376
```

This version does pass the counter example with enharmonics.

**Comment by jacobtylerwalls** [comment]
Nice, that looks promising. You're right that `hasAnyRepeatedDiatonicNote()` is expensive:
- checks all 7 chord steps
- runs `interval.notesToInterval` per pitch, per chord step, after the current `isTriad` also already ran it per pitch
- call from `isTriad()` doesn't pass `testRoot=self.root()` so `self.root()` runs 7 times

**Comment by mscuthbert** [comment]
Is fixing `hasAnyRepeatedDiatonicNote()` to this good enough:

```
        if len(set(p.step for p in self.pitches)) != len(set(p.name for p in self.pitches)):
            return False
        else:
            return True
```

**Comment by mscuthbert** [comment]
That moves from

```
In [1]: %timeit chord.Chord('C4 E4 G4').isTriad()
4.71 ms ± 552 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

to

```
In [1]: %timeit chord.Chord('C4 E4 G4').isTriad()
240 µs ± 8.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Which is a 19-fold speed up. Not as good as the 48-fold speed up you have, so I think we do both.

Immediately I can see that hasAnyRepeatedDiatonicNote() is being called once per pitch rather than once total, so that's no good!

**Comment by mscuthbert** [comment]
Thanks!  See #744

**Comment by MarkGotham** [comment]
Nice!
