### ISSUE TITLE
Missing optional packages with Python 3.8+ results in exception

### ISSUE THREAD

**Issue by nblumoe** [cuthbertLab/music21#750]
**music21 version**

`6.5.0`   

**Problem summary**
Importing music21 with Python 3.9 or 3.8 results in an unhandled exception, when `matplotlib` or `numpy` are missing.

**Steps to reproduce**

1. create python environment with Python 3.9 or 3.8 and `matplotlib` and `numpy` not installed
2. create simple script with `from music21 import *`
3. run the script

-> observe the following exception:

```
/Users/nblu/.virtualenvs/python_music/bin/python "/Users/nblu/src/Python Composition/00_test.py"
Traceback (most recent call last):
  File "/Users/nblu/src/Python Composition/00_test.py", line 1, in <module>
    from music21 import *
  File "/Users/nblu/.virtualenvs/python_music/lib/python3.9/site-packages/music21/__init__.py", line 169, in <module>
    from music21 import base  # noqa: E402
  File "/Users/nblu/.virtualenvs/python_music/lib/python3.9/site-packages/music21/base.py", line 119, in <module>
    loader = importlib.util.find_spec(modName)
AttributeError: module 'importlib' has no attribute 'util'

Process finished with exit code 1
```

**Expected vs. actual behavior**
I expect the packages to be optional and music21 to work without them. When the packages are missing, it should be handled gracefully without crashing the process.

**More information**

This seems to get triggered from this code in `base.py`, which will invoke `importlib.util` when the packages aren't installed:
```
# music21/base.py

_missingImport = []
for modName in ('matplotlib', 'numpy'):
    loader = importlib.util.find_spec(modName)
    if loader is None:
        _missingImport.append(modName)
```

macOS Catalina

The issue resolves when the two packages mentioned above get installed.

Thanks for providing and maintaining this great library. 🖤

**Comment by mscuthbert** [comment]
Cannot reproduce right now.  What OS are you using?

**Comment by mscuthbert** [comment]
my guess is that you might have another file called importlib somewhere on your system.  Does starting Python and running:

```
from importlib.util import find_spec
```

work?

If it does not work, try this:

```
import importlib
print(importlib.__file__)
```

and it should say something like:

```
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py
```

if it says something very different then that's probably the problem.

**Comment by nblumoe** [comment]
@mscuthbert it seems to me, that everything from this issue applies for me, despite using macOS Catalina (and not Win like in the issue reported): https://bugs.python.org/issue31318

Thus, I would expect the fix to resolve my issues (haven't had a chance to test yet).

Adding an explicit `from importlib.util import find_spec` before `from music import *` also fixes it. I suspect this makes the submodule available when `music21` tries to use it.

About the checks you suggested:
```
from importlib.util import find_spec
```
works and it also resolves to what seems to be the correct files, e.g. for a Python 3.9 env: 
```python
print(importlib.__file__)
#=> /usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py
```

I think the problem was indeed that the submodule wasn't imported explicitly, which should be fixed now with https://github.com/cuthbertLab/music21/pull/752 by @jacobtylerwalls ! 👍

**Comment by mscuthbert** [comment]
The fix is in -- so using the Git version of music21 from Master will now work for you.  Was there no problem before on earlier music21 versions?  The error that you've seen is based on code that's been in for two years.  Thus, I won't be rushing out a maintenance release too quickly.

**Comment by nblumoe** [comment]
@mscuthbert this is the first time I am using music21, I never used any earlier versions.
