### ISSUE TITLE
MEI import fails with 'AttributeError: 'NoneType' object has no attribute 'split''

### ISSUE THREAD

**Issue by heinzr** [cuthbertLab/music21#762]
I have looked at this problem more closely, and it happens in the following situation:
 - The MEI files contains something like ```<artic xml:id="artic-xxxx" />```.
In this case the function '_makeArticList (attrib)' is called, and fails on attrib.split, since attrib in this case is None.

 - In two of three situations where '_makeArticList' is called, it is checked whether the attrib is None before calling, but in articFromElement it is not. 

Beyond that it gets too complicated for me...

Of course the input file should not include non-sensical lines like the above, but sometimes this happens, and it would be nice if the import would not fail, especially since find the cause is not trivial. A better way would be just to ignore it. (IMHO the best way would be to ignore it, and write a log entry that the line was ignored and why.)

**Comment by ahankinson** [comment]
I think GitHub has masked the sample MEI -- if you could put code formatting around it, it will show correctly.

**Comment by mscuthbert** [comment]
> I think GitHub has masked the sample MEI -- if you could put code formatting around it, it will show correctly.

I don't see it in the "edit" mode above so if it was once there it was removed completely.  But I do think that this has given enough information to patch the problem.
