### ISSUE TITLE
MEI import fails when determining key signature from attributes (pname and mode)

### ISSUE THREAD

**Issue by heinzr** [cuthbertLab/music21#765]
In a MEI file from DME one finds ```<key mode="major" pname="d"/>```. The import tries to derive the key signature from it and fails, when combining tonic and accidental, since the accidental is set to None.

I think that this can be fixed by changing one line in _keySigFromAttrs:
From:
```return key.Key(tonic=elem.get('key.pname') + _accidentalFromAttr(elem.get('key.accid')), mode=mode)```
to:
```return key.Key(tonic=elem.get('key.pname') + _accidentalFromAttr(elem.get('key.accid',default='')),mode=mode)```

**Comment by mscuthbert** [comment]
Thanks!  Great issue file and great PR!
