### ISSUE TITLE
Conversion of non-string lyric when instantiating music21.note.GeneralNote and childs

### ISSUE THREAD

**Issue by 0x2b3bfa0** [cuthbertLab/music21#768]
**music21 version**

`6.3.0`

**Problem summary**

When instantiating a `GeneralNote` object or any of its child classes with a `lyric` keyword argument equal to a non-string value, it gets converted to its string representation even if it's `None`.

**Steps to reproduce**

```python
>>> import music21
>>> note_a = music21.note.GeneralNote(lyric=None)  # Unexpected behavior.
>>> note_b = music21.note.GeneralNote(); note_b.lyric = None  # Desired behavior.
```

**Expected vs. actual behavior**

When passing `None` as the value for the `lyric` keyword argument, it's being processed through the [`addLyric`](https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L467-L538) method, which [converts](https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L522-L523) any non-string lyric to a string, disregarding the special type `None` that indicates the absence of lyrics.

```python
>>> type(note_a.lyric)
<class 'str'>
>>> note_a.lyric
'None'  # Unexpected behavior; converts the type to string.
```

```python
>>> type(note_b.lyric)
<class 'NoneType'>
>>> note_b.lyric
None  # Desired behavior, keeps the original type.
```

**More information**

In my opinion, it would be nice to replace [`addLyric`](https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L467-L538) by [`_setLyric`](https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L420-L430) [here](https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L379
), so the special `None` and `False` values are taken into account:

https://github.com/cuthbertLab/music21/blob/4c25aeac5462de6c1d5c9513a9a6ed3ea19eb6ad/music21/note.py#L379

**Comment by mscuthbert** [comment]
It seems to me that second version `n.lyric = None` is a shortcut for the imaginary method `n.deleteLyric()` whereas putting lyric=None in the constructor is the equivalent of saying "do nothing" -- which seems to defeat the point.

What  about simply putting in the constructor:

```
if 'lyric' in keywords and keywords['lyric'] is not None:
     ... do what we did previously...
```

?
