### ISSUE TITLE
MusicXML conversion error encountered after upgrade to version 6.5

### ISSUE THREAD

**Issue by snarrenberg** [cuthbertLab/music21#774]
**music21 version**

`6.5`

**Problem summary**
Conversion of a MusicXML score for piano that worked under previous versions of music21 now no longer works.

**Steps to reproduce**

```
source = 'XmlConversionTest.musicxml'
s = converter.parse(source)
s.show()
```

**Expected vs. actual behavior**

[XmlConversionTest.musicxml.zip](https://github.com/cuthbertLab/music21/files/5809823/XmlConversionTest.musicxml.zip)

**More information**

**Comment by jacobtylerwalls** [comment]
Thanks for the report and for the fast turnaround. My hunch was right; music21 created two `layout.StaffGroup` objects, one from the `<part-group>` in the source musicxml, and one from the new piano import/export improvements used to merge piano staves back together.

```
>>> s = converter.parse('/Users/jwalls/Downloads/XmlConversionTest.musicxml')
>>> s.show('t')
{0.0} <music21.text.TextBox 'Westergaar...'>
{0.0} <music21.metadata.Metadata object at 0x109694dc0>
{0.0} <music21.stream.PartStaff P1-Staff1>
    {0.0} <music21.instrument.Instrument 'P1: Piano: Piano'>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.layout.SystemLayout>
        {0.0} <music21.clef.TrebleClef>
        {0.0} <music21.key.KeySignature of 1 flat>
        {0.0} <music21.meter.TimeSignature 1/1>
        {0.0} <music21.note.Note D>
{0.0} <music21.stream.PartStaff P1-Staff2>
    {0.0} <music21.instrument.Instrument 'P1: Piano: Piano'>
    {0.0} <music21.stream.Measure 1 offset=0.0>
        {0.0} <music21.layout.SystemLayout>
        {0.0} <music21.layout.StaffLayout distance 65, staffNumber 2, staffSize None, staffLines None>
        {0.0} <music21.clef.BassClef>
        {0.0} <music21.key.KeySignature of 1 flat>
        {0.0} <music21.meter.TimeSignature 1/1>
        {0.0} <music21.note.Note D>
{0.0} <music21.layout.ScoreLayout>
{0.0} <music21.layout.StaffGroup <music21.stream.PartStaff P1-Staff1><music21.stream.PartStaff P1-Staff2>>
{0.0} <music21.layout.StaffGroup <music21.stream.PartStaff P1-Staff1><music21.stream.PartStaff P1-Staff2>>
```

The source file says it was created in Musescore. It opens like this in Musescore:

![rendered-musescore](https://user-images.githubusercontent.com/38668450/104519899-37a03b00-55c8-11eb-916d-4726deb68b6b.png)

And like this in Finale, which shows what I would expect, that the `<part-group>` bracket is extraneous:

![rendered-Finale](https://user-images.githubusercontent.com/38668450/104519918-425ad000-55c8-11eb-9e20-bf366ea89fe1.png)

Still, the `PartStaffExporter` in v.6.5 shouldn't crash when it gets two `layout.StaffGroup` objects covering the same objects. I'll look into a patch.

***

Finally, may I ask if this Musescore's default behavior to add these `<part-group>` brackets, or were the brackets deliberately added? If there is faulty default behavior in Musescore I can take a look at their issue tracker and see if it's known.

**Comment by jacobtylerwalls** [comment]
Ah, these brackets may have been added deliberately as a workaround for music21's lack of support for exporting piano music to musicxml with a brace until v.6.5! 

As of 6.5 those workarounds should be unnecessary.

**Comment by mscuthbert** [comment]
Should be fixed in latest commit -- please feel free to reopen if not!
