### ISSUE TITLE
Uncaught TypeError: Cannot read property 'py/id' of null

### ISSUE THREAD

**Issue by ubaldino** [cuthbertLab/music21#78]
I want to generate a json file in the following example
http://web.mit.edu/music21/doc/moduleReference/moduleVexflowToMusic21j.html

to tranportarlo to music21j the following example
https://github.com/cuthbertLab/music21j/blob/master/testHTML/jsonpickleParse.html

but when testing throws the following error in the console browser
"Uncaught TypeError: Cannot read property 'py/id' of null"

**Comment by mscuthbert** [comment]
Hello ubaldino -- can you give some more information, including a minimal test case.  Thank you.  Sorry for the long delay.s

**Comment by ubaldino** [comment]
Thank you and please.

I want to generate the notes from python with MusicXML syntax that can be
interpreted with javascript.

I miss several tests and I can not generate from python.

2015-10-08 17:06 GMT-04:00 Michael Scott Cuthbert <notifications@github.com>
:

**Comment by mscuthbert** [comment]
Ubaldino -- I'm going to need more information -- do you have a small file and code you run on it that generates the error? Nothing is arising in our tests.

**Comment by mscuthbert** [comment]
Closed for lack of activity; feel free to reopen.
