### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by amcdawes** [cuthbertLab/music21#787]
**music21 version**

`6.5.0`   

**Problem summary**

Documentation found at http://web.mit.edu/music21/ includes sample code:
```
catalog = stream.Opus()
for workName in corpus.chorales.Iterator():
  work = converter.parse(workName)
  firstTS = work.recurse().getElementsByClass('TimeSignature')[0]
  if firstTS.ratioString == '6/8':
    catalog.append(work.measures(0, 2))
catalog.show() 
```

That throws an error "Score has no attribute startswith"

**Steps to reproduce**

 - Install from scratch.
 - Run the following:
```
catalog = stream.Opus()
for workName in corpus.chorales.Iterator():
  work = converter.parse(workName)
  firstTS = work.recurse().getElementsByClass('TimeSignature')[0]
  if firstTS.ratioString == '6/8':
    catalog.append(work.measures(0, 2))
catalog.show() `
```

**Expected vs. actual behavior**

**More information**

Suggested fix:
Removing the parse step fixes the issue. It appears Iterator already returns `Score` objects.

The following complete example works:

```
catalog = stream.Opus()
for work in corpus.chorales.Iterator():
  firstTS = work.recurse().getElementsByClass('TimeSignature')[0]
  if firstTS.ratioString == '3/4':
    print("found one")
    catalog.append(work.measures(0, 2))
catalog.show() 
```

**Comment by mscuthbert** [comment]
Thank you!  Should be fixed in an hour (next MIT web update).
