### ISSUE TITLE
Parsing MusicXML ignores repeat 'backward'

### ISSUE THREAD

**Issue by slychief** [cuthbertLab/music21#80]
Hi!

I am trying to analyse a MusicXML file:

```Python

# input files
music_score_output_musicxml_page1 = "IMSLP5673-Bach-partita-flute-allemande_Seite_1.xml"

# load MusicXML using music21
score_object_page1 = converter.parse(music_score_output_musicxml_page1)

for page in layout.divideByPages(score_object_page1, fastMeasures = False).pages:
    
    print "Page", page
        
    for system in page.systems:
        for staff in system.staves:
            for measure in staff.getElementsByClass('Measure'):
                
                print "\t", measure

                for elem in measure._elements:
                    if type(elem) == Repeat:
                    
                        print "\t\t", elem
```

Using this file:
http://www.ifs.tuwien.ac.at/~schindler/files/IMSLP5673-Bach-partita-flute-allemande_Seite_1.xml

It was first extracted from an image using Audiveris and then manually corrected using MuseScore. Finally I checked in the XML source if the <repeat> and <ending> tags are set properly.

Applying the code on the file provides the following output:

	Page <music21.layout.Page 369844296>
		<music21.stream.Measure 0 offset=0.0>
			<music21.bar.Repeat direction=start>
		<music21.stream.Measure 1 offset=3.625>
		<music21.stream.Measure 2 offset=7.625>
		<music21.stream.Measure 3 offset=11.625>
		<music21.stream.Measure 4 offset=15.625>
		<music21.stream.Measure 5 offset=19.375>
		<music21.stream.Measure 6 offset=23.0625>
		<music21.stream.Measure 7 offset=27.0625>
		<music21.stream.Measure 8 offset=31.0625>
		<music21.stream.Measure 9 offset=34.0625>
		<music21.stream.Measure 10 offset=37.8125>
		<music21.stream.Measure 11 offset=41.875>
		<music21.stream.Measure 12 offset=45.875>
		<music21.stream.Measure 13 offset=49.75>
		<music21.stream.Measure 14 offset=53.625>
		<music21.stream.Measure 15 offset=57.625>
		<music21.stream.Measure 16 offset=61.625>
		<music21.stream.Measure 17 offset=65.625>
		<music21.stream.Measure 18 offset=69.625>
		<music21.stream.Measure 19 offset=73.5>
		<music21.stream.Measure 20 offset=77.375>
			<music21.bar.Repeat direction=start>
		<music21.stream.Measure 21 offset=81.375>
		<music21.stream.Measure 22 offset=85.375>
		<music21.stream.Measure 23 offset=89.375>
		<music21.stream.Measure 24 offset=93.125>

Maybe there is something wrong with the MusicXML file or there seems to be a bug in music21's MusicXML parser.

**Comment by mscuthbert** [comment]
Why are you using ``for el in measure._elements`` instead of ``for el in measure``? this is almost certainly the problem.

**Comment by slychief** [comment]
It was!

Thanks for the quick response!

**Comment by mscuthbert** [comment]
Great! In general there's nothing in a ``_private`` method in music21 that ever needs to be called. :-)

**Comment by mscuthbert** [comment]
For reference: ._elements returns elements that are positioned in a measure.   ._endElements finds elements that are positioned at the end of the measure no matter how many elements are placed in the measure.  For instance, repeat signs.  Iterating over a Stream finds both types.
