### ISSUE TITLE
Catch non-zero exits in SubConverter.launch?

### ISSUE THREAD

**Issue by Meekohi** [cuthbertLab/music21#804]
https://github.com/cuthbertLab/music21/blob/2a3ba8d6ba759897bbd93879b70cae23ca111fd9/music21/converter/subConverters.py#L196

`Finale.exe` at least fails to return 0 when called from a python notebook, which bubbles up an annoying `CalledProcessError` even though everything worked fine. Would it be worth wrapping this in a `try:` / `except subprocess.CalledProcessError` to deal with this use case? If handling it silently seems bad, maybe we could just print a one-liner warning instead of forcing the developer to deal with the full exception?

**Comment by jacobtylerwalls** [comment]
I'm the guilty party--I moved show/launch over to using subprocess.run, and I don't use Python notebooks so didn't catch it. Thanks for the report.

If Finale.exe doesn't return 0 in a Python notebook, that's a pretty basic use case for .show/.launch, so I would think we should just set `check=False` to get closer to the old behavior. The launch is a convenience; I doubt there are programs that will miss bugs if `.launch` fails to open a viewer.

**Comment by Meekohi** [comment]
Thank you!
