### ISSUE TITLE
Part staffs with multiple keys

### ISSUE THREAD

**Issue by mscuthbert** [cuthbertLab/music21#808]
**music21 version**

`6.7`   

**Problem summary**

41b and 41c in musicxml test are both failing -- check to see if it is music21 or MuseScore?

**Comment by jacobtylerwalls** [comment]
Missing feature in `setEarliestAttributesAndClefsPartStaff`, which probably needs to just be `setInitialAttributes`.

**Comment by jacobtylerwalls** [comment]
Well, and also this is a regression since #734 , since now we have an extra ks in the subsequent staff in the Python objects.
