### ISSUE TITLE
MIDI could make measures

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#824]
**music21 version**

7

**Problem summary**
MIDI doesn't make measures. It makes:
- Score
-- Part
---- Voice

The lack of a measure layer leads to user questions (hence the tip in #754), but we have the knowledge of time signatures, so I'm not sure what's holding us back from just making the measures. A user will probably import midi, `.show()` it to find out how it turned out, see measures, but in reality they only have measures by virtue of `.show()` making notation.

The part-direct-to-voice hierarchy also leads to funny things, like making notation on `.show()` attempting to make voices a second time, because there aren't measures:

https://github.com/cuthbertLab/music21/blob/4f67e0ddb4e5d9fce459d7aa0802b278de1c9d06/music21/stream/__init__.py#L6306-L6316

That second-time-through `makeVoices` turns out okay because it doesn't recurse, so there are no notes in the part container, and it quits. But that should be made safer? Print a warning? If somebody `.insert()`'s notes into a part created from MIDI (with voices), then this second-time-around makeVoices is going to do nothing, unless the added flat notes have overlaps, in which case you'll get 4 voices instead of 2.

Opinions?

**Comment by jacobtylerwalls** [comment]
Well, there's a problem here, which is that I've been encouraging people to makeMeasures, but that's dangerous if there are parts, because unlike makeNotation, makeNotation just flattens everything, destroying the parts.

```
>>> s = converter.parse("/Users/jwalls/Downloads/obr.mid", forceSource=True)
>>> s.parts[0]
<music21.stream.Part 0x10dbb5700>
>>> made = s.makeMeasures()
>>> made.parts[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/stream/iterator.py", line 340, in __getitem__
    e = fe[k]
IndexError: list index out of range
```
That's probably something to address separately.

**Comment by jacobtylerwalls** [comment]
There appears to be a chorus of Medium posts about AI music generation using music21 to parse MIDI, and they all get around this by calling `.partitionByInstrument()`, which is a little strange, but I suppose demonstrates the point that ultimately people are trying to get well-formed notation.

**Comment by mscuthbert** [comment]
One of the tasks for v7 is to remake MIDI translate into two modules / two classes to handle import and export to make improvements like this better.  So happy to take PRs to help with this, but I think that making the modules/classes first is a necessary step soon -- I don't improve MIDI much because I don't fully understand the workflow the way I would if it resembled other translators.

**Comment by jacobtylerwalls** [comment]
I get that. Refactor might be needed for percussion?

Right now I think we can just do this:
```diff --git a/music21/midi/translate.py b/music21/midi/translate.py
index c24c9e298..2743021d2 100644
--- a/music21/midi/translate.py
+++ b/music21/midi/translate.py
@@ -1873,12 +1873,14 @@ def midiTrackToStream(
                    inPlace=True,
                    recurse=False)  # shouldn't be any substreams yet
 
-    if voicesRequired:
-        # this procedure will make the appropriate rests
-        s.makeVoices(inPlace=True, fillGaps=True)
-    else:
-        # always need to fill gaps, as rests are not found in any other way
-        s.makeRests(inPlace=True, fillGaps=True)
+    s.makeMeasures(inPlace=True)
+    for m in s.getElementsByClass(stream.Measure):
+        if voicesRequired:
+            # this procedure will make the appropriate rests
+            m.makeVoices(inPlace=True, fillGaps=True)
+        else:
+            # always need to fill gaps, as rests are not found in any other way
+            m.makeRests(inPlace=True, fillGaps=True)
     return s
```

Eventually (not this week), I'll open a PR--bunch of tests to fix up.


```
----------------------------------------------------------------------
File "/Users/jwalls/music21/music21/midi/translate.py", line 2534, in __main__.midiStringToStream
Failed example:
    s.show('text')
Expected:
    {0.0} <music21.stream.Part ...>
        {0.0} <music21.note.Note G>
Got:
    {0.0} <music21.stream.Part 0x105f74c40>
        {0.0} <music21.stream.Measure 1 offset=0.0>
            {0.0} <music21.instrument.Instrument ''>
            {0.0} <music21.clef.TrebleClef>
            {0.0} <music21.meter.TimeSignature 4/4>
            {0.0} <music21.note.Note G>
            {1.0} <music21.bar.Barline type=final>
```

**Comment by mscuthbert** [comment]
This is a great change to do during the v6 -> v7 time.
