### ISSUE TITLE
Converter.parse should not parse string if ends with a known format extension.

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#847]
**Version of music21**
Dev (github)

**Problem summary**
There's currently no check that the file exists when attempting to open Roman text files. (No prizes for guessing how I found that out!). Instead you get right through to this error message:

```
romanText/rtObjects.py", line 1096, in splitAtHeader
    raise RomanTextException('Cannot find the first measure definition in this file. '
music21.romanText.rtObjects.RomanTextException: ('Cannot find the first measure definition in this file. Dumping contexts: %s'
```

**Proposed Fix**
It looks like the place to introduce the check is in `romanText.rtObjects.RTFile.open()` around line 1383. A simple `os.path.exists(fp)` would perhaps do?

**Comment by jacobtylerwalls** [comment]
Hi Mark -- can you add a few more lines to reproduce? I'm seeing this:

```
>>> from music21 import *
>>> rtf = romanText.rtObjects.RTFile()
>>> rtf.open('no_exit.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/romanText/rtObjects.py", line 1397, in open
    self.file = io.open(filename, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'no_exit.txt'
```

or:
```
>>> s = converter.parse('/Users/jwalls/Desktop/a.rntxt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 1184, in parse
    return parseData(value, number=number, format=m21Format, **keywords)
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 1038, in parseData
    v.parseData(dataStr, number=number, format=format, **keywords)
  File "/Users/jwalls/music21/music21/converter/__init__.py", line 626, in parseData
    raise ConverterException('File not found or no such format found for: %s' %
music21.converter.ConverterException: File not found or no such format found for: /Users/jwalls/Desktop/a.rntxt
```

**Comment by MarkGotham** [comment]
Oh. That looks good.

**Comment by MarkGotham** [comment]
I get this:

```
from music21 import converter
analysis = converter.parse(thisPath, format='Romantext')
analysis.show('t')
```

If thisPath is a real rntxt file:
- you get the analysis - no problem there!

If thisPath is a directory:
- you get a good error message (so no issue there either):
`IsADirectoryError: [Errno 21] Is a directory`

If thisPath leads to a non-existent file:
- you get a misleading error message 
```
raise RomanTextException('Cannot find the first measure definition in this file. '
music21.romanText.rtObjects.RomanTextException: ('Cannot find the first measure definition in this file. Dumping contexts: %s
```

**Comment by MarkGotham** [comment]
Perhaps I'm accidentally running on a non-dev copy. I'll check.

**Comment by MarkGotham** [comment]
I've pulled the to-off-the-press latest commits and can still reproduce this in different ways. If the issue is on my end then I'll investigate further and apologise for the false alarm.

**Comment by MarkGotham** [comment]
macOS Catalina, for what it's worth

**Comment by jacobtylerwalls** [comment]
Oh got it, it's `format=('Romantext')` that's necessary. Thanks!

**Comment by jacobtylerwalls** [comment]
Had a quick look: `converter.parse` accepts either path objects or strings, and if it's a string, it checks if it's a valid filepath, and if not, it attempts to process it as data. So your nonexistent file path was processed as data, and there's your unhelpful failure message.

Maybe converter.parse should just raise `FileNotFoundError` when a string ends in one of the allowed extensions instead of attempting to process it as a data string?

**Comment by mscuthbert** [comment]
That's a better overall solution.  Changing the title of the issue and adopting it as a TODO.

**Comment by mscuthbert** [comment]
Note that this won't help for the case of a file that ends with an unknown file-extension like .txt

**Comment by MarkGotham** [comment]
Thanks @mscuthbert and @jacobtylerwalls 

What do you think about starting every `converter.parse` call with an `exists` check on the file path, before doing anything else? Surely if the proposed file doesn't exist, we don't want to do anything at all: no attempted parse, no format checking, nothing. I imagine that accidental errors in file paths are pretty common.

**Comment by jacobtylerwalls** [comment]
Well it does that already, but the problem is that also accepts plain strings of data (like an xml dump), so we need a way to tell apart a string that failed os.exists from an xml dump.

**Comment by MarkGotham** [comment]
Ah, yes. True. Thanks.
