### ISSUE TITLE
No information how to run the tests

### ISSUE THREAD

**Issue by maxalbert** [cuthbertLab/music21#85]
I couldn't find any info on how to run the tests in the repository. It would be helpful to mention this in the toplevel README file. Alternatively (or even better in addition) this could be mentioned in the [Developer Reference section](http://web.mit.edu/music21/doc/index.html) of the documentation. It may also be useful to have some quick guidelines in that section on how to write new tests and where they should be added.

**Comment by mscuthbert** [comment]
It's at http://web.mit.edu/music21/doc/developerReference/usingGit.html?highlight=multiprocesstest at the bottom.  I will separate this out to another document since people not using Eclipse will miss it.  It doesn't belong in the top level README file since we have about 50 people using the system for everyone developing it. (regrettably).

**Comment by maxalbert** [comment]
Ah thanks, I missed that. Yes, I agree it would be good to separate it out and place it somewhere more prominent (when I searched for "test" in the Developer Reference section there was no match). I can see that the toplevel README file is not the right place for this kind of information, but it could be a good idea to add another README file in `music21/test` because just from looking in that directory it's not obvious which file is the main test file to run (for example, I personally would never have thought of running `multiprocessTest.py`). I wasn't even sure whether it's the correct directory to look at because when I grepped for "test" in the code base it also returned a lot of matches in the regular code files, so I thought that perhaps running "py.test" from the toplevel directory would be enough (and indeed it returns 172 passed tests, but `multiprocessTest.py` appears to run some additional ones).

**Comment by mscuthbert** [comment]
Max -- it's probably not so high priority any more now that TravisCI will flag any pull requests with problems and point to the test program.

**Comment by maxalbert** [comment]
Fair enough. It's still nice to be able to run the tests locally, though, and I guess a brief entry in a README file would be sufficient so that someone looking for this information can discover it. It's just that there is a variety of testing frameworks out there, and almost every open source project seems to apply its own little twist to them so it's helpful to know what the correct incantation is to run the tests without having to guess.

**Comment by mscuthbert** [comment]
Okay, I'll keep it as a to-do to improve the developer docs for that or happy to take a pull request.

**Comment by shimpe** [comment]
does running a test locally always imply one needs to install first? or is there some clever PYTHONPATH manipulation or other trick that will allow testing the local changes without installing?

**Comment by mscuthbert** [comment]
No you definitely can't run tests without an installation.  But making local changes to an installed version will definitely be reflected in the tests -- a new commit and installation is not required.  Run test/multiprocessTest.py to check first (and if you're used to Py2 only, run it on Py3 and vice-versa) then if that looks good you can run test/singleCoreAll.py (5x slower) or by that point go ahead and make a pull request.

**Comment by mscuthbert** [comment]
Thanks to this thread, at least there's some info on test running.  :-)

**Comment by japrogramer** [comment]
This two commands work for me
```
python -c 'from music21.test.testSingleCoreAll import travisMain as tm; tm()'
python -m unittest -vvv music21.converter.subConverters.Test.testXMLtoPNGtooLong
```

**Comment by mscuthbert** [comment]
http://web.mit.edu/music21/doc/developerReference/testing.html

**Comment by pconerly** [comment]
@mscuthbert Maybe using a `Makefile` would be a good way to explicitly reference the test command?  One of the first things I and many developers do in a repo is look for a Makefile for run/build/test commands.
