### ISSUE TITLE
Durationless element can get inserted twice; missing safeguard in coreGuardBeforeAddElement

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#854]
**music21 version**

7

**Problem summary**
`makeMeasures` can insert the same element in a stream twice when the element coincides with the end of the stream. We made this change in #592 but didn't notice that it was inserting the identical element from the flat source into the newly created measure.

**Steps to reproduce**

```
>>> p = stream.Part()
>>> p.insert(4, meter.TimeSignature())
>>> p.makeMeasures(inPlace=True)
>>> for el in p.recurse():
...   print(el, id(el))
```

**Expected vs. actual behavior**
<music21.stream.Measure 1 offset=0.0> 4465547536
<music21.clef.TrebleClef> 4465548496
<music21.meter.TimeSignature 4/4> 4465547392
<music21.meter.TimeSignature 4/4> **4465410544**
<music21.bar.Barline type=final> 4465692736
<music21.meter.TimeSignature 4/4> **4465410544**

**More information**
This came up putting together the make measures patch for MIDI import, since the conductor track will only extend as far as the last element (which will be durationless time signature or key signature), and if we make measures, we choke here.

Making a deep copy before inserting might work, but in addition, I would think a safeguard is missing here? It wasn't obvious to me since `storeAtEnd` runs `coreGuardBeforeAddElement`.

**Comment by jacobtylerwalls** [comment]
Fixed the issue in makeMeasures with a `continue`, but here is the issue with `insert` missing a guardrail:
```
>>> p = stream.Part()
>>> m = stream.Measure()
>>> p.append(m)
>>> obj
<music21.base.Music21Object object at 0x10b217c10>
>>> p.storeAtEnd(obj)
>>> m.insert(4, obj)
>>> p.show('t')
{0.0} <music21.stream.Measure 0 offset=0.0>
    {4.0} <music21.base.Music21Object object at 0x10b217c10>
{4.0} <music21.base.Music21Object object at 0x10b217c10>
```

**Comment by jacobtylerwalls** [comment]
I guess maybe this has never worked this way -- `m` could be in 100 streams, and I suppose `coreGuardBeforeAddElement` isn't responsible for checking all of them?

**Comment by mscuthbert** [comment]
yeah, we don't guard against adding the same element into more than one stream and then putting those two streams into one hierarchy.  When it happens, the error message could be better, but there's no good way to do it.

The ultimate goal was always to allow it to happen, but never figured out a way to make it work -- it'd be a HUGE refactor.
