### ISSUE TITLE
Repeats in Roman text

### ISSUE THREAD

**Issue by MarkGotham** [cuthbertLab/music21#858]
`romanText.rtObjects` includes a provision for start/end repeat tokens in Roman text (e.g. `:||`) but `romanText.translate` leaves those tokens unprocessed.

**Minimal Proposal:**
Process the token to create a `bar.Repeat` object for these tokens (with correct direction for start versus end repeats).

**Additional Proposal:**
As this is an in-line token, could we accept beat definitions like `m4 V :|| b3 vi` (i.e. mid-measure repeats) and split the measure into two partial measures at that point, adding the repeat marks at the start/end of those partial measures?

(That's assuming I haven't missed a smarter way of doing mid-measure repeats that's consistent with musicxml etc.)

**Comment by MarkGotham** [comment]
p.s.
You can get these repeat markings into a rntxt-generated score by using first/second time bars (`mXa` / `mXb`) but apparently not by typing them in directly (i.e. for cases without first/second time).

**Comment by mscuthbert** [comment]
Repeat signs can go anywhere in music21, but they gain much more functionality if they're put into two separate measures -- including export to systems that can only handle repeats at ends/beginnings of measures (I believe that MusicXML supports them mid-measure also, but no software will respect them.)

My sense for direction to go.  First to parse end of bar repeats / beginning of bar repeats.  make sure they work.  Then make a second PR for mid-bar repeats/etc.  -- ensure that they appear where they should in the bar.  Then create a generalized "splitOnMidMeasureBarlines" function (not in Stream.base.py, but maybe in stream.makeNotation?) that given a measure either returns itself intact or two new measures with the elements put into the proper sub-measure.  Then another function called "splitMeasuresOnMidMeasureBarlines" that works on a Part and returns a new Part with the measures split up. (or, optionally, the same Part if nothing needs to be done).  Then have that function run as part of the RNText process.  If well-tested enough, it's something that we can consider doing in makeNotation on musicxml output.

**Comment by napulen** [comment]
One comment on this: the notation `||` in RomanText means *phrase boundary*, which might be confusing if at some point `:||` means *repeat barline*. In that case, `||` would make more sense as a *double barline* or maybe *end barline*. In fact, I originally interpreted `||` as a double barline, and then I had to look into the documentation to see what it really meant.

**Comment by MarkGotham** [comment]
Thanks @mscuthbert and @napulen! 

Responding to @napulen's comment re: `||`, you're completely right, though:
- there's a clear benefit to having repeat marks in rntxt (e.g. for expanding repeats) but less of a _need_ for double barlines;
- I suspect that Myke will (understandably) consider the meaning of these symbols fixed now and not open to debate.

I'm sure you appreciate all that; I raise it here for reference in case anyone else wants to weigh in and to suggest that if there's a job to be done on this specific issue, it's probably in the documentation rather than elsewhere.

In any case, it would definitely make sense to think through (and perhaps implement) the `||` alongside the `||:` and `:||` when sorting this out.

Thanks again

**Comment by malcolmsailor** [comment]
Hello all, has anyone worked on this at all? If not, I will implement at least the first part of @mscuthbert's proposal above (repeats at barlines) shortly.

**Comment by malcolmsailor** [comment]
> they gain much more functionality if they're put into two separate measures

@mscuthbert, can you clarify what you mean by this? As opposed to having both repeat signs in a single measure? Thanks.

**Comment by mscuthbert** [comment]
> > they gain much more functionality if they're put into two separate measures
> 
> @mscuthbert, can you clarify what you mean by this? As opposed to having both repeat signs in a single measure? Thanks.

Most music representation isn't prepared to have repeat signs inside a Measure -- as represented even if not as conceived, so something like:

4/4  Q | Q Q Q Q | Q Q Q :|| Q | Q Q Q Q | etc.

is generally represented as:

4/4 m0 | m1 | m2a :|| m2b | m3 | etc.

where there is NO mid-measure repeat, but instead two measures both called "measure 2", probably (in m21) with m2a's .paddingRight = 1.0 and m2b's .paddingLeft = 3.0 (same as m0) to set the beat counts properly in the two.

I think that given the problems with mid-measure repeats in all formats, I'm going to close this issue, given #1378's closure (an important issue number for me: the year of the great papal schism) and a new issue about mid-measure repeats/barlines in general can be opened AND/OR just an issue about parsing/outputting mid-measure repeats in romantext (we'll probably need both: the RN text PR to get them into and out from m21, and a separate one for doing something smart with them in RepeatExpander, etc.).
