### ISSUE TITLE
Accidental reiterated on tied chromatic pitch if key signature present

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#865]
**music21 version**

7

**Problem summary**
A tied pitch has its accidental unnecessarily reiterated when running `makeNotation` if <s>the key is no sharps or flats</s> there is a key object somewhere.

**Steps to reproduce**

```
from music21 import converter
p = converter.parse('tinynotation: 4/4 f#1~ f#1')
p.measure(1).insert(0, key.KeySignature(sharps=0))
# makeNotation performs some checks before calling makeAccidentals
p.makeNotation(inPlace=True)
p.show()
```

![image](https://user-images.githubusercontent.com/38668450/108523871-6af77900-729c-11eb-9f63-103899ab3b1e.png)

**More information**

Noticed this in the User's Guide, the last example in Ch. 9 shows an image of this working correctly (based on the series of calls to chordify, etc.), but it no longer works.

**Comment by jacobtylerwalls** [comment]
Ah, I need to generalize this a bit because it doesn't just affect keyless (0 sharps/flats) scenarios, it affects key changes also:

```
>>> bm = converter.parse('tinynotation: 4/4 f#1~ f#1')
>>> bm.measure(2).insert(0, key.KeySignature(-1))
>>> made = bm.makeNotation()
>>> made.measure(2).notes[0].pitches[0].accidental.displayStatus
True
```

![key-of-f](https://user-images.githubusercontent.com/38668450/108577448-1fba8600-72ef-11eb-99ab-f30a1f010910.png)

**Comment by jacobtylerwalls** [comment]
Aaaaand--any pitch not in the key sig.

```
p = converter.parse('tinynotation: 4/4 d#1~ d#1')
p.measure(1).insert(0, key.KeySignature(-7))
made = p.makeNotation()
made.show()
```
![made](https://user-images.githubusercontent.com/38668450/108579592-b0946000-72f5-11eb-80d3-710605be4bf8.png)

**Comment by mscuthbert** [comment]
If they keySignature changes, I think that accidentals that aren't in the new key signature are nice to display again.  (That F# when the key changes).  If it doesn't change then they shouldn't be shown.  If it changes but the tied pitch is in the new key signature, then better not to show (but not a big deal if it does).

The reason for showing after a key signature is that key signature changes often coincide with rehearsal marks (or are used as rehearsal marks), and the last thing you want is someone starting there with the wrong note.  If there's no key signature there, then people are used to looking back to the beginning of the tie to get their notes.

**Comment by jacobtylerwalls** [comment]
Agreed. I think we got as far as that on the PR and then I just didn't update this issue ticket. See the comments on the tests in `testMakeNotationTiesKeyChange()`, I think they address your three cases.
