### ISSUE TITLE
Enharmonic simplifications for romanNumeralFromChord

### ISSUE THREAD

**Issue by gulnazaki** [cuthbertLab/music21#869]
**music21 version**

`6.7.0`   

**Currently there is no way to do enharmonic simplifications for roman numeral analysis**

**Steps to reproduce**

```
>>> from music21 import *
>>> k = key.Key('C#')

>>> ch = chord.Chord('E-4 G-4 B-4')
>>> roman.romanNumeralFromChord(ch, k)
<music21.roman.RomanNumeral bbiii in C# major>

>>> ch = chord.Chord('F4 A-4 C-5')
>>> roman.romanNumeralFromChord(ch, k)
<music21.roman.RomanNumeral bivo5b3 in C# major>
```

**Expected vs. actual behavior**
It can be argued that the above are `ii`  and `iii` chords respectively if the enharmonics of the pitches above (`D#4 F#4 A#4`) and (`E#4 G#4 B#4`) where chosen instead.

I am not able to find any way to simplify enharmonics in order to avoid this and get simpler roman numerals, since the `simplifyEnharmonics` chord method is key independent. I can go forward with a PR adding a `simplifyEnharmonics` option to the `romanNumeralFromChord` if you find this feature useful.

**Comment by jacobtylerwalls** [comment]
Would `simplifyMultipleEnharmonics` help your use case?

```
>>> ch
<music21.chord.Chord E-4 G-4 B-4>
>>> pitch.simplifyMultipleEnharmonics([n.pitch for n in ch], keyContext=key.Key('C#'))
[<music21.pitch.Pitch D#4>, <music21.pitch.Pitch F#4>, <music21.pitch.Pitch A#4>]
```

**Comment by gulnazaki** [comment]
Thanks a lot! 

I wasn't aware of this method, it definitely does the trick.

**Comment by jacobtylerwalls** [comment]
Maybe there's an opportunity for syntactic sugar here so that the user doesn't have to collect the pitch objects from the chord and call a method on the pitch module; maybe there could be a `chord.respell(key, inPlace=False)` method taking a key or key sig object.

**Comment by gulnazaki** [comment]
Actually, there could be an optional `keyContext` argument to the `chord.simplifyEnharmonics` defaulting to `None`, that would change the simplification goal if provided. 
It would be more intuitive and there is no need to add another method I believe.

I could do a PR about it, if you prefer.

**Comment by jacobtylerwalls** [comment]
Look at that -- chord.simplifyEnharmonics just runs pitch.simplifyMultipleEnharmonics anyway, so you're quite right. Myke hasn't weighed in yet, but in my view that would be a great usability improvement to have a PR for that keyword. Thanks!

**Comment by gulnazaki** [comment]
@jacobtylerwalls I believe there could be something wrong with pylint as I see from other PRs

**Comment by jacobtylerwalls** [comment]
I think a new check went into effect yesterday and old music21 code is failing on it. At the risk of drowning @mscuthbert in PRs I'll open one he can merge first to fix it.

**Comment by mscuthbert** [comment]
Thanks @gulnazaki and @jacobtylerwalls for the PR and comments.  The failing tests are no problem.
