### ISSUE TITLE
mscore3 executable is expected by music21 but isn't installed by musescore

### ISSUE THREAD

**Issue by yurivict** [cuthbertLab/music21#879]
Version: ```6.7.1```

**Problem summary**
Here https://github.com/cuthbertLab/music21/blob/master/music21/environment.py#L409 ```mscore3``` is expected but musescore-3.6.1 doesn't install an executable with this name.

**Steps to reproduce**

```
from music21 import *
converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#").show()
```

Replacing ```mscore3``` with ```mscore``` that ```musescore``` causes GUI window to show up, which probably isn't what is expected from a python script.

OS: FreeBSD 12.2

**Comment by jacobtylerwalls** [comment]
Thanks for the report. `show()` indeed opens an application, if that's what you're asking.

Hiya @wilsonify -- your input here would be welcome.

**Comment by yurivict** [comment]
Then there are 2 things that are wrong.

1. The ```MusicScore``` executable name is ```mscore```, not ```mscore3```.
2. Hardcoding paths (```/usr/bin```) is wrong - you should resolve them through ```PATH```. On BSDs, for example, packages are installed into ```/usr/local/bin```, which can also be a different path on some other installations. So the only correct way to find them is resolve it through ```PATH```.

**Comment by jacobtylerwalls** [comment]
Have you tried running `configure.run()` to let the Configuration Assistant search your system for MusicXML readers? Michael proposed an approach where configure.run() is called the first time a user attempts to `.show()` in https://github.com/cuthbertLab/music21/pull/721#issuecomment-747880023.

**Comment by jacobtylerwalls** [comment]
I'm asking very honestly -- we lack maintainers who develop and test on Linux, FreeBSD, etc., so I'm honestly wondering if `configure.run()` will do anything. Our CI at GitHub doesn't open GUIs, of course.

**Comment by mscuthbert** [comment]
What is the OS we're discussing?  Linux and other Unix systems are not officially supported by music21 -- users on those systems are expected to be able to edit a config file themselves.

**Comment by mscuthbert** [comment]
See https://web.mit.edu/music21/doc/about/faq.html#consulting  for further options.

**Comment by wilsonify** [comment]
These are just defaults.
environment should respect ~/music21-settings.xml

**Comment by prodgers13** [comment]
On fedora I was able to edit ~/music21rc to point to /usr/bin/musescore and it worked on Linux. FYI.

**Comment by mscuthbert** [comment]
The issue is closed unless someone puts in a PR or hires consulting.  I need to set support boundaries.
