### ISSUE TITLE
A comment in search/segment.py points users to an outdated distribution of python-Levenshtein

### ISSUE THREAD

**Issue by dhgutteridge** [cuthbertLab/music21#883]
In search/segment.py (lines 20-25 presently on git master), there's a comment that references a rather dated version of python-Levenshtein, usable as an option to increase performance. (You also rely on it unconditionally for testing purposes in test/commonTest.py.) In fact, it is now available on pypi.org ([https://pypi.org/project/python-Levenshtein/](https://pypi.org/project/python-Levenshtein/)) and can be installed via pip. I'd suggest updating the comment to point to this newer version that's actually maintained. Version 0.12.1 fixed bugs with potential security issues that were present in the older version your comment points to. (I could submit a pull request to adjust this, but I'm not sure the exact phrasing you'd want to change it to.)

**Comment by jacobtylerwalls** [comment]
Thanks for noticing. Please do submit a PR!

**Comment by dhgutteridge** [comment]
I've submitted this as #917, thanks!
