### ISSUE TITLE
The hash of the music21 2.0.0 package seems to be incorrect.

### ISSUE THREAD

**Issue by jakob-zwiener** [cuthbertLab/music21#89]
When trying to install the package using pip the following error will be encountered:

Collecting music21==2.0.0
  Downloading https://github.com/cuthbertLab/music21/releases/download/v2.0.0/music21-2.0.0.tar.gz (47.2MB)
    100% |################################| 47.2MB 12kB/s 
  Hash of the package https://github.com/cuthbertLab/music21/releases/download/v2.0.0/music21-2.0.0.tar.gz#md5=60183b92885d7ed4176f712e4c8f75b3 (from https://pypi.python.org/simple/music21/) (edde023c5be495bdefc3a3ac13e0dfb7) doesn't match the expected hash 60183b92885d7ed4176f712e4c8f75b3!
  Bad md5 hash for package https://github.com/cuthbertLab/music21/releases/download/v2.0.0/music21-2.0.0.tar.gz#md5=60183b92885d7ed4176f712e4c8f75b3 (from https://pypi.python.org/simple/music21/)

**Comment by mscuthbert** [comment]
Is this fixed for more recent versions?

**Comment by jakob-zwiener** [comment]
I have tried installing version 2.1.2 and 2.0.0 using pip and it worked without any trouble. So I guess this has been fixed, thanks very much!
