### ISSUE TITLE
Suggest using math.isclose

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#894]
Hope you don't mind my poking around with the profiler. 
Any interest in using `math.isclose` instead of `common.almostEquals`? Improvement in each case except exact equality of Fractions.

```
>>> timeit('common.almostEquals(1, 1.0001, grain=1e-7)', setup='from music21 import common')
0.7664678169999206
>>> timeit('isclose(1, 1.0001, abs_tol=1e-7)', setup='from math import isclose')
0.12834536200000457

>>> timeit('common.almostEquals(Fraction(1e-9), Fraction(1e-10), grain=1e-7)',
setup='from music21 import common;from fractions import Fraction')
21.67478096700006
>>> timeit('isclose(Fraction(1e-9), Fraction(1e-10), abs_tol=1e-7)',
setup='from math import isclose;from fractions import Fraction')
7.039263527000003

>>> timeit('common.almostEquals(Fraction(1e-10), Fraction(1e-10), grain=1e-7)',
setup='from music21 import common;from fractions import Fraction')
6.708897176999926
>>> timeit('isclose(Fraction(1e-10), Fraction(1e-10), abs_tol=1e-7)',
setup='from math import isclose;from fractions import Fraction')
6.948409474000073
```

`almostEquals` could just be a shim in v7 for `isclose` with a deprecation warning?

**Comment by mscuthbert** [comment]
That's great!  It was added in 3.5 so it's only been recently that we had it here.  Agree that we should leave it in as a shim in v7 with deprecation warning.

**Comment by mscuthbert** [comment]
Is the default grain the same?

**Comment by jacobtylerwalls** [comment]
Cool. No, the default is different -- only a relative tolerance is defaulted:

`math.isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)`

But I think we have enough near 0 comparisons and very few orders of magnitudes that we need the abs_tol.

I can just pass the existing grain for the abs_tol.
