### ISSUE TITLE
Attribute 'Instrument' of a two-voices part is lost when applying Stream.voicesToParts() method

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#902]
Version of music21:  6.5.0
Good morning! Here martín from DIDONE project. First of all, thanks a lot for creating this library and keeping the support and improvements. I just installed the new 6.7 version but i doesn't seem to have solved my problem, so here I open an issue in case is useful for anyone:

**Problem summary**
Attribute 'Instrument' of a two-voices part is lost when applying Stream.voicesToParts() method. When having a Stream that defines two voices (in this case two wind insturments), I wanna use this method to split them in two andoperate with them separatedly. 
The point is that BEFORE the method I can run part.getInstrument() and get something like '<music21.instrument.Instrument 'P1: Oboi: SmartMusic SoftSynth 1'>' . But, after the method is called, this information is lost and the new parts that correspond to the previous don't have this attrubute, so if you call part.getInstrument() you just get an empty string. Therefore, afterwards I have no way to identify the type of the instrument.

**Steps to reproduce**

My code to separate the voices goes like follows:

            if has_voices:
                parts_splited = part.voicesToParts().elements
                num_measure = 0
                for measure in part.elements: #add missing information to both parts (dynamics, text annotations, etc are missing)
                    if isinstance(measure, stream.Measure) and any(not isinstance(e, stream.Voice) for e in measure.elements):
                        not_voices_elements = [e for e in measure.elements if not isinstance(e, stream.Voice)] #elements such as clefs, dynamics, text annotations...
                        for p in parts_splited:
                            p.elements[num_measure].elements += tuple(e for e in not_voices_elements if e not in p.elements[num_measure].elements)
              

And it works just fine. I just would like to call later parts_splited[0].getInstrument() to identify it.
I have come with 'kind of a ' workaround in the source code, but I think I needs expert hands on it. In the definition of the method (file __init__.py of stream class), I just added this line to get all the information of the original part to the subparts:

        for i in range(partCount):
            p = Part()
            # p.elements = self.elements #
            s.insert(0, p)

in lines 10402-10404. It does preserve the info, however some aspects of the object now chenged (looking at my code, the first elements of p.elements is not longer a measure but a instrument, so the iteration just doesen't work) and therefore I didnt wanted to go on with it yet not to rewriter all the code without knowing if its agood idea to make this change in the source code or not.

In any case, I just wanted to let you know about this issue in the method and hope it works to help to improve the library.

Hope to hear from you soon. 

Kind regards.

**Comment by jacobtylerwalls** [comment]
Hi, and thanks for the report. Yes, `voicesToParts()` will discard the Instrument object found in the original part. We can patch that. I added key, meter, and barline objects to this routine in #576 last summer but didn't handle Instrument.

Regarding unexpected things with iteration -- you'll probably have a better experience never touching `.elements`. Streams are designed like lists--but with cool filters. So you can insert or append instead of manipulating `.elements`, and you can filter by doing `for m in part.getElementsByClass('Measure'):`

So when we do patch this to include Instrument objects, yes, they will probably appear in the resulting parts before the first measure. That's fine, because if you need to depend on the first encountered object being a Measure, you need a filter!

**Comment by DIDONEproject** [comment]
Okay! Thanks for replying so fast :) And also for the advice on the elements list. I will wait for the patch then to modify my code :)
