### ISSUE TITLE
text.assembleLyrics(part) failos on parsing lyrics of a voice in new update 

### ISSUE THREAD

**Issue by DIDONEproject** [cuthbertLab/music21#906]
**music21 version**

'6.7.0'

**Problem summary**
When parsing a score by doing converter.parse(score), in version I was able to run 
for p in score.parts:
    if not text.assembleLyrics(p): 

and get the lyrics of a voice part. However, in latest update 6.7.0 this function fails wen running into certaing syllabes.
I have been loking into the assembleLyrics function into text.py. It parses every word well, like this
words =['Fra', 'tutte', '', 'le', '', 'pene', '', 'v’è', '', 'pena', '', 'maggiore?', 'Son', 'pres'] 
until it encounters 'so al', which are two subsequent syllabes separated by a space, and when extracting the text in lyricObj.text the output is 'so\xa0al'. This corresponds to a lyricObj.syllabic= 'composite', which throws an error 'no known Text syllabic setting: composite'

It clearly seems like an encoding problem, I have tried parsing the score by doing converter.parse(xml_file, encoding='utf-8') but gives similar results, and I hacen't been able to find any parameter to be set in order to change the encoding in which the lyrics are parsed. Also, I don't know if any setting regarding 'composite' in the type of syllabe can be set.

**Expected vs. actual behavior**
In versions up to 6.5 this wasn't a problem and I was able to load the score and lyrics without any problem of this kind.

Thank you in advance for looking at this issue.

Regards!

**Comment by jacobtylerwalls** [comment]
Hello! I believe Michael fixed this in v6.7.1, which went out about a week ago. Would you be willing to upgrade and let us know if still a problem?

**Comment by DIDONEproject** [comment]
Hi! Yes, I just tried and it works just fine. Didn't know v6.7.1 was out already. Thanks!

**Comment by mscuthbert** [comment]
I changed some handling of multiple syllabics in one lyric recently so there might be bugs in code that assumes the 6.7.0 method.  Feel free to reopen if they come up in 6.7.1
