### ISSUE TITLE
Composer popularity feature always returns 0

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#907]
**music21 version**

`7.0.1`

**Problem summary**
Composer popularity feature always returns 0.

**Steps to reproduce**
Can also reproduce using the doctest example with Mozart.
```
>>> x = converter.parse('tinynotation: d1')
>>> y = stream.Score([metadata.Metadata(), x])
>>> y.metadata.composer = 'Stevie Wonder'
>>> fe = features.native.ComposerPopularity(y)
>>> fe.extract().vector
[0]
```

Should probably fail more loudly if it's not working.

**Comment by jacobtylerwalls** [comment]
oh, do I need to set something in my environment?

**Comment by mscuthbert** [comment]
yeah, it was a demonstration of how an internet-savvy application could take advantage of features not available before.  I've never actually used it.  If there were an easy way of getting the data from IMSLP I'd consider switching to that, BUT I suspect time has come to deprecate it in v.7 and then remove.  But I thought we had a test of it that should have noticed that it wasn't working?  Something about Mozart > Handel or something.

**Comment by jacobtylerwalls** [comment]
Somewhere in Italy the Handel scholar I know is weeping. Yes, there's a doctest, but it's cheating:

https://github.com/cuthbertLab/music21/blob/747316f350319f0832d704c5d06a0c0bc2f07cbe/music21/features/native.py#L851-L858
