### ISSUE TITLE
'show' not working

### ISSUE THREAD

**Issue by tsmithe** [cuthbertLab/music21#91]
This seems to be a Python 3 incompatibility. I'd much, much rather not be forced to use Python 2.7 any more.

```
In [18]: music21.environment.set('musicxmlPath', '/usr/bin/musescore')

In [19]: f.show()
sh: 1: b/usr/bin/musescore: not found
```

Also: can't there be sensible defaults? The users' guide says that ``f.show('midi')`` will play the note, but I just get environment errors. I don't know what I'm supposed to set the relevant settings to! It seems somewhat disingenuous that this doesn't seem to be covered in the guide.

**Comment by mscuthbert** [comment]
I'm sorry to be disingenuous. Please contact customer service for a refund.

**Comment by tsmithe** [comment]
Thanks.

**Comment by tsmithe** [comment]
Hi, again. I don't think you realised that my request / report was sincere, and so I'm not sure that your facetious response was warranted. Clearly, if someone is asking for help (which at the same time as reporting a bug, I plainly was), then they are probably not in a position to contribute a bugfix. Moreover, since this is a free product, I don't expect any help -- but since you advertise this issue tracker, and don't say clearly anywhere, "don't ask for help, contribute instead", one might expect to receive some voluntary support. At the very least, one should expect some courtesy between strangers.

I stand by my comment that presenting the software in your users' guide as more easy to use than it turns out to be, whilst at the same time providing no clear instructions on how to set the software up so that the advertised features are available, is disingenuous.

If you're actually sorry to be disingenuous, then perhaps you could be more helpful? Otherwise, you might disagree with my assessment, but then to say that you are sorry is just lying, and that's simply unwarranted. I was tempted to respond in a similar manner to yours, but I thought better of it.

**Comment by ahankinson** [comment]
- Can you confirm that '/usr/bin/musescore' exists and your path is correct? I think that's the most likely explanation of your problem, given the limited error message and description you posted.
 - What environment errors are you getting? Posting the exact error message goes a long way towards getting someone to help you.

**Comment by tsmithe** [comment]
Yes, /usr/bin/musescore exists, and music21 complains if I set a path that does not exist, with a UserSettingsException. The reason I think this is a Python3 incompatibility is because ``sh`` complains about ``b/usr/bin/musescore``, which is what one would get if passing directly a ``bytes`` object to the shell. Instead, it needs a string. I don't know where to look in the code to fix this, and whilst I did spend some time looking, the inheritance hierarchy meant it was not obvious.

Moreover, if I restart the interpreter and re-import music21, then clearly it has saved a settings file somewhere, and correctly interprets the path as a string, so that the program starts correctly.

The environment errors look like:

```
In [7]: f.show('midi')
---------------------------------------------------------------------------
SubConverterException                     Traceback (most recent call last)
<ipython-input-7-7e769aaed1a9> in <module>()
----> 1 f.show('midi')

/home/toby/.local/lib/python3.4/site-packages/music21/base.py in show(self, fmt, app, **keywords)
   2283         scClass = common.findSubConverterForFormat(regularizedConverterFormat)
   2284         formatWriter = scClass()
-> 2285         return formatWriter.show(self, regularizedConverterFormat, app=app, subformats=subformats, **keywords)
   2286 
   2287     #--------------------------------------------------------------------------

/home/toby/.local/lib/python3.4/site-packages/music21/converter/subConverters.py in show(self, obj, fmt, app, subformats, **keywords)
    150     def show(self, obj, fmt, app=None, subformats=None, **keywords):
    151         returnedFilePath = self.write(obj, fmt, subformats=subformats, **keywords)
--> 152         self.launch(returnedFilePath, fmt=fmt, app=app)
    153 
    154     def getExtensionForFormatOrSubformats(self, fmt=None, subformats=None):

/home/toby/.local/lib/python3.4/site-packages/music21/converter/subConverters.py in launch(self, filePath, fmt, options, app, key)
    139                     "Specify this in your Environment by calling "
    140                     "environment.set({!r}, 'pathToApplication')".format(
--> 141                         self.registerFormats[0], self.launchKey))
    142         elif platform == 'win':  # note extra set of quotes!
    143             cmd = '""%s" %s "%s""' % (app, options, filePath)

SubConverterException: Cannot find a valid application path for format midi. Specify this in your Environment by calling environment.set(None, 'pathToApplication')
```

The reason I find this opaque is because ``None`` is not a valid key here: ``EnvironmentException: no preference: None``.

The reason I report this as a bug is because the recent release notes claim Python 3 compatibility. This bug suggests that the release was not tested on a fresh Python 3 installation, as does the fact that the environment errors are unknown! I'm surprised at this: I thought the environment errors were my fault! If the release had been so tested, then it seems that these bugs would have been obvious immediately -- unless of course they really are my fault, which is why I was open-ended in my original request.

I still think that @mscuthbert was frightfully rude, and that nothing I said deserved the response I got. I was quite excited to use this software until then.

**Comment by ahankinson** [comment]
What's the contents of `~/.music21rc`?

**Comment by tsmithe** [comment]
```
<?xml version="1.0" ?>
<settings>
  <preference name="autoDownload" value="ask"/>
  <preference name="braillePath"/>
  <preference name="debug" value="0"/>
  <preference name="directoryScratch"/>
  <preference name="graphicsPath"/>
  <preference name="ipythonShowFormat" value="ipython.lilypond.png"/>
  <preference name="lilypondBackend" value="ps"/>
  <preference name="lilypondFormat" value="pdf"/>
  <preference name="lilypondPath" value="lilypond"/>
  <preference name="lilypondVersion"/>
  <localCorporaSettings/>
  <localCorpusSettings/>
  <preference name="manualCoreCorpusPath"/>
  <preference name="midiPath"/>
  <preference name="musescoreDirectPNGPath"/>
  <preference name="musicxmlPath" value="/usr/bin/musescore"/>
  <preference name="pdfPath"/>
  <preference name="showFormat" value="musicxml"/>
  <preference name="vectorPath"/>
  <preference name="warnings" value="1"/>
  <preference name="writeFormat" value="musicxml"/>
</settings>
```

**Comment by ahankinson** [comment]
Also: I don't know if you're a native English speaker, but the word "disingenuous" has a decidedly negative connotation:

"not candid or sincere, typically by pretending that one knows less about something than one really does."

It may have been an innocent mistake, but your choice of words at the outset may not have been the best way to ask for help.

**Comment by ahankinson** [comment]
You can try setting `midiPath` to a valid MIDI player on your platform. Mine (OS X) looks like:

`<preference name="midiPath" value="/Applications/QuickTime Player.app"/>`

**Comment by tsmithe** [comment]
OK, I'll try that. But whilst that might work for me, I suspect the encoding bug will remain! One more thing: is the SubConverterException supposed to look like it does above? I found it strange that I was told to set a ``None`` key, which clearly doesn't work.

And, yes, I'm a native English speaker, but perhaps it's a British/American difference. I still think that the definition applies, because the user guide gave the impression that after installing music21 and MuseScore, ``f.show()`` and ``f.show('midi')`` would just work, and there was no indication that anything extra would need to be set up. If it was known that more set-up would be needed, then indeed it would be disingenuous to give the impression otherwise!

In any case, for @mscuthbert to get so het up about one word is remarkable. It would have been easier all round if, instead of being facetious, he had been straightforward,

I won't say any more about these non-technical points.

**Comment by mscuthbert** [comment]
Please do not continue to use the software. I'm done with your accusations of rudeness. Thank you.
