### ISSUE TITLE
Stem problem when exporting a tab stream in MusicXML

### ISSUE THREAD

**Issue by louisbigo** [cuthbertLab/music21#912]
**music21 version**

`7.0.1`

**Problem summary**
When writing a tab stream in MusicXML, it looks like m21 tries to make stems and that makes an error as a TabClef can't return an appropriate direction for stems (function `getStemDirectionForPitches` in `clef.py`) :

```
music21/music21/clef.py", line 262, in getStemDirectionForPitches
    midLine = self.lowestLine + 4
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

Apparently, stems are rather rare in tablatures, but when they appear, they are all in the same direction, generally downwards (see [this link](http://www.xx-europe.de/tablature-breizh-guitare-mandocello-bouzouki-cistre.html) for example).

Would it be appropriate when the clef is TabClef to either disable stems either force them to be downwards ?

PS : curiously the error does not appear when omitting the time signature, but I was not able to see the relation here.

**Steps to reproduce**

```
from music21 import *

test_tab = stream.Stream()
p = stream.Part()
m = stream.Measure()
c = clef.TabClef()

n1 = note.Note(64,quarterLength=0.25)
s1 = articulations.StringIndication()
s1.number = 2
f1 = articulations.FretIndication()
f1.number = 5
n1.articulations = [s1,f1]

n2 = note.Note(67,quarterLength=0.25)
s2 = articulations.StringIndication()
s2.number = 2
f2 = articulations.FretIndication()
f2.number = 8
n2.articulations = [s2,f2]

m.append(clef.TabClef())
m.append(meter.TimeSignature('4/4'))
m.append(n1)
m.append(n2)

p.append(m)

test_tab.append(p)
test_tab.show('text')
test_tab.write('musicxml','output')
```

**Comment by louisbigo** [comment]
That's true, I remember it was working before my last pull. What about forcing stems downards in case of TabClef for the moment ? I'll be happy to help if you think that's the way to go. (By the way I'll need that to be fixed in order to work on #909)

**Comment by jacobtylerwalls** [comment]
Special-casing tab clefs to force stems down sounds good. The other thing I notice is that `TabClef` probably shouldn't subclass `PitchClef`, just `Clef`. That's another way to prevent this crash.

**Comment by jacobtylerwalls** [comment]
On second thought, can't we just return early and leave the stem directions as they are? And on third thought, until we have more tab functionality, it's too early to fiddle with subclasses that are already documented one way.

**Comment by louisbigo** [comment]
I agree, it might be too early to modify inheritance. Would it be ok to simply override `getStemDirectionForPitches` in `TabClef` ? The following seems to work for me (I just copied parameters declaration of `getStemDirectionForPitches` from class `Clef`):

```
class TabClef(PitchClef):
    '''
    represents a Tablature clef.

    >>> a = clef.TabClef()
    >>> a.sign
    'TAB'
    '''

    def __init__(self):
        super().__init__()
        self.sign = 'TAB'
        self.line = 5

    def getStemDirectionForPitches(
        self,
        pitchList: Union[pitch.Pitch, Iterable[pitch.Pitch]],
        *,
        firstLastOnly: bool = True,
        extremePitchOnly: bool = False,
    ) -> str:
        return "down"
```

**Comment by jacobtylerwalls** [comment]
Yes, I suppose that's a good idea. I'm realizing now this is in the `makeBeams` functionality, which won't run if beams are already defined, so it's okay to be "helpful" in this case and just set stems down (rather than leave "unspecified").

**Comment by louisbigo** [comment]
Great, thanks. Should I create a pull request to add these few lines of code ? Do not hesitate to tell me if there's an other way to proceed, it's the first time I have a modification to bring into music21, I'll be informed for the next ones :)

**Comment by jacobtylerwalls** [comment]
I say go for it. Ordinarily you'd include a test. Stick two eighth notes and a time signature and a TabClef in a measure and run `makeBeams()`, then find the beam and assert == "down", something like that.
