### ISSUE TITLE
Installation instructions still mention outdated Google Code URL

### ISSUE THREAD

**Issue by maxalbert** [cuthbertLab/music21#92]
The installation instructions for [Mac](http://web.mit.edu/music21/doc/installing/installMac.html#installmac), [Windows](http://web.mit.edu/music21/doc/installing/installWindows.html#installwindows) and [Linux](http://web.mit.edu/music21/doc/installing/installLinux.html#installlinux) still mention that music21 should be downloaded from the obsolete site http://code.google.com/p/music21/downloads/list. I presume that this should be changed to https://pypi.python.org/pypi/music21.

**Comment by mscuthbert** [comment]
Thanks! Fixed.
