### ISSUE TITLE
Fast 3/8 accent sequence no longer partitioned

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#925]
**music21 version**

`7.0.2`

**Problem summary**
"FAST" 3/8 (new in v7) no longer gets a partitioned accent sequence (new) <s>or beat sequence (status quo for other 1-beat meters like 1/4, but doesn't seem ideal.)</s> Lack of a partitioned accent sequence could be an inconvenience for doing syncopation analysis.

**Steps to reproduce**

```
>>> ts38 = meter.TimeSignature('3/8')
meter: cannot set default accents for: <music21.meter.TimeSignature 3/8>
>>> ts38.accentSequence
<music21.meter.core.MeterSequence {3/8}>
>>> ts38.beatSequence
<music21.meter.core.MeterSequence {3/8}>
>>> ts38.beatDivisionDurations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/meter/base.py", line 988, in beatDivisionDurations
    raise TimeSignatureException(
music21.exceptions21.TimeSignatureException: cannot determine beat division for a non-partitioned beat
>>> ts38.classification
'Other Single'
```

**Expected behavior**

beatSequence:  <music21.meter.core.MeterSequence {3/8}>
accentSequence: <music21.meter.core.MeterSequence {1/16+1/16+1/16+1/16+1/16+1/16}>
classification: 'Compound Single'

Other 1-beat meters <s>don't get beat partitions (which I suggest they could)</s>, but they at least get a partitioned accent sequence:
```
>>> ts14 = meter.TimeSignature('1/4')
>>> ts14.accentSequence
<MeterSequence {1/32+1/32+1/32+1/32+1/32+1/32+1/32+1/32}>
>>> ts14.beatSequence
<MeterSequence {1/4}>
```

**Comment by mscuthbert** [comment]
ack!  That's a bug I should have checked.
