### ISSUE TITLE
spellingIsInferred should remain True when Chord created from MIDI numbers is respelled

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#929]
**music21 version**
reproduced on current and on 5.1.0; expect it goes back to the introduction of the attribute

**Problem summary**
`.spellingIsInferred` should still be True on chord members created from MIDI numbers that happened to have been simplified, as I understand it.

**Steps to reproduce**

```
>>> b_maj = chord.Chord([59, 63, 66])
```

**Expected vs. actual behavior**
```
>>> [p.spellingIsInferred for p in b_maj.pitches]  # expect [True, True, True]
[True, False, True]
```

**More information**
Noticed in discussing #928

**Comment by mscuthbert** [comment]
Ah, yes, this IS a bug.
