### ISSUE TITLE
Pitch.transpose(inPlace=True) doesn't set spellingIsInferred True

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#933]
If I correctly understood this last point, it actually doesn't work:
```
>>> c = chord.Chord('C# E G#')
>>> c.pitches[1].transpose(1, inPlace=True)
>>> print([p.spellingIsInferred for p in c.pitches])
[False, False, False]
```

_Originally posted by @ax-le in https://github.com/cuthbertLab/music21/pull/931#discussion_r601779841_

**Contrast with inPlace=False:**
```
>>> p = pitch.Pitch('C#4')
>>> p.spellingIsInferred
False
>>> p.transpose(1, inPlace=True)
>>> p.spellingIsInferred  # expect True
False
>>> p2 = pitch.Pitch('C#4')
>>> p3 = p.transpose(1, inPlace=False)
>>> p3.spellingIsInferred
True
```

**Comment by jacobtylerwalls** [comment]
This is another good issue for new contributors, since it's evident in the body of `Pitch.transpose()` where this isn't handled. Up for another one, @ax-le?

**Comment by ax-le** [comment]
Thanks @jacobtylerwalls , but I actually have a lot of work to do in the short term so I'd rather let someone else fix this, instead of doing a sloppy fix!
