### ISSUE TITLE
Decide whether to support class strings as keys for `Stream.__getitem__`

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#947]
https://github.com/cuthbertLab/music21/blob/ebc47a1fbc9d65981bc52928593b4b564ae96cd5/music21/stream/base.py#L322-L324

Doesn't work as described; only names work, not strings:

```
>>> h = corpus.parse('handel')
>>> h[stream.Part]
<music21.stream.Score 0x110207ee0>
>>> h['stream.Part']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/stream/base.py", line 451, in __getitem__
    raise KeyError(f'provided key ({k}) does not match any id or group')
KeyError: 'provided key (stream.Part) does not match any id or group'
>>> h['Part']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/stream/base.py", line 451, in __getitem__
    raise KeyError(f'provided key ({k}) does not match any id or group')
KeyError: 'provided key (Part) does not match any id or group'
```

**More information**
Shall we correct the docs or add the feature?

Here's adding the feature:
```diff
diff --git a/music21/stream/base.py b/music21/stream/base.py
index 4d8f92316..3e792a754 100644
--- a/music21/stream/base.py
+++ b/music21/stream/base.py
@@ -398,7 +398,8 @@ class Stream(core.StreamCoreMixin, base.Music21Object):
         KeyError: "provided class (<class 'music21.layout.StaffLayout'>) does
             not match any contained Objects"
 
-        Changed in v7. -- out of range indexes now raise an IndexError, not StreamException
+        Changed in v7. -- out of range indexes now raise an IndexError, not StreamException.
+        Unsupported types now raise TypeError. Strings now supported for class names.
         '''
         # need to sort if not sorted, as this call may rely on index positions
         if not self.isSorted and self.autoSort:
@@ -447,15 +448,20 @@ class Stream(core.StreamCoreMixin, base.Music21Object):
                 groupStream = self.iter.getElementsByGroup(k)
                 if groupStream:
                     return groupStream.stream()
-                else:
-                    raise KeyError(f'provided key ({k}) does not match any id or group')
-        elif isinstance(k, type(type)):
+                # else:
+                    # raise KeyError(f'provided key ({k}) does not match any id or group')
+
+        if isinstance(k, (str, type)):
             # assume it is a class name
             classStream = self.iter.getElementsByClass(k)
             if classStream:
                 return classStream.stream()
-            else:
+            elif isinstance(k, type):
                 raise KeyError(f'provided class ({k}) does not match any contained Objects')
+            else:
+                raise KeyError(f'provided key ({k}) does not match any id, group, or class name')
+
+        raise TypeError(f'Get items by int, slice, id, or class; got {type(k)}')
```

**Comment by jacobtylerwalls** [comment]
We should also decide whether to continue returning a stream from this getElementsByClass synonym.

Honestly, I appreciate being able to save the keystrokes:

```
>>> s.getElementsByClass(stream.Measure)
<music21.stream.iterator.StreamIterator for Score:0x10817ebb0 @:0>
>>> s[stream.Measure]  # would be nice to get a StreamIterator
<music21.stream.Score 0x105dd7970>
```

**Comment by mscuthbert** [comment]
Oh, That should DEFINITELY be changed to return an iterator.  YES!

I think that removing `id` is something to do at this point.  Never been used and probably just creates errors.

The issue is whether this will make more people not realize it is doing a non-nested search.  Is this the time to make: `s[CLASS]` a synonym for `s.recurse().getElementsByClass(CLASS)`?  that's where the real keystroke savings will occur!

my only other hesitation is that because ProxyClasses are still so crappy in Javascript, it's one more thing that ends up being different between music21p and music21j -- though I suppose this could be implemented in `j`'s `.get(X)` method.

**Comment by mscuthbert** [comment]
this has a certain elegance that would make v7 really stand out:

```
jazz = corpus.parse('someLeadSheet')
all_chords = jazz[harmony.ChordSymbol]
return len(all_chords)
```

**Comment by mscuthbert** [comment]
I will DEFINITELY have to release v7 by September 1, 2021 if we do this, because I'll get super used to typing it and then when I teach my seminar, if the students are still using v6 nothing will work for them.

**Comment by jacobtylerwalls** [comment]
Also, the original question about whether to support strings:

```
score['LayoutBase']
```

**Comment by mscuthbert** [comment]
I don't think we can allow it, because strings represent id or group.

**Comment by mscuthbert** [comment]
Ah, we could, but it'd be much slower.

**Comment by mscuthbert** [comment]
yeah, actually, it's okay as it is, but I think we should encourage using classes.  In fact, I'd like to do a PR where we convert every internal use to classes EXCEPT where we cannot import the class directly into that module.

**Comment by jacobtylerwalls** [comment]
My thought is if we start promoting this as a synonym for getElementsByClass, with or without the extra recurse, people will try it with strings if they're used to using gEBC() that way. So rather than raise KeyError, just let them have the synonym for gEBC().

**Comment by mscuthbert** [comment]
Yes, good point.  It'll just be slower so we shouldn't use it in internal code.
