### ISSUE TITLE
stream._cache can disappear at the most inopportune moment

### ISSUE THREAD

**Issue by gregchapman-dev** [cuthbertLab/music21#957]
**music21 version**

`6.3.0`   

**Problem summary**

The cache can get cleared between adding _cache_['Duration'] and setting _cache_['Duration'].quarterLength.

**Steps to reproduce**
I set duration.tuplets on a note that was already in a stream. Some time later, someone called stream.duration, and the following code in stream/__init__.py (_getDuration) crashed:

            # environLocal.printDebug(['creating new duration based on highest time'])
            self._cache['Duration'] = duration.Duration()
            self._cache['Duration'].quarterLength = self.highestTime <--- BOOM, KeyError, which seems impossible, right?
            return self._cache['Duration']

Some investigation showed that self.highestTime cleared the cache in coreElementsChanged().  To be more clear, self.highestTime called _getQuarterLength on my modified duration, so updateQuarterLength gets called, which ultimately calls informClient/informSites/coreElementsChanged, which sets stream._cache_ to {}, making:
            self._cache['Duration'].quarterLength = self.highestTime
raise KeyError while trying to evaluate self._cache['Duration'] on an empty cache.

Proposed fix:
    In place of:
            self._cache['Duration'] = duration.Duration()
            self._cache['Duration'].quarterLength = self.highestTime
    do:
            highestTime = self.highestTime # might clear self._cache!
            self._cache['Duration'] = duration.Duration()
            self._cache['Duration'].quarterLength = highestTime

Workaround:
In my new Humdrum converter's tuplet handling code, when I set duration.tuplets on notes that are already in a stream, I now immediately get the quarterLength, to avoid this situation.

```
Paste minimal code example here. Most issues can be reproduced with just a few elements.
Attach external files only after attempting to reproduce using a simple stream.

I'm afraid I don't have a minimal example.

```

**Expected vs. actual behavior**

**More information**

**Comment by jacobtylerwalls** [comment]
Thanks for the report; I was able to reproduce on current version (at ebc47a1fbc9d65981bc52928593b4b564ae96cd5) like so:

```
>>> n = note.Note()
>>> s = stream.Stream()
>>> s.insert(0, n)
>>> s.duration
<music21.duration.Duration 1.0>
>>> s._cache
{'Duration': <music21.duration.Duration 1.0>, 'HighestTime': 1.0}
>>> tup = duration.Tuplet()
>>> n.duration.tuplets = (tup1,)
>>> s.duration
<music21.duration.Duration 1.0>
>>> s.coreElementsChanged()
>>> s.duration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/stream/base.py", line 7886, in _getDuration
    self._cache['Duration'].quarterLength = self.highestTime
KeyError: 'Duration'
>>> s._cache
{'HighestTime': Fraction(2, 3)}
```

This probably escaped notice because the intended method for this usage is `appendTuplet()`, which works:

```
>>> s  = stream.Stream()
>>> n = note.Note()
>>> s.insert(0, n)
>>> n.duration.appendTuplet(tup)
>>> s.duration
<music21.duration.Duration 2/3>
```

Still, this shouldn't crash. This diff appears to fix it (preventing the intermediate extra cache clearing alchemy) and is also probably faster. I'll open a PR in a few days.

```diff
diff --git a/music21/stream/base.py b/music21/stream/base.py
index 4d8f92316..c1371fdfc 100644
--- a/music21/stream/base.py
+++ b/music21/stream/base.py
@@ -7882,8 +7882,7 @@ class Stream(core.StreamCoreMixin, base.Music21Object):
             return self._cache['Duration']
         else:
             # environLocal.printDebug(['creating new duration based on highest time'])
-            self._cache['Duration'] = duration.Duration()
-            self._cache['Duration'].quarterLength = self.highestTime
+            self._cache['Duration'] = duration.Duration(self.highestTime)
             return self._cache['Duration']
```

**Comment by mscuthbert** [comment]
totally approve of this fix and great bug report.
