### ISSUE TITLE
meter.TimeSignature objects with `.0` in string result in incorrect output

### ISSUE THREAD

**Issue by Luke-Poeppel** [cuthbertLab/music21#964]
**music21 version**

`6.7.1`   

**Problem summary**
If a `meter.TimeSignature` object is created with a float in the `value` string, it has an incorrect numerator and denominator.

**Steps to reproduce**

```
>>> x = TimeSignature("5.0/4.0")
```

**Expected vs. actual behavior**

I'm expecting the following:
```
>>> x
<music21.meter.TimeSignature 5/4>
```
but am instead getting
```
>>> x 
<music21.meter.TimeSignature 50/40>
```
**More information**
I haven't tried to debug it, but I think the issue is in the regex line in `meter.core.tools.slashToTuple` (see line 61). 
https://github.com/cuthbertLab/music21/blob/450859475497dd70510e5ebde6184536bdac15a8/music21/meter/tools.py#L50-L64
I'm not sure if it's better to assert that the two `value` elements are of type `int` when loaded, or allow them if they're still digits.

**Comment by jacobtylerwalls** [comment]
Hi Luke, nice to meet you! My reaction is that if we accept floats we will leave the impression that fractional numerators/denominators are accepted. But silently accepting 50/40 is bad.

How about this? Matches other regexes in the system where add a period to this argument. And the error looks informative. 

```diff
diff --git a/music21/meter/tools.py b/music21/meter/tools.py
index d1eafd0a4..f995f675e 100644
--- a/music21/meter/tools.py
+++ b/music21/meter/tools.py
@@ -48,7 +48,7 @@ def slashToTuple(value: str) -> Optional[MeterTerminalTuple]:
     '''
     # split by numbers, include slash
     valueNumbers, valueChars = common.getNumFromStr(value,
-                                                    numbers='0123456789/')
+                                                    numbers='0123456789/.')
     valueNumbers = valueNumbers.strip()  # remove whitespace
     valueChars = valueChars.strip()  # remove whitespace
     if 'slow' in valueChars.lower():
```
```
>>> m = meter.TimeSignature('5.0/4.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/meter/base.py", line 469, in __init__
    self.resetValues(value, divisions)
  File "/Users/jwalls/music21/music21/meter/base.py", line 489, in resetValues
    self.load(value, divisions)
  File "/Users/jwalls/music21/music21/meter/base.py", line 533, in load
    self.displaySequence = MeterSequence(value)
  File "/Users/jwalls/music21/music21/meter/core.py", line 413, in __init__
    self.load(value, partitionRequest)
  File "/Users/jwalls/music21/music21/meter/core.py", line 1142, in load
    ratioList, self.summedNumerator = tools.slashMixedToFraction(value)
  File "/Users/jwalls/music21/music21/meter/tools.py", line 137, in slashMixedToFraction
    raise TimeSignatureException('cannot create time signature from:', valueSrc)
music21.exceptions21.TimeSignatureException: ('cannot create time signature from:', '5.0/4.0')
```

Any interest in wrapping this up into a PR?

**Comment by jacobtylerwalls** [comment]
We should improve that exception message while we're at it by using an f-string.

**Comment by Luke-Poeppel** [comment]
Great to meet you, @jacobtylerwalls! Took your suggestion (including changing the `TimeSignatureException`) in the PR above. Hope this looks ok.
