### ISSUE TITLE
`getGraceDuration()` doesn't preserve unlinked type

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#968]
**music21 version**

dev

**Problem summary**
Seems inappropriate to drop the unlinked type when creating a GraceDuration.

**Steps to reproduce**

```
>>> r = note.Rest(quarterLength=0.5)
>>> r.duration.type
'eighth'
>>> r2 = r.getGrace(inPlace=False)
>>> r2.duration.type
'zero'
>>> r2.duration
<music21.duration.GraceDuration unlinked type:zero quarterLength:0.0>
```

**More information**
Spotted when working on #941

**Comment by mscuthbert** [comment]
Yikes!  The whole point of having a GraceDuration is that it represents as a type.  Yes!  This is an interesting problem.  Probably related to changes in duration parsing in v6 or v7, but lacked a test.
