### ISSUE TITLE
tarball does not include LICENSE file

### ISSUE THREAD

**Issue by keszybz** [cuthbertLab/music21#98]
I'm preparing a package for Fedora. A license file is present in the repo but not in the tarball.

**Comment by mscuthbert** [comment]
eek... I'll make sure to fix that.  Is this on the latest version or for one of the older?

**Comment by keszybz** [comment]
The latest (https://github.com/cuthbertLab/music21/releases/download/v2.0.5/music21-2.0.5.tar.gz).
But when I do 'python setup.py sdist', LICENSE is included, so you must be using some different process to generate it...

**Comment by mscuthbert** [comment]
it was there, I believe but as license.txt -- it is now symlinked to LICENSE as well.
