### ISSUE TITLE
Way too many pitch objects in Music XML

### ISSUE THREAD

**Issue by capital-G** [cuthbertLab/music21#99]
I have written a simple score in MuseScore and exported it as MusicXML in MuseScore. I just wanted to count all pitch classes after importing the song via letitbe = converter.parse('Let It Be.xml')

	for pitch in letitbe.pitches:
		count_dict[pitch.name] = count_dict.get(pitch.name, 0) + 1
	
	return count_dict

But this returns completly false countings, also the plot function return false counting, even the relations do not fit and it also counted pitches that weren't actually in the score (although they were in the Bass of the Chord, so e.g. G/B). I just added Chrod symboles in MuseScore (with Ctrl+K) and Lyrics (with Ctrl+L), nothing else.

Is this a known problem?

**Comment by mscuthbert** [comment]
Chord symbols are treated like chords for the purpose of returning pitches.  It's not a problem, it's designed behavior.  We can chat more on the mailing list.  Filter out your ChordSymbol objects first if you want the counts to be what you think should be the default.
